Repository taiga-family/taiga-ui, pull requests merged in 2022-07, with the labels that each got.

#2031 feat(addon-doc): new token `TUI_DOC_PAGE_LOADED` to fix anchor links (scroll to examples)
  projects/addon-doc/src/components/navigation/navigation.component.ts
  projects/addon-doc/src/directives/scroll-into-view/scroll-into-view.directive.ts
  projects/addon-doc/src/public-api.ts
  projects/addon-doc/src/tokens/page-loaded.ts
  projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
Labels: ready to merge

#2035 chore(demo): also wait loading of `tui-doc-code` before scroll
  projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
  projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
Labels: ready to merge

#2040 ci: fix flaky e2e
  projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
Labels: ready to merge

#2038 ci: correct processing of `dry-run` mode or `rc` mode
  .github/workflows/create-release.yml
Labels: ready to merge

#2048 chore: skip flaky tests
  projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
Labels: ready to merge

#2050 fix(kit): `MultiSelect` inside `Group` border-radius problem
  projects/demo/src/modules/components/group/examples/1/index.html
  projects/demo/src/modules/components/group/examples/1/index.ts
  projects/demo/src/modules/components/group/group.module.ts
  projects/kit/components/multi-select/multi-select.style.less
Labels: ready to merge

#2045 ci: choose another page for testing viewport in e2e
  projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
Labels: ready to merge

#2042 ci: don't create github release when is `dry-run`
  .github/workflows/create-release.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: ready to merge

#2046 fix(kit): sequences of white space are preserved for `inputTag`
  projects/core/styles/mixins/mixins.less
  projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.spec.ts
  projects/demo-integrations/cypress/tests/kit/input/input-tag.spec.ts
  projects/kit/components/tag/tag.style.less
Labels: ready to merge

#2060 chore(cdk): textfield icons migration
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts
  projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
Labels: ready to merge

#2066 chore: add migration for deprecated functions
  projects/cdk/schematics/ng-update/constants/deprecated-functions.ts
  projects/cdk/schematics/ng-update/constants/types.ts
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
  projects/cdk/utils/format/pad-start.ts
  projects/core/utils/miscellaneous/color-fallback.ts
Labels: ready to merge

#2072 ci: autorebase for marked pull request
  .github/workflows/autorebase.yml
Labels: ready to merge

#2071 fix(addon-charts): use ng-container[ngTemplateOutlet] instead of structural directive
  projects/addon-charts/components/bar-set/bar-set.template.html
  projects/addon-charts/components/pie-chart/pie-chart.template.html
  projects/addon-doc/src/components/demo/demo.template.html
  projects/addon-doc/src/components/documentation/documentation.template.html
  projects/addon-doc/src/components/example/example.template.html
  projects/addon-doc/src/components/page/page.template.html
  projects/addon-table/components/table/th/th.template.html
  projects/core/components/expand/expand.template.html
  projects/demo-integrations/cypress/tests/addon-charts/line-chart.spec.ts
  projects/demo-integrations/cypress/tests/addon-charts/pie-chart.spec.ts
  projects/demo/src/modules/components/tree/examples/5/content.ts
  projects/demo/src/modules/directives/dropdown-context/dropdown-context.component.html
  projects/kit/components/action/action.template.html
  projects/kit/components/breadcrumbs/breadcrumbs-wrapper.template.html
  projects/kit/components/files/file/file.template.html
  projects/kit/components/input-file/file/file.template.html
  projects/kit/components/input-tag/input-tag.template.html
  projects/kit/components/multi-select-option/multi-select-option.template.html
  projects/kit/components/select-option/select-option.template.html
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
  projects/kit/components/tree/components/tree-item-content/tree-item-content.template.html
Labels: ready to merge

#2064 refactor(cdk): `Hovered` simplify directive
  projects/cdk/components/dropdown-host/dropdown-host.component.ts
  projects/cdk/constants/empty.ts
  projects/cdk/directives/hovered/hovered.directive.ts
  projects/cdk/directives/hovered/test/hovered.directive.spec.ts
  projects/cdk/services/hovered.service.ts
  projects/cdk/utils/dom/index.ts
  projects/cdk/utils/dom/point-to-client-rect.ts
  projects/core/components/hints-host/hint-box/hint-box.component.ts
  projects/core/components/hints-host/hint-box/hint-box.module.ts
  projects/core/components/hints-host/hint-box/hint-box.template.html
  projects/core/components/hints-host/hints-host.component.ts
  projects/core/components/hints-host/hints-host.module.ts
  projects/core/components/hints-host/hints-host.template.html
  projects/core/interfaces/hint.ts
  projects/core/interfaces/index.ts
  projects/kit/directives/dropdown-context/dropdown-context.directive.ts
  projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
Labels: ready to merge

#2077 ci: skip e2e for v3.x branch
  .github/workflows/e2e.yml
Labels: ready to merge

#2076 feat!: enable ivy by default
  projects/demo/src/modules/app/stackblitz/project-files/configs.md
  projects/demo/tsconfig.app.json
  tsconfig.json
Labels: ready to merge

#2082 ci: save demo-next for pre-release branch and main
  .github/workflows/deploy-next.yml
Labels: ready to merge

#2081 ci: ignore v3+ branches for screenshot bot
  .github/screenshot-bot.config.toml
Labels: ready to merge

#2070 fix(core): align to baseline value decoration postfix
  projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
  projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
  projects/demo-integrations/cypress/tests/kit/input-time/input-time.spec.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
Labels: ready to merge

#2083 fix(core): `tuiLink` mustn't break inline model for anchors
  projects/core/components/link/link.style.less
  projects/demo/src/modules/components/link/examples/4/index.html
  projects/demo/src/modules/components/link/examples/4/index.less
  projects/demo/src/modules/components/link/examples/4/index.ts
  projects/demo/src/modules/components/link/link.component.ts
  projects/demo/src/modules/components/link/link.module.ts
  projects/demo/src/modules/components/link/link.template.html
Labels: ready to merge

#2093 ci: fix concurrency problem
  .github/actions/nodejs/action.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-next.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate-tag.yml
Labels: ready to merge

#2088 fix(addon-editor): customize text color in dark/light mode
  projects/addon-editor/styles/editor-socket.css
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
Labels: ready to merge

#2092 fix(addon-editor): support styles without paragraph for lists
  projects/addon-editor/constants/tiptap-editor-styles.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
  projects/demo/src/modules/components/editor-new/examples/1/index.html
  projects/demo/src/modules/components/editor-new/examples/1/index.ts
Labels: ready to merge

#2104 ci: support some workflows when target is any bases branch
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: ready to merge

#2097 feat!: update to Angular 11
  angular.json
  package-lock.json
  package.json
  projects/addon-charts/ng-package.json
  projects/addon-commerce/ng-package.json
  projects/addon-doc/ng-package.json
  projects/addon-doc/package.json
  projects/addon-editor/components/color-selector/palette/palette.template.html
  projects/addon-editor/ng-package.json
  projects/addon-mobile/components/sheet/components/sheet-bar/sheet-bar.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.providers.ts
  projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
  projects/addon-mobile/components/sheet/directives/sheet-stop/sheet-stop.directive.ts
  projects/addon-mobile/components/sheet/directives/sheet-top/sheet-top.directive.ts
  projects/addon-mobile/components/sheet/directives/sheet-wrapper/sheet-wrapper.directive.ts
  projects/addon-mobile/components/sheet/sheet-options.ts
  projects/addon-mobile/components/sheet/sheet-tokens.ts
  projects/addon-mobile/components/sheet/sheet.ts
  projects/addon-mobile/ng-package.json
  projects/addon-preview/ng-package.json
  projects/addon-table/ng-package.json
  projects/addon-tablebars/ng-package.json
  projects/cdk/ng-package.json
  projects/core/components/primitive-textfield/primitive-textfield-types.ts
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
  projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
  projects/core/ng-package.json
  projects/demo/package.json
  projects/demo/tsconfig.app.json
  projects/demo/tsconfig.server.json
  projects/i18n/ng-package.json
  projects/icons/ng-package.json
  projects/kit/ng-package.json
  projects/taiga-schematics/ng-package.json
  projects/taiga-schematics/package.json
  projects/testing/ng-package.json
Labels: v3.0 candidates, ready to merge

#2102 Some stuff
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-editor/components/editor/editor.component.ts
  projects/cdk/classes/assert.ts
  projects/cdk/directives/hovered/hovered.directive.ts
  projects/cdk/directives/hovered/hovered.service.ts
  projects/cdk/directives/hovered/index.ts
  projects/cdk/services/hovered.service.ts
  projects/cdk/services/index.ts
  projects/cdk/utils/focus/get-closest-keyboard-focusable.ts
  projects/core/components/button/button.component.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/dropdown-box/dropdown-box.component.ts
  projects/core/components/hints-host/hints-host.style.less
  projects/core/components/hosted-dropdown/test/hosted-dropdown.component.spec.ts
  projects/core/constants/described-by.ts
  projects/core/constants/index.ts
  projects/core/directives/described-by/described-by.directive.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/directives/hint/test/hint.directive.spec.ts
  projects/core/directives/pointer-hint/pointer-hint.directive.ts
  projects/core/interfaces/hint.ts
  projects/kit/abstract/slider/slider.ts
  projects/kit/components/multi-select/test/multi-select.component.spec.ts
  projects/kit/components/stepper/stepper.component.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
  projects/kit/directives/highlight/test/highlight.directive.spec.ts
  projects/kit/pipes/field-error/test/field-error-content-pipe.spec.ts
Labels: v3.0 candidates

#2119 chore(demo-integrations): page should be loaded before scroll+screenshot
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/addon-icons/customization-icons.spec.ts
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge

#2120 chore(demo-integrations): improve stability of cypress tests
  projects/demo-integrations/cypress/support/shared.entities.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.spec.ts
Labels: ready to merge

#2107 ci: fix problem with build workflow
  .github/workflows/build.yml
Labels: ready to merge

#2126 fix(i18n): fix vietnamese
  projects/i18n/languages/vietnamese/addon-editor.ts
  projects/i18n/languages/vietnamese/kit.ts
Labels: ready to merge

#2127 ci: improve logs for schematics
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
  projects/cdk/schematics/ng-update/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/steps/miscellaneous.ts
  projects/cdk/schematics/ng-update/steps/remove-module.ts
  projects/cdk/schematics/ng-update/steps/rename-types.ts
  projects/cdk/schematics/ng-update/steps/replace-const.ts
  projects/cdk/schematics/ng-update/steps/replace-deep-import.ts
  projects/cdk/schematics/ng-update/steps/replace-enums.ts
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/steps/replace-services.ts
  projects/cdk/schematics/utils/colored-log.ts
Labels: ready to merge

#2111 chore: add example for aligning content to API page
  projects/demo-integrations/cypress/tests/kit/input-number/input-number.spec.ts
  projects/demo/src/modules/components/input-number/input-number.component.ts
  projects/demo/src/modules/components/input-number/input-number.template.html
Labels: ready to merge

#2131 ci: use `encodeURI` by default in `tuiVisit`
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts
  projects/demo-integrations/cypress/tests/kit/input-number/input-number.spec.ts
  projects/demo-integrations/cypress/tests/kit/input/input.spec.ts
  projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts
Labels: ready to merge

#2123 fix(kit): `Slider` incorrect progress-filling after patching of `[(ngModel)]`-value
  projects/demo-integrations/cypress/tests/kit/slider/slider.spec.ts
  projects/demo/src/modules/components/slider/examples/3/index.html
  projects/demo/src/modules/components/slider/examples/3/index.less
  projects/demo/src/modules/components/slider/examples/3/index.ts
  projects/demo/src/modules/components/slider/examples/6/index.html
  projects/demo/src/modules/components/slider/examples/6/index.less
  projects/demo/src/modules/components/slider/examples/6/index.ts
  projects/demo/src/modules/components/slider/slider.component.html
  projects/demo/src/modules/components/slider/slider.component.ts
  projects/demo/src/modules/components/slider/slider.module.ts
  projects/kit/components/slider/slider-key-steps.directive.ts
  projects/kit/components/slider/slider.component.ts
Labels: ready to merge

#2139 fix(addon-editor): support nested bullet list
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.component.ts
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
  projects/addon-editor/constants/tiptap-editor-styles.ts
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/addon-editor/extensions/indent-outdent.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
  projects/demo/src/modules/components/editor-new/examples/1/index.html
  projects/demo/src/modules/components/editor-new/examples/1/index.ts
Labels: ready to merge

#2135 fix(core): changed `vw/vh` to `percentage` for correct ensure viewport in safari
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.style.less
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less
  projects/addon-mobile/directives/sidebar/sidebar.style.less
  projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.style.less
  projects/cdk/components/dialog-host/dialog-host.style.less
  projects/core/components/dialog/dialog.style.less
  projects/demo/src/modules/components/preview/examples/2/index.less
  projects/demo/src/modules/components/sheet/examples/5/index.less
  stylelint.config.js
Labels: ready to merge

#2145 chore(demo): improved ux for icons page
  projects/demo/src/modules/markup/icons/icons.tokens.ts
  projects/kit/components/line-clamp/line-clamp.component.ts
Labels: ready to merge

#2143 chore: small style changes
  projects/core/components/root/root.style.less
  projects/core/styles/mixins/wrapper.less
  projects/kit/components/tabs/tab/tab.style.less
Labels: ready to merge

#2133 feat(addon-editor): support customization font-size
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts
  projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html
  projects/addon-editor/constants/default-font-options-handler.ts
  projects/addon-editor/constants/index.ts
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/addon-editor/extensions/default-editor-extensions.ts
  projects/addon-editor/extensions/font-size.ts
  projects/addon-editor/extensions/index.ts
  projects/addon-editor/tokens/editor-options.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
  projects/i18n/interfaces/language.ts
  projects/i18n/languages/dutch/addon-editor.ts
  projects/i18n/languages/english/addon-editor.ts
  projects/i18n/languages/french/addon-editor.ts
  projects/i18n/languages/german/addon-editor.ts
  projects/i18n/languages/italian/addon-editor.ts
  projects/i18n/languages/polish/addon-editor.ts
  projects/i18n/languages/portuguese/addon-editor.ts
  projects/i18n/languages/russian/addon-editor.ts
  projects/i18n/languages/spanish/addon-editor.ts
  projects/i18n/languages/turkish/addon-editor.ts
  projects/i18n/languages/ukrainian/addon-editor.ts
  projects/i18n/languages/vietnamese/addon-editor.ts
Labels: ready to merge

#2161 fix(addon-editor): add `font-size` entry point
  projects/addon-editor/extensions/font-size/font-size.extension.ts
  projects/addon-editor/extensions/font-size/index.ts
  projects/addon-editor/extensions/font-size/package.json
  projects/addon-editor/extensions/index.ts
Labels: ready to merge

#2162 fix(addon-mobile): replaced `percentages` to `vh` for prevent regression
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less
Labels: ready to merge

#2159 ci: each decorator will be on a different line
  .eslintrc.js
  package-lock.json
  package.json
  projects/demo/src/modules/components/select/examples/9/account/my-account.component.ts
  scripts/eslint/decorators.js
Labels: ready to merge

#2155 ci: use `ref_name` instead `head_ref`
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: ready to merge

#2101 fix(kit): clamp activeIndex for `tabs-with-more`
  projects/demo-integrations/cypress/tests/kit/tabs/tabs.spec.ts
  projects/demo/src/modules/components/tabs/examples/5/index.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
Labels: ready to merge

#2166 chore(demo-integrations): new cypress tests for code blocks
  projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
Labels: ready to merge

#2168 Revert "ci: use `ref_name` instead `head_ref` (#2155)"
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: ready to merge

#2169 chore: flaky cypress tests
  projects/demo-integrations/cypress/support/commands.ts
  projects/demo-integrations/cypress/support/wait-code-highlight.ts
  projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
Labels: ready to merge

#2170 chore(cdk): polymorpheus migrations
  projects/cdk/schematics/ng-update/steps/migrate-polymorpheus.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
  projects/cdk/schematics/utils/replace-tag.ts
  projects/cdk/schematics/utils/templates/elements.ts
Labels: v3.0 candidates, ready to merge

#2128 feat(kit): `Slider` new helper `tuiSliderThumbLabel`
  projects/demo-integrations/cypress/tests/kit/slider/slider.spec.ts
  projects/demo/src/modules/components/slider/examples/6/index.html
  projects/demo/src/modules/components/slider/examples/6/index.less
  projects/demo/src/modules/components/slider/examples/6/index.ts
  projects/demo/src/modules/components/slider/slider.component.html
  projects/demo/src/modules/components/slider/slider.module.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/helpers/slider-readonly.directive.ts
  projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.component.ts
  projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.style.less
  projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.template.html
  projects/kit/components/slider/index.ts
  projects/kit/components/slider/slider.component.ts
  projects/kit/components/slider/slider.module.ts
Labels: ready to merge

#2141 refactor(addon-preview): `PreviewZoom` replace legacy `Slider` with new one
  projects/addon-preview/components/preview/zoom/preview-zoom.component.ts
  projects/addon-preview/components/preview/zoom/preview-zoom.style.less
  projects/addon-preview/components/preview/zoom/preview-zoom.template.html
  projects/demo/src/modules/app/landing/landing.template.html
  projects/demo/src/modules/directives/media/examples/2/index.html
  projects/demo/src/modules/directives/media/examples/3/index.html
Labels: ready to merge

#2183 ci: prevent override sha of commits
  .github/workflows/lint.yml
Labels: ready to merge

#2173 fix(cdk, schematics): add BrowserAnimationsModule before TuiRootModule
  projects/cdk/schematics/ng-add/constants/modules.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
  projects/taiga-schematics/schematics/ng-add/constants/modules.ts
  projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
Labels: ready to merge

#2179 chore: fix flaky cypress test
  projects/demo-integrations/cypress/support/wait-code-highlight.ts
Labels: ready to merge

#2178 feat(addon-doc): set fragment to url when copy link
  projects/addon-doc/src/components/example/example.component.ts
Labels: ready to merge

#2188 fix(core): add more customization for `font-size` in buttons
  projects/core/components/button/button.style.less
Labels: ready to merge

#2191 ci: fix dependency graph for testing package
  angular.json
Labels: ready to merge

#2192 chore(kit): export files module from input-files
  projects/kit/components/input-files/input-files.module.ts
Labels: ready to merge

#2185 chore(cdk): `schematics` proprietary migrations
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/cdk/schematics/ng-update/constants/modules.ts
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/cdk/schematics/ng-update/constants/warnings.ts
Labels: ready to merge

#2196 fix(core): redundant width by `desktop-m-min` for alerts
  projects/core/components/alert/alert.style.less
Labels: ready to merge

#2195 ci: should be fail if it has conflicts
  .github/workflows/autorebase-v3.yml
  .github/workflows/autorebase.yml
  projects/i18n/languages/chinese/countries.ts
  projects/i18n/languages/chinese/index.ts
Labels: ready to merge

#2200 feat!: `Range` remove deprecated API for labels of segments
  projects/demo/src/modules/components/range/examples/3/index.html
  projects/demo/src/modules/components/range/examples/4/index.html
  projects/demo/src/modules/components/range/range.component.ts
  projects/demo/src/modules/components/range/range.template.html
  projects/kit/components/range/range.component.ts
  projects/kit/components/range/range.module.ts
  projects/kit/components/range/range.style.less
  projects/kit/components/range/range.template.html
Labels: ready to merge

#2187 feat(i18n): add `Republic of Kosovo` code
  projects/i18n/enums/country-iso-code.ts
  projects/i18n/languages/dutch/countries.ts
  projects/i18n/languages/english/countries.ts
  projects/i18n/languages/french/countries.ts
  projects/i18n/languages/italian/countries.ts
  projects/i18n/languages/polish/countries.ts
  projects/i18n/languages/portuguese/countries.ts
  projects/i18n/languages/russian/countries.ts
  projects/i18n/languages/spanish/countries.ts
  projects/i18n/languages/vietnamese/countries.ts
  projects/kit/components/input-phone-international/const/countries.ts
Labels: ready to merge

#2205 chore: fix failure build
  projects/i18n/languages/chinese/countries.ts
Labels: ready to merge

#2204 fix(i18n): translated some fields for `addon-editor`
  projects/i18n/languages/russian/addon-editor.ts
Labels: ready to merge

#2210 feat(addon-table): `TableFilters` add new module
  .eslintrc.js
  projects/addon-table/directives/index.ts
  projects/addon-table/directives/package.json
  projects/addon-table/directives/table-filters/abstract-table-filter.ts
  projects/addon-table/directives/table-filters/generic-filter.directive.ts
  projects/addon-table/directives/table-filters/index.ts
  projects/addon-table/directives/table-filters/package.json
  projects/addon-table/directives/table-filters/table-filter.directive.ts
  projects/addon-table/directives/table-filters/table-filter.ts
  projects/addon-table/directives/table-filters/table-filters.directive.ts
  projects/addon-table/directives/table-filters/table-filters.module.ts
  projects/addon-table/directives/table-filters/table-filters.pipe.ts
  projects/addon-table/index.ts
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/tables/table-filters/examples/1/index.html
  projects/demo/src/modules/tables/table-filters/examples/1/index.less
  projects/demo/src/modules/tables/table-filters/examples/1/index.ts
  projects/demo/src/modules/tables/table-filters/examples/import/import-module.md
  projects/demo/src/modules/tables/table-filters/examples/import/insert-template.md
  projects/demo/src/modules/tables/table-filters/table-filters.component.ts
  projects/demo/src/modules/tables/table-filters/table-filters.module.ts
  projects/demo/src/modules/tables/table-filters/table-filters.template.html
Labels: ready to merge

#2207 feat(kit)!: `InputSlider` remove all deprecated API
  projects/demo/src/modules/components/input-slider/examples/2/index.html
  projects/demo/src/modules/components/input-slider/examples/3/index.html
  projects/demo/src/modules/components/input-slider/examples/5/index.html
  projects/demo/src/modules/components/input-slider/examples/5/index.ts
  projects/demo/src/modules/components/input-slider/input-slider.component.ts
  projects/demo/src/modules/components/input-slider/input-slider.template.html
  projects/demo/src/modules/components/pagination/examples/1/index.html
  projects/demo/src/modules/components/pagination/examples/2/index.html
  projects/demo/src/modules/components/pagination/examples/3/index.html
  projects/demo/src/modules/components/pagination/pagination.module.ts
  projects/demo/src/modules/markup/form/example/index.html
  projects/demo/src/modules/markup/form/example/index.style.less
  projects/demo/src/modules/markup/form/example/index.ts
  projects/kit/components/input-slider/input-slider.component.ts
  projects/kit/components/input-slider/input-slider.module.ts
  projects/kit/components/input-slider/input-slider.style.less
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/input-slider/test/input-slider-new.component.spec.ts
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/slider.module.ts
Labels: v3.0 candidates, ready to merge

#2190 chore(demo): add example in `hosted-dropdown`
  projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html
  projects/demo/src/modules/components/hosted-dropdown/examples/4/index.less
  projects/demo/src/modules/components/hosted-dropdown/examples/4/index.ts
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
Labels: ready to merge

#2212 chore(demo): `?raw` fix typings
  projects/demo/src/typings.d.ts
  projects/demo/webpack.config.ts
Labels: ready to merge

#2199 refactor: remove deprecated re-exports
  projects/addon-doc/src/languages/russian.ts
  projects/addon-editor/extensions/default-editor-extensions.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.module.ts
  projects/addon-preview/components/preview/preview-action/preview-action.directive.ts
  projects/addon-table/components/table/providers/table.provider.ts
  projects/addon-table/components/table/providers/table.providers.ts
  projects/cdk/components/dialog-host/dialog-host.component.ts
  projects/cdk/directives/auto-focus/autofocus.options.ts
  projects/cdk/observables/replay-control-value-changes.ts
  projects/cdk/observables/test/replay-control-value-changes.spec.ts
  projects/core/components/primitive-textfield/primitive-textfield-options.ts
  projects/core/directives/dropdown-controller/dropdown-controller.provider.ts
  projects/core/directives/hint-controller/hint-controller.provider.ts
  projects/core/directives/hint/hint-options.ts
  projects/core/providers/watched-controller-provider-factory.ts
  projects/demo/src/modules/components/input/examples/4/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts
  projects/demo/src/modules/tables/table/examples/4/index.ts
  projects/kit/components/arrow/arrow-options.ts
  projects/kit/components/calendar-range/test/range-calendar.component.spec.ts
  projects/kit/components/carousel/carousel-buttons.directive.ts
  projects/kit/components/combo-box/combo-box.providers.ts
  projects/kit/components/input-count/input-count-options.ts
  projects/kit/components/input-date-range/input-date-range.providers.ts
  projects/kit/components/input-date-time/input-date-time.providers.ts
  projects/kit/components/input-date/input-date.providers.ts
  projects/kit/components/input-password/input-password-options.ts
  projects/kit/components/input-time/input-time-options.ts
  projects/kit/components/multi-select/multi-select-group/multi-select-group.component.ts
  projects/kit/components/multi-select/multi-select-group/multi-select-group.directive.ts
  projects/kit/components/select/select.providers.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts
  projects/kit/components/tabs/tabs/tabs.component.ts
  projects/kit/providers/value-accessor.provider.ts
  projects/kit/utils/miscellaneous/replay-control-value-changes-factory.ts
Labels: v3.0 candidates, ready to merge

#2213 feat(addon-editor): add `TUI_EDITOR_CONTENT_PROCESSOR`
  projects/addon-editor/components/editor-new/editor-new.component.ts
  projects/addon-editor/tokens/editor-processor.ts
  projects/addon-editor/tokens/index.ts
  projects/addon-editor/utils/index.ts
  projects/addon-editor/utils/legacy-converter.ts
  projects/addon-editor/utils/test/legacy-converter.spec.ts
  projects/demo/src/modules/components/editor-new/editor-new.component.ts
  projects/demo/src/modules/components/editor-new/editor-new.module.ts
  projects/demo/src/modules/components/editor-new/editor-new.template.html
  projects/demo/src/modules/components/editor-new/examples/5/index.html
  projects/demo/src/modules/components/editor-new/examples/5/index.less
  projects/demo/src/modules/components/editor-new/examples/5/index.ts
Labels: ready to merge

#2220 feat(kit)!: `Slider` | `InputSlider` | `Range` | `InputRange` use strict version of `TuiKeySteps`
  projects/demo/src/modules/components/input-range/input-range.component.ts
  projects/demo/src/modules/components/input-slider/examples/3/index.ts
  projects/demo/src/modules/components/input-slider/input-slider.component.ts
  projects/demo/src/modules/components/range/range.component.ts
  projects/kit/components/input-slider/input-slider.component.ts
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/range/range.component.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/types/key-steps.ts
  projects/kit/types/test/key-steps.spec.ts
  projects/kit/utils/math/key-steps.ts
Labels: v3.0 candidates, ready to merge

#2218 chore(addon-editor): move starter-kit extension
  projects/addon-editor/extensions/default-editor-extensions.ts
  projects/addon-editor/extensions/index.ts
  projects/addon-editor/extensions/starter-kit/index.ts
  projects/addon-editor/extensions/starter-kit/package.json
  projects/addon-editor/extensions/starter-kit/starter-kit.ts
  projects/demo/src/modules/components/editor-new/examples/2/index.ts
  projects/demo/src/modules/components/editor-new/examples/3/index.ts
  projects/demo/src/modules/components/editor-new/examples/4/index.ts
Labels: ready to merge

#2225 fix(kit): `InputSlider` props `[prefix]`/`[postfix]` + `[valueContent]` overlaps each other on blur
  projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.spec.ts
  projects/kit/components/input-slider/input-slider.component.ts
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/input-slider/test/input-slider-new.component.spec.ts
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
Labels: ready to merge

#2229 refactor: removed `basic` example from tui-editor
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/support/shared.entities.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/support/wait-kit-dialog.ts
  projects/demo-integrations/cypress/tests/addon-editor/color-picker.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-api.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-dropdown.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-img.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-toolbar.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/utils.ts
  projects/demo/src/modules/components/abstract/control.ts
  projects/demo/src/modules/components/editor-new/editor-new.component.ts
  projects/demo/src/modules/components/editor-new/editor-new.module.ts
  projects/demo/src/modules/components/editor-new/editor-new.template.html
  projects/demo/src/modules/components/editor-new/examples/1/index.html
  projects/demo/src/modules/components/editor-new/examples/1/index.less
  projects/demo/src/modules/components/editor-new/examples/1/index.ts
  projects/demo/src/modules/components/editor-new/examples/1/smiles-tool/emoji.extension.ts
  projects/demo/src/modules/components/editor-new/examples/1/smiles-tool/smiles-tool.component.ts
  projects/demo/src/modules/components/editor-new/examples/1/smiles-tool/smiles-tool.module.ts
  projects/demo/src/modules/components/editor-new/examples/1/smiles-tool/smiles-tool.styles.less
  projects/demo/src/modules/components/editor-new/examples/1/smiles-tool/smiles-tool.template.html
  projects/demo/src/modules/components/editor-new/examples/2/index.html
  projects/demo/src/modules/components/editor-new/examples/2/index.less
  projects/demo/src/modules/components/editor-new/examples/2/index.ts
  projects/demo/src/modules/components/editor-new/examples/3/image-preview/image-preview.component.ts
  projects/demo/src/modules/components/editor-new/examples/3/image-preview/image-preview.module.ts
  projects/demo/src/modules/components/editor-new/examples/3/image-preview/image-preview.style.less
  projects/demo/src/modules/components/editor-new/examples/3/image-preview/image-preview.template.html
  projects/demo/src/modules/components/editor-new/examples/3/index.html
  projects/demo/src/modules/components/editor-new/examples/3/index.ts
  projects/demo/src/modules/components/editor-new/examples/4/index.html
  projects/demo/src/modules/components/editor-new/examples/4/index.less
  projects/demo/src/modules/components/editor-new/examples/4/index.ts
  projects/demo/src/modules/components/editor-new/examples/5/index.html
  projects/demo/src/modules/components/editor-new/examples/5/index.less
  projects/demo/src/modules/components/editor-new/examples/5/index.ts
Labels: ready to merge

#2232 chore(cdk): some schematic fixes
  projects/cdk/schematics/ng-update/constants/services.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
  projects/cdk/schematics/utils/add-import-to-closest-module.ts
  projects/cdk/schematics/utils/add-styles.ts
  projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
Labels: ready to merge

#2239 chore(kit): `InputSlider` sync `main` and `v3.x` branches
  projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.spec.ts
  projects/kit/components/input-slider/input-slider.component.ts
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
Labels: v3.0 candidates, ready to merge

#2241 chore(addon-editor): `editor` sync `main` and `v3.x` branches
  projects/addon-editor/components/edit-link/edit-link.component.ts
  projects/addon-editor/components/editor/editor.component.html
  projects/addon-editor/components/editor/editor.component.ts
  projects/addon-editor/components/editor/editor.style.less
  projects/addon-editor/tokens/index.ts
  projects/cdk/utils/dom/index.ts
  projects/cdk/utils/dom/is-element.ts
  projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
Labels: v3.0 candidates, ready to merge

#2234 chore(cdk): some more schematic fixes
  projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/utils/add-styles.ts
  projects/cdk/schematics/utils/get-project.ts
Labels: ready to merge

#2243 feat(kit)!: `Range` remove all deprecated API
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/demo/src/modules/components/range/examples/1/index.html
  projects/demo/src/modules/components/range/examples/3/index.html
  projects/demo/src/modules/components/range/examples/3/index.ts
  projects/demo/src/modules/components/range/examples/4/index.html
  projects/demo/src/modules/components/range/examples/4/index.ts
  projects/demo/src/modules/components/range/range.component.ts
  projects/demo/src/modules/components/range/range.template.html
  projects/kit/abstract/index.ts
  projects/kit/abstract/package.json
  projects/kit/abstract/slider/slider.ts
  projects/kit/components/input-range/input-range.component.ts
  projects/kit/components/input-range/input-range.template.html
  projects/kit/components/range/range-change.directive.ts
  projects/kit/components/range/range.component.ts
  projects/kit/components/range/test/range.component.spec.ts
Labels: v3.0 candidates, ready to merge
