Repository taiga-family/taiga-ui, pull requests merged in 2022-09, with the labels that each got.

#2545 chore(cdk): add fallback project in schematic
  projects/cdk/schematics/utils/get-project.ts
Labels: ready to merge

#2546 ci: fix relative base href
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
  projects/demo/src/modules/app/version-manager/version-manager.template.html
  projects/demo/src/modules/app/version-manager/versions.constants.ts
  scripts/postbuild-demo.ts
Labels: ready to merge

#2549 ci: trigger build/test when have changes in `testing`
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ready to merge

#2552 chore(cdk): `schematics` fix file globs patterns for migration 3.0
  projects/cdk/schematics/constants/file-globs.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
Labels: ready to merge

#2551 ci: fix relative base href (#2546)
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
  projects/demo/src/modules/app/version-manager/version-manager.template.html
  projects/demo/src/modules/app/version-manager/versions.constants.ts
  scripts/postbuild-demo.ts
Labels: ready to merge

#2548 chore(demo): add `TUI_IS_MOBILE_RES` example
  projects/demo/src/modules/utils/tokens/examples/7/index.html
  projects/demo/src/modules/utils/tokens/examples/7/index.ts
  projects/demo/src/modules/utils/tokens/tokens.template.html
Labels: ready to merge

#2555 ci: save snapshots when changed files into version branches
  .github/workflows/save-snapshots.yml
Labels: ready to merge

#2559 feat(core): add dialog header type
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/core/interfaces/dialog-options.ts
Labels: ready to merge

#2567 ci: building pure demo on e2e stage
  .github/actions/cypress/action.yml
  .github/workflows/deploy-next.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  .github/workflows/save-snapshots.yml
  package.json
  projects/demo/project.json
Labels: ready to merge

#2562 chore(cdk): `schematics` more logs for migration v3.0
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/utils/colored-log.ts
  projects/cdk/schematics/utils/progress.ts
Labels: ready to merge

#2573 chore(core): remove forgotten exampleText
  projects/core/components/primitive-textfield/textfield/textfield.component.ts
Labels: ready to merge

#2572 chore: fix demo serve configuration
  projects/demo/project.json
Labels: ready to merge

#2574 chore(cdk): `parse5` & `ng-morph` should be `optionalDependencies`
  package-lock.json
  projects/cdk/package.json
Labels: ready to merge, v2

#2577 chore: fix `npm start`-command
  projects/demo/project.json
Labels: ready to merge

#2570 ci: remove redundant exec script
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy.yml
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  scripts/postinstall.ts
  scripts/shared/post-build-all-version.ts
  tsconfig.json
  tsconfig.tools.json
Labels: ready to merge

#2576 chore(demo): `stackblitz` fix import of non-existing entities
  projects/demo/src/modules/app/stackblitz/project-files/configs.md
  projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
Labels: ready to merge

#2581 ci: don't persist local cache in github
  .github/actions/nodejs/action.yml
Labels: ready to merge

#2588 ci: save snapshots when changed files into version branches (#2555)
  .github/workflows/save-snapshots.yml
Labels: ready to merge

#2575 fix(kit): `InputNumber` fix positive min/negative max clipping
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
Labels: ready to merge

#2591 ci: publish snapshots into different job
  .github/workflows/deploy-next.yml
  .github/workflows/save-snapshots.yml
Labels: ready to merge

#2593 fix(kit): InputNumber fix positive min/negative max clipping
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
Labels: ready to merge

#2604 fix(cdk): `parse5` & `ng-morph` move `dependencies` => `optionalDependencies`
  package-lock.json
  projects/cdk/package.json
Labels: ready to merge

#2561 chore(cdk): show warning in less file after migration
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/replace-styles.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
  projects/demo/src/modules/app/home/home.template.html
Labels: ready to merge

#2601 fix(addon-table): `ThGroup` fix columns updating
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/demo-integrations/cypress/tests/addon-table/table/table.spec.ts
  projects/demo/src/modules/tables/table/examples/6/index.html
  projects/demo/src/modules/tables/table/examples/6/index.less
  projects/demo/src/modules/tables/table/examples/6/index.ts
  projects/demo/src/modules/tables/table/table.component.ts
  projects/demo/src/modules/tables/table/table.module.ts
  projects/demo/src/modules/tables/table/table.template.html
Labels: ready to merge

#2602 fix(addon-table): `ThGroup` fix columns updating
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/demo-integrations/cypress/tests/addon-table/table/table.spec.ts
  projects/demo/src/modules/tables/table/examples/6/index.html
  projects/demo/src/modules/tables/table/examples/6/index.less
  projects/demo/src/modules/tables/table/examples/6/index.ts
  projects/demo/src/modules/tables/table/table.component.ts
  projects/demo/src/modules/tables/table/table.module.ts
  projects/demo/src/modules/tables/table/table.template.html
Labels: ready to merge

#2597 chore: copy-pasted source code from `angular2TextMask`-package
  package-lock.json
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/addon-commerce/components/input-card/input-card.module.ts
  projects/addon-commerce/components/input-cvc/input-cvc.component.ts
  projects/addon-commerce/components/input-cvc/input-cvc.module.ts
  projects/addon-commerce/components/input-expire/input-expire.component.ts
  projects/addon-commerce/components/input-expire/input-expire.module.ts
  projects/addon-commerce/package.json
  projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
  projects/addon-editor/components/color-selector/color-edit/color-edit.module.ts
  projects/demo/project.json
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-count/input-count.module.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/input-date-range.module.ts
  projects/kit/components/input-date-time/input-date-time.component.ts
  projects/kit/components/input-date-time/input-date-time.module.ts
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.module.ts
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-phone/input-phone.module.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.module.ts
  projects/kit/directives/index.ts
  projects/kit/directives/mask/index.ts
  projects/kit/directives/mask/legacy-mask.ts
  projects/kit/directives/mask/ng-package.json
  projects/kit/package.json
Labels: ready to merge

#2595 Revert "fix(core): character descenders overflow the line (#2387)"
  projects/core/components/primitive-textfield/primitive-textfield.style.less
  projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
  projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
Labels: ready to merge

#2605 ci: correct deploy (#2603)
  .github/actions/cypress/action.yml
  .github/actions/nodejs/action.yml
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-next.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e.yml
  .github/workflows/save-snapshots.yml
  nx.json
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo/project.json
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
  projects/demo/src/modules/app/version-manager/versions.constants.ts
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/taiga-schematics/project.json
  scripts/postbuild-demo.ts
  scripts/postinstall.ts
  scripts/shared/argv.utils.ts
  scripts/shared/make-publishable-versions-map.ts
  scripts/shared/post-build-all-version.ts
  tsconfig.json
  tsconfig.tools.json
Labels: ready to merge

#2612 ci: fix build
  .github/workflows/build.yml
  package-lock.json
  package.json
  projects/testing/core/badge.harness.ts
  projects/testing/core/button.harness.ts
  projects/testing/core/index.ts
  projects/testing/core/loader.harness.ts
  projects/testing/core/svg.harness.ts
Labels: ready to merge

#2613 fix(kit): `Carousel` reset autoscroll timer when index changes
  projects/kit/components/carousel/carousel.directive.ts
Labels: ready to merge

#2615 ci: use lts tag for prev versions
  scripts/publish.ts
Labels: ready to merge

#2609 ci: prevent build greater versions
  .github/workflows/deploy.yml
  nx.json
  package.json
  projects/demo/project.json
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
  projects/demo/src/modules/app/version-manager/versions.constants.ts
  projects/icons/scripts/delete-all-to-compile-file.ts
  scripts/compile-icons.ts
  scripts/postbuild-demo.ts
  scripts/shared/argv.utils.ts
  scripts/shared/build-demo.ts
  scripts/shared/make-publishable-versions-map.ts
Labels: ready to merge

#2616 fix(addon-commerce): `InputCardGrouped` fix dropdown width
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
Labels: ready to merge

#2620 ci: correct implicit dependencies
  nx.json
Labels: ready to merge, cherry_pick_v2.x

#2619 chore(demo): fix stackblitz
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
Labels: ready to merge, v2

#2618 ci: use lts tag for prev versions
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  scripts/publish.ts
  scripts/shared/argv.utils.ts
Labels: ready to merge

#2622 chore(cdk) `Stackblitz` use the same major taiga-version as selected documentation
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
Labels: ready to merge

#2607 chore(core): `styles` mark TODOs for 4.0
  projects/core/styles/mixins/text.less
  projects/core/styles/theme/variables.less
Labels: ready to merge

#2628 ci: fix build
  .github/actions/nodejs/action.yml
  .github/workflows/deploy-next.yml
  .github/workflows/e2e.yml
  .github/workflows/save-snapshots.yml
  nx.json
  package-lock.json
  package.json
  scripts/shared/build-demo.ts
Labels: ready to merge

#2631 fix(addon-editor): using editor-socket inside editor to fix editor styles
  projects/addon-editor/components/editor/editor.component.html
  projects/demo-integrations/cypress/tests/addon-editor/editor-img.spec.ts
  projects/demo-integrations/cypress/tests/addon-table/table/table.spec.ts
Labels: ready to merge

#2637 chore: fix editor e2e
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-img.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.spec.ts
  projects/demo/src/modules/components/editor/editor.template.html
Labels: ready to merge

#2641 ci: disable optimization to scripts for prevent flaky e2e tests
  projects/demo/project.json
Labels: ready to merge

#2636 fix(demo): make `Stackblitz` to be compatible with `Taiga UI 3.0`
  projects/demo/src/modules/app/stackblitz/project-files/configs.md
  projects/demo/src/modules/app/stackblitz/project-files/src/app/@stackblitz/README.md
  projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
  projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
  projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
Labels: ready to merge

#2644 ci: disable optimization to scripts for prevent flaky e2e tests
  .github/workflows/e2e.yml
Labels: ready to merge

#2645 chore(cdk): `schematics` forgotten migration for `TuiInputFileModule` => `TuiInputFilesModule`
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/demo/src/modules/components/input-files/input-files.template.html
Labels: ready to merge

#2650 chore: add additional description for help
  projects/cdk/services/destroy.service.ts
Labels: ready to merge

#2643 chore(demo): improve documentation for jest
  projects/demo/src/modules/info/testing/jest/examples/setup-jest-js.md
Labels: ready to merge

#2649 fix(addon-table): type string is not assignable to type keyof T
  projects/addon-table/components/table/directives/head.directive.ts
  projects/addon-table/components/table/directives/row.directive.ts
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/sortable.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/pipes/table-sort.pipe.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/addon-table/components/table/tr/tr.template.html
Labels: ready to merge

#2653 ci: improved logs
  package-lock.json
  scripts/shared/sync-versions.ts
Labels: ready to merge

#2646 ci: refactor jobs
  .github/workflows/autorebase.yml
  .github/workflows/build.yml
  .github/workflows/deploy-next.yml
  .github/workflows/release.yml
  .github/workflows/save-snapshots.yml
  .github/workflows/validate-tag.yml
Labels: ready to merge

#2647 feat(kit): `InputDateRange` navigate months in sync, cancel unfinished range on esc
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/calendar-range.template.html
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
  projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
Labels: ready to merge

#2693 ci: final fixes
  .github/workflows/deploy-gh-pages.yml
Labels: ready to merge

#2711 fix(kit): `InputFlies` new value of i18n-token `TUI_INPUT_FILE_TEXTS` triggers text changes
  projects/demo-integrations/cypress/support/commands.ts
  projects/demo-integrations/cypress/support/set-language.ts
  projects/demo-integrations/cypress/tests/kit/input-files/input-files.spec.ts
  projects/i18n/languages/dutch/kit.ts
  projects/i18n/languages/italian/kit.ts
  projects/kit/components/input-files/input-files.component.ts
  projects/kit/components/input-files/input-files.module.ts
  projects/kit/components/input-files/input-files.template.html
  projects/kit/components/input-files/max-size-rejection-error.pipe.ts
Labels: v3

#2713 fix(kit): `InputPhoneInternational` extend country masks for Croatia and Bosnia
  projects/kit/components/input-phone-international/tokens/countries-masks.ts
Labels: community contribution

#2715 chore: broken `npm start`-command
  nx.json
Labels: v2

#2716 fix(kit): `InputFlies` new value of i18n-token `TUI_INPUT_FILE_TEXTS` triggers text changes
  projects/demo-integrations/cypress/support/commands.ts
  projects/demo-integrations/cypress/support/set-language.ts
  projects/demo-integrations/cypress/tests/kit/input-files/input-files.spec.ts
  projects/i18n/languages/dutch/kit.ts
  projects/i18n/languages/italian/kit.ts
  projects/kit/components/input-files/input-files.component.ts
  projects/kit/components/input-files/input-files.module.ts
  projects/kit/components/input-files/input-files.template.html
  projects/kit/components/input-files/max-size-rejection-error.pipe.ts
Labels: v2

#2726 docs(addon-editor): `Editor` fix `max-height`-description (API-page)
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo/src/modules/components/editor/editor.template.html
Labels: community contribution

#2727 feat(testing): add harness for island
  projects/kit/components/island/test/island.component.spec.ts
  projects/testing/core/index.ts
  projects/testing/core/island.harness.ts
Labels: community contribution

#2747 fix(demo): `Stackblitz` broken styles
  projects/core/styles/theme/dialog.less
  projects/core/styles/theme/wrapper/accent.less
  projects/core/styles/theme/wrapper/base.less
  projects/core/styles/theme/wrapper/icon.less
  projects/core/styles/theme/wrapper/mono.less
  projects/core/styles/theme/wrapper/outline.less
  projects/core/styles/theme/wrapper/primary.less
  projects/core/styles/theme/wrapper/secondary-destructive.less
  projects/core/styles/theme/wrapper/secondary.less
  projects/core/styles/theme/wrapper/table.less
  projects/core/styles/theme/wrapper/textfield.less
  projects/core/styles/theme/wrapper/whiteblock.less
  projects/demo/src/modules/app/stackblitz/project-files/src/stackblitz.less.md
  projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/styles/taiga-ui-global.less
Labels: ready to merge

#2744 fix(cdk): `schematics` add `Node.js < 16`-support
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
  projects/cdk/schematics/ng-update/steps/replace-styles.ts
Labels: ready to merge

#2751 chore: `CHANGELOG` add `Migration guide` for `3.0.0`-release
  CHANGELOG.md
Labels: ready to merge

#2749 fix(core): `Hint` fix offscreen position on small devices
  projects/core/directives/hint/hint.component.ts
  projects/testing/core/badge.harness.ts
Labels: ready to merge

#2584 feat(testing): add component harness test for primitive-textfield component
  projects/core/components/primitive-textfield/test/primitive-textfield.component.spec.ts
  projects/testing/core/index.ts
  projects/testing/core/primitive-textfield.harness.ts
Labels: community contribution

#2757 fix(addon-editor): add deps for starter-kit
  projects/addon-editor/package.json
Labels: ready to merge

#2759 fix(addon-editor): add deps for starter-kit
  package-lock.json
  projects/addon-editor/package.json
Labels: ready to merge

#2763 feat(kit): `InputTime` add checkmark near selected time
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.module.ts
  projects/kit/components/input-time/input-time.template.html
Labels: ready to merge

#2762 feat(core): `Dialog` allow `Default` change detection strategy to work
  projects/cdk/components/alert-host/alert-host.component.ts
  projects/cdk/components/dialog-host/dialog-host.component.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/hints-host/hints-host.component.ts
  projects/core/components/root/root.component.ts
Labels: ready to merge

#2765 fix(addon-editor): add missing starterkit dependencies
  package-lock.json
  projects/addon-editor/package.json
Labels: ready to merge

#2767 chore(demo): fix commands `nx serve-default demo` and `nx serve-shadow demo`
  projects/demo/project.json
  projects/demo/src/modules/app/home/home.component.ts
Labels: ready to merge

#2772 refactor(demo): `Stackblitz` drop legacy code
  projects/addon-doc/src/utils/raw-load.ts
  projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
Labels: ready to merge
