Repository taiga-family/taiga-ui, pull requests merged in 2022-08, with the labels that each got.

#2245 ci: prevent flaky tests
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
  projects/demo-integrations/cypress/tests/addon-icons/customization-icons.spec.ts
  projects/demo-integrations/cypress/tests/core/hint/hint.spec.ts
Labels: ready to merge

#2250 chore: remove redundant line in main branch
  .github/workflows/create-release.yml
Labels: ready to merge

#2244 fix(kit): use `break-all` for `LineClamp`
  projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts
  projects/demo/src/modules/components/line-clamp/line-clamp.component.ts
  projects/demo/src/modules/components/line-clamp/line-clamp.template.html
  projects/kit/components/line-clamp/line-clamp.module.ts
  projects/kit/components/line-clamp/line-clamp.style.less
  projects/kit/components/line-clamp/line-clamp.template.html
Labels: ready to merge

#2255 ci: back is Nx Cloud
  nx.json
  package-lock.json
  package.json
Labels: ready to merge

#2258 chore(demo): `stackblitz` add `backtick` support
  projects/demo/src/modules/app/classes/ts-file-component.parser.ts
Labels: ready to merge

#2262 fix(kit): `Slider` incorrect calculations with `[ngModel]` + `[keySteps]`
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/slider.component.ts
Labels: ready to merge

#2272 refactor!: remove some deprecations
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
  projects/addon-editor/extensions/image-editor/image-editor.component.ts
  projects/addon-editor/services/picker.service.ts
  projects/addon-editor/tokens/image-loader.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.providers.ts
  projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
  projects/addon-mobile/components/sheet/ios.hacks.ts
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/addon-mobile/directives/ripple/ripple.providers.ts
  projects/addon-mobile/directives/touchable/touchable.directive.ts
  projects/addon-preview/components/preview/preview.component.ts
  projects/addon-table/components/table/directives/resized.directive.ts
  projects/cdk/directives/droppable/droppable.directive.ts
  projects/cdk/directives/focused/focused.directive.ts
  projects/cdk/directives/overscroll/overscroll.directive.ts
  projects/cdk/observables/drag-and-drop-from.ts
  projects/cdk/observables/focus-visible-observable.ts
  projects/cdk/observables/mouse-drag-finish-from.ts
  projects/cdk/observables/pressed-observable.ts
  projects/cdk/observables/typed-from-event.ts
  projects/cdk/services/directive-styles.service.ts
  projects/cdk/services/pan.service.ts
  projects/cdk/services/parents-scroll.service.ts
  projects/cdk/services/swipe.service.ts
  projects/cdk/services/zoom.service.ts
  projects/cdk/tokens/active-element.ts
  projects/cdk/tokens/index.ts
  projects/cdk/tokens/sanitizer.ts
  projects/cdk/tokens/window-height.ts
  projects/cdk/utils/miscellaneous/identity.ts
  projects/cdk/utils/miscellaneous/index.ts
  projects/cdk/utils/miscellaneous/test/identity.spec.ts
  projects/core/components/button/button-options.ts
  projects/core/components/data-list/data-list-dropdown-manager.directive.ts
  projects/core/components/dialog/dialog.providers.ts
  projects/core/components/link/link.component.ts
  projects/core/components/scroll-controls/scrollbar.directive.ts
  projects/core/directives/described-by/described-by.providers.ts
  projects/core/directives/textfield-controller/textfield-controller.provider.ts
  projects/core/providers/is-mobile-resolution.provider.ts
  projects/core/providers/mode.provider.ts
  projects/core/tokens/is-mobile-resolution.ts
  projects/core/tokens/sanitizer.ts
  projects/kit/components/carousel/carousel-scroll.directive.ts
  projects/kit/components/carousel/carousel.directive.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/line-clamp/line-clamp.component.ts
  projects/kit/components/range/range-change.directive.ts
  projects/kit/components/select-option/select-option.component.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/helpers/slider-readonly.directive.ts
  projects/kit/components/slider/slider.component.ts
  projects/kit/components/tabs/tab/tab.providers.ts
  projects/kit/directives/dropdown-hover/dropdown-hover.directive.ts
  projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
Labels: v3.0 candidates, ready to merge

#2278 refactor!: remove redundant export of providers' factories
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/addon-commerce/utils/is-card-length-valid.ts
  projects/addon-commerce/utils/is-card-number-valid.ts
  projects/addon-doc/src/components/navigation/navigation.providers.ts
  projects/addon-doc/src/components/page/page.providers.ts
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/editor/editor.providers.ts
  projects/addon-editor/components/input-color/input-color.component.ts
  projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.providers.ts
  projects/addon-mobile/directives/ripple/ripple.providers.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.service.ts
  projects/addon-table/components/table/providers/stuck.provider.ts
  projects/addon-table/components/table/providers/table.providers.ts
  projects/cdk/tokens/is-cypress.ts
  projects/cdk/utils/focus/get-native-focused.ts
  projects/cdk/utils/focus/is-native-focused-in.ts
  projects/cdk/utils/focus/is-native-focused.ts
  projects/cdk/utils/focus/is-native-mouse-focusable.ts
  projects/cdk/utils/focus/move-focus.ts
  projects/cdk/utils/format/px.ts
  projects/core/components/dialog/dialog.providers.ts
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/directives/described-by/described-by.providers.ts
  projects/core/directives/mask-accessor/mask-accessor.directive.ts
  projects/core/directives/textfield-controller/textfield-autocomplete.directive.ts
  projects/core/directives/textfield-controller/textfield-cleaner.directive.ts
  projects/core/directives/textfield-controller/textfield-custom-content.directive.ts
  projects/core/directives/textfield-controller/textfield-example-text.directive.ts
  projects/core/directives/textfield-controller/textfield-input-mode.directive.ts
  projects/core/directives/textfield-controller/textfield-label-outside.directive.ts
  projects/core/directives/textfield-controller/textfield-max-length.directive.ts
  projects/core/directives/textfield-controller/textfield-size.directive.ts
  projects/core/directives/textfield-controller/textfield-type.directive.ts
  projects/demo/src/modules/app/customization/customization.providers.ts
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts
  projects/demo/src/modules/markup/icons/customization/customization-icons.component.ts
  projects/kit/components/input-phone/input-phone.providers.ts
  projects/kit/components/multi-select/multi-select-group/multi-select-group.directive.ts
  projects/kit/components/tabs/tab/tab.providers.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts
  projects/kit/components/tree/components/tree-item/tree-item.providers.ts
  projects/kit/providers/month-formatter.provider.ts
  projects/kit/providers/specific-dropdown-controllers.ts
  projects/testing/utils/helpers.ts
Labels: v3.0 candidates, ready to merge

#2276 refactor!: replace `setNativeFocused(el)` with `el.focus()`
  projects/addon-editor/components/toolbar/toolbar-navigation-manager.directive.ts
  projects/addon-editor/components/toolbar/toolbar.component.ts
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/utils/focus/index.ts
  projects/cdk/utils/focus/move-focus.ts
  projects/cdk/utils/focus/set-native-focused.ts
  projects/cdk/utils/focus/set-native-mouse-focused.ts
  projects/cdk/utils/focus/tests/blur-native-focused.spec.ts
  projects/cdk/utils/focus/tests/set-native-focused.spec.ts
  projects/core/components/data-list/data-list-dropdown-manager.directive.ts
  projects/core/components/data-list/option/option.component.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/demo/src/modules/components/data-list/examples/4/custom-list/custom-list.component.ts
  projects/demo/src/modules/directives/active-zone/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.ts
  projects/kit/components/combo-box/combo-box.component.ts
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input/input.component.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/pagination/pagination.component.ts
  projects/kit/components/select/select.component.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
  projects/kit/components/tag/tag.component.ts
  projects/kit/components/text-area/text-area.component.ts
  projects/kit/directives/dropdown-context/dropdown-context.directive.ts
Labels: v3.0 candidates, ready to merge

#2277 fix(core): card number overlay after autofill in dark theme
  projects/core/styles/mixins/mixins.less
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts
Labels: ready to merge

#2273 Chart hints
  projects/addon-charts/components/bar-chart/bar-chart.component.ts
  projects/addon-charts/components/bar-chart/bar-chart.module.ts
  projects/addon-charts/components/bar-chart/bar-chart.template.html
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/addon-charts/components/line-chart/line-chart.template.html
  projects/addon-charts/components/line-days-chart/line-days-chart.module.ts
  projects/addon-charts/components/line-days-chart/line-days-chart.template.html
  projects/addon-charts/components/pie-chart/pie-chart.component.ts
  projects/addon-charts/components/pie-chart/pie-chart.template.html
  projects/addon-charts/components/ring-chart/ring-chart.component.ts
  projects/core/components/tooltip/tooltip.component.ts
  projects/core/directives/hint-controller/hint-controller.directive.ts
  projects/core/directives/hint-controller/hint-controller.provider.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/directives/hint/hint.style.less
  projects/core/interfaces/hint.ts
  projects/core/types/direction.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.component.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.module.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.style.less
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.template.html
  projects/demo/src/modules/charts/axes/axes.module.ts
  projects/demo/src/modules/charts/axes/examples/2/index.html
  projects/demo/src/modules/charts/bar-chart/bar-chart.component.ts
  projects/demo/src/modules/charts/bar-chart/bar-chart.module.ts
  projects/demo/src/modules/charts/bar-chart/bar-chart.template.html
  projects/demo/src/modules/charts/bar-chart/examples/2/index.html
  projects/demo/src/modules/charts/bar-chart/examples/2/index.ts
  projects/demo/src/modules/charts/line-chart/examples/4/index.html
  projects/demo/src/modules/charts/line-chart/line-chart.component.ts
  projects/demo/src/modules/charts/line-chart/line-chart.module.ts
  projects/demo/src/modules/charts/line-chart/line-chart.template.html
  projects/demo/src/modules/components/abstract/hint-controller-documentation/hint-controller-documentation.template.html
  projects/demo/src/modules/components/abstract/inherited-documentation/inherited-documentation.template.html
  projects/demo/src/modules/components/tooltip/tooltip.template.html
  projects/demo/src/modules/directives/hint-controller/hint-controller.template.html
  projects/kit/components/line-clamp/index.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
  projects/kit/components/line-clamp/line-clamp-box.style.less
  projects/kit/components/line-clamp/line-clamp-box/line-clamp-box.template.html
  projects/kit/components/line-clamp/line-clamp.component.ts
  projects/kit/components/line-clamp/line-clamp.module.ts
Labels: v3.0 candidates, ready to merge

#2280 feat!: move all color-converter utils (`addon-editor` / `addon-doc` => `cdk`)
  projects/addon-doc/src/components/documentation/documentation.component.ts
  projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
  projects/addon-editor/components/color-selector/color-picker/color-picker.component.ts
  projects/addon-editor/components/color-selector/color-selector.component.ts
  projects/addon-editor/utils/hex-to-rgb.ts
  projects/addon-editor/utils/index.ts
  projects/addon-editor/utils/rgb-to-hex.ts
  projects/addon-editor/utils/test/rgb-to-hex.spec.ts
  projects/addon-editor/utils/to-gradient.ts
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/cdk/schematics/ng-update/constants/deprecated-functions.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
  projects/cdk/utils/color/hex-to-rgb.ts
  projects/cdk/utils/color/hsv-to-rgb.ts
  projects/cdk/utils/color/index.ts
  projects/cdk/utils/color/package.json
  projects/cdk/utils/color/parse-color.ts
  projects/cdk/utils/color/rgb-to-hex.ts
  projects/cdk/utils/color/rgb-to-hsv.ts
  projects/cdk/utils/color/test/hex-to-rgb.spec.ts
  projects/cdk/utils/color/test/hsv-to-rgb.spec.ts
  projects/cdk/utils/color/test/parse-color.spec.ts
  projects/cdk/utils/color/test/rgb-to-hex.spec.ts
  projects/cdk/utils/color/test/rgb-to-hsv.spec.ts
  projects/cdk/utils/index.ts
Labels: v3.0 candidates, ready to merge

#2275 fix(cdk): correct autofill value for input controls
  projects/core/components/primitive-textfield/primitive-textfield.style.less
  projects/core/components/primitive-textfield/primitive-textfield.template.html
  projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
Labels: ready to merge

#2282 feat(core): `Button` add `secondary-destructive` appearance
  projects/cdk/directives/autofilled/autofilled.style.less
  projects/core/enums/appearance.ts
  projects/core/styles/theme/wrapper.less
  projects/core/styles/theme/wrapper/secondary-destructive.less
  projects/demo/src/modules/components/button/button.component.ts
  projects/demo/src/modules/components/button/examples/2/index.html
Labels: ready to merge

#2289 chore(demo): prevent compile `i18n/esm2015/*` in proprietary
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/app/app.tabs.ts
Labels: ready to merge

#2284 feat(core): add round corners to paddingless tables
  projects/core/styles/markup/tui-table.less
  projects/demo/src/modules/markup/tables/examples/1/index.html
Labels: ready to merge

#2264 ci: fix e2e flaky again
  projects/demo-integrations/cypress/support/commands.ts
  projects/demo-integrations/cypress/support/hide-doc-page.ts
  projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-groups.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-img.spec.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
  projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts
Labels: ready to merge

#2299 chore: forgot add export for some i18n tokes
  projects/i18n/index.ts
Labels: ready to merge

#2300 ci: improved e2e workflow
  .github/actions/cypress/action.yml
  .github/workflows/e2e.yml
  nx.json
Labels: ready to merge

#2298 refactor!: move some i18n tokens to secondary package
  projects/i18n/switch/language-switcher.providers.ts
  projects/i18n/switch/language-switcher.service.ts
  projects/i18n/tokens/index.ts
  projects/i18n/tokens/language.ts
  projects/i18n/tools/extract-i18n.ts
  projects/i18n/tools/index.ts
Labels: v3.0 candidates, ready to merge

#2305 chore: `Changelog` add section `Deprecations`
  commitlint.config.js
  package.json
Labels: ready to merge

#2286 deprecate(kit): `InputTag` deprecate property `[allowSpaces]`
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.spec.ts
  projects/demo/src/modules/components/input-tag/examples/5/index.less
  projects/demo/src/modules/components/input-tag/examples/6/index.less
  projects/demo/src/modules/components/input-tag/examples/7/index.html
  projects/demo/src/modules/components/input-tag/examples/7/index.ts
  projects/demo/src/modules/components/input-tag/input-tag.component.ts
  projects/demo/src/modules/components/input-tag/input-tag.module.ts
  projects/demo/src/modules/components/input-tag/input-tag.template.html
Labels: ready to merge

#2296 refactor!: remove deprecated entities
  projects/addon-doc/src/components/navigation/navigation.template.html
  projects/cdk/date-time/day.ts
  projects/cdk/date-time/month.ts
  projects/cdk/date-time/test/day.spec.ts
  projects/cdk/date-time/test/month.spec.ts
  projects/cdk/date-time/test/year.spec.ts
  projects/cdk/date-time/year.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
  projects/core/components/data-list/option/option.component.ts
  projects/core/pipes/calendar-sheet/utils.ts
  projects/core/styles/theme/variables.less
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/constants/max-day-range-length-mapper.ts
  projects/kit/interfaces/bread-crumbs-item.ts
  projects/kit/interfaces/index.ts
Labels: v3.0 candidates, ready to merge

#2304 ci: add publish script
  angular.json
  scripts/publish.ts
  scripts/shared/run-standard-verion.ts
Labels: ready to merge

#2302 refactor(kit)!: `Slider[keySteps]` update control value on `input` event (+ delete `keyStepsInput`)
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/types/test/key-steps.spec.ts
Labels: v3.0 candidates, ready to merge

#2281 fix(kit): current range must be a text node only
  projects/demo-integrations/cypress/tests/kit/dropdown-selection/dropdown-selection.spec.ts
  projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
Labels: ready to merge

#2314 chore(demo): `Changelog` fix header font + small customization upgrade
  projects/demo/src/modules/info/changelog/changelog.style.less
Labels: ready to merge

#2315 ci: prevent flaky
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-api.spec.ts
Labels: ready to merge

#2317 feat(kit)!: `DataListDropdownManager` move into separate module
  projects/core/components/data-list/data-list.module.ts
  projects/core/components/data-list/index.ts
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/data-list/data-list.template.html
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.module.ts
  projects/kit/directives/data-list-dropdown-manager/index.ts
  projects/kit/directives/data-list-dropdown-manager/package.json
  projects/kit/directives/index.ts
Labels: ready to merge

#2309 refactor(core)!: `tuiFormatNumber(value, configs)` new function signature
  projects/addon-commerce/components/money/pipes/integer-part.pipe.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
  projects/cdk/schematics/utils/insert-todo.ts
  projects/core/constants/default-number-format.ts
  projects/core/constants/index.ts
  projects/core/interfaces/number-format-settings.ts
  projects/core/pipes/format-number/format-number.pipe.ts
  projects/core/tokens/number-format.ts
  projects/core/utils/format/format-number.ts
  projects/core/utils/format/test/format-number.spec.ts
  projects/demo/src/modules/pipes/format-number/examples/1/index.html
  projects/demo/src/modules/pipes/format-number/format-number.component.ts
  projects/demo/src/modules/pipes/format-number/format-number.template.html
  projects/demo/src/modules/utils/format/examples/6/index.ts
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-number/input-number.component.ts
Labels: v3.0 candidates, ready to merge

#2322 ci: decomposition angular.json file
  angular.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
Labels: ready to merge

#2324 chore(cdk): add proprietary package to ng-update package group
  projects/cdk/package.json
Labels: ready to merge

#2321 ci: prevent some problems when use proprietary workspace
  package.json
Labels: ready to merge

#2328 fix: prevent emit `null` for editor
  projects/addon-editor/components/toolbar-tools/align-content/align-content.template.html
  projects/addon-editor/components/toolbar-tools/font-style/font-style.module.ts
  projects/addon-editor/components/toolbar-tools/font-style/font-style.template.html
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
  projects/addon-editor/components/toolbar-tools/table-merge-cells/table-merge-cells.template.html
  projects/kit/components/input-password/input-password.module.ts
  projects/kit/components/input-password/input-password.template.html
Labels: ready to merge

#2329 fix(kit): support dark-theme for `TuiLazyLoadingDirective`
  projects/kit/directives/lazy-loading/lazy-loading.directive.ts
  projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
Labels: ready to merge

#2330 chore(demo): ssr build errors
  .github/workflows/e2e.yml
  projects/demo/project.json
  projects/demo/tsconfig.app.json
  projects/demo/tsconfig.server.json
Labels: ready to merge

#2327 refactor!: remove deprecations
  projects/core/components/button/button-options.ts
  projects/core/components/button/button.component.ts
  projects/core/components/data-list/option/option.component.ts
  projects/core/components/expand/expand.template.html
  projects/core/internal/svg-defs-host/svg-defs-host.component.ts
  projects/core/utils/index.ts
  projects/core/utils/polyfills/index.ts
  projects/core/utils/polyfills/inner-html.ts
  projects/core/utils/polyfills/package.json
  projects/demo/src/modules/components/input-tag/input-tag.component.ts
  projects/demo/src/modules/components/input-tag/input-tag.template.html
  projects/kit/components/input-tag/input-tag-options.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-tag/input-tag.template.html
  projects/kit/components/input-tag/test/input-tag-no-mode.component.spec.ts
  projects/kit/components/input-tag/test/input-tag.component.spec.ts
  projects/kit/components/tag/tag.component.ts
  projects/kit/tokens/index.ts
  projects/kit/tokens/tag-status.ts
  stylelint.config.js
Labels: v3.0 candidates, ready to merge

#2338 fix(kit): `Tabs` fix opening dropdown on clicking margin area
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
Labels: ready to merge

#2339 feat(core): `Button` add `mono` style
  projects/core/styles/theme/wrapper.less
  projects/core/styles/theme/wrapper/mono.less
  projects/demo/src/modules/components/button/button.component.ts
Labels: ready to merge

#2342 chore(demo): new documentation page `Breakpoints`
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/markup/breakpoints/breakpoints.component.ts
  projects/demo/src/modules/markup/breakpoints/breakpoints.module.ts
  projects/demo/src/modules/markup/breakpoints/breakpoints.style.less
  projects/demo/src/modules/markup/breakpoints/breakpoints.template.html
  projects/demo/src/modules/markup/breakpoints/examples/1/index.html
  projects/demo/src/modules/markup/breakpoints/examples/1/index.less
  projects/demo/src/modules/markup/breakpoints/examples/1/index.ts
  projects/demo/src/modules/markup/breakpoints/examples/import/base-breakpoint-usage.md
  projects/demo/src/modules/markup/breakpoints/examples/import/import-taiga-ui-local-less.md
Labels: ready to merge

#2343 fix(cdk): don't override deep imports inside less files
  projects/cdk/schematics/ng-update/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
  projects/cdk/schematics/ng-update/steps/replace-deep-import.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
  projects/cdk/schematics/utils/angular/ng-module.ts
Labels: ready to merge

#2345 chore(demo): fix import
  projects/demo/src/modules/app/app.routes.ts
Labels: ready to merge

#2344 fix(i18n): `InputFiles` small misspells corrections (English)
  projects/i18n/languages/english/kit.ts
Labels: ready to merge

#2352 chore(demo): `Breakpoints` documentation page updates
  projects/demo-integrations/cypress/support/shared.entities.ts
  projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
  projects/demo/src/modules/markup/breakpoints/examples/1/index.less
  projects/demo/src/modules/markup/breakpoints/examples/1/index.ts
Labels: ready to merge

#2354 fix(core): set transparent of autofill only for bank cards
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/core/styles/mixins/mixins.less
Labels: ready to merge

#2355 ci: prevent override range in peerDependencies
  scripts/shared/bump-tui-deps.ts
  scripts/shared/sync-versions.ts
  scripts/shared/update-package-json-structure.ts
Labels: ready to merge

#2347 chore: minor tweaks
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
  projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
  projects/cdk/abstract/portal-host.ts
  projects/cdk/observables/items-query-list-observable.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/hints-host/hints-host.component.ts
  projects/core/components/hints-host/hints-host.template.html
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/interfaces/hint.ts
  projects/core/interfaces/index.ts
  projects/core/interfaces/portal-item.ts
  projects/core/services/hint.service.ts
  projects/demo/src/modules/components/abstract/control.ts
  projects/demo/src/modules/components/button/examples/3/index.html
  projects/demo/src/modules/components/button/examples/3/index.ts
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/demo/src/modules/components/input-phone-international/input-phone-international.component.ts
  projects/demo/src/modules/components/input-phone/input-phone.component.ts
  projects/demo/src/modules/components/input-time/input-time.component.ts
  projects/demo/src/modules/components/multi-select/multi-select.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.template.html
Labels: ready to merge

#2333 fix(core): css media breakpoints correction (edge cases)
  projects/core/styles/variables/media-old.less
  projects/core/styles/variables/media.less
  projects/core/styles/variables/media.scss
Labels: ready to merge

#2351 ci: add `nx` facade for `ng` cli
  package.json
  scripts/nx/decorate-angular-cli.ts
  scripts/postinstall.ts
Labels: ready to merge

#2359 chore(demo): reuse app logic for proprietary demo
  projects/demo-integrations/cypress/support/hide-header.ts
  projects/demo-integrations/cypress/support/hide-language-switcher.ts
  projects/demo-integrations/cypress/support/hide-navigation.ts
  projects/demo-integrations/cypress/support/hide-version-manager.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/theme.service.ts
Labels: ready to merge

#2366 ci: improved cache processing for taiga-schematics project
  projects/taiga-schematics/project.json
Labels: ready to merge

#2368 fix(cdk): `ParentAnimation` properly query direct child
  projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html
  projects/cdk/constants/parent-animation.ts
Labels: ready to merge

#2367 ci: simplify cypress startup commands
  .github/workflows/e2e.yml
  package-lock.json
  package.json
  projects/demo/project.json
Labels: ready to merge

#2371 chore(cdk): `schematics` backtick problem + exclude schematic and typing-files
  projects/cdk/schematics/constants/file-globs.ts
  projects/cdk/schematics/constants/index.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
  projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/steps/replace-deep-import.ts
  projects/cdk/schematics/ng-update/steps/replace-enums.ts
  projects/cdk/schematics/ng-update/steps/show-warnings.ts
  projects/cdk/schematics/utils/angular/ng-module.ts
  projects/cdk/schematics/utils/get-named-import-references.ts
  projects/cdk/schematics/utils/templates/get-component-templates.ts
Labels: ready to merge

#2376 chore(cdk): `schematics` more logs
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/utils/get-execution-time.ts
  projects/cdk/schematics/utils/progress.ts
Labels: ready to merge

#2362 refactor!: `AlertComponent` use new context
  projects/cdk/schematics/ng-update/constants/warnings.ts
  projects/core/components/alert/alert.component.ts
  projects/core/components/alert/alert.template.html
  projects/demo/src/modules/services/alerts/alerts.template.html
  projects/demo/src/modules/services/alerts/examples/3/alert-example/alert-example.component.ts
  projects/demo/src/modules/services/alerts/examples/4/alert-example-with-data/alert-example-with-data.component.ts
  projects/demo/src/modules/services/alerts/examples/5/alert-example-with-custom-label/alert-example-with-custom-label.component.ts
  projects/demo/src/modules/services/alerts/examples/import/custom-alert.md
Labels: v3.0 candidates, ready to merge

#2377 chore: flaky
  projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts
  projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts
  projects/demo-integrations/cypress/tests/kit/tabs/tabs.spec.ts
Labels: ready to merge

#2372 ci: expose config for proprietary repo
  projects/demo-integrations/cypress.config.ts
Labels: ready to merge

#2385 ci: move new issues into Triage
  .github/workflows/move-opened-issue.yml
Labels: ready to merge

#2388 ci: fix flaky
  projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
Labels: ready to merge

#2384 fix(i18n): support typings for custom languages
  projects/i18n/README.md
  projects/i18n/interfaces/language-names.ts
Labels: ready to merge

#2396 chore: fix typo
  .github/workflows/move-opened-issue.yml
Labels: ready to merge

#2386 chore(cdk): `schematics` v3.x migration `RangeError`
  projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
  projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts
Labels: ready to merge

#2391 feat!: update supported browser versions (bump supported `Safari` to `12.1+`)
  projects/demo/src/modules/info/browsers/browsers.template.html
Labels: v3.0 candidates, ready to merge

#2397 feat(kit): `Badge` add new `xs` size
  projects/demo/src/modules/components/badge/badge.component.ts
  projects/demo/src/modules/components/badge/examples/2/index.html
  projects/kit/components/badge/badge.component.ts
  projects/kit/components/badge/badge.style.less
  projects/kit/components/badged-content/badged-content.component.ts
  projects/kit/components/badged-content/badged-content.style.less
  projects/kit/components/badged-content/badged-content.template.html
Labels: ready to merge

#2394 ci: increase timeout for slow jobs
  projects/demo-integrations/cypress.config.ts
  projects/demo-integrations/cypress/plugins/index.ts
  projects/demo-integrations/cypress/support/shared.entities.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/addon-preview/addon-preview.spec.ts
  projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts
  projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts
  projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts
  projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts
Labels: ready to merge

#2399 chore(cdk): `FeedItem` migration
  projects/cdk/schematics/ng-update/constants/templates.ts
Labels: ready to merge

#2403 fix(kit): `tui-text-area` label alignment on IOS
  projects/kit/components/text-area/text-area.style.less
Labels: ready to merge

#2401 fix(core): use `textContent` instead of `innerText`
  projects/core/components/primitive-calendar/primitive-calendar.template.html
  projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
  projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
  projects/kit/components/input-date/test/input-date.component.spec.ts
  projects/kit/components/input-tag/input-tag.template.html
  projects/kit/components/input-tag/test/input-tag.component.spec.ts
  projects/kit/components/multi-select/test/multi-select.component.spec.ts
Labels: ready to merge

#2405 ci: `npm ci` error `SyntaxError: Cannot use import statement outside a module`
  scripts/nx/decorate-angular-cli.ts
Labels: ready to merge

#2393 feat!: new names of css breakpoints
  projects/addon-doc/src/components/main/main.style.less
  projects/addon-doc/src/internal/header/header.style.less
  projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less
  projects/cdk/schematics/ng-update/constants/breakpoints.ts
  projects/cdk/schematics/ng-update/steps/replace-styles.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
  projects/core/components/group/group.style.less
  projects/core/styles/variables/media.less
  projects/core/styles/variables/media.scss
  projects/demo/src/modules/charts/legend-item/examples/1/index.less
  projects/demo/src/modules/charts/legend-item/examples/2/index.less
  projects/demo/src/modules/components/input-slider/examples/1/index.less
  projects/demo/src/modules/components/input-slider/examples/2/index.less
  projects/demo/src/modules/components/input-slider/examples/3/index.less
  projects/demo/src/modules/components/input-slider/examples/4/index.less
  projects/demo/src/modules/components/multi-select/examples/2/index.less
  projects/demo/src/modules/components/progress-bar/examples/1/index.less
  projects/demo/src/modules/components/progress-bar/examples/2/index.less
  projects/demo/src/modules/components/progress-bar/examples/3/index.less
  projects/demo/src/modules/components/progress-bar/examples/4/index.less
  projects/demo/src/modules/components/progress-bar/examples/5/index.less
  projects/demo/src/modules/components/progress-bar/progress-bar.component.less
  projects/demo/src/modules/components/progress-segmented/examples/1/index.less
  projects/demo/src/modules/components/progress-segmented/examples/2/index.less
  projects/demo/src/modules/components/progress-segmented/examples/3/index.less
  projects/demo/src/modules/components/range/examples/2/index.less
  projects/demo/src/modules/components/slider/examples/6/index.less
  projects/demo/src/modules/markup/breakpoints/breakpoints.component.ts
  projects/demo/src/modules/markup/breakpoints/examples/1/index.less
  projects/demo/src/modules/markup/breakpoints/examples/1/index.ts
  projects/demo/src/modules/markup/breakpoints/examples/import/base-breakpoint-usage.md
  projects/styles/markup/tui-container-old.less
  projects/styles/markup/tui-container.less
  projects/styles/markup/tui-form-old.less
  projects/styles/markup/tui-form.less
  projects/styles/markup/tui-group-old.less
  projects/styles/markup/tui-mobile-only.less
  projects/styles/markup/tui-row-old.less
  projects/styles/markup/tui-row.less
Labels: v3.0 candidates, ready to merge

#2407 chore(demo): `stackblitz` fix error `Could not import wrapper/mono.less`
  projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
Labels: ready to merge

#2415 chore(cdk): `schematics` migration v3.x code comments causes `Manipulation error`
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
Labels: ready to merge

#2422 ci: move new issues into triage
  .github/workflows/add-to-project.yml
Labels: ready to merge

#2416 ci: prevent recalculate cache when spec.ts files changed
  .eslintrc.js
  nx.json
  package-lock.json
  package.json
Labels: ready to merge

#2424 chore(cdk): add schematic for migrate `tds` icons
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-tds.spec.ts
Labels: ready to merge

#2387 fix(core): character descenders overflow the line
  projects/core/components/primitive-textfield/primitive-textfield.style.less
  projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
  projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
  projects/demo-integrations/cypress/tests/kit/input/input.spec.ts
Labels: ready to merge

#2427 ci: fix typo
  .github/workflows/add-to-project.yml
Labels: ready to merge

#2428 ci: run schematics via `schematics ./dist/cdk:updateToV3 --allow-private --skip-deep-imports`
  projects/cdk/project.json
  projects/cdk/schematics/collection.json
  projects/cdk/schematics/constants/file-globs.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/schema.json
  projects/taiga-schematics/project.json
  tsconfig.schematics.json
Labels: ready to merge

#2375 fix(addon-editor): fix tab behaviour
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.component.ts
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
  projects/addon-editor/constants/tiptap-editor-styles.ts
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/addon-editor/extensions/indent-outdent.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-new-api.spec.ts
  projects/demo/src/modules/components/editor-new/examples/2/index.ts
  projects/demo/src/modules/components/editor-new/examples/3/index.ts
  projects/demo/src/modules/components/editor-new/examples/4/index.html
  projects/demo/src/modules/components/editor-new/examples/4/index.less
  projects/demo/src/modules/components/editor-new/examples/5/index.ts
  projects/demo/src/modules/components/editor-new/examples/6/index.ts
Labels: ready to merge

#2402 chore(demo): improved search in icons page
  projects/cdk/pipes/index.ts
  projects/cdk/pipes/keys/index.ts
  projects/cdk/pipes/keys/keys.module.ts
  projects/cdk/pipes/keys/keys.pipe.ts
  projects/cdk/pipes/keys/package.json
  projects/demo/src/modules/markup/icons/icons-group/icons-group.component.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.directive.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.module.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.style.less
  projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
  projects/demo/src/modules/markup/icons/icons.component.ts
  projects/demo/src/modules/markup/icons/icons.module.ts
  projects/demo/src/modules/markup/icons/icons.style.less
  projects/demo/src/modules/markup/icons/icons.template.html
  projects/demo/src/modules/markup/icons/icons.tokens.ts
  projects/demo/src/modules/markup/icons/pipes/icon-highlight.pipe.ts
Labels: ready to merge

#2434 ci: fix broken e2e tests
  projects/demo-integrations/cypress/support/editor/html.ts
Labels: ready to merge

#2437 refactor!: `Stepper` rename `state` input to avoid collision with `routerLink`
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/demo/src/modules/components/stepper/examples/1/index.html
  projects/demo/src/modules/components/stepper/stepper.template.html
  projects/kit/components/stepper/step/step.component.ts
Labels: v3.0 candidates, ready to merge

#2414 feat(cdk): schematics shouldn't be a direct depended on cdk
  projects/cdk/constants/index.ts
  projects/cdk/constants/version.ts
  projects/cdk/project.json
  projects/cdk/schematics/ng-add/constants/versions.ts
  projects/core/components/root/root.component.ts
  projects/core/constants/version.ts
  projects/demo/src/modules/app/version-manager/versions.constants.ts
  projects/taiga-schematics/package.json
  projects/taiga-schematics/project.json
  projects/taiga-schematics/schematics/ng-add/constants/versions.ts
  projects/taiga-schematics/tsconfig.schematics.json
  scripts/postbump.ts
  scripts/shared/overwrite-version.ts
  tsconfig.schematics.json
Labels: ready to merge

#2436 feat(cdk)!: add configuration to `tuiGetClosestFocusableElement`
  projects/addon-editor/components/toolbar/toolbar-navigation-manager.directive.ts
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/schematics/ng-update/constants/deprecated-functions.ts
  projects/cdk/schematics/ng-update/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
  projects/cdk/utils/focus/get-closest-focusable.ts
  projects/cdk/utils/focus/index.ts
  projects/cdk/utils/focus/tests/get-closest-keyboard.spec.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
Labels: v3.0 candidates, ready to merge

#2441 ci: use postinstall script in proprietary repo
  scripts/postinstall.ts
Labels: ready to merge

#2439 chore(demo): provide icon group key
  projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
Labels: ready to merge

#2446 ci: fixup postinstall script in proprietary repo
  scripts/postinstall.ts
Labels: ready to merge

#2447 chore(cdk): fix migration for global styles
  projects/cdk/schematics/constants/taiga-styles.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-hints.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-progress.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-sliders.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-tds.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-miscellaneous.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-enums.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-warnings.spec.ts
  projects/cdk/schematics/utils/add-styles.ts
Labels: v3.0 candidates

#2417 ci: wait load images inside subject before screenshot
  projects/demo-integrations/cypress.config.ts
  projects/demo-integrations/cypress/support/commands.ts
  projects/demo-integrations/cypress/support/hide-doc-page.ts
  projects/demo-integrations/cypress/support/hide-header.ts
  projects/demo-integrations/cypress/support/hide-language-switcher.ts
  projects/demo-integrations/cypress/support/hide-navigation.ts
  projects/demo-integrations/cypress/support/hide-version-manager.ts
  projects/demo-integrations/cypress/support/visit.ts
  projects/demo-integrations/cypress/tests/demo/landing.spec.ts
  projects/demo-integrations/cypress/tests/kit/button/button.spec.ts
  projects/demo-integrations/cypress/tests/kit/combo-box/combo-box.spec.ts
  projects/testing/cypress/commands/wait-all-img-inside.command.ts
  projects/testing/cypress/index.ts
  projects/testing/cypress/snapshot/command.ts
Labels: ready to merge

#2462 chore(cdk): fix polymorpheus migration
  projects/cdk/schematics/ng-update/steps/migrate-polymorpheus.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
Labels: v3.0 candidates

#2457 refactor(demo): delete some legacy code
  projects/cdk/schematics/ng-update/constants/enums.ts
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.template.html
  projects/demo/src/modules/components/select/examples/7/index.html
  projects/demo/src/modules/directives/highlight/examples/1/index.html
  projects/demo/src/modules/directives/highlight/highlight.module.ts
  projects/demo/src/modules/markup/form/example/index.html
  projects/demo/src/modules/pipes/field-error/examples/2/index.html
  projects/demo/src/modules/pipes/format-number/format-number.module.ts
  projects/demo/src/modules/pipes/format-number/format-number.template.html
Labels: ready to merge

#2464 chore(addon-charts): `PieChart` add `tuiHintContent`-directive support
  projects/addon-charts/components/pie-chart/pie-chart.component.ts
  projects/demo/src/modules/charts/pie-chart/examples/2/index.html
  projects/demo/src/modules/charts/pie-chart/pie-chart.module.ts
  projects/demo/src/modules/charts/pie-chart/pie-chart.template.html
Labels: ready to merge

#2459 chore: add schematics for migrate `proprietary-banking`
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-proprietary-consts.spec.ts
Labels: v3.0 candidates

#2452 chore(core): `Button` allow dynamic switch of appearance with DI
  projects/core/components/button/button.component.ts
  projects/core/components/button/button.template.html
Labels: ready to merge

#2468 feat(cdk): `FormatDate` add new pipe
  package-lock.json
  projects/addon-tablebars/services/table-bars.service.ts
  projects/cdk/observables/index.ts
  projects/cdk/observables/is-observed.ts
  projects/core/components/notification/notification.component.ts
  projects/core/pipes/format-date/format-date.module.ts
  projects/core/pipes/format-date/format-date.pipe.ts
  projects/core/pipes/format-date/index.ts
  projects/core/pipes/format-date/package.json
  projects/core/pipes/index.ts
  projects/core/services/format-date.service.ts
  projects/core/services/index.ts
  projects/demo/package.json
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/pipes/format-date/examples/1/index.html
  projects/demo/src/modules/pipes/format-date/examples/1/index.ts
  projects/demo/src/modules/pipes/format-date/examples/1/service.ts
  projects/demo/src/modules/pipes/format-date/examples/import/import-module.md
  projects/demo/src/modules/pipes/format-date/examples/import/insert-template.md
  projects/demo/src/modules/pipes/format-date/examples/import/provide-service.md
  projects/demo/src/modules/pipes/format-date/format-date.component.ts
  projects/demo/src/modules/pipes/format-date/format-date.module.ts
  projects/demo/src/modules/pipes/format-date/format-date.template.html
  projects/demo/src/modules/pipes/format-number/format-number.template.html
  projects/demo/src/modules/pipes/format-phone/format-phone.template.html
  projects/kit/components/files/file/file.component.ts
Labels: ready to merge

#2470 chore(cdk): `schematics` error-handling for not-supported angular.json
  projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
  projects/cdk/schematics/ng-update/index.ts
  projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
  projects/cdk/schematics/utils/angular-json-manipulations.ts
Labels: v3.0 candidates, ready to merge

#2472 chore: fix button default appearance
  projects/core/components/button/button-options.ts
  projects/core/components/button/button.component.ts
  projects/demo/src/modules/components/button/examples/1/index.ts
Labels: v3.0 candidates, ready to merge

#2469 feat(kit): `Push` add new component
  projects/demo/src/assets/images/roy.jpg
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/push/examples/1/index.html
  projects/demo/src/modules/components/push/examples/1/index.less
  projects/demo/src/modules/components/push/examples/1/index.ts
  projects/demo/src/modules/components/push/examples/2/index.html
  projects/demo/src/modules/components/push/examples/2/index.ts
  projects/demo/src/modules/components/push/examples/3/index.html
  projects/demo/src/modules/components/push/examples/3/index.ts
  projects/demo/src/modules/components/push/examples/import/import-module.md
  projects/demo/src/modules/components/push/examples/import/insert-template.md
  projects/demo/src/modules/components/push/push.component.ts
  projects/demo/src/modules/components/push/push.module.ts
  projects/demo/src/modules/components/push/push.template.html
  projects/kit/components/index.ts
  projects/kit/components/push/index.ts
  projects/kit/components/push/package.json
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/push/push-alert.directive.ts
  projects/kit/components/push/push-alert.style.less
  projects/kit/components/push/push-alert.template.html
  projects/kit/components/push/push.component.ts
  projects/kit/components/push/push.directive.ts
  projects/kit/components/push/push.module.ts
  projects/kit/components/push/push.options.ts
  projects/kit/components/push/push.service.ts
  projects/kit/components/push/push.style.less
  projects/kit/components/push/push.template.html
Labels: ready to merge

#2479 refactor(kit)!: `Action` refactor to `button[tuiAction], a[tuiAction]`
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/demo/src/modules/components/action/action.component.ts
  projects/demo/src/modules/components/action/action.template.html
  projects/demo/src/modules/components/action/examples/1/index.html
  projects/demo/src/modules/components/action/examples/1/index.less
  projects/demo/src/modules/components/action/examples/import/insert-template.md
  projects/kit/components/action/action.component.ts
  projects/kit/components/action/action.style.less
  projects/kit/components/action/action.template.html
Labels: v3.0 candidates, ready to merge

#2483 chore: reuse schematics from @taiga-ui/cdk
  projects/taiga-schematics/karma.conf.js
  projects/taiga-schematics/package.json
  projects/taiga-schematics/project.json
  projects/taiga-schematics/schematics/collection.json
  projects/taiga-schematics/schematics/ng-add/constants/modules.ts
  projects/taiga-schematics/schematics/ng-add/constants/versions.ts
  projects/taiga-schematics/schematics/ng-add/index.ts
  projects/taiga-schematics/schematics/ng-add/schema.json
  projects/taiga-schematics/schematics/ng-add/schema.ts
  projects/taiga-schematics/schematics/ng-add/setup-project.ts
  projects/taiga-schematics/schematics/ng-add/steps/add-taiga-icons.ts
  projects/taiga-schematics/schematics/ng-add/steps/add-taiga-modules.ts
  projects/taiga-schematics/schematics/ng-add/steps/add-taiga-styles.ts
  projects/taiga-schematics/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
  projects/taiga-schematics/schematics/utils/get-project-target-options.ts
  projects/taiga-schematics/schematics/utils/get-project.ts
  projects/taiga-schematics/test.ts
  projects/taiga-schematics/tsconfig.schematics.json
  projects/taiga-schematics/tsconfig.spec.json
Labels: v3.0 candidates

#2493 chore(cdk): add hover/focus/active button migration
  projects/cdk/schematics/ng-update/constants/templates.ts
Labels: v3.0 candidates, ready to merge

#2445 chore(cdk): add textfield-controller migration
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/cdk/schematics/ng-update/constants/tui-interactive-selectors.ts
  projects/cdk/schematics/ng-update/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/steps/migrate-textfield-controller.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
  projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts
  projects/cdk/schematics/utils/templates/elements.ts
Labels: v3.0 candidates, ready to merge

#2500 refactor!: remove autofill enums
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/addon-commerce/components/input-cvc/input-cvc.component.ts
  projects/addon-commerce/components/input-expire/input-expire.component.ts
  projects/cdk/enums/autocomplete.ts
  projects/cdk/enums/index.ts
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/cdk/schematics/ng-update/constants/enums.ts
  projects/cdk/types/autocomplete.ts
  projects/cdk/types/index.ts
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
Labels: v3.0 candidates, ready to merge

#2499 chore(demo): delete usage of `raw-loader`
  projects/demo/src/modules/components/push/push.component.ts
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.component.ts
  projects/demo/src/modules/info/testing/jest/jest.component.ts
  projects/demo/src/modules/info/testing/screenshot-github-bot/screenshot-github-bot.component.ts
  projects/demo/src/modules/pipes/format-date/format-date.component.ts
Labels: v3.0 candidates, ready to merge

#2504 chore(cdk): tuiHintDescribe migration
  projects/cdk/schematics/ng-update/constants/modules.ts
  projects/cdk/schematics/ng-update/constants/templates.ts
Labels: v3.0 candidates, ready to merge

#2498 chore: remove `taiga-ui` package after ng-add
  projects/cdk/schematics/ng-add/index.ts
Labels: v3.0 candidates, ready to merge

#2503 fix(cdk): support to override return type in compile time for dialogs
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
  projects/cdk/abstract/dialog.service.ts
  projects/core/components/alert/alert.service.ts
  projects/demo/src/modules/customization/dialogs/examples/1/index.ts
  projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.service.ts
  projects/kit/components/push/push.service.ts
Labels: ready to merge

#2496 fix(cdk)!: the `tuiLet` directive can possibility emit of null
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/addon-editor/components/toolbar-tools/align-content/align-content.template.html
  projects/addon-editor/components/toolbar-tools/highlight-color/highlight-color.template.html
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
  projects/addon-editor/components/toolbar-tools/table-cell-color/table-cell-color.template.html
  projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.template.html
  projects/cdk/components/dialog-host/dialog-host.template.html
  projects/cdk/directives/let/let.directive.ts
  projects/core/components/scroll-controls/scroll-controls.template.html
  projects/demo/src/modules/components/input-phone/examples/3/index.html
  projects/demo/src/modules/components/input/examples/4/index.html
  projects/demo/src/modules/components/input/examples/8/index.html
  projects/demo/src/modules/tables/table/examples/4/index.html
  projects/kit/components/input-date-range/input-date-range.template.html
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/line-clamp/line-clamp.template.html
Labels: v3.0 candidates, ready to merge

#2505 feat(kit)!: `Action` better customization + new API
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/components/action/action.component.ts
  projects/demo/src/modules/components/action/action.module.ts
  projects/demo/src/modules/components/action/action.template.html
  projects/demo/src/modules/components/action/examples/3/index.html
  projects/demo/src/modules/components/action/examples/3/index.less
  projects/demo/src/modules/components/action/examples/3/index.ts
  projects/demo/src/modules/components/action/examples/4/index.html
  projects/demo/src/modules/components/action/examples/4/index.less
  projects/demo/src/modules/components/action/examples/4/index.ts
  projects/demo/src/modules/components/action/examples/5/index.html
  projects/demo/src/modules/components/action/examples/5/index.less
  projects/demo/src/modules/components/action/examples/5/index.ts
  projects/demo/src/modules/components/action/examples/import/insert-template.md
  projects/demo/src/modules/components/island/island.module.ts
  projects/demo/src/modules/components/island/island.template.html
  projects/kit/components/action/action.component.ts
  projects/kit/components/action/action.style.less
  projects/kit/components/action/action.template.html
  projects/styles/markup/tui-island.less
Labels: ready to merge

#2501 feat(core)!: remove `tuiExpandContent` directive
  projects/addon-doc/src/components/demo/demo.template.html
  projects/cdk/schematics/ng-update/constants/templates.ts
  projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
  projects/core/components/expand/expand-content.directive.ts
  projects/core/components/expand/expand.component.ts
  projects/core/components/expand/expand.module.ts
  projects/core/components/expand/index.ts
  projects/core/components/expand/test/expand.component.spec.ts
  projects/demo/src/modules/components/expand/examples/1/index.html
  projects/demo/src/modules/components/expand/examples/import/insert-template.md
  projects/demo/src/modules/components/expand/expand.template.html
  projects/kit/components/accordion/accordion-item/accordion-item.template.html
Labels: v3.0 candidates, ready to merge

#2512 ci: small fix for concurrency problem
  projects/demo/project.json
Labels: ready to merge

#2509 ci: link any issues to taiga-ui project
  .github/workflows/add-to-project.yml
Labels: ready to merge

#2514 chore(cdk): migration for some types
  projects/cdk/schematics/ng-update/constants/consts.ts
  projects/cdk/schematics/ng-update/constants/enums.ts
Labels: v3.0 candidates, ready to merge

#2508 fix(core): prevent injection conflict with CSS global interface
  projects/cdk/types/index.ts
  projects/cdk/types/injection-token-type.ts
  projects/core/components/scrollbar/scrollbar.component.ts
Labels: ready to merge

#2515 chore(cdk): fix parsing utf-8 with BOM
  projects/cdk/schematics/utils/templates/elements.ts
Labels: v3.0 candidates, ready to merge

#2518 chore: eslint errors
  .eslintrc.js
  projects/core/components/scrollbar/scrollbar.component.ts
Labels: v3.0 candidates, ready to merge

#2520 chore: enable e2e for `v3.x`-branch
  .github/workflows/e2e.yml
Labels: v3.0 candidates

#2528 ci: fixup bump version
  scripts/shared/bump-version.ts
Labels: ready to merge

#2526 chore: cleanup
  .github/workflows/autorebase-v3.yml
  .github/workflows/deploy-next.yml
  .github/workflows/e2e.yml
Labels: ready to merge

#2530 chore(demo): `Changelog` update description of `3.0.0`-release
  CHANGELOG.md
Labels: ready to merge

#2535 fix(core): `DropdownContext` close previous dropdown after new one is opened
  projects/core/directives/dropdown/dropdown-context.directive.ts
  projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts
  projects/demo/src/modules/components/island/island.template.html
Labels: ready to merge

#2537 refactor: compat with TypeScript 4.6+
  projects/cdk/constants/empty.ts
  projects/cdk/tokens/is-webkit.ts
  projects/cdk/utils/dom/point-to-client-rect.ts
  projects/core/utils/dom/get-word-range.ts
  projects/kit/directives/highlight/highlight.directive.ts
Labels: ready to merge

#2539 chore(demo): `webpack.config.ts` add `css`-files with `?raw`-query to webpack assets modules
  projects/demo/webpack.config.ts
Labels: ready to merge

#2540 chore(demo): fix texarea API tab
  projects/demo/src/modules/components/text-area/text-area.template.html
Labels: ready to merge

#2542 refactor: compat with TypeScript 4.6+
  .gitignore
  .prettierignore
  projects/addon-doc/src/components/navigation/navigation.component.ts
  projects/addon-table/components/table/directives/head.directive.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/addon-table/components/table/tr/tr.template.html
  projects/cdk/schematics/utils/get-project.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/data-list/examples/5/index.ts
  projects/demo/src/modules/components/editor/examples/2/index.html
  projects/demo/src/modules/components/editor/examples/3/index.html
  projects/demo/src/modules/components/editor/examples/4/index.html
  projects/demo/src/modules/components/editor/examples/5/index.html
  projects/demo/src/modules/components/editor/examples/6/index.html
  projects/demo/src/modules/components/editor/examples/7/index.html
  projects/demo/src/modules/components/input-card/examples/1/index.ts
  projects/demo/src/modules/components/input-files/examples/2/index.ts
  projects/demo/src/modules/components/input-slider/examples/2/index.ts
  projects/demo/src/modules/components/input-tag/examples/4/index.ts
  projects/demo/src/modules/components/input/examples/4/index.ts
  projects/demo/src/modules/components/input/examples/8/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/utils/format/examples/1/index.ts
  projects/demo/src/modules/utils/format/examples/3/index.ts
  projects/demo/src/modules/utils/format/examples/4/index.ts
  projects/demo/src/modules/utils/format/examples/5/index.ts
  projects/demo/src/modules/utils/format/examples/6/index.ts
  projects/demo/src/modules/utils/math/examples/1/index.ts
  projects/demo/src/modules/utils/math/examples/2/index.ts
  projects/demo/src/modules/utils/math/examples/3/index.ts
  projects/demo/src/modules/utils/math/examples/4/index.ts
  projects/demo/src/modules/utils/math/examples/5/index.ts
  projects/demo/src/modules/utils/miscellaneous/examples/4/index.ts
  projects/demo/src/modules/utils/miscellaneous/examples/5/index.ts
  projects/icons/scripts/rollup-svgo.ts
  projects/testing/cypress/commands/wait-all-img-inside.command.ts
  projects/testing/utils/input/cleaner.unit-common.ts
Labels: ready to merge

#2544 fix(cdk): `schematics` fix 3.0-migration for `tuiTextfieldInputMode`
  projects/cdk/schematics/ng-update/steps/migrate-textfield-controller.ts
  projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
Labels: ready to merge
