Repository taiga-family/taiga-ui, pull requests merged in 2023-02, with the labels that each got.

#3553 chore(demo): `Getting started`-page fix wrong import
  projects/demo/src/modules/app/home/home.component.ts
Labels: ready to merge

#3554 chore: add `minMoreWidth` to tabs options
  projects/kit/components/tabs/tabs-options.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
Labels: ready to merge

#3536 fix(addon-mobile): wait before update viewport dimension
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: ready to merge

#3559 chore: `lint-staged` remove redundant command
  package.json
Labels: ready to merge

#3558 fix(cdk): `Schematics` add `tuiDropdownContext` migration
  projects/cdk/schematics/ng-update/v3/constants/templates.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-html.spec.ts
Labels: ready to merge

#3552 ci: `tsconfig.json` update `compilerOptions.lib`
  projects/addon-doc/src/components/example/example.component.ts
  projects/cdk/utils/miscellaneous/index.ts
  projects/cdk/utils/miscellaneous/object-from-entries.ts
  projects/demo/src/modules/app/home/home.component.ts
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/constants/max-day-range-length-mapper.ts
  projects/testing/project.json
  projects/testing/tsconfig.build.json
  tsconfig.build.json
  tsconfig.json
Labels: ready to merge

#3520 feat(addon-editor): add `Iframe` extension
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/editor-resizable/editor-resizable.abstract.ts
  projects/addon-editor/components/editor-resizable/editor-resizable.component.html
  projects/addon-editor/components/editor-resizable/editor-resizable.component.less
  projects/addon-editor/components/editor-resizable/editor-resizable.component.ts
  projects/addon-editor/components/editor-resizable/editor-resizable.module.ts
  projects/addon-editor/components/editor-resizable/index.ts
  projects/addon-editor/components/editor-resizable/ng-package.json
  projects/addon-editor/components/index.ts
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/addon-editor/extensions/iframe-editor/iframe-editor.component.html
  projects/addon-editor/extensions/iframe-editor/iframe-editor.component.less
  projects/addon-editor/extensions/iframe-editor/iframe-editor.component.ts
  projects/addon-editor/extensions/iframe-editor/iframe-editor.extension.ts
  projects/addon-editor/extensions/iframe-editor/iframe-editor.module.ts
  projects/addon-editor/extensions/iframe-editor/iframe-editor.options.ts
  projects/addon-editor/extensions/iframe-editor/index.ts
  projects/addon-editor/extensions/iframe-editor/ng-package.json
  projects/addon-editor/extensions/image-editor/image-editor.component.html
  projects/addon-editor/extensions/image-editor/image-editor.component.less
  projects/addon-editor/extensions/image-editor/image-editor.component.ts
  projects/addon-editor/extensions/image-editor/image-editor.extension.ts
  projects/addon-editor/extensions/image-editor/image-editor.module.ts
  projects/addon-editor/extensions/image-editor/image-editor.options.ts
  projects/addon-editor/extensions/image-editor/index.ts
  projects/addon-editor/extensions/index.ts
  projects/demo/src/modules/components/editor/embed/editor-embed.component.html
  projects/demo/src/modules/components/editor/embed/editor-embed.component.ts
  projects/demo/src/modules/components/editor/embed/editor-embed.module.ts
  projects/demo/src/modules/components/editor/embed/examples/2/embed-tool/embed-tool.component.ts
  projects/demo/src/modules/components/editor/embed/examples/2/embed-tool/embed-tool.module.ts
  projects/demo/src/modules/components/editor/embed/examples/2/embed-tool/embed-tool.styles.less
  projects/demo/src/modules/components/editor/embed/examples/2/embed-tool/embed-tool.template.html
  projects/demo/src/modules/components/editor/embed/examples/2/index.html
  projects/demo/src/modules/components/editor/embed/examples/2/index.less
  projects/demo/src/modules/components/editor/embed/examples/2/index.ts
  projects/demo/src/modules/components/editor/resizable-images/examples/1/index.ts
  projects/demo/src/modules/components/editor/uploading-images/examples/1/index.ts
Labels: ready to merge

#3561 ci: cleanup serve commands
  package.json
  projects/demo/project.json
Labels: ready to merge

#3563 feat(addon-commerce): add `tuiGetCurrencyByCode`
  projects/addon-commerce/utils/get-currency-by-code.ts
  projects/addon-commerce/utils/index.ts
  projects/addon-commerce/utils/test/get-currency-by-code.spec.ts
Labels: ready to merge

#3569 fix(cdk): `schematics` fix require() of ES modules error
  projects/cdk/schematics/utils/angular-json-manipulations.ts
  projects/cdk/schematics/utils/templates/elements.ts
  projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
Labels: ready to merge

#3579 test(cdk): cover `TUI_IS_MOBILE` token
  projects/cdk/tokens/tests/is-mobile.spec.ts
Labels: ready to merge

#3580 ci: fix e2e flaky
  projects/demo-integrations/cypress/tests/demo/demo.cy.ts
  projects/demo/src/modules/components/editor/embed/examples/2/index.ts
Labels: ready to merge

#3294 docs: add data-list-wrapper page
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.module.ts
  projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.template.html
  projects/demo/src/modules/components/data-list-wrapper/examples/1/index.html
  projects/demo/src/modules/components/data-list-wrapper/examples/1/index.ts
  projects/demo/src/modules/components/data-list-wrapper/examples/2/index.html
  projects/demo/src/modules/components/data-list-wrapper/examples/2/index.ts
  projects/demo/src/modules/components/data-list-wrapper/examples/3/index.html
  projects/demo/src/modules/components/data-list-wrapper/examples/3/index.ts
  projects/demo/src/modules/components/data-list-wrapper/examples/import/import-module.md
  projects/demo/src/modules/components/data-list-wrapper/examples/import/insert-template.md
Labels: state: postponed

#3595 ci: remove `firebase-tools`
  package-lock.json
  package.json
  projects/demo/webpack.config.ts
Labels: ready to merge

#3585 feat(addon-editor): support `audio/video` tag in editor
  projects/addon-editor/components/editor-socket/editor-socket.component.less
  projects/addon-editor/components/editor/editor.component.ts
  projects/addon-editor/extensions/index.ts
  projects/addon-editor/extensions/link/link.ts
  projects/addon-editor/extensions/media/audio.extension.ts
  projects/addon-editor/extensions/media/index.ts
  projects/addon-editor/extensions/media/ng-package.json
  projects/addon-editor/extensions/media/source.extension.ts
  projects/addon-editor/extensions/media/video.extension.ts
  projects/addon-editor/interfaces/attached.ts
  projects/addon-editor/utils/get-nested-nodes.ts
  projects/addon-editor/utils/index.ts
  projects/addon-editor/utils/parse-node-attributes.ts
  projects/demo/src/modules/components/editor/embed/editor-embed.component.html
  projects/demo/src/modules/components/editor/embed/editor-embed.component.ts
  projects/demo/src/modules/components/editor/embed/editor-embed.module.ts
  projects/demo/src/modules/components/editor/embed/examples/3/index.html
  projects/demo/src/modules/components/editor/embed/examples/3/index.ts
Labels: ready to merge

#3610 ci: skip editor as workaround
  projects/demo/src/modules/app/stackblitz/utils.ts
Labels: ready to merge

#3617 feat(core): `TUI_VIEWPORT` add new token
  projects/addon-editor/components/editor/portal/editor-portal.directive.ts
  projects/core/abstract/rect-accessor.ts
  projects/core/directives/dropdown/dropdown-position-sided.directive.ts
  projects/core/directives/dropdown/dropdown-position.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/tokens/index.ts
  projects/core/tokens/viewport.ts
Labels: ready to merge

#3640 ci: fix flaky e2e
  projects/demo/src/modules/components/editor/embed/html5/examples/1/index.less
  projects/demo/src/modules/components/editor/embed/html5/examples/1/index.ts
Labels: ready to merge

#3643 feat(core): support options for dropdown-hover directive
  projects/core/directives/dropdown/dropdown-hover-options.directive.ts
  projects/core/directives/dropdown/dropdown-hover.directive.ts
  projects/core/directives/dropdown/index.ts
  projects/demo/src/modules/app/app.providers.ts
Labels: ready to merge

#3641 ci: abort rebase when merge conflict
  .github/actions/rebase/action.yml
  .github/workflows/e2e.yml
Labels: ready to merge

#3635 chore(demo): fix broken stackblitz
  projects/demo/src/modules/app/stackblitz/utils.ts
Labels: ready to merge

#3639 feat(styles): remove legacy browser clearfix
  projects/demo/src/modules/components/island/examples/3/index.html
  projects/demo/src/modules/components/island/examples/3/index.less
  projects/demo/src/modules/components/island/island.module.ts
  projects/styles/markup/tui-island.less
Labels: ready to merge

#3650 chore: expose public icons in demo
  projects/demo/src/modules/markup/icons/icons.tokens.ts
Labels: ready to merge

#3662 feat(addon-editor): customize css classes for font-tool in toolbar
  projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts
  projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html
  projects/addon-editor/interfaces/editor-font-option.ts
Labels: ready to merge

#3657 ci: publish eslint-plugin
  package-lock.json
  projects/eslint-plugin/.npmignore
  projects/eslint-plugin/package.json
  projects/eslint-plugin/project.json
Labels: ready to merge

#3649 feat(addon-editor): support focus extension
  package-lock.json
  projects/addon-editor/package.json
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/focus/editor-focus.component.html
  projects/demo/src/modules/components/editor/focus/editor-focus.component.ts
  projects/demo/src/modules/components/editor/focus/editor-focus.module.ts
  projects/demo/src/modules/components/editor/focus/examples/1/index.html
  projects/demo/src/modules/components/editor/focus/examples/1/index.less
  projects/demo/src/modules/components/editor/focus/examples/1/index.ts
Labels: ready to merge

#3647 feat(addon-editor): add a little bit space between top and bottom in editor
  projects/addon-editor/components/editor-socket/editor-socket.component.less
Labels: ready to merge

#3668 chore: change to icons for proprietary packages
  projects/core/components/svg/deprecated-icons.ts
  projects/core/components/svg/svg-options.ts
  projects/core/components/svg/svg.component.ts
  projects/demo/src/modules/components/tabs/examples/1/index.ts
  projects/demo/src/modules/markup/icons/icons.tokens.ts
  projects/icons/project.json
  projects/icons/scripts/index.ts
  projects/icons/scripts/prepare-feather-icons.ts
  projects/kit/components/files/file/file.style.less
  projects/kit/components/files/file/file.template.html
  scripts/compile-icons.ts
  scripts/preprocess-icons.ts
Labels: ready to merge

#3646 feat(addon-editor): support drop/paste event for resizable
  projects/addon-editor/extensions/image-editor/image-editor.extension.ts
Labels: ready to merge

#3673 chore: fix icons
  projects/addon-preview/components/preview/zoom/preview-zoom.template.html
  projects/demo/src/modules/components/input-inline/examples/2/template.html
  projects/demo/src/modules/components/input-range/examples/4/index.html
  projects/demo/src/modules/components/preview/examples/1/index.html
  projects/demo/src/modules/components/preview/examples/import/template.md
  projects/demo/src/modules/components/primitive-textfield/examples/1/index.html
  projects/demo/src/modules/components/primitive-textfield/primitive-textfield.module.ts
  projects/demo/src/modules/components/tabs/examples/4/index.html
  projects/demo/src/modules/pipes/field-error/examples/4/index.html
  projects/demo/src/modules/services/svg/svg.template.html
  projects/demo/src/modules/services/table-bar/examples/1/index.html
  projects/demo/src/modules/tables/table/examples/2/index.html
Labels: ready to merge

#3638 feat(core): `Dialog` allow closing confirmation
  projects/core/components/dialog/dialog-close.service.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.providers.ts
  projects/core/components/dialog/dialog.template.html
  projects/core/components/dialog/dialog.tokens.ts
  projects/core/components/dialog/index.ts
  projects/core/interfaces/dialog-options.ts
  projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts
  projects/demo/src/modules/components/dialog/dialog.component.ts
  projects/demo/src/modules/components/dialog/dialog.module.ts
  projects/demo/src/modules/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/8/index.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
  projects/i18n/interfaces/language.ts
  projects/i18n/languages/chinese/kit.ts
  projects/i18n/languages/dutch/kit.ts
  projects/i18n/languages/english/kit.ts
  projects/i18n/languages/french/kit.ts
  projects/i18n/languages/german/kit.ts
  projects/i18n/languages/italian/kit.ts
  projects/i18n/languages/polish/kit.ts
  projects/i18n/languages/portuguese/kit.ts
  projects/i18n/languages/russian/kit.ts
  projects/i18n/languages/spanish/kit.ts
  projects/i18n/languages/turkish/kit.ts
  projects/i18n/languages/ukrainian/kit.ts
  projects/i18n/languages/vietnamese/kit.ts
  projects/kit/components/index.ts
  projects/kit/components/prompt/index.ts
  projects/kit/components/prompt/ng-package.json
  projects/kit/components/prompt/prompt.component.ts
  projects/kit/components/prompt/prompt.module.ts
  projects/kit/components/prompt/prompt.style.less
  projects/kit/components/prompt/prompt.template.html
  projects/kit/tokens/i18n.ts
Labels: ready to merge

#3679 chore(demo): add example `custom image tool`
  projects/demo-integrations/cypress/tests/addon-editor/editor-groups.cy.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.cy.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/editor-paste-emoji.component.html
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/editor-paste-emoji.component.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/editor-paste-emoji.module.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/index.html
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/index.less
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/index.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/smiles-tool/emoji.extension.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/smiles-tool/smiles-tool.component.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/smiles-tool/smiles-tool.module.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/smiles-tool/smiles-tool.styles.less
  projects/demo/src/modules/components/editor/custom-tool/paste-emoji/examples/1/smiles-tool/smiles-tool.template.html
  projects/demo/src/modules/components/editor/custom-tool/paste-image/editor-paste-image-tool.component.html
  projects/demo/src/modules/components/editor/custom-tool/paste-image/editor-paste-image-tool.component.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-image/editor-paste-image-tool.module.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/image-tool/image-tool.component.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/image-tool/image-tool.module.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/image-tool/image-tool.styles.less
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/image-tool/image-tool.template.html
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/image-tool/paste.extension.ts
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/index.html
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/index.less
  projects/demo/src/modules/components/editor/custom-tool/paste-image/examples/1/index.ts
Labels: ready to merge

#3680 fix(addon-editor): use `imageEditor` extension instead of `image` for copy-paste
  projects/addon-editor/extensions/image-editor/image-editor.extension.ts
Labels: ready to merge

#3686 ci: support `Nx` 15
  .eslintrc.js
  .nxignore
  angular.json
  nx.json
  package-lock.json
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo-integrations/package.json
  projects/demo/project.json
  projects/eslint-plugin/package.json
  projects/eslint-plugin/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
  scripts/eslint/nx.js
  tsconfig.json
Labels: ready to merge

#3685 chore: fix some styling issues
  projects/addon-table/components/table/tbody/tbody.style.less
  projects/core/components/link/link.style.less
  projects/demo/src/modules/components/dialog/dialog.template.html
  projects/demo/src/modules/components/link/link.component.ts
  projects/demo/src/modules/components/link/link.template.html
Labels: ready to merge

#3695 fix(addon-editor): do not inherit previous text style for heading
  projects/addon-editor/abstract/editor-adapter.abstract.ts
  projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-font.cy.ts
Labels: ready to merge

#3696 fix(kit): `TabsWithMore` properly calculate overflow
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
Labels: ready to merge

#3701 chore(demo): update links in documentation header
  projects/demo/src/assets/icons/discord.svg
  projects/demo/src/assets/icons/stackblitz.svg
  projects/demo/src/assets/icons/telegram.svg
  projects/demo/src/assets/images/github.svg
  projects/demo/src/modules/app/app.style.less
  projects/demo/src/modules/app/app.template.html
Labels: ready to merge

#3710 chore(demo): change `editor/getting-started` to `editor/setup`
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/setup/editor-setup.component.ts
  projects/demo/src/modules/components/editor/setup/editor-setup.module.ts
  projects/demo/src/modules/components/editor/setup/editor-setup.styles.less
  projects/demo/src/modules/components/editor/setup/editor-setup.template.html
  projects/demo/src/modules/components/editor/setup/examples/import/editor-options-token.md
  projects/demo/src/modules/components/editor/setup/examples/import/import-module.md
  projects/demo/src/modules/components/editor/setup/examples/import/insert-template.md
  projects/demo/src/modules/components/editor/setup/examples/import/provide-extensions.md
Labels: ready to merge

#3007 feat(core): implement `tuiTextfieldAppearance` directive
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-table/components/table/providers/table.providers.ts
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
  projects/core/directives/textfield-controller/index.ts
  projects/core/directives/textfield-controller/textfield-appearance.directive.ts
  projects/core/directives/textfield-controller/textfield-controller.module.ts
  projects/core/directives/textfield-controller/textfield-controller.provider.ts
  projects/core/directives/textfield-controller/textfield.controller.ts
  projects/core/tokens/textfield-appearance.ts
  projects/demo/src/modules/customization/wrapper/examples/1/index.ts
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-range/input-range.component.ts
  projects/kit/components/input-range/input-range.module.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/text-area/text-area.component.ts
Labels: state: postponed

#3720 chore(demo): rename folder
  projects/demo/src/modules/utils/format/examples/2/index.html
  projects/demo/src/modules/utils/format/examples/2/index.less
  projects/demo/src/modules/utils/format/examples/2/index.ts
  projects/demo/src/modules/utils/format/examples/3/index.html
  projects/demo/src/modules/utils/format/examples/3/index.ts
  projects/demo/src/modules/utils/format/examples/4/index.html
  projects/demo/src/modules/utils/format/examples/4/index.ts
  projects/demo/src/modules/utils/format/examples/5/index.html
  projects/demo/src/modules/utils/format/examples/5/index.ts
  projects/demo/src/modules/utils/format/examples/6/index.html
  projects/demo/src/modules/utils/format/examples/6/index.ts
  projects/demo/src/modules/utils/format/format.component.ts
  projects/demo/src/modules/utils/format/format.module.ts
  projects/demo/src/modules/utils/format/format.template.html
Labels: ready to merge

#3722 ci: enable `@angular-eslint/no-lifecycle-call: error`
  projects/kit/components/tree/components/tree-item/tree-item.component.ts
  projects/kit/components/tree/components/tree/tree.component.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3688 feat(addon-editor): add `highlight` extension
  package-lock.json
  projects/addon-editor/components/editor-socket/editor-socket.component.less
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.types.ts
  projects/addon-editor/package.json
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/highlight/editor-highlight.component.html
  projects/demo/src/modules/components/editor/highlight/editor-highlight.component.ts
  projects/demo/src/modules/components/editor/highlight/editor-highlight.module.ts
  projects/demo/src/modules/components/editor/highlight/examples/1/index.html
  projects/demo/src/modules/components/editor/highlight/examples/1/index.less
  projects/demo/src/modules/components/editor/highlight/examples/1/index.ts
Labels: ready to merge

#3723 ci: enable `@angular-eslint/component-max-inline-declarations: error`
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.html
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.ts
  projects/demo/src/modules/app/styles-info/styles-info.component.html
  projects/demo/src/modules/app/styles-info/styles-info.component.ts
  projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content.component.html
  projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content.component.ts
  projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.html
  projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.less
  projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.ts
  projects/demo/src/modules/components/pdf-viewer/pdf-viewer.component.ts
  projects/demo/src/modules/decorators/pure/pure-function.component.html
  projects/demo/src/modules/decorators/pure/pure-function.component.ts
  projects/demo/src/modules/decorators/pure/pure-getter.component.html
  projects/demo/src/modules/decorators/pure/pure-getter.component.ts
  projects/demo/src/modules/decorators/pure/pure.component.ts
  projects/demo/src/modules/markup/icons/icons.component.ts
  projects/demo/src/modules/markup/icons/inline-svg/inline-svg.component.html
  projects/demo/src/modules/markup/icons/inline-svg/inline-svg.component.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3728 chore(demo): source code button for `2.x`-demo should open `v2.x`-branch
  projects/demo/src/modules/app/app.providers.ts
Labels: v2

#3712 fix(kit): set `pointer-events: none` by readonly state for checkbox
  projects/kit/components/checkbox/checkbox.style.less
Labels: ready to merge

#3725 feat(core): new `tuiFlag` pipe
  projects/addon-doc/src/components/language-switcher/language-switcher.component.html
  projects/addon-doc/src/components/language-switcher/language-switcher.component.ts
  projects/addon-doc/src/components/language-switcher/language-switcher.module.ts
  projects/core/pipes/flag/flag.module.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/pipes/flag/index.ts
  projects/core/pipes/flag/ng-package.json
  projects/core/pipes/flag/test/flag.pipe.spec.ts
  projects/core/pipes/index.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/pipes/flag/examples/1/component.ts
  projects/demo/src/modules/pipes/flag/examples/1/template.html
  projects/demo/src/modules/pipes/flag/examples/import/import-module.md
  projects/demo/src/modules/pipes/flag/examples/import/insert-template.md
  projects/demo/src/modules/pipes/flag/flag.component.ts
  projects/demo/src/modules/pipes/flag/flag.module.ts
  projects/demo/src/modules/pipes/flag/flag.template.html
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.module.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Labels: ready to merge

#3729 feat(addon-doc): new `TUI_DOC_EXAMPLE_OPTIONS` DI-token
  projects/addon-doc/src/components/example/example-options.ts
  projects/addon-doc/src/components/example/example.component.ts
  projects/addon-doc/src/public-api.ts
Labels: ready to merge

#3726 fix(core): `Hint`/`Dropdown` fix directives order mattering
  projects/addon-editor/components/color-selector/color-selector.template.html
  projects/addon-editor/components/editor/portal/editor-portal.directive.ts
  projects/addon-editor/components/toolbar-tools/align-content/align-content.template.html
  projects/addon-editor/components/toolbar-tools/code/code.component.html
  projects/addon-editor/components/toolbar-tools/details/details-remove/details-remove.template.html
  projects/addon-editor/components/toolbar-tools/details/details.template.html
  projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html
  projects/addon-editor/components/toolbar-tools/font-style/font-style.template.html
  projects/addon-editor/components/toolbar-tools/group/group.component.html
  projects/addon-editor/components/toolbar-tools/highlight-color/highlight-color.template.html
  projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
  projects/addon-editor/components/toolbar-tools/table-cell-color/table-cell-color.template.html
  projects/addon-editor/components/toolbar-tools/table-create/table-create.template.html
  projects/addon-editor/components/toolbar-tools/table-merge-cells/table-merge-cells.template.html
  projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.template.html
  projects/addon-editor/components/toolbar-tools/text-color/text-color.template.html
  projects/addon-editor/components/toolbar/toolbar.template.html
  projects/addon-preview/components/preview/preview.template.html
  projects/addon-preview/components/preview/zoom/preview-zoom.template.html
  projects/core/abstract/abstract-driver.directive.ts
  projects/core/abstract/driver.ts
  projects/core/abstract/position-accessor.ts
  projects/core/abstract/rect-accessor.ts
  projects/core/abstract/vehicle.ts
  projects/core/directives/dropdown/dropdown-context.directive.ts
  projects/core/directives/dropdown/dropdown-driver.directive.ts
  projects/core/directives/dropdown/dropdown-host.directive.ts
  projects/core/directives/dropdown/dropdown-hover.directive.ts
  projects/core/directives/dropdown/dropdown-manual.directive.ts
  projects/core/directives/dropdown/dropdown-position-sided.directive.ts
  projects/core/directives/dropdown/dropdown-position.directive.ts
  projects/core/directives/dropdown/dropdown-selection.directive.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/hint/hint-describe.directive.ts
  projects/core/directives/hint/hint-driver.directive.ts
  projects/core/directives/hint/hint-host.directive.ts
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint-manual.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/directives/hint/hint.providers.ts
  projects/core/tokens/viewport.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
  projects/kit/components/line-clamp/line-clamp-position.directive.ts
Labels: ready to merge

#3766 ci: add typescript-eslint rules
  projects/addon-doc/src/components/language-switcher/language-switcher.component.ts
  projects/addon-doc/src/tokens/example-content-processor.ts
  projects/addon-editor/components/toolbar-tools/font-style/font-style.component.ts
  projects/addon-editor/components/toolbar/toolbar.component.ts
  projects/cdk/directives/for-async/test/for.directive.spec.ts
  projects/demo-integrations/cypress/support/helpers/components-excluded.ts
  projects/demo/src/modules/components/combo-box/examples/1/index.ts
  projects/kit/components/arrow/arrow-options.ts
  projects/kit/components/tree/directives/tree-controller.directive.ts
  projects/kit/tokens/i18n.ts
  scripts/eslint/typescript.js
Labels: ready to merge
