Repository taiga-family/taiga-ui, pull requests merged in 2023-03, with the labels that each got.

#3791 chore: fix small issue with margin collapse
  projects/kit/components/elastic-container/elastic-container.component.html
  projects/kit/components/elastic-container/elastic-container.component.less
Labels: ready to merge

#3790 feat(kit): `InputDate` add ability to use native date picker on mobile
  projects/demo-integrations/cypress/tests/kit/input-date/input-date.mobile.cy.ts
  projects/demo/src/modules/components/input-date/examples/6/index.html
  projects/demo/src/modules/components/input-date/examples/6/index.ts
  projects/demo/src/modules/components/input-date/input-date.component.ts
  projects/demo/src/modules/components/input-date/input-date.module.ts
  projects/demo/src/modules/components/input-date/input-date.template.html
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/input-date/native-date/native-date.component.ts
  projects/kit/components/input-date/native-date/native-date.style.less
  projects/kit/tokens/input-date-options.ts
Labels: ready to merge

#3810 chore: fix native date reset
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.directive.ts
  projects/kit/components/input-date/native-date/native-date.component.ts
Labels: ready to merge

#3797 fix(cdk): `schematics` fix global-styles migration
  projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
Labels: ready to merge

#3832 fix(kit): `InputTag`, `Multiselect` fix placeholder
  projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.cy.ts
  projects/demo/src/modules/components/input-tag/input-tag.template.html
  projects/demo/src/modules/components/multi-select/multi-select.template.html
  projects/kit/components/input-tag/input-tag.style.less
Labels: ready to merge

#3824 fix(kit): `InputCount` fix formatting, fix cutting by min value, use `InputNumber` inside
  projects/demo/src/modules/components/input-count/input-count.module.ts
  projects/demo/src/modules/components/input-count/input-count.template.html
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-count/input-count.directive.ts
  projects/kit/components/input-count/input-count.module.ts
  projects/kit/components/input-count/input-count.template.html
  projects/kit/components/input-count/test/input-count.component.spec.ts
Labels: ready to merge

#3767 fix(cdk): improve type annotation for `tuiForAsync`
  projects/cdk/directives/for-async/for-async.directive.ts
Labels: ready to merge

#3846 chore: simplify spin button
  projects/core/components/primitive-spin-button/primitive-spin-button.module.ts
  projects/core/components/primitive-spin-button/primitive-spin-button.style.less
  projects/core/components/primitive-spin-button/primitive-spin-button.template.html
  projects/core/components/primitive-spin-button/test/primitive-spin-button.component.spec.ts
Labels: ready to merge

#3833 fix(core): `Textarea` fix line breaks in disabled/readonly state
  projects/core/components/primitive-textfield/textfield/textfield.style.less
  projects/demo-integrations/cypress/tests/core/text-area/text-area.cy.ts
Labels: ready to merge

#3845 fix(kit): use ellipsis for label in `pdf-viewer` when overflow text
  projects/kit/components/pdf-viewer/pdf-viewer.style.less
Labels: ready to merge

#3852 fix(kit): `InputCount` fix cutting by min
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-count/test/input-count.component.spec.ts
Labels: ready to merge

#3865 fix(cdk): correct detect that is safari
  projects/cdk/utils/browser/is-safari.ts
  projects/cdk/utils/browser/test/browsers.spec.ts
Labels: v2

#3876 fix(kit): use wrap for non-breaking string in `line-clamp`
  projects/kit/components/line-clamp/line-clamp.style.less
Labels: ready to merge

#3872 fix(addon-editor): dispatch `ImageNode` in `viewModel`
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/demo/src/modules/components/editor/images/resizable/examples/1/index.html
  projects/demo/src/modules/components/editor/images/resizable/examples/1/index.ts
Labels: ready to merge

#3851 feat(kit): `DialogForm` add new service
  projects/core/components/dialog/dialog.component.ts
  projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts
  projects/demo/src/modules/components/dialog/examples/8/index.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
  projects/kit/index.ts
  projects/kit/services/dialog-form.service.ts
  projects/kit/services/index.ts
  projects/kit/services/ng-package.json
Labels: ready to merge

#3884 feat(core): add helper `tuiNumberFormatProvider`
  projects/core/tokens/number-format.ts
  projects/demo/src/modules/components/input-number/examples/4/index.ts
  projects/demo/src/modules/components/input-number/examples/5/index.ts
  projects/demo/src/modules/components/input-range/examples/2/index.ts
  projects/demo/src/modules/components/money/examples/5/index.ts
  projects/kit/components/input-number/test/input-number-format.spec.ts
Labels: ready to merge

#3799 fix(addon-commerce): emulate focus on iOS by `tuiAutoFocus`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/cdk/directives/auto-focus/handlers/sync.handler.ts
  projects/cdk/directives/auto-focus/index.ts
  projects/demo/src/assets/images/ios-keyboard.png
  projects/demo/src/modules/components/dialog/dialog.component.ts
  projects/demo/src/modules/components/dialog/dialog.module.ts
  projects/demo/src/modules/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/9/helpers/mock-cards.ts
  projects/demo/src/modules/components/dialog/examples/9/helpers/models.ts
  projects/demo/src/modules/components/dialog/examples/9/helpers/pay.service.ts
  projects/demo/src/modules/components/dialog/examples/9/helpers/validator.ts
  projects/demo/src/modules/components/dialog/examples/9/index.html
  projects/demo/src/modules/components/dialog/examples/9/index.less
  projects/demo/src/modules/components/dialog/examples/9/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.less
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.module.ts
  projects/demo/src/modules/directives/auto-focus/auto-focus.component.less
  projects/demo/src/modules/directives/auto-focus/auto-focus.component.ts
  projects/demo/src/modules/directives/auto-focus/auto-focus.module.ts
  projects/demo/src/modules/directives/auto-focus/auto-focus.template.html
Labels: ready to merge

#3751 fix(core): escape event doesn't work in Safari
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.template.html
  projects/demo-integrations/cypress/tests/core/dropdown/dropdown.cy.ts
Labels: ready to merge

#3890 feat(styles): add `--tui-skeleton-radius` for skeleton
  projects/demo/src/modules/markup/skeleton/examples/1/index.html
  projects/demo/src/modules/markup/skeleton/examples/1/index.less
  projects/demo/src/modules/markup/skeleton/examples/1/index.ts
  projects/demo/src/modules/markup/skeleton/skeleton.module.ts
  projects/demo/src/modules/markup/skeleton/skeleton.template.html
  projects/styles/markup/tui-skeleton.less
Labels: ready to merge

#3896 fix(kit): `InputTime` fix wrong preudofocus state
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.template.html
Labels: ready to merge

#3919 ci: support `prefer-includes`
  scripts/eslint/typescript.js
Labels: ready to merge

#3916 ci: support `ban-types`
  scripts/eslint/typescript.js
Labels: ready to merge

#3918 ci: support `no-implied-eval`
  scripts/eslint/typescript.js
Labels: ready to merge

#3912 ci: support `no-confusing-non-null-assertion`
  scripts/eslint/typescript.js
Labels: ready to merge

#3909 ci: support `consistent-type-assertions`
  jest.config.ts
  projects/cdk/abstract/theme-switcher.ts
  projects/cdk/components/dropdown-host/test/dropdown-portal.service.spec.ts
  projects/cdk/utils/focus/tests/is-native-focused-in.spec.ts
  projects/demo/src/modules/pipes/field-error/examples/4/index.ts
  projects/kit/components/action/test/action.component.spec.ts
  projects/kit/components/routable-dialog/test/routable-dialog.component.spec.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3920 fix(cdk): `tuiIfMap` add operator
  package.json
  projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
  projects/addon-mobile/components/sheet/ios.hacks.ts
  projects/addon-mobile/components/sheet/sheet.directive.ts
  projects/cdk/abstract/dialog.directive.ts
  projects/cdk/directives/obscured/obscured.directive.ts
  projects/cdk/observables/focus-visible-observable.ts
  projects/cdk/observables/if-map.ts
  projects/cdk/observables/index.ts
  projects/cdk/utils/miscellaneous/index.ts
  projects/cdk/utils/miscellaneous/is-falsy.ts
  projects/demo/src/modules/components/sheet/examples/1/index.ts
  projects/demo/src/modules/pipes/field-error/examples/2/index.ts
  projects/demo/src/modules/tables/table/examples/4/index.ts
  projects/kit/components/carousel/carousel.directive.ts
  projects/kit/components/push/push-alert.directive.ts
Labels: ready to merge

#3922 ci: support `no-unnecessary-type-arguments`
  projects/cdk/directives/resizer/resizeable.directive.ts
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/demo-integrations/cypress/support/commands/basic.ts
  projects/demo-integrations/cypress/support/helpers/type-tab.ts
  projects/demo-integrations/cypress/tests/deep/deep.cy.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/preview/examples/1/index.ts
  projects/demo/src/modules/components/preview/examples/2/index.ts
  projects/demo/src/modules/components/preview/examples/3/index.ts
  projects/kit/components/push/push-alert.directive.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3921 ci: support `no-extra-non-null-assertion`
  scripts/eslint/typescript.js
Labels: ready to merge

#3934 ci: support `restrict-plus-operands`
  projects/addon-doc/src/components/navigation/navigation.providers.ts
  projects/demo/src/modules/components/input-slider/examples/2/index.ts
  projects/kit/components/input-files/max-size-rejection-error.pipe.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3926 chore: improve issues template
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-feature-request.yml
  .github/ISSUE_TEMPLATE/3-dev-infra-request.yml
  .github/ISSUE_TEMPLATE/3-docs-bug.yml
Labels: ready to merge

#3932 feat(addon-doc): add `TUI_DOC_MAP_PAGES` for cached map pages
  projects/addon-doc/src/internal/see-also/see-also.component.ts
  projects/addon-doc/src/tokens/pages.ts
  projects/addon-doc/src/utils/to-flat-map-pages.ts
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#3928 ci: support `no-unnecessary-qualifier`
  scripts/eslint/typescript.js
Labels: ready to merge

#3930 ci: support `prefer-for-of`
  projects/core/utils/format/format-phone.ts
  projects/demo/src/modules/components/tree/examples/6/index.ts
  projects/kit/utils/miscellaneous/create-time-periods.ts
  scripts/eslint/typescript.js
Labels: ready to merge

#3942 fix(kit): cannot read properties of null in `input-phone-international`
  projects/icons/src/XK.png
  projects/kit/components/input-phone-international/input-phone-international.module.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
Labels: v2

#3950 chore: update README.md
  README.md
Labels: v2

#3940 fix(core): fix `Hint` position on pinch-to-zoom in webkit
  projects/cdk/components/dropdown-host/dropdown-host.component.ts
  projects/cdk/components/dropdown-host/dropdown-host.template.html
  projects/cdk/components/dropdown-host/test/dropdown-host.component.spec.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/services/index.ts
  projects/core/services/visual-viewport.service.ts
Labels: ready to merge

#3946 fix(addon-mobile): `Sheet` disable scroll snap for Firefox
  projects/addon-mobile/components/sheet/components/sheet-heading/sheet-heading.style.less
  projects/addon-mobile/components/sheet/components/sheet/sheet.style.less
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html
  projects/addon-mobile/components/sheet/directives/sheet-wrapper/sheet-wrapper.directive.ts
  projects/addon-mobile/components/sheet/ios.hacks.ts
  projects/core/components/dialog/dialog.style.less
  projects/demo/src/modules/components/sheet/examples/5/index.less
Labels: ready to merge

#3933 feat(addon-doc): support `icon` for code editor button
  projects/addon-doc/src/components/example/example.module.ts
  projects/addon-doc/src/components/example/example.template.html
  projects/addon-doc/src/interfaces/code-editor.ts
  projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
Labels: ready to merge

#3957 fix(core): `HostedDropdown` properly detect size in case of custom host
  projects/core/components/hosted-dropdown/hosted-dropdown.template.html
  projects/demo/src/modules/components/hosted-dropdown/examples/2/index.html
Labels: ready to merge

#3748 feat(addon-editor): support custom full color picker
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.component.html
  projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.component.ts
  projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.module.ts
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.html
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.less
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.ts
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.module.ts
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/index.html
  projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/index.ts
Labels: ready to merge

#3980 fix(kit): `InputTag` remove trailing comma for non editable mode
  projects/kit/components/input-tag/input-tag.style.less
  projects/kit/components/input-tag/input-tag.template.html
Labels: ready to merge

#3995 feat(kit): `InputFiles` customize content
  projects/demo/src/modules/components/input-files/examples/5/index.html
  projects/demo/src/modules/components/input-files/examples/5/index.less
  projects/demo/src/modules/components/input-files/input-files.module.ts
  projects/kit/components/input-files/input-files.component.ts
  projects/kit/components/input-files/input-files.style.less
  projects/kit/components/input-files/input-files.template.html
Labels: ready to merge

#3994 fix(core): increase default font size from 15px to 16px to remove iOS zoom
  projects/core/styles/theme/variables.less
Labels: ready to merge

#4000 feat(addon-editor): improve styles for `details` component
  projects/addon-editor/components/editor-socket/editor-socket.component.less
  projects/addon-editor/components/editor-socket/styles/details.less
  projects/addon-editor/extensions/details/details.extension.ts
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
Labels: ready to merge

#3999 fix(kit): align placeholder
  projects/kit/components/text-area/text-area.style.less
Labels: ready to merge

#4004 fix(cdk): `Resizer` leave irrelevant dimensions untouched
  projects/cdk/directives/resizer/resizer.directive.ts
Labels: ready to merge

#4003 fix(addon-editor): overflow `tui-editor-socket` only inside `tui-editor`
  projects/addon-editor/components/editor-socket/editor-socket.component.less
Labels: ready to merge

#3983 feat(kit): `MultiSelect` add ability to use native dropdown on mobile
  projects/core/components/data-list/data-list.directive.ts
  projects/demo/src/modules/components/multi-select/examples/10/index.html
  projects/demo/src/modules/components/multi-select/examples/10/index.ts
  projects/demo/src/modules/components/multi-select/multi-select.component.ts
  projects/demo/src/modules/components/multi-select/multi-select.module.ts
  projects/demo/src/modules/components/multi-select/multi-select.template.html
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-tag/input-tag.template.html
  projects/kit/components/multi-select/index.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.directive.ts
  projects/kit/components/multi-select/multi-select.module.ts
  projects/kit/components/multi-select/multi-select.style.less
  projects/kit/components/multi-select/multi-select.template.html
  projects/kit/components/multi-select/native-multi-select/native-multi-select-group.component.ts
  projects/kit/components/multi-select/native-multi-select/native-multi-select-group.template.html
  projects/kit/components/multi-select/native-multi-select/native-multi-select.component.ts
  projects/kit/components/multi-select/native-multi-select/native-multi-select.style.less
  projects/kit/components/multi-select/native-multi-select/native-multi-select.template.html
  projects/kit/components/multi-select/native-multi-select/native-multi-select.ts
  projects/kit/components/select/native-select/native-select-group.component.ts
  projects/kit/components/select/native-select/native-select.component.ts
  projects/kit/components/select/select.template.html
Labels: ready to merge

#3968 fix(addon-editor): trigger `updateValueAndValidity` after `focus/blur` events in `tui-editor`
  projects/addon-editor/components/editor/editor.component.ts
  projects/demo-integrations/cypress/support/editor/helpers.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-links.cy.ts
  projects/demo/src/modules/components/editor/images/upload/editor-upload-images.module.ts
  projects/demo/src/modules/components/editor/images/upload/examples/1/image-loader.ts
  projects/demo/src/modules/components/editor/images/upload/examples/1/imgbb.service.ts
  projects/demo/src/modules/components/editor/images/upload/examples/1/index.html
  projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts
Labels: ready to merge

#4013 feat(core): `Tooltip` close on click
  projects/core/components/tooltip/tooltip.component.ts
  projects/core/directives/hint/hint-hover.directive.ts
Labels: ready to merge

#4021 chore: add `SECURITY.md`
  SECURITY.md
Labels: ready to merge

#4018 fix(addon-editor): compatibility with legacy html model of previous versions
  projects/addon-editor/components/editor-socket/styles/details.less
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
Labels: ready to merge

#4027 fix(cdk): remove `protected` from abstract classes for DI
  projects/addon-editor/components/editor-resizable/editor-resizable.abstract.ts
  projects/cdk/abstract/control.ts
  projects/cdk/abstract/interactive.ts
  projects/cdk/directives/auto-focus/handlers/abstract.handler.ts
  projects/demo/src/modules/app/abstract.app.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.ts
Labels: ready to merge

#4019 docs: change PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#4033 chore: update test command and CONTRIBUTING.md
  CONTRIBUTING.md
  package.json
Labels: ready to merge

#4035 chore(demo): add `Maskito` to `Friendly libraries` documentation page
  projects/demo/src/modules/info/related/related.template.html
Labels: ready to merge

#4011 fix(kit): add missing dependency `@ng-web-apis/resize-observer`
  projects/kit/package.json
Labels: ready to merge

#4032 fix(kit): `InputSlider` broken disabled state
  projects/kit/components/input-slider/input-slider.template.html
Labels: ready to merge, v2

#4031 fix(kit): `InputSlider` broken disabled state
  projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.cy.ts
  projects/kit/components/input-slider/input-slider.template.html
Labels: v3, ready to merge

#4049 fix(cdk): correct extraction of id for processing in svg
  projects/cdk/utils/svg/svg-linear-gradient-processor.ts
  projects/cdk/utils/svg/tests/svg-linear-gradient-processor.spec.ts
Labels: community contribution

#4066 chore: remove unnecessary instruction
  projects/demo/src/modules/services/breakpoint/breakpoint.component.ts
  projects/demo/src/modules/services/breakpoint/breakpoint.template.html
  projects/demo/src/modules/services/breakpoint/examples/provide-service.md
Labels: ready to merge
