Repository taiga-family/taiga-ui, pull requests merged in 2023-12, with the labels that each got.

#6086 feat(addon-doc): add type reference handler for improve documentation
  projects/addon-doc/components/documentation/documentation.module.ts
  projects/addon-doc/components/documentation/documentation.style.less
  projects/addon-doc/components/documentation/documentation.template.html
  projects/addon-doc/components/documentation/pipes/content-tooltip.pipe.ts
  projects/addon-doc/components/documentation/pipes/type-reference.pipe.ts
  projects/addon-doc/components/index.ts
  projects/addon-doc/components/main/main.style.less
  projects/addon-doc/tokens/index.ts
  projects/addon-doc/tokens/type-reference-handler.ts
  projects/addon-doc/utils/index.ts
  projects/addon-doc/utils/test/type-reference-parser.spec.ts
  projects/addon-doc/utils/type-reference-parser.ts
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/components/link/link.template.html
Labels: ready to merge

#6165 feat(addon-doc): use white color for deprecated tag
  projects/addon-doc/components/page/page.style.less
Labels: ready to merge

#6163 chore(demo): invalid styles on dark theme
  projects/demo/src/modules/info/related/related.style.less
Labels: ready to merge

#6164 chore: update README.md
  README.md
Labels: ready to merge

#6157 refactor: remove redundant files
  projects/addon-charts/jest.config.ts
  projects/addon-charts/project.json
  projects/addon-commerce/jest.config.ts
  projects/addon-commerce/project.json
  projects/addon-doc/jest.config.ts
  projects/addon-doc/project.json
  projects/addon-mobile/jest.config.ts
  projects/addon-mobile/project.json
  projects/addon-preview/jest.config.ts
  projects/addon-preview/project.json
  projects/addon-table/jest.config.ts
  projects/addon-table/project.json
  projects/addon-tablebars/jest.config.ts
  projects/addon-tablebars/project.json
  projects/cdk/jest.config.ts
  projects/cdk/project.json
  projects/core/jest.config.ts
  projects/core/project.json
  projects/demo/jest.config.ts
  projects/demo/project.json
  projects/experimental/jest.config.ts
  projects/experimental/project.json
  projects/i18n/jest.config.ts
  projects/i18n/project.json
  projects/icons/jest.config.ts
  projects/icons/project.json
  projects/kit/jest.config.ts
  projects/kit/project.json
  projects/layout/jest.config.ts
  projects/layout/project.json
  projects/testing/jest.config.ts
  projects/testing/project.json
Labels: ready to merge

#6160 ci: enable some Nx options
  nx.json
Labels: ready to merge

#6179 chore: remove redundant job
  .github/workflows/auto-cleanup-caches.yml
Labels: ready to merge

#6183 ci: remove `dropdown.cy.ts`
  projects/demo-cypress/cypress/tests/core/dropdown/dropdown.cy.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
Labels: ready to merge

#6167 chore(demo): update disable-animation page
  projects/addon-doc/components/doc-tab/doc-tab.component.html
  projects/addon-doc/components/doc-tab/doc-tab.component.less
  projects/addon-doc/components/doc-tab/doc-tab.component.ts
  projects/addon-doc/components/doc-tab/doc-tab.module.ts
  projects/addon-doc/components/documentation/documentation.module.ts
  projects/addon-doc/components/index.ts
  projects/demo-cypress/cypress.config.ts
  projects/demo-cypress/cypress/plugins/index.ts
  projects/demo/src/assets/icons/cypress.svg
  projects/demo/src/assets/icons/playwright.svg
  projects/demo/src/modules/app/home/home.module.ts
  projects/demo/src/modules/app/home/home.style.less
  projects/demo/src/modules/app/home/home.template.html
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.component.ts
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.module.ts
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.style.less
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.template.html
  projects/demo/src/modules/info/testing/disable-animation/examples/cypress.md
  projects/demo/src/modules/info/testing/disable-animation/examples/disable-all-animation.md
  projects/demo/src/modules/info/testing/disable-animation/examples/playwright.md
Labels: ready to merge

#6209 feat(kit): `Push` allow string in timestamp for custom formatting
  projects/demo/src/modules/components/push/push.component.ts
  projects/demo/src/modules/components/push/push.template.html
  projects/kit/components/push/push.component.ts
  projects/kit/components/push/push.options.ts
  projects/kit/components/push/push.template.html
Labels: ready to merge

#6210 fix(addon-commerce): treat US Diners as Mastercard internationally
  projects/addon-commerce/utils/get-payment-system.ts
  projects/addon-commerce/utils/test/get-payment-system.spec.ts
Labels: ready to merge

#6177 chore(demo): fix example
  projects/demo/src/modules/components/tabs/examples/5/index.html
  projects/demo/src/modules/components/tabs/examples/5/index.ts
  projects/demo/src/modules/components/tabs/tabs.module.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
Labels: ready to merge

#6197 chore(demo): fix color in tab
  projects/addon-doc/components/doc-tab/doc-tab.component.html
  projects/addon-doc/components/doc-tab/doc-tab.module.ts
  projects/demo/src/assets/icons/cypress.svg
Labels: ready to merge

#6214 fix(kit): `InputPhone` should erase value on blur if it's just country code
  projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-phone/test/input-phone.component.spec.ts
Labels: ready to merge

#6180 feat(addon-doc): improve code block ui
  projects/addon-doc/components/documentation/documentation.style.less
  projects/addon-doc/components/documentation/documentation.template.html
  projects/addon-doc/components/main/main.style.less
  projects/demo/src/modules/components/notification/examples/1/index.html
Labels: ready to merge

#6220 fix(core): use immutable range for trigger stream in Safari
  projects/core/directives/dropdown/dropdown-selection.directive.ts
Labels: ready to merge

#6182 feat(addon-doc): use `anchorScrolling` by default
  projects/addon-doc/components/example/example.style.less
  projects/addon-doc/components/main/main.style.less
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/styles.less
Labels: ready to merge

#6215 chore: remove addon-doc on cypress
  .github/workflows/e2e.yml
  projects/demo-cypress/cypress/tests/addon-doc/code.cy.ts
  projects/demo-cypress/cypress/tests/addon-doc/viewport.cy.ts
  projects/demo-playwright/tests/addon-doc/code.spec.ts
  projects/demo-playwright/tests/addon-doc/viewport.spec.ts
Labels: ready to merge

#6221 feat(addon-doc): add markdown theme
  projects/addon-doc/ng-package.json
  projects/addon-doc/styles/markdown.less
  projects/demo/src/modules/customization/i18n/i18n.component.ts
  projects/demo/src/modules/customization/i18n/i18n.style.less
  projects/demo/src/modules/customization/i18n/i18n.template.html
  projects/demo/src/modules/info/changelog/changelog.style.less
  projects/demo/src/modules/info/doc/doc.component.ts
  projects/demo/src/modules/info/doc/doc.style.less
  projects/demo/src/styles.less
Labels: ready to merge

#6224 fix(kit): prevent stretching to full height
  projects/kit/components/files/file/file.style.less
Labels: ready to merge

#6242 chore(demo): invalid selected version on next page
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
Labels: ready to merge

#6243 chore(demo): invalid selected version on next page
  projects/demo/src/modules/app/version-manager/version-manager.providers.ts
Labels: v3

#6244 chore(demo): prevent overflow body when height is auto
  projects/addon-doc/components/main/main.style.less
  projects/demo/src/styles.less
Labels: ready to merge

#6226 feat(experimental): `Appearance`, `Icons` change to host directives
  projects/addon-mobile/styles/android/checkbox.less
  projects/addon-mobile/styles/android/radio.less
  projects/addon-mobile/styles/android/toggle.less
  projects/addon-mobile/styles/ios/checkbox.less
  projects/addon-mobile/styles/ios/toggle.less
  projects/cdk/directives/index.ts
  projects/cdk/directives/native-validator/index.ts
  projects/cdk/directives/native-validator/native-validator.directive.ts
  projects/cdk/directives/native-validator/ng-package.json
  projects/core/styles/theme/appearance/outline.less
  projects/core/styles/theme/appearance/primary.less
  projects/core/styles/theme/appearance/secondary.less
  projects/core/styles/theme/appearance/status.less
  projects/demo/src/modules/experimental/appearance/appearance.module.ts
  projects/demo/src/modules/experimental/appearance/examples/import/import-module.md
  projects/demo/src/modules/experimental/avatar/examples/2/index.html
  projects/demo/src/modules/experimental/avatar/examples/2/index.less
  projects/demo/src/modules/experimental/badge/badge.component.ts
  projects/demo/src/modules/experimental/tooltip/tooltip.module.ts
  projects/experimental/components/avatar/avatar.component.ts
  projects/experimental/components/avatar/avatar.options.ts
  projects/experimental/components/badge/badge.directive.ts
  projects/experimental/components/badge/badge.module.ts
  projects/experimental/components/badge/badge.options.ts
  projects/experimental/components/button/button.directive.ts
  projects/experimental/components/button/button.module.ts
  projects/experimental/components/button/button.options.ts
  projects/experimental/components/checkbox/checkbox.component.ts
  projects/experimental/components/checkbox/checkbox.options.ts
  projects/experimental/components/checkbox/checkbox.style.less
  projects/experimental/components/chip/chip.directive.ts
  projects/experimental/components/chip/chip.module.ts
  projects/experimental/components/chip/chip.options.ts
  projects/experimental/components/radio/index.ts
  projects/experimental/components/radio/radio.component.ts
  projects/experimental/components/radio/radio.options.ts
  projects/experimental/components/radio/radio.style.less
  projects/experimental/components/toggle/toggle.component.ts
  projects/experimental/components/toggle/toggle.options.ts
  projects/experimental/components/toggle/toggle.style.less
  projects/experimental/components/tooltip/tooltip.module.ts
  projects/experimental/components/tooltip/tooltip.template.html
  projects/experimental/directives/appearance/appearance.directive.ts
  projects/experimental/directives/appearance/appearance.module.ts
  projects/experimental/directives/appearance/appearance.options.ts
  projects/experimental/directives/appearance/index.ts
  projects/experimental/directives/cell/cell.styles.less
  projects/experimental/directives/icons/icons.component.ts
  projects/experimental/directives/icons/icons.directive.ts
  projects/experimental/directives/icons/icons.module.ts
  projects/experimental/directives/icons/index.ts
Labels: ready to merge, v4

#6256 ci: run `auto-label.yml` only if `github.event.review.state == 'APPROVED'`
  .github/workflows/auto-label.yml
Labels: ready to merge

#6251 chore: fix datalist e2e
  projects/demo-cypress/cypress/tests/core/data-list/data-list.cy.ts
Labels: v4

#6258 fix(core): `Calendar` properly react to markers change
  package-lock.json
  projects/addon-preview/package.json
  projects/addon-table/package.json
  projects/cdk/package.json
  projects/core/components/primitive-calendar/primitive-calendar.component.ts
  projects/core/components/primitive-calendar/primitive-calendar.template.html
  projects/core/package.json
  projects/kit/package.json
Labels: ready to merge

#6293 fix(core): page scrolling jumps to top in Iframe when modal is opened
  projects/core/components/root/root.style.less
Labels: v3

#6298 feat(experimental): `Textfield` add new component
  .cspell.json
  projects/cdk/directives/native-validator/native-validator.directive.ts
  projects/cdk/services/directive-styles.service.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/hint/hint-describe.directive.ts
  projects/core/styles/theme/appearance.less
  projects/core/styles/theme/appearance/textfield.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/textfield/examples/1/index.html
  projects/demo/src/modules/experimental/textfield/examples/1/index.less
  projects/demo/src/modules/experimental/textfield/examples/1/index.ts
  projects/demo/src/modules/experimental/textfield/examples/import/import-module.md
  projects/demo/src/modules/experimental/textfield/examples/import/insert-template.md
  projects/demo/src/modules/experimental/textfield/textfield.component.ts
  projects/demo/src/modules/experimental/textfield/textfield.module.ts
  projects/demo/src/modules/experimental/textfield/textfield.template.html
  projects/experimental/components/index.ts
  projects/experimental/components/textfield/index.ts
  projects/experimental/components/textfield/label.component.ts
  projects/experimental/components/textfield/label.directive.ts
  projects/experimental/components/textfield/label.style.less
  projects/experimental/components/textfield/label.template.html
  projects/experimental/components/textfield/ng-package.json
  projects/experimental/components/textfield/textfield.component.ts
  projects/experimental/components/textfield/textfield.directive.ts
  projects/experimental/components/textfield/textfield.module.ts
  projects/experimental/components/textfield/textfield.options.ts
  projects/experimental/components/textfield/textfield.style.less
  projects/experimental/components/textfield/textfield.template.html
  projects/experimental/components/tooltip/tooltip.component.ts
  projects/experimental/components/tooltip/tooltip.template.html
Labels: ready to merge

#6305 fix(cdk): `DirectiveStylesService` fix ssr memory leak
  projects/cdk/services/directive-styles.service.ts
Labels: ready to merge, v4

#6288 fix(cdk): `DirectiveStylesService` fix ssr memory leak
  projects/cdk/services/directive-styles.service.ts
Labels: ready to merge, v3

#6314 ci: add `deep.spec.ts`
  .github/workflows/e2e.yml
  projects/demo-cypress/cypress.config.ts
  projects/demo-cypress/cypress/support/helpers/deep-paths.ts
  projects/demo-cypress/cypress/tests/deep/deep.cy.ts
  projects/demo-playwright/tests/deep/deep.spec.ts
Labels: ready to merge

#6292 fix(core): page scrolling jumps to top in Iframe when modal is opened
  projects/core/components/root/root.style.less
Labels: v4

#6315 feat(addon-doc)!: remove deprecated entities
  projects/addon-doc/components/documentation/documentation-property-connector.directive.ts
  projects/addon-doc/interfaces/page.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts
  projects/kit/components/textarea/deprecated.ts
  projects/kit/components/textarea/index.ts
  projects/kit/components/textarea/test/text-area.component.spec.ts
  projects/kit/pipes/filter-by-input/filter-by-input.base.ts
Labels: ready to merge

#6277 feat(addon-doc): support standalone route in addon-doc
  projects/addon-doc/utils/index.ts
  projects/addon-doc/utils/provide-route-page-tab.ts
Labels: ready to merge

#6307 fix(kit): `ComboBox` fix empty string option incorrect behavior
  projects/kit/components/combo-box/combo-box.component.ts
Labels: v4

#6323 fix(cdk): respect client size in `TUI_WINDOW_SIZE`
  projects/cdk/tokens/window-size.ts
  projects/core/services/breakpoint.service.ts
  projects/core/services/test/breakpoint.service.spec.ts
Labels: ready to merge

#6326 feat(kit)!: remove deprecated `tui-card`
  projects/addon-commerce/components/thumbnail-card/deprecated.ts
  projects/addon-commerce/components/thumbnail-card/index.ts
  projects/addon-commerce/components/thumbnail-card/test/card.component.spec.ts
Labels: ready to merge

#6331 ci: simplify unit tests job
  .github/workflows/auto-approve.yml
  .github/workflows/test.yml
Labels: ready to merge

#6296 feat(kit)!: `InputTag`, `Multiselect`, `InputDateMulti` remove `expandable` property
  projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
  projects/demo/src/modules/components/group/examples/1/index.html
  projects/demo/src/modules/components/input-date-multi/input-date-multi.component.ts
  projects/demo/src/modules/components/input-date-multi/input-date-multi.template.html
  projects/demo/src/modules/components/input-tag/input-tag.component.ts
  projects/demo/src/modules/components/input-tag/input-tag.template.html
  projects/demo/src/modules/components/multi-select/examples/2/index.html
  projects/demo/src/modules/components/multi-select/examples/5/index.html
  projects/demo/src/modules/components/multi-select/examples/9/index.html
  projects/demo/src/modules/components/multi-select/multi-select.component.ts
  projects/demo/src/modules/components/multi-select/multi-select.template.html
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.options.ts
  projects/kit/components/multi-select/multi-select.template.html
Labels: ready to merge

#6304 chore: add `expandable` migration
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-expandable.spec.ts
Labels: ready to merge

#6339 ci: improve unit tests logs on CI
  .github/workflows/test.yml
  jest.config.ts
Labels: ready to merge

#6340 ci: improve demo content for E2E
  projects/addon-doc/components/demo/demo.style.less
  projects/addon-doc/components/demo/demo.template.html
Labels: ready to merge

#6317 feat(experimental): `Textfield` add select mode
  projects/cdk/tokens/active-element.ts
  projects/core/styles/theme/appearance/textfield.less
  projects/demo/src/modules/experimental/textfield/examples/1/index.html
  projects/demo/src/modules/experimental/textfield/examples/3/index.html
  projects/experimental/components/textfield/index.ts
  projects/experimental/components/textfield/select.directive.ts
  projects/experimental/components/textfield/select.template.html
  projects/experimental/components/textfield/textfield.component.ts
  projects/experimental/components/textfield/textfield.directive.ts
  projects/experimental/components/textfield/textfield.module.ts
  projects/experimental/components/textfield/textfield.style.less
  projects/experimental/components/textfield/textfield.template.html
  projects/kit/components/input-phone/test/input-phone.component.spec.ts
Labels: ready to merge
