Repository taiga-family/taiga-ui, pull requests merged in 2023-04, with the labels that each got.

#4069 fix(core): `Link` delete wrong icon opacity
  projects/core/components/link/link.style.less
Labels: ready to merge

#4068 feat(addon-editor): use `https` by default for links in editor
  projects/addon-editor/components/edit-link/edit-link.component.ts
  projects/addon-editor/constants/default-link-options-handler.ts
  projects/addon-editor/constants/index.ts
  projects/addon-editor/tokens/editor-options.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-links.cy.ts
Labels: ready to merge

#4012 feat(core): increase space between textfield icons
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/cdk/abstract/control.ts
  projects/cdk/abstract/interactive.ts
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
  projects/core/components/primitive-textfield/primitive-textfield.style.less
  projects/core/components/primitive-textfield/primitive-textfield.template.html
  projects/core/styles/mixins/textfield.less
  projects/core/styles/mixins/textfield.scss
  projects/demo/src/modules/components/input-tag/examples/6/index.html
  projects/demo/src/modules/components/input-tag/input-tag.module.ts
  projects/kit/components/input-tag/input-tag.style.less
  projects/kit/components/input-tag/input-tag.template.html
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.template.html
  projects/kit/components/text-area/text-area.style.less
Labels: ready to merge

#4082 fix(core): `Error` fix animation inside `Expand`
  projects/core/components/error/error.component.ts
  projects/core/components/error/error.style.less
  projects/core/components/error/error.template.html
  projects/core/components/expand/expand.component.ts
  projects/core/components/expand/expand.template.html
  projects/core/components/expand/test/expand.component.spec.ts
Labels: ready to merge

#4081 chore: add closing example to custom dialog
  projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.component.ts
Labels: ready to merge

#4078 ci: change `.browserslistrc`
  .browserslistrc
Labels: ready to merge

#4071 fix(core): `PrimitiveTextfield` don't show decoration when placeholder is present
  projects/addon-editor/components/color-selector/color-edit/color-edit.template.html
  projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
  projects/demo/src/modules/components/input-number/examples/1/index.html
  projects/demo/src/modules/components/input-number/examples/2/index.html
  projects/demo/src/modules/components/input-number/examples/4/index.html
  projects/demo/src/modules/components/input-number/examples/5/index.html
  projects/demo/src/modules/components/input-time/examples/5/index.html
  projects/demo/src/modules/markup/form/example/index.html
  projects/demo/src/modules/pipes/currency/currency.module.ts
  projects/demo/src/modules/pipes/currency/currency.template.html
  projects/demo/src/modules/pipes/currency/examples/2/template.html
  projects/demo/src/modules/pipes/field-error/examples/6/index.html
Labels: ready to merge

#4083 feat(core): `Textfield` add unfocused error state
  projects/core/styles/theme/wrapper/textfield.less
Labels: ready to merge

#4016 feat(core): `HostedDropdown` support custom `PositionAccessor` directives
  projects/core/components/hosted-dropdown/accessor-proxy.directive.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.module.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.template.html
  projects/core/components/hosted-dropdown/index.ts
  projects/demo-integrations/cypress/tests/core/dropdown/dropdown.cy.ts
  projects/demo/src/modules/components/hosted-dropdown/examples/5/accessor.ts
  projects/demo/src/modules/components/hosted-dropdown/examples/5/index.html
  projects/demo/src/modules/components/hosted-dropdown/examples/5/index.less
  projects/demo/src/modules/components/hosted-dropdown/examples/5/index.ts
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html
Labels: ready to merge

#4076 ci: enable `require-array-sort-compare`
  projects/addon-editor/components/color-selector/color-selector.component.ts
  scripts/eslint/off.js
  scripts/eslint/typescript.js
Labels: ready to merge

#4087 feat(kit): `Multiselect` add tag validator
  projects/demo/src/modules/components/multi-select/examples/1/index.html
  projects/demo/src/modules/components/multi-select/examples/1/index.ts
  projects/demo/src/modules/components/multi-select/multi-select.component.ts
  projects/demo/src/modules/components/multi-select/multi-select.template.html
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-tag/test/input-tag.component.spec.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.template.html
Labels: ready to merge

#4074 fix(kit): `Tag` fix padding
  projects/core/components/loader/loader.style.less
  projects/core/components/loader/loader.template.html
  projects/core/components/notification/notification.component.ts
  projects/core/components/notification/notification.style.less
  projects/core/directives/textfield-controller/textfield-options.ts
  projects/demo/src/modules/components/tag/tag.component.ts
  projects/kit/components/accordion/accordion-item/accordion-item.component.ts
  projects/kit/components/accordion/accordion-item/accordion-item.style.less
  projects/kit/components/badge/badge.component.ts
  projects/kit/components/badge/badge.style.less
  projects/kit/components/badged-content/badged-content.component.ts
  projects/kit/components/badged-content/badged-content.style.less
  projects/kit/components/checkbox-block/checkbox-block.component.ts
  projects/kit/components/checkbox-block/checkbox-block.style.less
  projects/kit/components/input-tag/test/input-tag-no-mode.component.spec.ts
  projects/kit/components/radio-block/radio-block.component.ts
  projects/kit/components/radio-block/radio-block.style.less
  projects/kit/components/radio-list/radio-list.component.ts
  projects/kit/components/radio-list/radio-list.style.less
  projects/kit/components/tag/tag.component.ts
  projects/kit/components/tag/tag.style.less
  projects/kit/components/tag/tag.template.html
  projects/testing/core/accordion-item.harness.ts
  projects/testing/core/badge.harness.ts
Labels: ready to merge

#4089 feat(kit): `Multiselect` add tag validator
  projects/demo/src/modules/components/multi-select/examples/1/index.html
  projects/demo/src/modules/components/multi-select/examples/1/index.ts
  projects/demo/src/modules/components/multi-select/multi-select.component.ts
  projects/demo/src/modules/components/multi-select/multi-select.template.html
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-tag/test/input-tag.component.spec.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.template.html
Labels: v2

#4006 feat(addon-editor): refactor code-block for correct highlight in the future
  projects/addon-doc/src/components/main/main.style.less
  projects/addon-editor/components/editor-socket/editor-socket.component.less
  projects/addon-editor/components/editor-socket/styles/code-blocks.less
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/highlight/code/editor-code-block.component.html
  projects/demo/src/modules/components/editor/highlight/code/editor-code-block.component.ts
  projects/demo/src/modules/components/editor/highlight/code/editor-code-block.module.ts
  projects/demo/src/modules/components/editor/highlight/code/examples/1/example.md
  projects/demo/src/modules/components/editor/highlight/code/examples/1/index.html
  projects/demo/src/modules/components/editor/highlight/code/examples/1/index.less
  projects/demo/src/modules/components/editor/highlight/code/examples/1/index.ts
  projects/demo/src/modules/components/editor/highlight/text/editor-mark-text.component.html
  projects/demo/src/modules/components/editor/highlight/text/editor-mark-text.component.ts
  projects/demo/src/modules/components/editor/highlight/text/editor-mark-text.module.ts
  projects/demo/src/modules/components/editor/highlight/text/examples/1/index.html
  projects/demo/src/modules/components/editor/highlight/text/examples/1/index.less
  projects/demo/src/modules/components/editor/highlight/text/examples/1/index.ts
Labels: ready to merge

#4084 ci: skip `prettier` for eslint
  scripts/eslint/off.js
Labels: ready to merge

#4070 feat(addon-doc): prevent override theme styles when we use own custom night theme
  projects/addon-doc/src/components/main/main.component.ts
  projects/addon-doc/src/components/main/main.template.html
  projects/addon-doc/src/public-api.ts
  projects/addon-doc/src/services/theme-night.options.ts
  projects/addon-doc/src/services/theme-night.service.ts
  projects/addon-doc/src/services/theme.options.ts
  projects/addon-doc/src/services/theme.service.ts
  projects/demo-integrations/cypress/support/helpers/set-night-mode.ts
  projects/demo-integrations/cypress/support/helpers/visit.ts
  projects/demo/src/modules/app/theme.service.ts
  projects/demo/src/modules/components/svg/svg.component.ts
  projects/demo/src/modules/components/svg/svg.template.html
  projects/demo/src/modules/markup/colors/table/table.component.ts
Labels: ready to merge

#4100 fix(cdk): remove `protected` from constructors
  projects/cdk/abstract/control.ts
  projects/cdk/abstract/interactive.ts
Labels: ready to merge

#4106 fix(addon-commerce): `Money` fix decimal limit in integer part
  projects/addon-commerce/components/money/pipes/integer-part.pipe.ts
  projects/addon-commerce/components/money/test/integer-part.pipe.spec.ts
Labels: ready to merge

#4107 fix(kit): `FieldError` work when nested inside control
  projects/demo-integrations/project.json
  projects/demo/src/modules/pipes/field-error/examples/1/index.html
  projects/demo/src/modules/pipes/field-error/examples/1/index.ts
  projects/kit/pipes/field-error/field-error-pipe.ts
Labels: ready to merge

#4113 fix(cdk): make `AbstractTuiControl` constructor DI compatible
  projects/cdk/abstract/control.ts
  projects/cdk/abstract/index.ts
  projects/cdk/abstract/value-transformer.ts
  projects/cdk/interfaces/control-value-transformer.ts
  projects/demo/src/modules/components/input-date-range/examples/4/value-transformers.ts
  projects/demo/src/modules/components/input-date-time/examples/4/value-transformer.ts
  projects/demo/src/modules/components/input-date/examples/5/native-date-transformer.directive.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
  projects/kit/components/input-date-time/input-date-time.component.ts
  projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/test/input-date.component.spec.ts
  projects/kit/tokens/date-inputs-value-transformers.ts
Labels: ready to merge

#4115 fix(addon-editor): prevent override all paragraph styles inside list
  projects/addon-editor/components/editor-socket/styles/list.less
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
Labels: ready to merge

#4128 feat(cdk): `ValueChanges` add new directive
  projects/cdk/directives/index.ts
  projects/cdk/directives/value-changes/index.ts
  projects/cdk/directives/value-changes/ng-package.json
  projects/cdk/directives/value-changes/test/value-changes.directive.spec.ts
  projects/cdk/directives/value-changes/value-changes.directive.ts
  projects/cdk/directives/value-changes/value-changes.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/directives/value-changes/examples/1/index.html
  projects/demo/src/modules/directives/value-changes/examples/1/index.ts
  projects/demo/src/modules/directives/value-changes/examples/2/index.html
  projects/demo/src/modules/directives/value-changes/examples/2/index.ts
  projects/demo/src/modules/directives/value-changes/examples/import/import-module.md
  projects/demo/src/modules/directives/value-changes/examples/import/insert-template.md
  projects/demo/src/modules/directives/value-changes/value-changes.component.ts
  projects/demo/src/modules/directives/value-changes/value-changes.module.ts
  projects/demo/src/modules/directives/value-changes/value-changes.style.less
  projects/demo/src/modules/directives/value-changes/value-changes.template.html
Labels: ready to merge

#4122 fix(addon-commerce): emulate focus on iOS by `tuiAutoFocus`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/cdk/directives/auto-focus/handlers/sync.handler.ts
  projects/cdk/directives/auto-focus/index.ts
Labels: ready to merge, v2

#4118 feat(addon-doc): add `TUI_USE_DEFAULT_NIGHT_THEME` token for ignore dark theme styles
  projects/addon-doc/src/components/main/main.component.ts
  projects/addon-doc/src/components/main/main.template.html
  projects/addon-doc/src/services/theme-night.options.ts
  projects/addon-doc/src/services/theme-night.service.ts
Labels: ready to merge

#4120 feat(addon-mobile): `TabBar` add new component
  projects/addon-mobile/components/index.ts
  projects/addon-mobile/components/tab-bar/index.ts
  projects/addon-mobile/components/tab-bar/ng-package.json
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.style.less
  projects/addon-mobile/components/tab-bar/tab-bar-item.template.html
  projects/addon-mobile/components/tab-bar/tab-bar.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar.module.ts
  projects/addon-mobile/components/tab-bar/tab-bar.style.less
  projects/core/services/router-link-active.service.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/tab-bar/examples/1/index.html
  projects/demo/src/modules/components/tab-bar/examples/1/index.ts
  projects/demo/src/modules/components/tab-bar/examples/2/index.html
  projects/demo/src/modules/components/tab-bar/examples/2/index.ts
  projects/demo/src/modules/components/tab-bar/examples/3/index.html
  projects/demo/src/modules/components/tab-bar/examples/3/index.less
  projects/demo/src/modules/components/tab-bar/examples/3/index.ts
  projects/demo/src/modules/components/tab-bar/examples/import/import-module.md
  projects/demo/src/modules/components/tab-bar/examples/import/insert-template.md
  projects/demo/src/modules/components/tab-bar/tab-bar.component.ts
  projects/demo/src/modules/components/tab-bar/tab-bar.module.ts
  projects/demo/src/modules/components/tab-bar/tab-bar.style.less
  projects/demo/src/modules/components/tab-bar/tab-bar.template.html
  projects/demo/src/modules/components/tabs/tabs.template.html
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#4127 feat(cdk): `Control` add new directive
  projects/cdk/directives/control/control.directive.ts
  projects/cdk/directives/control/control.module.ts
  projects/cdk/directives/control/index.ts
  projects/cdk/directives/control/ng-package.json
  projects/cdk/directives/control/test/control.directive.spec.ts
  projects/cdk/directives/index.ts
Labels: ready to merge

#4131 fix(core): `BreakpointService` replay value for new subscribers
  package.json
  projects/core/services/breakpoint.service.ts
Labels: ready to merge

#4123 fix(kit): `Stepper` use `TuiScrollService` instead of scrollIntoView
  projects/demo/src/modules/components/stepper/examples/3/index.html
  projects/demo/src/modules/components/stepper/examples/3/index.less
  projects/demo/src/modules/components/stepper/examples/3/index.ts
  projects/demo/src/modules/components/stepper/stepper.component.ts
  projects/demo/src/modules/components/stepper/stepper.module.ts
  projects/demo/src/modules/components/stepper/stepper.template.html
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#4140 fix(addon-doc): resizer shows `NaN` during SSR
  projects/addon-doc/src/components/demo/demo.component.ts
Labels: ready to merge

#4143 feat(cdk): add `@tuiParentStop` animation
  projects/cdk/constants/parent-animation.ts
Labels: ready to merge

#4141 fix(core): `Dialog` fix close button appearance
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.style.less
  projects/core/components/dialog/dialog.template.html
Labels: ready to merge

#4146 fix(kit): `ElasticContainer` handle nested height transitions
  projects/demo/src/modules/components/elastic-container/elastic-container.component.ts
  projects/demo/src/modules/components/elastic-container/elastic-container.module.ts
  projects/demo/src/modules/components/elastic-container/elastic-container.template.html
  projects/demo/src/modules/components/elastic-container/examples/4/index.html
  projects/demo/src/modules/components/elastic-container/examples/4/index.less
  projects/demo/src/modules/components/elastic-container/examples/4/index.ts
  projects/kit/components/elastic-container/elastic-container.component.html
  projects/kit/components/elastic-container/elastic-container.component.less
  projects/kit/components/elastic-container/elastic-container.component.ts
  projects/kit/components/elastic-container/elastic-container.directive.ts
Labels: ready to merge

#4147 fix(core): `Scrollbar` fix height in Firefox
  projects/core/components/scroll-controls/scroll-controls.style.less
Labels: ready to merge

#4148 fix(core): `Scrollbar` fix height in Firefox
  projects/core/components/scroll-controls/scroll-controls.style.less
Labels: v2

#4139 feat(cdk): clear timeout for `tuiForAsync`
  projects/cdk/directives/for-async/for-async.directive.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.component.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.module.ts
  projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
Labels: ready to merge

#4149 feat(cdk): help to tree-shake away the code unneeded for production bundles
  projects/addon-doc/src/utils/to-flat-map-pages.ts
  projects/addon-editor/components/toolbar/toolbar.component.ts
  projects/addon-tablebars/services/table-bars.service.ts
  projects/cdk/abstract/control.ts
  projects/cdk/classes/assert.ts
  projects/cdk/date-time/day-range.ts
  projects/cdk/date-time/day.ts
  projects/cdk/date-time/month-range.ts
  projects/cdk/date-time/month.ts
  projects/cdk/date-time/time.ts
  projects/cdk/date-time/year.ts
  projects/cdk/decorators/default-prop.ts
  projects/cdk/decorators/required-setter.ts
  projects/cdk/services/scroll.service.ts
  projects/cdk/utils/dom/get-element-offset.ts
  projects/cdk/utils/format/px.ts
  projects/cdk/utils/math/clamp.ts
  projects/cdk/utils/math/in-range.ts
  projects/cdk/utils/math/normalize-to-int-number.ts
  projects/cdk/utils/math/quantize.ts
  projects/cdk/utils/math/round.ts
  projects/cdk/utils/miscellaneous/ease-in-out-quad.ts
  projects/core/components/root/root.component.ts
  projects/core/components/svg/svg.component.ts
  projects/core/pipes/calendar-sheet/utils.ts
  projects/core/pipes/format-phone/format-phone.pipe.ts
  projects/core/services/svg.service.ts
  projects/core/tokens/assert-enabled.ts
  projects/core/utils/mask/create-auto-corrected-money-pipe.ts
  projects/core/utils/mask/create-correction-mask.ts
  projects/core/utils/mask/create-number-mask.ts
  projects/demo-integrations/tsconfig.json
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/utils/miscellaneous/examples/1/index.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.component.ts
  projects/kit/utils/mask/create-date-mask.ts
  projects/kit/utils/mask/create-date-range-mask.ts
  scripts/types/ng-dev-mode/index.d.ts
  tsconfig.build.json
  tsconfig.json
  tsconfig.schematics.json
  tsconfig.spec.json
Labels: ready to merge

#4153 fix(kit): `Stepper` use `TuiScrollService` instead of scrollIntoView
  projects/demo/src/modules/components/stepper/examples/3/index.html
  projects/demo/src/modules/components/stepper/examples/3/index.less
  projects/demo/src/modules/components/stepper/examples/3/index.ts
  projects/demo/src/modules/components/stepper/stepper.component.ts
  projects/demo/src/modules/components/stepper/stepper.module.ts
  projects/demo/src/modules/components/stepper/stepper.template.html
  projects/kit/components/stepper/stepper.component.ts
Labels: v2

#4162 ci: include `.pipe.ts` for linting
  scripts/eslint/angular.js
Labels: ready to merge

#4067 fix(kit): use hosts `stringify` in `FilterByInput` pipe
  projects/core/interfaces/data-list-host.ts
  projects/demo/src/modules/pipes/filter-by-input/examples/2/index.html
  projects/demo/src/modules/pipes/filter-by-input/examples/2/index.ts
  projects/demo/src/modules/pipes/filter-by-input/examples/3/index.html
  projects/demo/src/modules/pipes/filter-by-input/examples/3/index.ts
  projects/demo/src/modules/pipes/filter-by-input/filter-by-input.component.ts
  projects/demo/src/modules/pipes/filter-by-input/filter-by-input.module.ts
  projects/demo/src/modules/pipes/filter-by-input/filter-by-input.template.html
  projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts
  projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
Labels: ready to merge

#4163 feat(core): `Alert` support basic HTML as string`
  projects/core/components/alert/alert.template.html
  projects/core/components/notification/notification.component.ts
  projects/demo/src/modules/components/push/examples/2/index.ts
  projects/demo/src/modules/services/alerts/examples/1/index.ts
  projects/demo/src/modules/services/alerts/examples/2/index.ts
  projects/kit/components/push/push-alert.template.html
  projects/kit/components/push/push.service.ts
Labels: ready to merge

#4160 fix(cdk): support `autofill` values when trigger autofocus on `iOS`
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
Labels: ready to merge

#4138 feat(cdk): `Replace` add new pipe
  projects/addon-doc/src/components/page/page.component.ts
  projects/addon-doc/src/components/page/page.module.ts
  projects/addon-doc/src/components/page/page.template.html
  projects/cdk/pipes/index.ts
  projects/cdk/pipes/replace/index.ts
  projects/cdk/pipes/replace/ng-package.json
  projects/cdk/pipes/replace/replace.module.ts
  projects/cdk/pipes/replace/replace.pipe.ts
  projects/cdk/pipes/replace/test/replace.pipe.spec.ts
Labels: ready to merge

#4168 chore: fix broken e2e
  projects/demo-integrations/cypress/tests/kit/input/input.cy.ts
Labels: ready to merge

#4178 fix(addon-charts): `LineDaysChart` fix hint circle not disappearing, fix wrong hover index
  projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/demo/src/modules/charts/line-chart/examples/1/index.html
  projects/demo/src/modules/charts/line-chart/examples/1/index.ts
Labels: ready to merge

#4171 fix(cdk): `schematics` fix incorrectly processing `setNativeFocused`
  projects/cdk/schematics/ng-update/v3/constants/deprecated-functions.ts
  projects/cdk/schematics/ng-update/v3/index.ts
  projects/cdk/schematics/ng-update/v3/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deprecated-functions.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-functions.spec.ts
Labels: ready to merge

#4184 ci: cleanup bundle of `taiga-ui.dev`
  package-lock.json
  projects/demo/package.json
  projects/demo/webpack.config.ts
Labels: ready to merge

#4191 fix(core): `Dropdown` fix scroll getting stuck
  projects/core/directives/dropdown/dropdown.component.ts
Labels: ready to merge

#4196 chore(demo): fix dialog links
  projects/demo/src/modules/components/dialog/dialog.template.html
  projects/demo/src/modules/utils/tokens/examples/2/index.html
Labels: ready to merge

#4203 fix(core): `tuiTextfield` don't handle input inside legacy mask
  projects/addon-commerce/components/input-expire/test/input-expire.component.spec.ts
  projects/core/components/primitive-textfield/textfield/textfield.component.ts
  projects/core/tokens/index.ts
  projects/core/tokens/legacy-mask.ts
  projects/kit/directives/mask/legacy-mask.ts
Labels: ready to merge

#4217 fix(kit): correct detect iso code for `Kazakhstan` when phone number start with `+7`
  projects/demo/src/modules/components/input-phone-international/examples/1/index.ts
  projects/kit/components/input-phone-international/index.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/components/input-phone-international/utils/not-kz-region.ts
Labels: ready to merge

#4224 fix(core): `PrimitiveTextfield` label should not be visible when filler used and input focused
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
  projects/demo-integrations/cypress/tests/core/primitive-textfield/primitive-textfield.cy.ts
Labels: ready to merge

#4232 fix(addon-editor): use `paragraph` type for correct detect empty
  projects/addon-editor/directives/tiptap-editor/utils/is-empty-paragraph.ts
Labels: ready to merge

#4236 ci: force resolve `jest` types in IDEA
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#4207 feat(kit): `InputTime` add ability to use native picker on mobile
  projects/demo/src/modules/components/input-time/examples/6/index.html
  projects/demo/src/modules/components/input-time/examples/6/index.ts
  projects/demo/src/modules/components/input-time/input-time.component.ts
  projects/demo/src/modules/components/input-time/input-time.module.ts
  projects/demo/src/modules/components/input-time/input-time.template.html
  projects/kit/components/input-time/index.ts
  projects/kit/components/input-time/input-time-options.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.directive.ts
  projects/kit/components/input-time/input-time.module.ts
  projects/kit/components/input-time/input-time.template.html
  projects/kit/components/input-time/native-time/native-time.component.ts
  projects/kit/components/input-time/native-time/native-time.style.less
Labels: ready to merge

#4239 ci: skip linting by eslint for `less,json` files
  package.json
Labels: ready to merge

#4206 feat(core): change default size for icon
  projects/addon-commerce/components/card/card.style.less
  projects/core/components/button/button.style.less
  projects/core/components/svg/svg.style.less
  projects/demo/src/modules/components/card/examples/3/index.less
  projects/demo/src/modules/components/dialog/examples/9/index.html
  projects/demo/src/modules/components/dialog/examples/9/index.less
  projects/demo/src/modules/components/marker-icon/marker-icon.template.html
  projects/icons/all.ts
  projects/icons/src/tuiIconElectron.svg
  projects/icons/src/tuiIconElectronMono.svg
  projects/icons/src/tuiIconMaestro.svg
  projects/icons/src/tuiIconMaestroMono.svg
  projects/icons/src/tuiIconMastercard.svg
  projects/icons/src/tuiIconMastercardMono.svg
  projects/icons/src/tuiIconMir.svg
  projects/icons/src/tuiIconMirMono.svg
  projects/icons/src/tuiIconVisa.svg
  projects/icons/src/tuiIconVisaMono.svg
  projects/kit/components/marker-icon/marker-icon.style.less
  projects/testing/core/svg.harness.ts
Labels: ready to merge

#4241 feat(kit): catch `Observable` instead of `PolymorpheusPrimitive` from `PolymorpheusHandler` in `fieldError`
  projects/demo/src/modules/pipes/field-error/examples/2/index.ts
  projects/kit/pipes/field-error/field-error-pipe.ts
Labels: ready to merge

#4249 ci: reuse `projectPath` for include svg files
  scripts/compile-icons.ts
Labels: ready to merge

#4250 ci: pin node.js
  .github/actions/nodejs/action.yml
Labels: ready to merge

#4251 feat(kit): `Tag` add button selector
  projects/demo/src/modules/components/card/examples/3/index.less
  projects/demo/src/modules/components/tag/examples/3/index.html
  projects/demo/src/modules/components/tag/examples/3/index.ts
  projects/demo/src/modules/components/tag/tag.component.ts
  projects/demo/src/modules/components/tag/tag.template.html
  projects/kit/components/tag/tag.component.ts
  projects/kit/components/tag/tag.style.less
Labels: ready to merge

#4258 refactor(cdk): `TuiStaticRequestService` use `fetch` instead of `XMLHttpRequest`
  projects/cdk/services/static-request.service.ts
  projects/cdk/services/test/static-request.service.spec.ts
Labels: ready to merge

#4257 feat(cdk): `ng-add` support apps bootstrapped using a standalone component
  projects/cdk/schematics/constants/file-globs.ts
  projects/cdk/schematics/ng-add/constants/modules.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/utils/add-import-to-component.ts
  projects/cdk/schematics/utils/get-component-from-identifier.ts
  projects/cdk/schematics/utils/get-named-import-references.ts
  projects/cdk/schematics/utils/get-standalone-bootstrap-function.ts
  projects/cdk/schematics/utils/push-to-array-property.ts
Labels: ready to merge

#4269 chore(demo): improve icons markup
  projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
  projects/demo/src/modules/markup/icons/icons.component.ts
  projects/demo/src/modules/markup/icons/icons.style.less
  projects/demo/src/modules/markup/icons/icons.template.html
Labels: ready to merge

#4260 feat(addon-editor): support any protocols in `link` component
  projects/addon-editor/components/edit-link/edit-link.component.ts
  projects/addon-editor/components/edit-link/index.ts
  projects/addon-editor/components/edit-link/test/edit-link-parse.spec.ts
  projects/addon-editor/components/edit-link/utils/edit-link-parse-url.ts
  projects/addon-editor/constants/default-link-options-handler.ts
  projects/cdk/utils/miscellaneous/index.ts
  projects/cdk/utils/miscellaneous/is-valid-url.ts
  projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
Labels: ready to merge

#4278 docs: add missing closing tag in app-bar docs
  projects/demo/src/modules/components/app-bar/examples/import/insert-template.md
Labels: community contribution

#4283 chore: remove redundant logs
  projects/demo/webpack.config.ts
Labels: ready to merge

#4285 fix(core): expose `TuiBreakpointMediaKey`
  projects/core/services/breakpoint.service.ts
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#4284 feat(addon-commerce): add `TUI_INPUT_CARD_GROUPED_OPTIONS` token
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
Labels: ready to merge

#4295 feat(kit): `InputDateTime` add ability to use native picker on mobile
  projects/demo/src/modules/components/input-date-time/examples/5/index.html
  projects/demo/src/modules/components/input-date-time/examples/5/index.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.component.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.module.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.template.html
  projects/kit/components/input-date-time/input-date-time.component.ts
  projects/kit/components/input-date-time/input-date-time.directive.ts
  projects/kit/components/input-date-time/input-date-time.module.ts
  projects/kit/components/input-date-time/input-date-time.style.less
  projects/kit/components/input-date-time/input-date-time.template.html
  projects/kit/components/input-date-time/native-date-time/native-date-time.directive.ts
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-date/input-date.style.less
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/input-date/native-date/native-date.component.ts
  projects/kit/components/input-date/native-date/native-date.style.less
Labels: ready to merge

#4302 ci: include `styles.[hash].css` in bundle size tracking
  .bundlemonrc.json
  .github/workflows/bundle-size-tracking.yml
Labels: ready to merge

#4299 fix(kit): `InputDateTime` fix value setting when using valueTransformer
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: v3, ready to merge

#4298 fix(kit): `InputDateTime` fix value setting when using valueTransformer
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: v2

#4304 fix(addon-commerce): `InputCardGrouped` fix incorrect initial value display
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
Labels: ready to merge
