Repository taiga-family/taiga-ui, pull requests merged in 2023-06, with the labels that each got.

#4566 fix(core): `TUI_SCROLL_REF` fallback to `documentElement`
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/core/components/scroll-controls/scroll-controls.component.ts
  projects/core/components/scroll-controls/scrollbar.directive.ts
  projects/core/tokens/scroll-ref.ts
Labels: ready to merge

#4561 fix(core): `PositionService` eliminate memory leak
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.style.less
  projects/addon-mobile/directives/sidebar/sidebar.component.ts
  projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts
  projects/cdk/services/parents-scroll.service.ts
  projects/cdk/tokens/removed-element.ts
  projects/core/animations/animations.ts
  projects/core/components/alert/alert.component.ts
  projects/core/components/error/error.component.ts
  projects/core/components/scroll-controls/scroll-controls.component.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/enums/dropdown-animation.ts
  projects/core/services/position.service.ts
  projects/core/tokens/animation-options.ts
  projects/kit/components/pdf-viewer/pdf-viewer.component.ts
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/radio/radio.component.ts
Labels: ready to merge

#4560 deprecate(addon-commerce): use new `TUI_CARD_HOLDER_MASK` instead of deprecated `cardHolderMask`
  projects/addon-commerce/constants/card-holder-mask.ts
  projects/addon-commerce/constants/tests/card-holder-mask.spec.ts
  projects/core/utils/mask/create-correction-mask.ts
Labels: ready to merge

#4567 fix(addon-mobile): `Sheet` remove focus from under sheet with overlay
  projects/addon-mobile/components/sheet/sheet.service.ts
Labels: ready to merge

#4569 fix(kit): `InputDateRange` fix showing same month twice when `min` is later than given month
  projects/kit/internal/primitive-calendar-range/primitive-calendar-range.template.html
Labels: ready to merge

#4568 fix(kit): `Tabs` align dropdown design with datalist
  projects/kit/components/tabs/tab/tab.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
Labels: ready to merge

#4555 feat(kit): `InputPhone` uses `Maskito` instead of legacy `text-mask`
  projects/core/utils/format/format-phone.ts
  projects/demo-integrations/cypress/support/constants/index.ts
  projects/demo-integrations/cypress/support/constants/real-events-support.ts
  projects/demo-integrations/cypress/tests/kit/input-date-time/input-date-time.cy.ts
  projects/demo-integrations/cypress/tests/kit/input-phone/input-phone.cy.ts
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-phone/input-phone.directive.ts
  projects/kit/components/input-phone/input-phone.module.ts
  projects/kit/components/input-phone/input-phone.template.html
  projects/kit/components/input-phone/test/complete-phone-insertion-preprocessor.spec.ts
  projects/kit/components/input-phone/test/input-phone.component.spec.ts
  projects/kit/components/input-phone/utils/complete-phone-insertion-preprocessor.ts
  projects/kit/components/input-phone/utils/create-phone-mask-expression.ts
  projects/kit/components/input-phone/utils/index.ts
  scripts/cspell/software.json
Labels: ready to merge

#4587 fix(addon-editor): prevent paste redundant break line
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
Labels: ready to merge

#4588 fix(addon-editor): immediately unsubscribe streams when toolbar is destroyed
  projects/addon-editor/components/toolbar/toolbar.component.ts
Labels: ready to merge

#4586 chore: ignore redundant rule
  scripts/cspell/angular.json
  scripts/eslint/off.js
Labels: ready to merge

#4590 fix(testing): support node.js 18.16, jest 26+ ships jsdom out of the box
  .github/actions/nodejs/action.yml
  jest.config.ts
  package-lock.json
  projects/testing/package.json
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#4604 fix(core): `TUI_SCROLL_REF` fallback to documentElement
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/core/components/scroll-controls/scroll-controls.component.ts
  projects/core/components/scroll-controls/scrollbar.directive.ts
  projects/core/tokens/scroll-ref.ts
Labels: ready to merge, v2

#4601 fix(addon-mobile): `Sheet` remove focus from under sheet with overlay
  projects/addon-mobile/components/sheet/sheet.service.ts
Labels: v2

#4607 feat(addon-mobile): `PullToRefresh` use `TUI_SCROLL_REF`
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.template.html
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.module.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.style.less
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/cdk/observables/index.ts
  projects/cdk/observables/scroll-from.ts
  projects/core/components/scroll-controls/scrollbar.directive.ts
  projects/demo/src/modules/components/pull-to-refresh/examples/1/index.html
  projects/demo/src/modules/components/pull-to-refresh/examples/2/index.html
  projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.module.ts
  projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.style.less
  projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.template.html
Labels: ready to merge, v2

#4597 feat(core): svg source interceptor should accept svg global options
  projects/core/components/svg/svg-options.ts
  projects/core/components/svg/svg.component.ts
  projects/core/tokens/icon-place.ts
Labels: ready to merge

#4622 fix(cdk): fix change detection issue in `DialogHost`
  projects/cdk/components/dialog-host/dialog-host.component.ts
Labels: ready to merge

#4620 fix(cdk): fix icons migration, improve performance
  projects/cdk/schematics/ng-update/steps/replace-const.ts
  projects/cdk/schematics/ng-update/v3-30/index.ts
  projects/cdk/schematics/ng-update/v3-30/steps/replace-imports.ts
Labels: ready to merge

#4616 feat(addon-editor): support all heading levels by default
  projects/addon-editor/extensions/default-editor-extensions.ts
Labels: v2

#4618 refactor(kit): drop redundant code inside `InputCount`
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-count/input-count.module.ts
  projects/kit/components/input-count/input-count.template.html
Labels: ready to merge

#4615 feat(addon-editor): support all heading levels by default
  projects/addon-editor/extensions/default-editor-extensions/default-editor-extensions.ts
  projects/addon-editor/interfaces/editor-font-option.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/editor/font/editor-font.component.html
  projects/demo/src/modules/components/editor/font/editor-font.component.ts
  projects/demo/src/modules/components/editor/font/editor-font.module.ts
  projects/demo/src/modules/components/editor/font/examples/1/index.html
  projects/demo/src/modules/components/editor/font/examples/1/index.less
  projects/demo/src/modules/components/editor/font/examples/1/index.ts
Labels: ready to merge

#4632 fix(cdk): using trackBy for re-order animations
  projects/cdk/components/alert-host/alert-host.component.ts
  projects/cdk/components/alert-host/alert-host.template.html
Labels: ready to merge

#4645 fix(addon-editor): prevent paste `undefined` in url
  projects/addon-editor/components/edit-link/edit-link.component.ts
Labels: ready to merge

#4644 fix(kit): pack items around the center in checkbox
  projects/kit/components/checkbox-block/checkbox-block.style.less
Labels: ready to merge

#4646 feat(addon-editor): use `icon` for preview type of links in edit mode
  projects/addon-editor/components/edit-link/edit-link.template.html
Labels: ready to merge

#4662 feat(kit): `ProgressCircle` design improvements
  projects/kit/components/progress/progress-circle/progress-circle.style.less
Labels: v2

#4665 fix(core): `NumberFormat` fix assertion warning
  projects/core/utils/format/format-number.ts
Labels: ready to merge

#4663 refactor(kit): drop deprecated Maskito API
  package-lock.json
  projects/addon-commerce/constants/card-holder-mask.ts
  projects/addon-commerce/constants/tests/card-holder-mask.spec.ts
  projects/addon-commerce/package.json
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-phone/test/complete-phone-insertion-preprocessor.spec.ts
  projects/kit/package.json
  scripts/cspell/software.json
Labels: ready to merge

#4648 fix(kit): `MultiSelectGroup` fix padding when used without label
  projects/core/components/data-list/data-list.style.less
  projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.cy.ts
  projects/demo/src/modules/components/multi-select/examples/5/index.html
  projects/kit/components/multi-select/multi-select-group/multi-select-group.component.ts
  projects/kit/components/multi-select/multi-select-group/multi-select-group.style.less
Labels: ready to merge

#4671 fix(kit): `InputDateRange` freezes UI if `[minLength]`/`[maxLength]` are ommited
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
Labels: ready to merge

#4677 chore: cleanup redundant eslint rule
  projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts
  projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.providers.ts
  projects/addon-mobile/directives/sidebar/sidebar.component.ts
  projects/addon-mobile/directives/sidebar/sidebar.directive.ts
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/sortable.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/providers/table.providers.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/cdk/abstract/portal-host.ts
  projects/cdk/abstract/portal-service.ts
  projects/cdk/directives/auto-focus/autofocus.options.ts
  projects/cdk/directives/auto-focus/handlers/default.handler.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/cdk/directives/auto-focus/handlers/sync.handler.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/option/option.component.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/dropdown/dropdown.providers.ts
  projects/demo/src/modules/app/customization/customization.component.ts
  projects/demo/src/modules/app/customization/customization.providers.ts
  projects/demo/src/modules/components/pdf-viewer/examples/2/index.ts
  projects/demo/src/modules/components/tree/examples/7/index.ts
  projects/kit/components/arrow/arrow-options.ts
  projects/kit/components/arrow/arrow.component.ts
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/push/push-alert.directive.ts
  projects/kit/components/push/push.service.ts
  projects/kit/components/slider/helpers/slider-key-steps.directive.ts
  projects/kit/components/slider/slider.component.ts
  projects/kit/components/stepper/step/step.component.ts
  projects/kit/components/stepper/stepper.component.ts
  projects/kit/components/tree/components/tree-item-content/tree-item-content.component.ts
  projects/kit/components/tree/components/tree-item/tree-item.component.ts
  projects/kit/components/tree/components/tree-item/tree-item.providers.ts
  projects/kit/components/tree/misc/tree.constants.ts
  projects/kit/components/tree/misc/tree.interfaces.ts
  projects/kit/components/tree/misc/tree.tokens.ts
Labels: ready to merge

#4650 feat(cdk): support `TUI_AUTOFOCUS_OPTIONS`
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/addon-editor/components/editor/editor.component.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/cdk/directives/auto-focus/autofocus.options.ts
  projects/cdk/directives/auto-focus/handlers/abstract.handler.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/core/tokens/animations-duration.ts
  projects/demo/src/modules/components/editor/starter/editor-starter.module.ts
  projects/demo/src/modules/components/editor/starter/editor-starter.template.html
  projects/demo/src/modules/directives/auto-focus/auto-focus.component.ts
  projects/demo/src/modules/directives/auto-focus/auto-focus.template.html
  projects/demo/src/modules/directives/auto-focus/examples/import/insert-component.md
Labels: ready to merge

#4667 docs: color picker documentation page returns 404
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/components/color-picker/color-picker.template.html
Labels: ready to merge

#4682 fix(kit): `ProgressCircle` fix initial animation
  projects/kit/components/progress/progress-circle/progress-circle.component.ts
  projects/kit/components/progress/progress-circle/progress-circle.style.less
  projects/kit/components/progress/progress-circle/progress-circle.template.html
Labels: ready to merge

#4697 refactor: switch from const enums to regular enums
  projects/addon-commerce/enums/currency-code.ts
  projects/addon-commerce/enums/currency.ts
  projects/cdk/enums/day-of-week.ts
  projects/cdk/enums/month-number.ts
  projects/cdk/observables/drag-and-drop-from.ts
  projects/core/components/expand/expand.component.ts
  projects/core/enums/appearance.ts
  projects/core/enums/dropdown-animation.ts
  projects/core/enums/interactive-state.ts
  projects/core/enums/notification.ts
  projects/core/enums/range-state.ts
Labels: ready to merge

#4640 feat(cdk): do not overlap close buttons in nested dialogs
  projects/core/components/dialog/dialog.style.less
Labels: ready to merge

#4688 feat(addon-editor): support `translate/spellcheck` option in editor DI
  projects/addon-editor/components/editor/editor.component.html
  projects/addon-editor/components/editor/editor.component.ts
  projects/addon-editor/components/editor/editor.module.ts
  projects/addon-editor/tokens/editor-options.ts
  projects/demo/src/modules/components/editor/starter/editor-starter.template.html
Labels: ready to merge

#4698 fix(kit): ProgressCircle fix initial animation
  projects/kit/components/progress/progress-circle/progress-circle.component.ts
  projects/kit/components/progress/progress-circle/progress-circle.style.less
  projects/kit/components/progress/progress-circle/progress-circle.template.html
Labels: v2

#4701 fix(addon-editor): fix distance between toolbar and content without label
  projects/addon-editor/components/editor/editor.component.less
Labels: ready to merge

#4709 feat(kit): `InputMonth` add ability to use native picker on mobile
  projects/core/components/root/root.component.ts
  projects/demo/src/modules/components/input-month/examples/3/index.html
  projects/demo/src/modules/components/input-month/examples/3/index.ts
  projects/demo/src/modules/components/input-month/input-month.component.ts
  projects/demo/src/modules/components/input-month/input-month.module.ts
  projects/demo/src/modules/components/input-month/input-month.template.html
  projects/kit/components/input-month/input-month.component.ts
  projects/kit/components/input-month/input-month.module.ts
  projects/kit/components/input-month/input-month.style.less
  projects/kit/components/input-month/input-month.template.html
Labels: ready to merge

#4717 chore: add min/max
  projects/demo/src/modules/components/input-month/examples/3/index.html
  projects/demo/src/modules/components/input-month/examples/3/index.ts
  projects/kit/components/input-month/input-month.component.ts
  projects/kit/components/input-month/input-month.template.html
Labels: ready to merge

#4712 ci: disable `preserveConstEnums`
  tsconfig.json
Labels: ready to merge

#4718 fix(kit): `DataListWrapper` extend content to full width
  projects/demo/src/modules/components/select/examples/9/account/my-account.component.less
  projects/kit/components/data-list-wrapper/data-list-wrapper.style.less
Labels: ready to merge

#4722 fix(addon-mobile): `MobileTabs` update iOS design
  projects/addon-mobile/directives/mobile-tabs/mobile-tabs.style.less
Labels: ready to merge

#4719 feat(layout): `BlockStatus` add new component
  angular.json
  projects/cdk/package.json
  projects/demo/src/assets/images/camping.svg
  projects/demo/src/assets/images/cancel.svg
  projects/demo/src/assets/images/going-up.svg
  projects/demo/src/assets/images/not-found.svg
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/home/examples/addons.md
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/block-status/block-status.component.ts
  projects/demo/src/modules/components/block-status/block-status.module.ts
  projects/demo/src/modules/components/block-status/block-status.template.html
  projects/demo/src/modules/components/block-status/examples/1/index.html
  projects/demo/src/modules/components/block-status/examples/1/index.ts
  projects/demo/src/modules/components/block-status/examples/2/index.html
  projects/demo/src/modules/components/block-status/examples/2/index.ts
  projects/demo/src/modules/components/block-status/examples/3/index.html
  projects/demo/src/modules/components/block-status/examples/3/index.less
  projects/demo/src/modules/components/block-status/examples/3/index.ts
  projects/demo/src/modules/components/block-status/examples/4/index.html
  projects/demo/src/modules/components/block-status/examples/4/index.less
  projects/demo/src/modules/components/block-status/examples/4/index.ts
  projects/demo/src/modules/components/block-status/examples/import/import-module.md
  projects/demo/src/modules/components/block-status/examples/import/insert-template.md
  projects/kit/components/avatar/avatar.style.less
  projects/layout/LICENCE
  projects/layout/README.md
  projects/layout/components/block-status/block-status.component.ts
  projects/layout/components/block-status/block-status.directive.ts
  projects/layout/components/block-status/block-status.module.ts
  projects/layout/components/block-status/block-status.style.less
  projects/layout/components/block-status/block-status.template.html
  projects/layout/components/block-status/index.ts
  projects/layout/components/block-status/ng-package.json
  projects/layout/components/index.ts
  projects/layout/components/ng-package.json
  projects/layout/index.ts
  projects/layout/ng-package.json
  projects/layout/package.json
  projects/layout/project.json
  projects/layout/tsconfig.spec.json
  tsconfig.build.json
  tsconfig.json
Labels: ready to merge, v2

#4724 fix(kit): `LineClamp` fix `overflownChange` false positives
  projects/kit/components/line-clamp/line-clamp.component.ts
Labels: v2

#4727 fix(core): `Textfield` fix label font size
  projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
  projects/core/styles/mixins/textfield.less
  projects/core/styles/theme/variables.less
  projects/demo/src/modules/markup/typography/typography.template.html
  projects/styles/markup/tui-list.less
Labels: ready to merge

#4721 fix(addon-editor): prevent erasing history on empty value
  projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
  projects/addon-editor/extensions/starter-kit/starter-kit.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.cy.ts
  projects/demo/src/modules/components/editor/font/examples/3/font-size-tool/font-size-tool.component.ts
Labels: ready to merge

#4744 chore: update `Maskito` to v1.0.0
  package-lock.json
  projects/addon-commerce/constants/tests/card-holder-mask.spec.ts
  projects/addon-commerce/package.json
  projects/kit/package.json
Labels: ready to merge

#4746 fix(addon-mobile): `PullToRefresh` properly disable when no component was provided
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
Labels: ready to merge

#4750 fix(core): `Dropdown` fix cyclic freeze
  projects/core/directives/dropdown/dropdown.directive.ts
Labels: ready to merge

#4742 chore(demo): immediate bootstrap because it does not respect for SSR in Angular 12+
  projects/demo/src/main.browser.ts
Labels: ready to merge

#4755 fix(addon-mobile): `MobileCalendar` fix initial view
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
Labels: v3, ready to merge

#4754 fix(addon-mobile): `MobileCalendar` fix initial view
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/tests/mobile-calendar.component.spec.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
Labels: ready to merge, v2

#4756 fix(addon-commerce): hide input filler in dark mode
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
Labels: ready to merge

#4733 feat(kit): `Multiselect` add ability to use objects in native select
  projects/demo/src/modules/components/multi-select/examples/10/index.html
  projects/demo/src/modules/components/multi-select/examples/10/index.ts
  projects/kit/components/multi-select/multi-select.component.ts
  projects/kit/components/multi-select/multi-select.directive.ts
  projects/kit/components/multi-select/multi-select.module.ts
  projects/kit/components/multi-select/native-multi-select/native-multi-select-group.component.ts
  projects/kit/components/multi-select/native-multi-select/native-multi-select-group.template.html
  projects/kit/components/multi-select/native-multi-select/native-multi-select.component.ts
  projects/kit/components/multi-select/native-multi-select/native-multi-select.template.html
  projects/kit/components/multi-select/native-multi-select/native-multi-select.ts
Labels: ready to merge

#4774 feat(addon-editor): `ColorSelector` uses `Maskito` instead of legacy `text-mask`
  projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
  projects/addon-editor/components/color-selector/color-edit/color-edit.module.ts
  projects/addon-editor/components/color-selector/color-edit/color-edit.template.html
  projects/kit/directives/mask/legacy-mask.ts
Labels: ready to merge

#4777 fix(addon-charts): `RingChart` fix mask url
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/addon-charts/components/pie-chart/pie-chart.component.ts
  projects/addon-charts/utils/prepare-external-url.ts
Labels: ready to merge

#4775 chore(cdk): partial revert `@tuiPure`
  projects/cdk/decorators/pure.ts
Labels: ready to merge

#4779 fix: `tuiSlot` extend type with a string
  projects/addon-mobile/components/app-bar/app-bar.directive.ts
  projects/layout/components/block-status/block-status.directive.ts
Labels: ready to merge

#4764 ci: upgrade nx
  .env
  nx.json
  package-lock.json
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-editor/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo-integrations/project.json
  projects/demo/project.json
  projects/eslint-plugin/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
  scripts/nx/decorate-angular-cli.ts
  scripts/postinstall.ts
  scripts/project.json
Labels: ready to merge

#4725 feat(kit): `InputNumber` uses `Maskito` instead of legacy `text-mask`
  projects/core/utils/mask/create-auto-corrected-money-pipe.ts
  projects/core/utils/mask/create-number-mask.ts
  projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts
  projects/core/utils/mask/masked-money-value-is-empty.ts
  projects/core/utils/mask/masked-number-string-to-number.ts
  projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.cy.ts
  projects/demo-integrations/cypress/tests/kit/input-number/input-number.cy.ts
  projects/demo-integrations/cypress/tests/kit/input-range/input-range.cy.ts
  projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.cy.ts
  projects/kit/components/input-count/input-count.component.ts
  projects/kit/components/input-count/test/input-count-options.component.spec.ts
  projects/kit/components/input-count/test/input-count.component.spec.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.module.ts
  projects/kit/components/input-number/input-number.template.html
  projects/kit/components/input-number/test/input-number-format.spec.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
  projects/kit/components/input-range/test/input-range.component.spec.ts
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
Labels: ready to merge

#4787 fix(cdk): `TuiStaticRequestService` should be throw error when response code is not `200`
  projects/cdk/services/static-request.service.ts
  projects/demo/src/modules/icons/icons.component.ts
  projects/demo/src/modules/icons/icons.template.html
Labels: ready to merge

#4796 fix(addon-table): fix z-index for 2-dimensional sticky tables
  projects/addon-table/components/table/th/th.style.less
Labels: ready to merge

#4785 fix(addon-editor): blinking caret doesn't appear in first item in list
  .cspell.json
  projects/addon-editor/components/editor-socket/styles/list.less
  projects/demo-integrations/cypress/support/editor/html.ts
  projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
Labels: ready to merge

#4795 feat(core): `Dropdown` add appearance option
  projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
  projects/core/directives/dropdown/dropdown-options.directive.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.module.ts
  projects/core/directives/dropdown/dropdown.style.less
  projects/core/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/components/tabs/tabs.component.ts
  projects/demo/src/modules/directives/dropdown/dropdown.component.ts
  projects/demo/src/modules/directives/dropdown/dropdown.module.ts
  projects/demo/src/modules/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/directives/dropdown/examples/1/index.html
  projects/demo/src/modules/directives/dropdown/examples/4/index.html
  projects/demo/src/modules/directives/dropdown/examples/4/index.less
  projects/demo/src/modules/directives/dropdown/examples/4/index.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
Labels: ready to merge

#4786 docs: setting up dynamic language switch
  projects/demo/src/modules/customization/i18n/app.esbuild.module.md
  projects/demo/src/modules/customization/i18n/i18n.component.ts
  projects/demo/src/modules/customization/i18n/i18n.template.html
Labels: ready to merge

#4798 chore: mark `GROUP_CLASS_NAMES` as deprecated
  projects/kit/constants/group-class-names.ts
Labels: ready to merge

#4797 fix(kit): `Checkbox`/`Radio` properly react to mode
  projects/kit/components/checkbox-block/checkbox-block.component.ts
  projects/kit/components/checkbox-block/checkbox-block.module.ts
  projects/kit/components/checkbox-block/checkbox-block.template.html
  projects/kit/components/checkbox-labeled/checkbox-labeled.component.ts
  projects/kit/components/radio-block/radio-block.component.ts
  projects/kit/components/radio-block/radio-block.module.ts
  projects/kit/components/radio-block/radio-block.template.html
  projects/kit/components/radio-labeled/radio-labeled.component.ts
Labels: ready to merge

#4799 fix(addon-mobile): `PullToRefresh` remove transform CSS
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html
Labels: ready to merge

#4806 fix(addon-mobile): `Sheet` fix premature closing
  projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
  projects/demo/src/modules/services/table-bar/examples/import/template.md
Labels: ready to merge

#4805 refactor(kit): drop mutations of caret's index from `InputNumber` (update `Maskito`)
  package-lock.json
  projects/addon-commerce/package.json
  projects/core/constants/decimal-symbols.ts
  projects/core/constants/mask-caret-trap.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.template.html
  projects/kit/components/input-range/test/input-range.component.spec.ts
  projects/kit/package.json
Labels: ready to merge
