Repository taiga-family/taiga-ui, pull requests merged in 2024-03, with the labels that each got.

#6921 feat(kit): support `[label]` in `tui-avatar-labeled`
  .cspell.json
  projects/demo/src/modules/experimental/avatar/examples/6/index.html
  projects/experimental/components/avatar-labeled/avatar-labeled.component.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.module.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.styles.less
Labels: ready to merge, v3

#6877 chore: support rel property for links
  projects/addon-doc/components/navigation/navigation.template.html
Labels: ready to merge, v4

#6932 chore: update ng-event-plugins
  package-lock.json
  package.json
  projects/cdk/package.json
  projects/core/package.json
Labels: ready to merge, v3

#6943 chore: fix demo
  projects/demo/src/modules/charts/axes/examples/2/index.html
  projects/demo/src/modules/charts/axes/examples/2/index.ts
Labels: v3

#6920 feat(kit): support `[label]` in `tui-avatar-labeled`
  projects/demo/src/modules/components/avatar/examples/6/index.html
  projects/kit/components/avatar-labeled/avatar-labeled.component.ts
  projects/kit/components/avatar-labeled/avatar-labeled.styles.less
Labels: ready to merge, v4

#6944 fix(kit): prevent navigation to parent page if navigation occurs from dialog
  projects/kit/components/routable-dialog/routable-dialog.component.ts
  projects/kit/components/routable-dialog/test/routable-dialog.component.spec.ts
Labels: ready to merge, v3

#6942 chore: fix demo
  projects/demo/src/modules/charts/axes/examples/2/index.html
  projects/demo/src/modules/charts/axes/examples/2/index.ts
Labels: ready to merge, v4

#6941 chore: use packages from peer dependencies
  package-lock.json
  package.json
Labels: ready to merge

#6949 chore: fix stackblitz starter
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Labels: ready to merge

#6950 chore: update jest preset
  package-lock.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-preview/package.json
  projects/addon-table/package.json
  projects/addon-tablebars/package.json
  projects/cdk/package.json
  projects/core/package.json
  projects/experimental/package.json
  projects/i18n/package.json
  projects/icons/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge

#6952 refactor!: `BadgeNotification` move to `kit`, make it standalone
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/badge-notification/badge-notification.component.ts
  projects/demo/src/modules/components/badge-notification/badge-notification.module.ts
  projects/demo/src/modules/components/badge-notification/badge-notification.template.html
  projects/demo/src/modules/components/badge-notification/examples/1/index.html
  projects/demo/src/modules/components/badge-notification/examples/1/index.less
  projects/demo/src/modules/components/badge-notification/examples/1/index.ts
  projects/demo/src/modules/components/badge-notification/examples/2/index.html
  projects/demo/src/modules/components/badge-notification/examples/2/index.less
  projects/demo/src/modules/components/badge-notification/examples/2/index.ts
  projects/demo/src/modules/components/badge-notification/examples/import/import-module.md
  projects/demo/src/modules/components/badge-notification/examples/import/insert-template.md
  projects/demo/src/modules/components/badged-content/badged-content.module.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/chip/chip.module.ts
  projects/demo/src/modules/experimental/header/header.module.ts
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/demo/src/modules/experimental/segmented/segmented.module.ts
  projects/experimental/components/badge-notification/badge-notification.module.ts
  projects/experimental/components/index.ts
  projects/experimental/components/navigation/header.component.ts
  projects/experimental/components/segmented/segmented.component.ts
  projects/kit/components/badge-notification/badge-notification.component.ts
  projects/kit/components/badge-notification/badge-notification.options.ts
  projects/kit/components/badge-notification/badge-notification.style.less
  projects/kit/components/badge-notification/index.ts
  projects/kit/components/badge-notification/ng-package.json
  projects/kit/components/index.ts
Labels: ready to merge, v4

#6946 fix(kit): `InputDateMulti` fix disableItemHandler
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
Labels: ready to merge, v4

#6947 fix(kit): `InputDateMulti` fix disableItemHandler
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
Labels: ready to merge, v3

#6948 fix(addon-table): eyes not draggable
  projects/addon-table/components/reorder/reorder.style.less
  projects/addon-table/components/reorder/reorder.template.html
Labels: ready to merge, v3

#6596 chore(demo): add new e2e test for field error
  projects/demo-playwright/tests/kit/field-error/field-error.spec.ts
  projects/demo/src/modules/pipes/field-error/examples/3/index.html
  projects/demo/src/modules/pipes/field-error/examples/3/index.less
  projects/demo/src/modules/pipes/field-error/examples/3/index.ts
  projects/demo/src/modules/pipes/field-error/field-error.module.ts
Labels: ready to merge

#6956 chore: cypress flaky
  projects/demo-cypress/src/tests/static-request.cy.ts
Labels: ready to merge

#6960 refactor!: `Sensitive` move to kit, make it standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/directives/sensitive/examples/1/index.html
  projects/demo/src/modules/directives/sensitive/examples/1/index.less
  projects/demo/src/modules/directives/sensitive/examples/1/index.ts
  projects/demo/src/modules/directives/sensitive/examples/2/index.html
  projects/demo/src/modules/directives/sensitive/examples/2/index.ts
  projects/demo/src/modules/directives/sensitive/examples/import/import-module.md
  projects/demo/src/modules/directives/sensitive/examples/import/insert-template.md
  projects/demo/src/modules/directives/sensitive/sensitive.component.ts
  projects/demo/src/modules/directives/sensitive/sensitive.module.ts
  projects/demo/src/modules/directives/sensitive/sensitive.template.html
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/header/header.module.ts
  projects/experimental/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/experimental/directives/index.ts
  projects/experimental/directives/sensitive/sensitive.module.ts
  projects/kit/directives/index.ts
  projects/kit/directives/sensitive/index.ts
  projects/kit/directives/sensitive/ng-package.json
  projects/kit/directives/sensitive/sensitive.component.ts
  projects/kit/directives/sensitive/sensitive.directive.ts
  projects/kit/directives/sensitive/sensitive.style.less
Labels: ready to merge, v4

#6961 refactor!: move `FallbackSrc`, `Initials`, `Autocolor` pipes to core, make it standalone
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
  projects/core/pipes/auto-color/auto-color.pipe.ts
  projects/core/pipes/auto-color/index.ts
  projects/core/pipes/auto-color/ng-package.json
  projects/core/pipes/fallback-src/fallback-src.pipe.ts
  projects/core/pipes/fallback-src/index.ts
  projects/core/pipes/fallback-src/ng-package.json
  projects/core/pipes/index.ts
  projects/core/pipes/initials/index.ts
  projects/core/pipes/initials/initials.pipe.ts
  projects/core/pipes/initials/ng-package.json
  projects/core/utils/format/index.ts
  projects/core/utils/format/string-hash-to-hsl.ts
  projects/core/utils/format/test/string-hash-to-hsl.spec.ts
  projects/demo/src/modules/components/avatar/avatar.template.html
  projects/demo/src/modules/components/avatar/examples/1/index.ts
  projects/demo/src/modules/components/avatar/examples/2/index.ts
  projects/demo/src/modules/components/avatar/examples/4/index.ts
  projects/demo/src/modules/components/avatar/examples/6/index.ts
  projects/demo/src/modules/components/badged-content/badged-content.module.ts
  projects/demo/src/modules/components/block-status/block-status.module.ts
  projects/demo/src/modules/components/combo-box/combo-box.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/demo/src/modules/components/multi-select/multi-select.module.ts
  projects/demo/src/modules/components/select/select.module.ts
  projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts
  projects/demo/src/modules/components/tooltip/tooltip.module.ts
  projects/demo/src/modules/directives/dropdown-selection/dropdown-selection.module.ts
  projects/demo/src/modules/directives/hint/hint.module.ts
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/experimental/index.ts
  projects/experimental/pipes/auto-color/auto-color.module.ts
  projects/experimental/pipes/auto-color/index.ts
  projects/experimental/pipes/fallback-src/fallback-src.module.ts
  projects/experimental/pipes/fallback-src/index.ts
  projects/experimental/pipes/index.ts
  projects/experimental/pipes/initials/index.ts
  projects/experimental/pipes/initials/initials.module.ts
  projects/experimental/pipes/initials/ng-package.json
  projects/kit/components/tag/tag.component.ts
  projects/kit/utils/format/index.ts
  projects/kit/utils/format/ng-package.json
  projects/kit/utils/index.ts
Labels: ready to merge, v4

#6964 chore(demo): migrate documentation page `Alert` to standalone components
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/alert/alert.component.ts
  projects/demo/src/modules/components/alert/alert.module.ts
  projects/demo/src/modules/components/alert/examples/1/index.ts
  projects/demo/src/modules/components/alert/examples/2/index.ts
  projects/demo/src/modules/components/alert/examples/3/alert-example/alert-example.component.ts
  projects/demo/src/modules/components/alert/examples/3/alert-example/alert-example.module.ts
  projects/demo/src/modules/components/alert/examples/3/index.ts
  projects/demo/src/modules/components/alert/examples/4/alert-example-with-data/alert-example-with-data.component.ts
  projects/demo/src/modules/components/alert/examples/4/alert-example-with-data/alert-example-with-data.module.ts
  projects/demo/src/modules/components/alert/examples/4/index.ts
  projects/demo/src/modules/components/alert/examples/5/alert-example-with-custom-label/alert-example-with-custom-label.component.ts
  projects/demo/src/modules/components/alert/examples/5/alert-example-with-custom-label/alert-example-with-custom-label.module.ts
  projects/demo/src/modules/components/alert/examples/5/custom-label/custom-label.component.ts
  projects/demo/src/modules/components/alert/examples/5/custom-label/custom-label.module.ts
  projects/demo/src/modules/components/alert/examples/5/index.ts
  projects/demo/src/modules/components/alert/examples/6/index.ts
Labels: ready to merge

#6969 chore(demo): migrate documentation page `Badge` to standalone components
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/badge/badge.component.ts
  projects/demo/src/modules/components/badge/badge.module.ts
  projects/demo/src/modules/components/badge/examples/1/index.ts
  projects/demo/src/modules/components/badge/examples/2/index.ts
  projects/demo/src/modules/components/badge/examples/3/index.ts
  projects/demo/src/modules/components/badge/examples/4/index.ts
  projects/demo/src/modules/components/badge/examples/5/index.ts
  projects/demo/src/modules/components/badge/examples/6/index.ts
Labels: ready to merge

#6970 chore(demo): fix `API` section of documentation page `FormatNumber`
  projects/demo/src/modules/pipes/format-number/format-number.template.html
Labels: ready to merge

#6978 chore(cdk): migrations for `TuiDestroyService` => `takeUntilDestroyed`(`@angular/core/rxjs-interop`)
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-destroy-service.spec.ts
Labels: ready to merge

#6982 chore(schematics): fix possibility to manually run migration schematics
  package-lock.json
  projects/cdk/package.json
  projects/cdk/schematics/utils/templates/elements.ts
Labels: ready to merge

#6971 chore(demo): remove global class `b-full-width`
  projects/demo/src/modules/components/accordion/accordion.template.html
  projects/demo/src/modules/components/expand/expand.template.html
  projects/demo/src/modules/components/input-card-grouped/input-card-grouped.template.html
  projects/demo/src/modules/components/input-card/input-card.template.html
  projects/demo/src/modules/icons/icons.template.html
  projects/demo/src/modules/pipes/format-number/format-number.template.html
  projects/demo/src/modules/pipes/format-phone/format-phone.template.html
  projects/demo/src/modules/services/scroll/scroll.template.html
  projects/demo/src/styles.less
Labels: ready to merge, v4

#6985 chore(schematics): enable possibility to manually run migration for `4.0.0`
  projects/cdk/schematics/collection.json
  projects/cdk/schematics/ng-update/v4/schema.json
  projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-legacy-mask.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-prevent-default.ts
Labels: ready to merge

#6965 refactor!: `Icon` component move to core, make standalone
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/icon/icon.component.ts
  projects/core/components/icon/icon.style.less
  projects/core/components/icon/index.ts
  projects/core/components/icon/ng-package.json
  projects/core/components/index.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/badge/examples/3/index.ts
  projects/demo/src/modules/components/badged-content/badged-content.module.ts
  projects/demo/src/modules/components/block/block.module.ts
  projects/demo/src/modules/components/icon/examples/1/index.html
  projects/demo/src/modules/components/icon/examples/1/index.ts
  projects/demo/src/modules/components/icon/examples/2/index.html
  projects/demo/src/modules/components/icon/examples/2/index.less
  projects/demo/src/modules/components/icon/examples/2/index.ts
  projects/demo/src/modules/components/icon/examples/3/index.html
  projects/demo/src/modules/components/icon/examples/3/index.ts
  projects/demo/src/modules/components/icon/examples/import/import-module.md
  projects/demo/src/modules/components/icon/examples/import/insert-template.md
  projects/demo/src/modules/components/icon/icon.component.ts
  projects/demo/src/modules/components/icon/icon.module.ts
  projects/demo/src/modules/components/icon/icon.template.html
  projects/demo/src/modules/components/swipe-action/swipe-actions.module.ts
  projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.module.ts
  projects/demo/src/modules/experimental/button-group/button-group.module.ts
  projects/demo/src/modules/experimental/button/button.module.ts
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/header/header.module.ts
  projects/demo/src/modules/experimental/label/label.module.ts
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/demo/src/modules/experimental/pin/pin.module.ts
  projects/demo/src/modules/experimental/segmented/segmented.module.ts
  projects/demo/src/modules/experimental/textfield/textfield.module.ts
  projects/demo/src/modules/experimental/tooltip/tooltip.module.ts
  projects/demo/used-icons.ts
  projects/experimental/components/icon/icon.module.ts
  projects/experimental/components/index.ts
  projects/experimental/components/rating/rating.module.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.module.ts
  projects/experimental/components/tooltip/tooltip.module.ts
  projects/kit/components/tag/tag.module.ts
Labels: ready to merge, v4

#6983 chore: `tui-checkbox-labeled`, `tui-radio-labeled` add migration
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: v4

#6987 chore: fix `v4` migration `TypeError: Cannot read properties of null (reading 'getSourceFiles')`
  .github/workflows/schematics.yml
  projects/cdk/project.json
  projects/cdk/schematics/ng-update/v4/index.ts
Labels: ready to merge

#6988 ci: add workflow to check `dry-run` of the latest migration schematic
  .github/workflows/schematics.yml
  package-lock.json
  package.json
  projects/cdk/project.json
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-hints.spec.ts
  projects/cdk/schematics/utils/get-named-import-references.ts
Labels: ready to merge, v3

#6910 feat(experimental): `BlockDetails` add new component
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/block-details/block-details.component.ts
  projects/demo/src/modules/experimental/block-details/block-details.module.ts
  projects/demo/src/modules/experimental/block-details/block-details.template.html
  projects/demo/src/modules/experimental/block-details/examples/1/index.html
  projects/demo/src/modules/experimental/block-details/examples/1/index.ts
  projects/demo/src/modules/experimental/block-details/examples/2/index.html
  projects/demo/src/modules/experimental/block-details/examples/2/index.less
  projects/demo/src/modules/experimental/block-details/examples/2/index.ts
  projects/demo/src/modules/experimental/block-details/examples/import/import-module.md
  projects/demo/src/modules/experimental/block-details/examples/import/insert-template.md
  projects/demo/src/modules/experimental/comment/comment.component.ts
  projects/demo/src/modules/experimental/comment/comment.module.ts
  projects/demo/src/modules/experimental/comment/comment.template.html
  projects/demo/src/modules/experimental/comment/examples/1/index.html
  projects/demo/src/modules/experimental/comment/examples/1/index.ts
  projects/demo/src/modules/experimental/comment/examples/2/index.html
  projects/demo/src/modules/experimental/comment/examples/2/index.less
  projects/demo/src/modules/experimental/comment/examples/2/index.ts
  projects/demo/src/modules/experimental/comment/examples/import/import-module.md
  projects/demo/src/modules/experimental/comment/examples/import/insert-template.md
  projects/demo/used-icons.ts
  projects/experimental/directives/block-details/block-details.component.ts
  projects/experimental/directives/block-details/block-details.directive.ts
  projects/experimental/directives/block-details/block-details.module.ts
  projects/experimental/directives/block-details/block-details.style.less
  projects/experimental/directives/block-details/index.ts
  projects/experimental/directives/block-details/ng-package.json
  projects/experimental/directives/comment/comment.component.ts
  projects/experimental/directives/comment/comment.directive.ts
  projects/experimental/directives/comment/comment.module.ts
  projects/experimental/directives/comment/comment.style.less
  projects/experimental/directives/comment/index.ts
  projects/experimental/directives/comment/ng-package.json
  projects/experimental/directives/index.ts
Labels: ready to merge, v3

#6993 chore(schematics): optimize `getNamedImportReferences` utility
  projects/cdk/schematics/utils/get-named-import-references.ts
Labels: ready to merge

#7007 chore(schematics): improve migration `TuiDestroyService` => `takeUntilDestroyed`
  projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
  projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/schematic-migrate-destroy-service.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/utils.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-destroy-service.spec.ts
Labels: ready to merge

#7016 fix(core): disable isObscured check for `HintPointer`
  projects/core/directives/hint/hint-hover.directive.ts
  projects/demo/src/modules/charts/pie-chart/examples/2/index.ts
Labels: ready to merge, v3

#7018 refactor: support `parse5@v7`
  package-lock.json
  projects/cdk/package.json
  projects/cdk/schematics/ng-update/interfaces/replacement-attribute-to-directive.ts
  projects/cdk/schematics/ng-update/interfaces/replacement-attribute.ts
  projects/cdk/schematics/ng-update/interfaces/replacement-tag.ts
  projects/cdk/schematics/ng-update/utils/templates/replace-tag.ts
  projects/cdk/schematics/ng-update/v3-5/steps/migrate-expand-templates.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-polymorpheus.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-textfield-controller.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts
  projects/cdk/schematics/ng-update/v4/steps/utils/remove-attrs.ts
  projects/cdk/schematics/utils/templates/elements.ts
  projects/cdk/schematics/utils/templates/inputs.ts
  projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
Labels: ready to merge

#7021 fix(core): disable isObscured check for `HintPointer`
  projects/core/directives/hint/hint-hover.directive.ts
Labels: ready to merge, v4

#7010 feat(layout): `BlockDetails`, `Comment` add new components
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/block-details/block-details.component.ts
  projects/demo/src/modules/components/block-details/block-details.template.html
  projects/demo/src/modules/components/block-details/examples/1/index.html
  projects/demo/src/modules/components/block-details/examples/1/index.ts
  projects/demo/src/modules/components/block-details/examples/2/index.html
  projects/demo/src/modules/components/block-details/examples/2/index.less
  projects/demo/src/modules/components/block-details/examples/2/index.ts
  projects/demo/src/modules/components/block-details/examples/import/import-module.md
  projects/demo/src/modules/components/block-details/examples/import/insert-template.md
  projects/demo/src/modules/directives/comment/comment.component.ts
  projects/demo/src/modules/directives/comment/comment.template.html
  projects/demo/src/modules/directives/comment/examples/1/index.html
  projects/demo/src/modules/directives/comment/examples/1/index.ts
  projects/demo/src/modules/directives/comment/examples/2/index.html
  projects/demo/src/modules/directives/comment/examples/2/index.less
  projects/demo/src/modules/directives/comment/examples/2/index.ts
  projects/demo/src/modules/directives/comment/examples/import/import-module.md
  projects/demo/src/modules/directives/comment/examples/import/insert-template.md
  projects/demo/used-icons.ts
  projects/kit/directives/comment/comment.component.ts
  projects/kit/directives/comment/comment.directive.ts
  projects/kit/directives/comment/comment.style.less
  projects/kit/directives/comment/index.ts
  projects/kit/directives/comment/ng-package.json
  projects/kit/directives/index.ts
  projects/layout/directives/block-details/block-details.component.ts
  projects/layout/directives/block-details/block-details.directive.ts
  projects/layout/directives/block-details/block-details.style.less
  projects/layout/directives/block-details/index.ts
  projects/layout/directives/block-details/ng-package.json
  projects/layout/directives/index.ts
  projects/layout/directives/ng-package.json
  projects/layout/index.ts
Labels: ready to merge, v4

#7008 chore: bump tui-editor
  package-lock.json
  package.json
Labels: ready to merge, v3

#6998 chore: nx 18
  package-lock.json
  package.json
Labels: ready to merge, v4

#6934 feat(kit): `Skeleton` add new directive
  projects/addon-doc/components/main/main.component.ts
  projects/addon-doc/components/main/main.template.html
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.html
  projects/demo/src/modules/directives/skeleton/examples/1/index.less
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/skeleton/examples/2/index.html
  projects/demo/src/modules/directives/skeleton/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/import/import.md
  projects/demo/src/modules/directives/skeleton/examples/import/insert.md
  projects/demo/src/modules/directives/skeleton/skeleton.component.ts
  projects/demo/src/modules/directives/skeleton/skeleton.module.ts
  projects/demo/src/modules/directives/skeleton/skeleton.template.html
  projects/demo/src/modules/markup/skeleton/examples/1/index.html
  projects/demo/src/modules/markup/skeleton/examples/1/index.less
  projects/demo/src/modules/markup/skeleton/examples/1/index.ts
  projects/demo/src/modules/markup/skeleton/examples/2/index.html
  projects/demo/src/modules/markup/skeleton/examples/2/index.less
  projects/demo/src/modules/markup/skeleton/examples/2/index.ts
  projects/demo/src/modules/markup/skeleton/skeleton.component.ts
  projects/demo/src/modules/markup/skeleton/skeleton.module.ts
  projects/demo/src/modules/markup/skeleton/skeleton.template.html
  projects/kit/directives/index.ts
  projects/kit/directives/skeleton/index.ts
  projects/kit/directives/skeleton/ng-package.json
  projects/kit/directives/skeleton/skeleton.component.ts
  projects/kit/directives/skeleton/skeleton.directive.ts
  projects/kit/directives/skeleton/skeleton.style.less
Labels: ready to merge, v4

#7022 fix(kit): `TasbWithMore` fix redundant left margin for single element
  projects/demo-playwright/tests/kit/tabs/tabs.spec.ts
  projects/kit/components/tabs/tab/tab.style.less
Labels: ready to merge, v4

#7024 feat(experimental): `Skeleton` add new directive
  projects/addon-doc/components/main/main.component.ts
  projects/addon-doc/components/main/main.template.html
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/skeleton/examples/1/index.html
  projects/demo/src/modules/experimental/skeleton/examples/1/index.less
  projects/demo/src/modules/experimental/skeleton/examples/1/index.ts
  projects/demo/src/modules/experimental/skeleton/examples/2/index.html
  projects/demo/src/modules/experimental/skeleton/examples/2/index.ts
  projects/demo/src/modules/experimental/skeleton/examples/import/import.md
  projects/demo/src/modules/experimental/skeleton/examples/import/insert.md
  projects/demo/src/modules/experimental/skeleton/skeleton.component.ts
  projects/demo/src/modules/experimental/skeleton/skeleton.module.ts
  projects/demo/src/modules/experimental/skeleton/skeleton.template.html
  projects/experimental/directives/index.ts
  projects/experimental/directives/skeleton/index.ts
  projects/experimental/directives/skeleton/ng-package.json
  projects/experimental/directives/skeleton/skeleton.component.ts
  projects/experimental/directives/skeleton/skeleton.directive.ts
  projects/experimental/directives/skeleton/skeleton.module.ts
  projects/experimental/directives/skeleton/skeleton.style.less
Labels: ready to merge

#7023 chore: ssr problem in editor demo
  projects/cdk/directives/native-validator/native-validator.directive.ts
Labels: ready to merge

#7028 fix(addon-table): key type check
  projects/addon-table/components/table/directives/head.directive.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/directives/table-filters/table-filter.directive.ts
Labels: ready to merge, v3

#7029 chore(demo): add example with sorter by default
  projects/demo/src/modules/tables/table/examples/3/index.html
Labels: ready to merge, v3

#7027 chore(demo): `app` should be `standalone` component
  .cspell.json
  projects/demo/project.json
  projects/demo/server.ts
  projects/demo/src/main.browser.ts
  projects/demo/src/main.server.ts
  projects/demo/src/main.ts
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/app/app.server.module.ts
  projects/demo/tsconfig.app.json
  projects/demo/tsconfig.server.json
Labels: ready to merge

#7030 feat(addon-doc): support external link in navigation
  projects/addon-doc/components/navigation/navigation.template.html
  projects/demo-playwright/tests/demo/get-demo-paths.ts
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge, v3

#7020 chore(demo): add example with sorter by default
  projects/demo/src/modules/tables/table/examples/3/index.html
Labels: ready to merge, v4

#7019 fix(addon-table): key type check
  projects/addon-table/components/table/directives/head.directive.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/directives/table-filters/table-filter.directive.ts
Labels: ready to merge, v4

#7037 chore(demo): revert for demo
  projects/demo/src/emulate/ng-zone-options.ts
Labels: ready to merge, v3

#7038 chore(demo): remove useless configs
  projects/demo/project.json
  projects/demo/src/emulate/ng-zone-options.coalescing.ts
  projects/demo/src/emulate/ng-zone-options.ts
Labels: ready to merge

#7039 chore: `HostedDropdown` add migration
  projects/addon-table/components/table-pagination/table-pagination.module.ts
  projects/addon-table/components/table-pagination/table-pagination.template.html
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-hosted-dropdown.spec.ts
  projects/demo-playwright/tests/core/data-list/data-list.spec.ts
  projects/demo-playwright/tests/kit/tabs/tabs.spec.ts
  projects/demo-playwright/utils/page-objects/table-pagination-page.po.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.module.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.template.html
  projects/demo/src/modules/components/breadcrumbs/breadcrumbs.module.ts
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.html
  projects/demo/src/modules/components/button/button.module.ts
  projects/demo/src/modules/components/button/examples/3/index.html
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/data-list/examples/1/index.html
  projects/demo/src/modules/components/data-list/examples/2/index.html
  projects/demo/src/modules/components/data-list/examples/2/index.ts
  projects/demo/src/modules/components/data-list/examples/3/index.html
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/data-list/examples/5/index.html
  projects/demo/src/modules/components/data-list/examples/6/index.html
  projects/demo/src/modules/components/items-with-more/examples/2/index.html
  projects/demo/src/modules/components/items-with-more/items-with-more.module.ts
  projects/demo/src/modules/components/line-clamp/examples/4/index.html
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/components/line-clamp/line-clamp.module.ts
  projects/demo/src/modules/components/tabs/examples/5/index.html
  projects/demo/src/modules/components/tabs/examples/5/index.ts
  projects/demo/src/modules/components/tabs/tabs.module.ts
  projects/demo/src/modules/directives/appearance/appearance.module.ts
  projects/demo/src/modules/directives/appearance/examples/1/index.html
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-large/examples/7/index.html
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/cell/examples/6/index.html
  projects/demo/src/modules/tables/table/examples/4/index.html
  projects/demo/src/modules/tables/table/table.module.ts
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
  projects/kit/components/tabs/tabs.module.ts
Labels: ready to merge, v4

#7034 feat(experimental): `Button` add manual :checked appearance
  projects/core/styles/theme/appearance/outline.less
  projects/demo/src/modules/experimental/button/examples/2/index.html
Labels: ready to merge, v3

#7040 chore(demo): add `provideZoneChangeDetection`
  projects/demo/src/modules/app/app.config.ts
Labels: ready to merge

#6995 ci: eslint `no-duplicate`
  projects/demo/src/modules/components/avatar/examples/4/index.html
Labels: ready to merge

#7050 feat(experimental): `Button` add manual :checked appearance
  projects/core/styles/theme/appearance/outline.less
  projects/demo/src/modules/experimental/button/examples/2/index.html
Labels: ready to merge

#7056 refactor(core): `Link` uses `Icon` instead of legacy `Svg`
  projects/addon-doc/components/doc-tab/doc-tab.component.html
  projects/addon-doc/components/doc-tab/doc-tab.component.less
  projects/addon-doc/components/doc-tab/doc-tab.module.ts
  projects/core/components/link/link.module.ts
  projects/core/components/link/link.style.less
  projects/core/components/link/link.template.html
  projects/demo/src/modules/app/app.style.less
Labels: ready to merge

#7051 chore(demo): fix typo
  projects/demo/src/modules/markup/shadows/shadows.template.html
Labels: ready to merge, v4

#7048 feat(addon-doc): support lazy component for preview
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.template.html
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/avatar/avatar.component.ts
  projects/demo/src/modules/components/avatar/examples/1/index.ts
  projects/demo/src/modules/components/avatar/examples/2/index.ts
  projects/demo/src/modules/components/avatar/examples/3/index.ts
  projects/demo/src/modules/components/avatar/examples/4/index.ts
  projects/demo/src/modules/components/avatar/examples/5/index.ts
  projects/demo/src/modules/components/avatar/examples/6/index.ts
  projects/demo/src/modules/components/avatar/examples/import/module.md
  projects/demo/src/modules/components/avatar/examples/import/template.md
  projects/demo/src/modules/components/avatar/index.html
  projects/demo/src/modules/components/avatar/index.ts
  projects/demo/src/utils/component.pipe.ts
  projects/demo/src/utils/example.pipe.ts
  projects/demo/src/utils/index.ts
  projects/demo/tsconfig.app.json
Labels: ready to merge

#7058 chore(demo): fix some warning logs during `nx serve-ssr`
  projects/demo/tsconfig.server.json
Labels: ready to merge

#7059 chore(experimental): fix invalid value of property `display`
  projects/experimental/components/navigation/main.style.less
Labels: ready to merge

#7053 chore(demo): update documentation
  projects/demo/src/modules/app/home/examples/angular-json-styles.md
  projects/demo/src/modules/app/home/examples/project-json-styles.md
Labels: ready to merge

#7046 chore(demo): fix notification example
  projects/demo/src/modules/components/notification/examples/3/index.html
Labels: ready to merge, v4

#7042 fix(core): set text-align on host notification
  projects/core/components/notification/notification.style.less
  projects/demo/src/modules/components/notification/examples/3/index.html
Labels: ready to merge, v3

#7041 fix(core): set text-align on host notification
  projects/core/components/notification/notification.style.less
Labels: ready to merge, v4

#7055 feat(kit): `Tabs` add size
  projects/demo/src/modules/components/tabs/examples/5/index.html
  projects/demo/src/modules/components/tabs/examples/6/index.html
  projects/demo/src/modules/components/tabs/examples/import/import.md
  projects/demo/src/modules/components/tabs/examples/import/template.md
  projects/demo/src/modules/components/tabs/tabs.component.ts
  projects/demo/src/modules/components/tabs/tabs.template.html
  projects/experimental/components/navigation/nav.component.ts
  projects/experimental/components/navigation/nav.style.less
  projects/kit/components/tabs/tab.directive.ts
  projects/kit/components/tabs/tabs-horizontal.directive.ts
  projects/kit/components/tabs/tabs-vertical.directive.ts
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/kit/components/tabs/tabs-with-more.style.less
  projects/kit/components/tabs/tabs-with-more.template.html
  projects/kit/components/tabs/tabs.directive.ts
  projects/kit/components/tabs/tabs.options.ts
  projects/kit/components/tabs/tabs.style.less
Labels: ready to merge

#7044 chore(cdk): fix 'no code comments'-problem in `TuiDestroyService => takeUntilDestroyed` migration
  projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
  projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/schematic-migrate-destroy-service.spec.ts
Labels: ready to merge

#7066 chore(demo): add link to browserslist
  projects/demo/src/modules/info/browsers/browsers.component.ts
  projects/demo/src/modules/info/browsers/browsers.template.html
Labels: ready to merge

#7068 feat(addon-commerce): add flag hide cvc code in InputCard, InputCardGrouped
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.options.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
  projects/addon-commerce/components/input-cvc/input-cvc.component.ts
  projects/addon-commerce/components/input-cvc/input-cvc.style.less
  projects/addon-commerce/components/input-cvc/input-cvc.template.html
Labels: ready to merge

#7077 feat(addon-charts): `RingChart` add xs size
  projects/addon-charts/components/pie-chart/pie-chart.style.less
  projects/addon-charts/components/ring-chart/ring-chart.component.ts
  projects/addon-charts/components/ring-chart/ring-chart.style.less
  projects/addon-charts/components/ring-chart/ring-chart.template.html
  projects/demo/src/modules/charts/ring-chart/ring-chart.component.ts
  projects/demo/src/modules/charts/ring-chart/ring-chart.template.html
  projects/experimental/components/checkbox/checkbox.component.ts
Labels: ready to merge, v3

#7082 feat(addon-charts): `RingChart` add xs size (#7077)
  projects/addon-charts/components/pie-chart/pie-chart.style.less
  projects/addon-charts/components/ring-chart/ring-chart.component.ts
  projects/addon-charts/components/ring-chart/ring-chart.style.less
  projects/addon-charts/components/ring-chart/ring-chart.template.html
  projects/demo/src/modules/charts/ring-chart/ring-chart.component.ts
  projects/demo/src/modules/charts/ring-chart/ring-chart.template.html
  projects/experimental/components/checkbox/checkbox.component.ts
Labels: ready to merge

#7086 chore(demo): documentation pages `ProgressBar` & `ProgressCircle` have infinite SSR
  projects/demo/src/modules/components/progress-bar/examples/1/index.ts
  projects/demo/src/modules/components/progress-bar/examples/2/index.ts
  projects/demo/src/modules/components/progress-bar/examples/4/index.ts
  projects/demo/src/modules/components/progress-circle/examples/1/index.ts
  projects/demo/src/modules/components/progress-circle/examples/3/index.ts
  projects/demo/src/modules/components/progress-circle/examples/5/index.ts
  projects/demo/src/modules/components/progress-circle/examples/6/index.ts
Labels: ready to merge

#7085 fix(kit): `File` throws SSR error `ReferenceError: File is not defined`
  projects/kit/components/files/file/file.component.ts
Labels: ready to merge

#7084 chore: fix proprietary build
  projects/kit/components/switch/switch.style.less
Labels: ready to merge

#7090 chore(demo): documentation page `Tooltip` has infinite SSR
  projects/demo/src/modules/components/tooltip/examples/1/index.html
  projects/demo/src/modules/components/tooltip/examples/1/index.ts
  projects/demo/src/modules/components/tooltip/tooltip.module.ts
Labels: ready to merge

#7089 chore(demo): documentation page `Dropdown` has infinite SSR
  projects/demo/src/modules/directives/dropdown/examples/3/index.html
  projects/demo/src/modules/directives/dropdown/examples/3/index.ts
Labels: ready to merge

#7097 fix(kit): `Tile` throws SSR error `TypeError: element.getBoundingClientRect is not a function`
  projects/kit/components/tiles/tile.service.ts
  projects/kit/components/tiles/tiles.style.less
Labels: ready to merge

#7100 chore(demo): experimental documentation page `Tooltip` has infinite SSR
  projects/demo/src/modules/experimental/tooltip/examples/1/index.html
  projects/demo/src/modules/experimental/tooltip/examples/1/index.ts
  projects/demo/src/modules/experimental/tooltip/tooltip.module.ts
Labels: ready to merge

#7104 fix(core): `Expand` do not react to transition on pseudo element
  projects/core/components/expand/expand.component.ts
Labels: ready to merge

#7095 chore: remove redundant imports
  projects/demo/src/modules/app/home/examples/main-standalone-optional.md
  projects/demo/src/modules/app/home/examples/main-standalone.md
Labels: ready to merge, v3

#7108 chore: remove checkbox-api e2e test
  projects/demo-playwright/tests/kit/checkbox/checkbox.spec.ts
Labels: ready to merge

#7109 fix(addon-table): added a check that `total` is zero
  projects/addon-table/components/table-pagination/table-pagination.template.html
Labels: community contribution, v4

#7102 fix(kit): remove pure getNativeElements
  projects/kit/components/stepper/stepper.component.ts
Labels: community contribution, v4

#7103 chore(demo): migrate documentation page `stepper` to standalone compo…
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/stepper/examples/1/index.less
  projects/demo/src/modules/components/stepper/examples/1/index.ts
  projects/demo/src/modules/components/stepper/examples/2/index.less
  projects/demo/src/modules/components/stepper/examples/2/index.ts
  projects/demo/src/modules/components/stepper/examples/3/index.ts
  projects/demo/src/modules/components/stepper/examples/import/import.md
  projects/demo/src/modules/components/stepper/examples/import/template.md
  projects/demo/src/modules/components/stepper/stepper.component.ts
  projects/demo/src/modules/components/stepper/stepper.module.ts
  projects/demo/src/modules/components/stepper/stepper.template.html
Labels: community contribution, v4

#7120 chore(demo): fix SSR error for `Edit on Stackblitz` button
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.less
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
Labels: ready to merge

#7115 fix(cdk): `Media` throws SSR error `TypeError: this.el.pause is not a function`
  projects/cdk/directives/media/media.directive.ts
Labels: ready to merge

#7121 chore(demo): documentation page `Carousel` has infinite SSR
  projects/demo/src/modules/components/carousel/examples/1/index.html
  projects/demo/src/modules/components/carousel/examples/1/index.ts
Labels: ready to merge

#7080 fix(kit): correct update model for `tui-input-date-multi`
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
Labels: ready to merge, v3

#7081 ci: any playwright test should fail on any uncaught SSR error
  .github/workflows/e2e-playwright.yml
  package.json
  projects/demo/server.ts
  projects/demo/src/main.server.ts
  projects/demo/src/modules/app/server-error-handler.ts
Labels: ready to merge

#7094 fix(core): `Textfield` fix next button on virtual keyboard
  projects/core/components/primitive-textfield/textfield/textfield.component.ts
Labels: ready to merge
