Repository taiga-family/taiga-ui, pull requests merged in 2024-02, with the labels that each got.

#6635 feat(layout): `BlockStatus` update mobile paddings
  projects/addon-mobile/styles/common/block-status.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
  projects/demo/src/modules/components/block-status/block-status.component.ts
  projects/demo/src/modules/components/block-status/block-status.module.ts
  projects/demo/src/modules/components/block-status/block-status.template.html
  projects/demo/src/modules/components/block-status/examples/5/index.html
  projects/demo/src/modules/components/block-status/examples/5/index.less
  projects/demo/src/modules/components/block-status/examples/5/index.ts
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge, v4

#6575 chore(demo): set screenshot-github-bot page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/testing/screenshot-github-bot/screenshot-github-bot.component.ts
  projects/demo/src/modules/info/testing/screenshot-github-bot/screenshot-github-bot.module.ts
Labels: ready to merge

#6638 chore: upgrade to latest Nx
  package-lock.json
  package.json
Labels: ready to merge

#6573 chore(demo): set disable-animation page as standalone
  projects/addon-doc/addon-doc.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.component.ts
  projects/demo/src/modules/info/testing/disable-animation/disable-animation.module.ts
Labels: ready to merge

#6660 feat(cdk)!: refactor the way new custom dialogs are created
  projects/addon-mobile/components/mobile-dialog/index.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog-options.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.options.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
  projects/addon-mobile/components/mobile-dialog/test/mobile-dialog.component.spec.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.directive.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.service.ts
  projects/addon-mobile/const/mobile-alert-options.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.service.ts
  projects/cdk/services/popover.service.ts
  projects/core/abstract/driver.ts
  projects/core/abstract/position-accessor.ts
  projects/core/abstract/rect-accessor.ts
  projects/core/abstract/vehicle.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.directive.ts
  projects/core/components/dialog/dialog.interfaces.ts
  projects/core/components/dialog/dialog.service.ts
  projects/core/components/dialog/dialog.tokens.ts
  projects/core/components/dialog/index.ts
  projects/core/components/dialog/test/dialog.component.spec.ts
  projects/core/interfaces/dialog-context.ts
  projects/core/interfaces/index.ts
  projects/core/types/dialog-size.ts
  projects/core/types/index.ts
  projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.service.ts
  projects/kit/components/pdf-viewer/pdf-viewer.directive.ts
  projects/kit/components/pdf-viewer/pdf-viewer.options.ts
  projects/kit/components/pdf-viewer/pdf-viewer.service.ts
  projects/kit/components/pdf-viewer/test/pdf-viewer.component.spec.ts
Labels: ready to merge

#6662 chore: add `lazy-loading.cy.ts`
  projects/demo-cypress/src/tests/lazy-loading.cy.ts
  projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
Labels: ready to merge

#6666 chore: add `elastic-sticky.cy.ts`
  projects/addon-mobile/directives/elastic-sticky/test/elastic-sticky.directive.spec.ts
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
Labels: ready to merge

#6663 chore(deps): update `Maskito` to `v2`
  jest.config.ts
  package-lock.json
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card/input-card.module.ts
  projects/addon-commerce/components/input-cvc/input-cvc.module.ts
  projects/addon-commerce/components/input-expire/input-expire.module.ts
  projects/addon-commerce/package.json
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/components/input-tag/input-tag.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/kit/components/input-date-multi/input-date-multi.module.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/input-date-range.module.ts
  projects/kit/components/input-date-time/input-date-time.component.ts
  projects/kit/components/input-date-time/input-date-time.module.ts
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.module.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
  projects/kit/components/input-phone/input-phone.module.ts
  projects/kit/components/input-range/input-range.template.html
  projects/kit/components/input-slider/input-slider.template.html
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
  projects/kit/components/input-time/input-time.module.ts
  projects/kit/components/input-year/input-year.module.ts
  projects/kit/package.json
Labels: ready to merge

#6577 feat(addon-doc): add standalone for `tui-language-switcher`
  projects/addon-doc/components/index.ts
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/addon-doc/components/language-switcher/language-switcher.module.ts
  projects/addon-doc/components/language-switcher/tests/language-switcher.component.spec.ts
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/customization/i18n/i18n.component.ts
  projects/demo/src/modules/customization/i18n/i18n.module.ts
Labels: ready to merge

#6571 chore(demo): set related page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/related/related.component.ts
  projects/demo/src/modules/info/related/related.module.ts
Labels: ready to merge

#6684 fix(experimental): `Surface` fix styles priority
  projects/experimental/directives/surface/surface.style.less
Labels: ready to merge, v4

#6668 feat!: delete all entities for legacy `text-mask` library
  projects/addon-commerce/constants/card-holder-mask.ts
  projects/addon-commerce/utils/create-auto-corrected-expire-pipe.ts
  projects/addon-commerce/utils/index.ts
  projects/core/components/primitive-textfield/textfield/textfield.component.ts
  projects/core/index.ts
  projects/core/mask/index.ts
  projects/core/mask/ng-package.json
  projects/core/mask/number-mask-options.ts
  projects/core/mask/text-mask-config.ts
  projects/core/mask/text-mask-correction-handler.ts
  projects/core/mask/text-mask-list-handler.ts
  projects/core/mask/text-mask-list.ts
  projects/core/mask/text-mask-options.ts
  projects/core/mask/text-mask-pipe-handler.ts
  projects/core/mask/text-mask-pipe-result.ts
  projects/core/tokens/index.ts
  projects/core/tokens/legacy-mask.ts
  projects/core/utils/index.ts
  projects/core/utils/mask/create-auto-corrected-money-pipe.ts
  projects/core/utils/mask/create-correction-mask.ts
  projects/core/utils/mask/create-number-mask.ts
  projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts
  projects/core/utils/mask/index.ts
  projects/core/utils/mask/masked-money-value-is-empty.ts
  projects/core/utils/mask/masked-number-string-to-number.ts
  projects/core/utils/mask/ng-package.json
  projects/core/utils/mask/test/create-correction-mask.spec.ts
  projects/core/utils/mask/test/masked-number-string-to-number.spec.ts
  projects/core/utils/mask/test/tui-create-auto-corrected-number-pipe.spec.ts
  projects/kit/constants/empty-mask.ts
  projects/kit/constants/index.ts
  projects/kit/constants/masks.ts
  projects/kit/directives/index.ts
  projects/kit/directives/mask/index.ts
  projects/kit/directives/mask/legacy-mask.ts
  projects/kit/directives/mask/ng-package.json
Labels: ready to merge

#6650 fix(experimental): fix problem with tuiCell
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.component.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.template.html
  projects/demo/src/modules/experimental/card-medium/examples/4/index.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/cell/examples/7/index.html
  projects/demo/src/modules/experimental/cell/examples/7/index.less
  projects/experimental/directives/card/card.styles.less
Labels: v3

#6644 feat(addon-mobile): `SwipeActions` add new component
  projects/addon-doc/components/internal/header/header.component.ts
  projects/addon-mobile/components/index.ts
  projects/addon-mobile/components/swipe-action/index.ts
  projects/addon-mobile/components/swipe-action/ng-package.json
  projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/addon-mobile/components/swipe-action/swipe-actions.component.ts
  projects/addon-mobile/components/swipe-action/swipe-actions.style.less
  projects/addon-mobile/components/swipe-action/swipe-actions.template.html
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/swipe-action/examples/1/index.html
  projects/demo/src/modules/components/swipe-action/examples/1/index.less
  projects/demo/src/modules/components/swipe-action/examples/1/index.ts
  projects/demo/src/modules/components/swipe-action/examples/2/index.html
  projects/demo/src/modules/components/swipe-action/examples/2/index.less
  projects/demo/src/modules/components/swipe-action/examples/2/index.ts
  projects/demo/src/modules/components/swipe-action/examples/3/index.html
  projects/demo/src/modules/components/swipe-action/examples/3/index.less
  projects/demo/src/modules/components/swipe-action/examples/3/index.ts
  projects/demo/src/modules/components/swipe-action/examples/4/index.html
  projects/demo/src/modules/components/swipe-action/examples/4/index.less
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
  projects/demo/src/modules/components/swipe-action/examples/5/index.html
  projects/demo/src/modules/components/swipe-action/examples/5/index.less
  projects/demo/src/modules/components/swipe-action/examples/5/index.ts
  projects/demo/src/modules/components/swipe-action/examples/import/import-module.md
  projects/demo/src/modules/components/swipe-action/examples/import/insert-template.md
  projects/demo/src/modules/components/swipe-action/swipe-actions.component.ts
  projects/demo/src/modules/components/swipe-action/swipe-actions.module.ts
  projects/demo/src/modules/components/swipe-action/swipe-actions.template.html
  projects/demo/used-icons.ts
  projects/experimental/directives/cell/cell.styles.less
  projects/kit/components/carousel/carousel.style.less
Labels: ready to merge, v4

#6688 chore(cdk): schematics for legacy mask utils
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-legacy-mask.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-legacy-mask.spec.ts
Labels: ready to merge

#6683 ci: add upgrade artifact actions
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#6685 chore: fix flaky
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
Labels: ready to merge

#6698 fix(core): `PrimitiveTextfield` fix memory leak (#6697)
  projects/core/styles/mixins/textfield.less
Labels: ready to merge, v4

#6693 refactor: prefer find method
  projects/cdk/schematics/utils/get-standalone-bootstrap-function.ts
Labels: ready to merge

#6707 fix(core): `Multiselect` fix dropdown shaking
  projects/core/directives/dropdown/dropdown-position.directive.ts
Labels: ready to merge, v3

#6708 fix(core): Multiselect fix dropdown shaking
  projects/core/directives/dropdown/dropdown-position.directive.ts
Labels: ready to merge, v4

#6696 chore: e2e can't find tui-doc-demo element
  projects/demo/src/modules/components/alert/alert.template.html
  projects/demo/src/modules/components/dialog/dialog.template.html
Labels: ready to merge

#6709 refactor: remove `tuiPreventDefault` directive
  projects/cdk/directives/index.ts
  projects/cdk/directives/prevent-default/index.ts
  projects/cdk/directives/prevent-default/ng-package.json
  projects/cdk/directives/prevent-default/prevent-default.directive.ts
  projects/cdk/directives/prevent-default/prevent-default.module.ts
  projects/demo/src/modules/components/dialog/dialog.module.ts
  projects/demo/src/modules/components/dialog/examples/4/index.html
  projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
  projects/kit/components/calendar-range/calendar-range.module.ts
  projects/kit/components/calendar-range/calendar-range.template.html
  projects/kit/components/files/file/file.template.html
  projects/kit/components/files/files.module.ts
  projects/kit/components/input-date-time/input-date-time.module.ts
  projects/kit/components/input-date-time/input-date-time.template.html
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/input-month-range/input-month-range.module.ts
  projects/kit/components/input-month-range/input-month-range.template.html
  projects/kit/components/input-month/input-month.module.ts
  projects/kit/components/input-month/input-month.template.html
  projects/kit/components/multi-select/multi-select.module.ts
  projects/kit/components/multi-select/multi-select.template.html
Labels: ready to merge

#6694 refactor: no inferable type for clean code
  projects/addon-charts/utils/control-point.ts
  projects/addon-commerce/pipes/format-card/format-card.pipe.ts
  projects/addon-doc/components/demo/demo.component.ts
  projects/addon-doc/components/documentation/pipes/inspect.pipe.ts
  projects/addon-doc/utils/inspect.ts
  projects/addon-doc/utils/parse-code-block.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts
  projects/cdk/date-time/day-range.ts
  projects/cdk/date-time/day.ts
  projects/cdk/date-time/time.ts
  projects/cdk/decorators/pure.ts
  projects/cdk/observables/is-alive.ts
  projects/cdk/schematics/ng-update/steps/rename-types.ts
  projects/cdk/utils/dom/get-scroll-parent.ts
  projects/cdk/utils/dom/point-to-client-rect.ts
  projects/cdk/utils/focus/set-native-mouse-focused.ts
  projects/cdk/utils/math/round.ts
  projects/cdk/utils/svg/svg-linear-gradient-processor.ts
  projects/core/components/button/button.options.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/observables/smart-search.ts
  projects/core/pipes/calendar-sheet/calendar-sheet.pipe.ts
  projects/core/pipes/format-phone/format-phone.pipe.ts
  projects/core/utils/miscellaneous/get-border.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/components/combo-box/examples/2/user.ts
  projects/demo/src/modules/components/input-phone/examples/3/index.ts
  projects/demo/src/modules/components/input/examples/4/index.ts
  projects/demo/src/modules/components/input/examples/8/index.ts
  projects/kit/components/combo-box/combo-box.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input/input.component.ts
  projects/kit/components/progress/progress-segmented/progress-segmented.component.ts
  projects/kit/components/select/select.component.ts
  projects/kit/utils/miscellaneous/create-time-periods.ts
  projects/testing/utils/keyboard-event.ts
  scripts/shared/is-tui-package-name.ts
Labels: ready to merge

#6661 refactor: svgNodeFilter
  projects/cdk/constants/svg-node-filter.ts
  projects/cdk/constants/test/svg-node-filter.spec.ts
Labels: ready to merge

#6689 chore: cleanup
  CHANGELOG.md
Labels: ready to merge, v3

#6704 fix(kit): add `line-height` for `[tuiTab]`
  projects/kit/components/tabs/tab/tab.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
Labels: v3

#6695 refactor: no redundant template wrap
  projects/cdk/date-time/time.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/app/utils/file-type-guards.utils.ts
  scripts/shared/sync-versions.ts
Labels: ready to merge

#6651 ci: add `experimentalSingleTabRunMode`
  projects/demo-cypress/cypress.config.ts
Labels: ready to merge

#6640 chore: add `swipe.cy.ts`
  projects/cdk/directives/swipe/test/swipe.directive.spec.ts
  projects/demo-cypress/src/tests/swipe.cy.ts
Labels: ready to merge

#6648 chore: add `request.cy.ts`
  projects/cdk/services/test/static-request.service.spec.ts
  projects/demo-cypress/src/tests/static-request.cy.ts
Labels: ready to merge

#6642 chore: add `zoom.cy.ts`
  projects/cdk/directives/zoom/test/zoom.directive.spec.ts
  projects/demo-cypress/src/tests/zoom.cy.ts
Labels: ready to merge

#6715 fix(kit): add `line-height` for `[tuiTab]`
  projects/kit/components/tabs/tab/tab.style.less
  projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
Labels: ready to merge, v4

#6717 refactor: drop language from addon-doc
  projects/addon-doc/index.ts
  projects/addon-doc/languages/index.ts
  projects/addon-doc/languages/ng-package.json
  projects/addon-doc/languages/russian.ts
Labels: ready to merge

#6729 refactor(core)!: `Group` remove `adaptive`
  projects/addon-doc/components/demo/demo.module.ts
  projects/addon-doc/components/documentation/documentation.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/group/group.component.ts
  projects/core/components/group/group.directive.ts
  projects/core/components/group/group.module.ts
  projects/core/components/group/group.options.ts
  projects/core/components/group/group.style.less
  projects/core/components/group/index.ts
  projects/demo/src/modules/components/checkbox-block/checkbox-block.module.ts
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/group/examples/2/index.html
  projects/demo/src/modules/components/group/examples/import/import-module.md
  projects/demo/src/modules/components/group/group.component.ts
  projects/demo/src/modules/components/group/group.module.ts
  projects/demo/src/modules/components/group/group.template.html
  projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
  projects/demo/src/modules/components/input-card/input-card.module.ts
  projects/demo/src/modules/components/input-tag/input-tag.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/demo/src/modules/components/items-with-more/items-with-more.module.ts
  projects/demo/src/modules/components/radio-block/radio-block.module.ts
  projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.module.ts
  projects/demo/src/modules/directives/dropdown-open/dropdown-open.module.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/markup/form/example/index.html
  projects/demo/src/modules/markup/form/form.module.ts
  projects/kit/components/accordion/accordion.module.ts
  projects/kit/components/files/files.module.ts
  projects/kit/components/input-files/input-files.module.ts
  projects/kit/components/input-phone-international/input-phone-international.module.ts
Labels: ready to merge

#6714 chore: `tuiPreventDefault` add migration
  .cspell.json
  projects/cdk/schematics/ng-update/steps/index.ts
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-prevent-default.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-prevent-default.spec.ts
Labels: ready to merge

#6718 test: add `clipboard.cy.ts`
  projects/demo-cypress/src/tests/clipboard.cy.ts
Labels: ready to merge

#6750 fix(experimental): `SwipeActions` fix scrolling without actions
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.ts
  projects/experimental/components/swipe-action/swipe-actions.style.less
Labels: ready to merge, v3

#6747 fix(core): cancel macrotask in `tui-expand` when component destroyed
  projects/core/components/expand/expand.component.ts
Labels: ready to merge, v3

#6746 fix(core): cancel macrotask in `tui-expand` when component destroyed
  projects/core/components/expand/expand.component.ts
Labels: ready to merge, v4

#6686 feat(experimental): add `tuiButtonGroup`
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/button-group/button-group.component.ts
  projects/demo/src/modules/experimental/button-group/button-group.module.ts
  projects/demo/src/modules/experimental/button-group/button-group.template.html
  projects/demo/src/modules/experimental/button-group/examples/1/index.html
  projects/demo/src/modules/experimental/button-group/examples/1/index.less
  projects/demo/src/modules/experimental/button-group/examples/1/index.ts
  projects/demo/src/modules/experimental/button-group/examples/2/index.html
  projects/demo/src/modules/experimental/button-group/examples/2/index.less
  projects/demo/src/modules/experimental/button-group/examples/2/index.ts
  projects/demo/src/modules/experimental/button-group/examples/3/index.html
  projects/demo/src/modules/experimental/button-group/examples/3/index.less
  projects/demo/src/modules/experimental/button-group/examples/3/index.ts
  projects/demo/src/modules/experimental/button-group/examples/import/import-module.md
  projects/demo/src/modules/experimental/button-group/examples/import/insert-template.md
  projects/demo/used-icons.ts
  projects/experimental/directives/button-group/button-group.component.ts
  projects/experimental/directives/button-group/button-group.directive.ts
  projects/experimental/directives/button-group/button-group.module.ts
  projects/experimental/directives/button-group/button-group.style.less
  projects/experimental/directives/button-group/index.ts
  projects/experimental/directives/button-group/ng-package.json
  projects/experimental/directives/index.ts
Labels: ready to merge, v3

#6721 feat(core): add iOS support to TuiDropdownContextDirective
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge

#6753 fix(core): fix `:active` state of interactive elements in Safari
  projects/core/components/root/root.component.ts
Labels: ready to merge

#6754 feat(kit)!: remove `text-mask-core` from `dependencies` of `@taiga-ui/kit`
  package-lock.json
  projects/demo/project.json
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
  projects/kit/package.json
Labels: ready to merge

#6735 chore: remove `wait` because flaky
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
Labels: ready to merge

#6757 chore: revert
  .npmrc
  package-lock.json
Labels: ready to merge

#6764 chore: flaky again
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
Labels: ready to merge

#6776 chore(deps): bump `jest-preset-angular` to `v13`
  jest.config.ts
  package-lock.json
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/testing/package.json
  tsconfig.spec.json
Labels: ready to merge

#6761 fix(addon-mobile): `SwipeActions` fix scrolling without actions
  projects/addon-mobile/components/swipe-action/swipe-actions.style.less
  projects/demo/src/modules/components/swipe-action/examples/4/index.html
  projects/demo/src/modules/components/swipe-action/examples/4/index.less
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
Labels: ready to merge, v4

#6762 fix(core): `Dropdown` fix max height
  projects/core/directives/dropdown/dropdown.component.ts
Labels: ready to merge, v4

#6775 fix(kit): cancel macrotask in `tui-input-date-time` when component destroyed
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: ready to merge

#6772 fix(kit): cancel macrotask in `tui-input-time` when component destroyed
  projects/kit/components/input-time/input-time.component.ts
Labels: ready to merge

#6770 fix(addon-charts): cancel macrotask in `[tuiSheetStop]` when element destroyed
  projects/addon-mobile/components/sheet/directives/sheet-stop/sheet-stop.directive.ts
Labels: ready to merge

#6758 fix(core): fix `:active` state of interactive elements in Safari
  projects/core/components/root/root.component.ts
Labels: ready to merge, v4

#6783 chore: small flaky in dropdown context test
  projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
Labels: ready to merge

#6760 feat(core): add interactive mode for notification
  projects/core/components/notification/notification.component.ts
  projects/core/components/notification/notification.style.less
  projects/core/components/notification/notification.template.html
  projects/demo/src/modules/components/notification/examples/1/index.html
  projects/demo/src/modules/components/notification/examples/1/index.less
  projects/demo/src/modules/components/notification/examples/1/index.ts
  projects/demo/src/modules/components/notification/notification.module.ts
Labels: ready to merge, v4

#6751 feat(kit): swap icons for show and hide text in input-password component
  projects/demo/src/modules/components/input-password/examples/2/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/input-password/input-password.component.ts
Labels: ready to merge

#6759 feat(experimental): add `tuiButtonGroup`
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/button-group/button-group.component.ts
  projects/demo/src/modules/experimental/button-group/button-group.module.ts
  projects/demo/src/modules/experimental/button-group/button-group.template.html
  projects/demo/src/modules/experimental/button-group/examples/1/index.html
  projects/demo/src/modules/experimental/button-group/examples/1/index.less
  projects/demo/src/modules/experimental/button-group/examples/1/index.ts
  projects/demo/src/modules/experimental/button-group/examples/2/index.html
  projects/demo/src/modules/experimental/button-group/examples/2/index.less
  projects/demo/src/modules/experimental/button-group/examples/2/index.ts
  projects/demo/src/modules/experimental/button-group/examples/3/index.html
  projects/demo/src/modules/experimental/button-group/examples/3/index.less
  projects/demo/src/modules/experimental/button-group/examples/3/index.ts
  projects/demo/src/modules/experimental/button-group/examples/import/import-module.md
  projects/demo/src/modules/experimental/button-group/examples/import/insert-template.md
  projects/demo/used-icons.ts
  projects/experimental/directives/button-group/button-group.component.ts
  projects/experimental/directives/button-group/button-group.directive.ts
  projects/experimental/directives/button-group/button-group.module.ts
  projects/experimental/directives/button-group/button-group.style.less
  projects/experimental/directives/button-group/index.ts
  projects/experimental/directives/button-group/ng-package.json
  projects/experimental/directives/index.ts
Labels: ready to merge, v4

#6771 fix(addon-mobile): cancel macrotask in `tui-sheet` when component destroyed
  projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
  projects/addon-mobile/components/sheet/ios.hacks.ts
Labels: ready to merge

#6773 fix(kit): cancel macrotask in `tui-input-tag` when component destroyed
  projects/kit/components/input-tag/input-tag.component.ts
Labels: ready to merge

#6724 refactor: change enum to const for `TuiMonthNumber`
  projects/cdk/enums/month-number.ts
Labels: ready to merge

#6769 fix(addon-charts): cancel macrotask in `tui-arc-chart` when component destroyed
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
Labels: ready to merge

#6768 fix(addon-core): cancel macrotask in `tui-mobile-calendar` when component destroyed
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: ready to merge

#6601 refactor(cdk)!: drop `CHROMIUM_EDGE_START_VERSION`
  projects/cdk/constants/browser.ts
  projects/cdk/constants/index.ts
  projects/cdk/utils/browser/index.ts
  projects/cdk/utils/browser/is-edge-older-than.ts
  projects/cdk/utils/browser/test/browsers.spec.ts
  projects/demo/src/modules/utils/browser/examples/1/index.ts
  projects/kit/components/progress/progress-bar/progress-color-segments.directive.ts
  projects/kit/components/progress/progress-circle/progress-circle.component.ts
  projects/kit/components/progress/progress-circle/progress-circle.template.html
  projects/kit/components/slider/slider.component.ts
  projects/kit/components/slider/slider.style.less
Labels: ready to merge

#6649 fix(core): do not hide nested scrollbars
  projects/core/components/root/root.style.less
Labels: v4

#6797 feat(experimental): `Avatar` shift sizes to match buttons and controls
  projects/demo/src/modules/experimental/avatar/avatar.component.ts
  projects/demo/src/modules/experimental/avatar/examples/3/index.html
  projects/demo/src/modules/experimental/avatar/examples/4/index.ts
  projects/demo/src/modules/experimental/button-vertical/examples/1/index.html
  projects/demo/src/modules/experimental/button/examples/3/index.html
  projects/experimental/components/avatar/avatar.component.ts
  projects/experimental/components/avatar/avatar.options.ts
  projects/experimental/components/avatar/avatar.style.less
  projects/experimental/components/chip/chip.directive.ts
Labels: ready to merge

#6789 chore: fix e2e
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
Labels: ready to merge

#6800 chore: small changes
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/components/scrollbar/scrollbar.template.html
  projects/experimental/components/badge-notification/badge-notification.style.less
  projects/i18n/languages/english/kit.ts
Labels: ready to merge

#6808 chore: small changes (#6800)
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/components/scrollbar/scrollbar.template.html
  projects/experimental/components/badge-notification/badge-notification.style.less
  projects/i18n/languages/english/kit.ts
Labels: ready to merge

#6801 feat(experimental): add autoClose when another element is focused, hide actions on non-touch devices
  projects/demo/src/modules/experimental/swipe-action/examples/5/index.less
  projects/experimental/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/experimental/components/swipe-action/swipe-actions.style.less
Labels: ready to merge

#6777 fix(cdk): cancel macrotask in `[tuiNativeValidator]` when element destroyed
  projects/cdk/directives/native-validator/native-validator.directive.ts
Labels: ready to merge

#6809 feat(experimental): add autoClose when another element is focused
  projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/addon-mobile/components/swipe-action/swipe-actions.style.less
  projects/demo/src/modules/components/swipe-action/examples/5/index.less
  projects/experimental/components/swipe-action/swipe-actions-auto-close.directive.ts
Labels: ready to merge

#6774 feat!: move some deps from direct `dependencies` to `peerDependencies` + drop `legacy-peer-deps=true`
  .github/renovate.json
  .npmrc
  package-lock.json
  package.json
  projects/addon-doc/package.json
  projects/cdk/package.json
  projects/demo-cypress/package.json
  projects/demo-playwright/package.json
  projects/demo/package.json
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
  projects/kit/package.json
  projects/testing/package.json
Labels: ready to merge

#6818 feat!: new browser support
  projects/demo/src/modules/info/browsers/browsers.component.ts
  projects/demo/src/modules/info/browsers/browsers.style.less
  projects/demo/src/modules/info/browsers/browsers.template.html
Labels: ready to merge

#6816 chore: fix failed test
  projects/demo-cypress/cypress/tests/kit/input-files/input-files.cy.ts
Labels: ready to merge

#6828 refactor: use `String.replaceAll`
  package-lock.json
  package.json
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/pipes/markdown/markdown.pipe.ts
  projects/addon-doc/utils/type-reference-parser.ts
  projects/cdk/date-time/date-separator.ts
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/cdk/schematics/ng-update/steps/rename-types.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
  projects/cdk/schematics/utils/templates/get-component-templates.ts
  projects/cdk/utils/color/rgba-to-hex.ts
  projects/cdk/utils/svg/svg-linear-gradient-processor.ts
  projects/core/utils/format/capitalize.ts
  projects/core/utils/format/format-phone.ts
  projects/demo-playwright/tests/demo/demo.spec.ts
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/app/classes/ts-file-component.parser.ts
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/app/utils/example-content-processor/typescript-processor.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/components/input/examples/3/index.ts
  projects/demo/src/modules/directives/copy-processor/examples/1/index.ts
  projects/demo/src/modules/markup/breakpoints/breakpoints.component.ts
  projects/icons/scripts/prepare-feather-icons.ts
  projects/kit/components/input-phone/input-phone.component.ts
  projects/kit/components/input-phone/utils/complete-phone-insertion-preprocessor.ts
  projects/kit/components/input-phone/utils/create-phone-mask-expression.ts
  projects/kit/utils/phone/get-max-allowed-phone-length.ts
Labels: ready to merge

#6793 chore: remove hard code
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#6796 chore: `Resize` add migration
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#6832 chore: `Money` add migration
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
  projects/cdk/schematics/utils/templates/inputs.ts
Labels: ready to merge

#6788 fix(kit): scroll over carousel items
  projects/kit/components/carousel/carousel.component.ts
Labels: v3

#6790 fix(core): take into account scrollbar in active zone
  projects/cdk/components/scroll-controls/scrollbar.directive.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
Labels: ready to merge, v3

#6845 fix(experimental): `Avatar` fix error when using `SafeResourceUrl`
  projects/experimental/components/avatar/avatar.component.ts
Labels: ready to merge, v4

#6842 fix(experimental): `Avatar` fix error when using `SafeResourceUrl`
  projects/experimental/components/avatar/avatar.component.ts
Labels: ready to merge, v3

#6843 chore: cypress component testing problem
  .github/workflows/auto-approve.yml
  .github/workflows/e2e-cypress.yml
  package-lock.json
  projects/demo-cypress/package.json
Labels: ready to merge

#6849 chore: npe
  projects/experimental/components/avatar/avatar.component.ts
Labels: ready to merge, v4

#6846 chore: improve demo
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/navigation.style.less
Labels: ready to merge

#6835 refactor(core,kit): remove deprecated `filler`, `postfix`, `prefix` inputs
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
  projects/core/components/primitive-textfield/primitive-textfield.component.ts
  projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts
  projects/demo-playwright/tests/kit/input-number/input-number.spec.ts
  projects/demo-playwright/tests/kit/input-slider/input-slider.spec.ts
  projects/demo/src/modules/components/input-number/input-number.template.html
  projects/demo/src/modules/components/input-slider/input-slider.template.html
  projects/demo/src/modules/components/input-time/examples/4/index.html
  projects/demo/src/modules/components/input-time/examples/4/index.ts
  projects/demo/src/modules/components/primitive-textfield/primitive-textfield.template.html
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-slider/input-slider.component.ts
  projects/kit/components/input-slider/test/input-slider.component.spec.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.options.ts
  projects/kit/components/input-time/input-time.template.html
Labels: ready to merge, v4

#6847 feat(experimental): `Navigation` add new module
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/experimental/navigation/examples/2/index.html
  projects/demo/src/modules/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/experimental/navigation/examples/3/index.html
  projects/demo/src/modules/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/experimental/navigation/examples/import/import-module.md
  projects/demo/src/modules/experimental/navigation/examples/import/insert-template.md
  projects/demo/src/modules/experimental/navigation/navigation.component.ts
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/demo/src/modules/experimental/navigation/navigation.style.less
  projects/demo/src/modules/experimental/navigation/navigation.template.html
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/experimental/components/navigation/aside.component.ts
  projects/experimental/components/navigation/aside.style.less
  projects/experimental/components/navigation/head.component.ts
  projects/experimental/components/navigation/head.style.less
  projects/experimental/components/navigation/index.ts
  projects/experimental/components/navigation/logo.component.ts
  projects/experimental/components/navigation/main.component.ts
  projects/experimental/components/navigation/main.style.less
  projects/experimental/components/navigation/nav.component.ts
  projects/experimental/components/navigation/nav.style.less
  projects/experimental/components/navigation/navigation.module.ts
  projects/experimental/components/navigation/ng-package.json
  projects/experimental/directives/fade/fade.style.less
  projects/experimental/directives/header/header.styles.less
  projects/kit/components/push/push-alert.template.html
  projects/kit/components/tabs/tab/tab.style.less
Labels: ready to merge

#6855 feat(experimental): `Fade` enable scrolling
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/examples/2/index.html
  projects/experimental/components/navigation/aside.style.less
  projects/experimental/components/navigation/header.component.ts
  projects/experimental/components/navigation/header.style.less
  projects/experimental/components/navigation/index.ts
  projects/experimental/components/navigation/logo.component.ts
  projects/experimental/components/navigation/logo.style.less
  projects/experimental/components/navigation/main.style.less
  projects/experimental/components/navigation/nav.style.less
  projects/experimental/components/navigation/navigation.module.ts
  projects/experimental/directives/fade/fade.directive.ts
  projects/experimental/directives/fade/fade.style.less
  projects/experimental/directives/header/header.component.ts
  projects/experimental/directives/header/header.directive.ts
  projects/experimental/directives/header/header.module.ts
Labels: ready to merge

#6853 refactor: use `INJECTOR`
  projects/addon-mobile/directives/sidebar/sidebar.directive.ts
  projects/demo/src/modules/components/alert/alert.component.ts
  projects/demo/src/modules/components/alert/examples/import/lazy-module.md
  projects/demo/src/modules/components/dialog/examples/2/index.ts
  projects/demo/src/modules/components/dialog/examples/7/index.ts
  projects/demo/src/modules/components/dialog/examples/import/lazy-module.md
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts
  projects/demo/src/modules/services/table-bar/examples/import/lazy-module.md
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/routable-dialog/routable-dialog.component.ts
  projects/kit/components/slider/slider.component.ts
  projects/kit/directives/unfinished-validator/unfinished-validator.directive.ts
  projects/kit/pipes/field-error/field-error-content-pipe.ts
Labels: ready to merge

#6859 chore: `Present` refactor
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/directives/present/examples/import/import-module.md
  projects/demo/src/modules/directives/present/present.module.ts
  projects/demo/src/modules/directives/present/present.template.html
  projects/kit/directives/present/index.ts
  projects/kit/directives/present/present.directive.ts
  projects/kit/directives/present/present.module.ts
Labels: ready to merge

#6858 chore: remove unnecessary service
  projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts
  projects/core/services/index.ts
  projects/core/services/router-link-active.service.ts
  projects/kit/components/stepper/step/step.component.ts
  projects/kit/components/tabs/tab/tab.component.ts
  projects/kit/components/tabs/tab/tab.providers.ts
Labels: ready to merge

#6864 fix(core): fix nested sided dropdown height
  projects/core/directives/dropdown/dropdown.component.ts
Labels: ready to merge, v4

#6863 fix(core): fix nested sided dropdown height
  projects/core/directives/dropdown/dropdown.component.ts
Labels: ready to merge, v3

#6634 chore(demo): small changes
  projects/demo/src/modules/app/home/examples/main-standalone-optional.md
  projects/demo/src/modules/app/home/examples/main-standalone.md
Labels: ready to merge

#6874 feat(addon-doc): support target property for links
  projects/addon-doc/components/navigation/navigation.template.html
  projects/addon-doc/interfaces/page.ts
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge, v4

#6786 fix(core): take into account scrollbar in active zone
  .github/workflows/e2e-playwright.yml
  projects/core/components/scroll-controls/scrollbar.service.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
Labels: ready to merge, v4

#6817 refactor: incorrect inferable type
  projects/core/components/dialog/dialogs.component.ts
Labels: ready to merge, v4

#6765 refactor: switch to factory
  projects/cdk/directives/platform/platform.directive.ts
  projects/cdk/tokens/platform.ts
Labels: ready to merge

#6876 feat(addon-doc): support target property for links
  projects/addon-doc/components/navigation/navigation.template.html
  projects/addon-doc/interfaces/page.ts
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge, v3

#6850 chore: npe
  projects/experimental/components/avatar/avatar.component.ts
Labels: ready to merge, v3

#6861 chore(demo): add `Example` pipe
  projects/demo/src/modules/components/badge/badge.component.ts
  projects/demo/src/modules/components/badge/badge.module.ts
  projects/demo/src/modules/components/badge/badge.template.html
  projects/demo/src/modules/experimental/card-large/card-large.component.ts
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-large/card-large.template.html
  projects/demo/src/utils/example.pipe.ts
  projects/demo/src/utils/index.ts
Labels: ready to merge

#6879 fix(experimental): `Fade` fix artifacts in Chrome
  projects/experimental/components/button/button.style.less
  projects/experimental/directives/fade/fade.style.less
Labels: ready to merge, v3

#6880 fix(styles): `List` fix line height
  projects/styles/markup/tui-list.less
Labels: ready to merge, v3

#6882 chore: fix comments
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/experimental/components/navigation/aside.style.less
  projects/experimental/components/navigation/header.style.less
  projects/experimental/components/navigation/logo.style.less
  projects/experimental/components/navigation/nav.style.less
Labels: ready to merge

#6897 fix(kit): `InputDateTime` does not change filler on dynamic change of `[timeMode]` prop
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: ready to merge, v3

#6890 chore(schematics): add migrations for renamed editor's entities
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#6844 chore(demo): fix example
  projects/experimental/directives/surface/surface.style.less
Labels: ready to merge, v4

#6908 refactor: fix typecheck in cypress files
  .github/workflows/e2e-cypress.yml
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
  projects/demo-cypress/src/tests/pan.cy.ts
  projects/demo-cypress/src/tests/range.cy.ts
  projects/demo-cypress/src/tests/swipe.cy.ts
  projects/demo-cypress/src/tests/tabs.cy.ts
  projects/demo-cypress/src/tests/zoom.cy.ts
Labels: ready to merge

#6909 refactor: fix typecheck in playwright files
  .github/workflows/e2e-playwright.yml
  projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts
  projects/demo-playwright/utils/page-objects/calendar.po.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
  projects/demo-playwright/utils/page-objects/documentation-page.po.ts
  projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
  projects/demo-playwright/utils/page-objects/input-card.po.ts
  projects/demo-playwright/utils/page-objects/input-date-range.po.ts
  projects/demo-playwright/utils/page-objects/input-date-time.po.ts
  projects/demo-playwright/utils/page-objects/input-month-range.po.ts
  projects/demo-playwright/utils/page-objects/input-month.po.ts
  projects/demo-playwright/utils/page-objects/input-phone.po.ts
  projects/demo-playwright/utils/page-objects/input-range.po.ts
  projects/demo-playwright/utils/page-objects/input-slider.po.ts
  projects/demo-playwright/utils/page-objects/input-tag.po.ts
  projects/demo-playwright/utils/page-objects/multi-select.po.ts
  projects/demo-playwright/utils/page-objects/range.po.ts
  projects/demo-playwright/utils/page-objects/slider.po.ts
  projects/demo-playwright/utils/page-objects/table-pagination-page.po.ts
  projects/demo-playwright/utils/page-objects/textfield-with-data-list.po.ts
  tsconfig.playwright.json
Labels: ready to merge

#6869 refactor: add some utils for stabilize flaky
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
  projects/demo-playwright/tests/deep/deep-select.spec.ts
  projects/demo-playwright/tests/demo/landing.spec.ts
  projects/demo-playwright/utils/goto.ts
  projects/demo-playwright/utils/hide-element.ts
  projects/demo-playwright/utils/index.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
  projects/demo-playwright/utils/wait-stable-state.ts
Labels: ready to merge

#6912 fix(styles): `List` fix line height (#6880)
  projects/styles/markup/tui-list.less
Labels: ready to merge, v4

#6857 chore: `Scrollbar` refactor
  projects/addon-doc/components/navigation/navigation.module.ts
  projects/addon-mobile/components/sheet/sheet.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/calendar/calendar.module.ts
  projects/core/components/scrollbar/index.ts
  projects/core/components/scrollbar/scrollable.directive.ts
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.module.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/components/scrollbar/scrollbar.template.html
  projects/core/directives/dropdown/dropdown.component.ts
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
  projects/demo/src/modules/components/combo-box/combo-box.module.ts
  projects/demo/src/modules/components/multi-select/multi-select.module.ts
  projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.module.ts
  projects/demo/src/modules/components/scrollbar/examples/import/import-module.md
  projects/demo/src/modules/components/scrollbar/scrollbar.module.ts
  projects/demo/src/modules/components/scrollbar/scrollbar.template.html
  projects/demo/src/modules/components/select/select.module.ts
  projects/demo/src/modules/components/tabs/tabs.module.ts
  projects/demo/src/modules/directives/elastic-sticky/elastic-sticky.module.ts
  projects/demo/src/modules/directives/elastic-sticky/elastic-sticky.template.html
  projects/demo/src/modules/directives/elastic-sticky/examples/import/import-module.md
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/demo/src/modules/experimental/fade/fade.module.ts
  projects/demo/src/modules/experimental/surface/surface.module.ts
  projects/demo/src/modules/services/scroll/scroll.module.ts
  projects/demo/src/modules/tables/table/table.module.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/kit/components/calendar-month/calendar-month.module.ts
  projects/kit/components/input-tag/input-tag.module.ts
  projects/kit/components/input-year/input-year.module.ts
  projects/kit/components/textarea/textarea.module.ts
  projects/kit/internal/primitive-calendar-range/primitive-calendar-range.module.ts
Labels: ready to merge

#6916 chore: cherry picks
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/examples/2/index.html
  projects/experimental/components/button/button.style.less
  projects/experimental/components/navigation/aside.style.less
  projects/experimental/components/navigation/header.component.ts
  projects/experimental/components/navigation/header.style.less
  projects/experimental/components/navigation/index.ts
  projects/experimental/components/navigation/logo.component.ts
  projects/experimental/components/navigation/logo.style.less
  projects/experimental/components/navigation/main.style.less
  projects/experimental/components/navigation/nav.style.less
  projects/experimental/components/navigation/navigation.module.ts
  projects/experimental/directives/cell/cell.styles.less
  projects/experimental/directives/fade/fade.directive.ts
  projects/experimental/directives/fade/fade.style.less
  projects/experimental/directives/header/header.component.ts
  projects/experimental/directives/header/header.directive.ts
Labels: ready to merge

#6856 feat(kit): allow dynamic changes to TUI_NUMBER_FORMAT
  projects/addon-commerce/pipes/amount/amount.pipe.ts
  projects/core/constants/default-number-format.ts
  projects/core/directives/number-format/number-format.directive.ts
  projects/core/interfaces/number-format-settings.ts
  projects/core/pipes/format-number/format-number.pipe.ts
  projects/core/tokens/index.ts
  projects/core/tokens/number-format-observable.ts
  projects/core/tokens/number-format.ts
  projects/core/utils/format/format-number.ts
  projects/demo/src/modules/charts/bar-set/examples/5/index.html
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
  projects/demo/src/modules/components/input-number/examples/7/index.html
  projects/demo/src/modules/components/input-number/examples/7/index.ts
  projects/demo/src/modules/components/input-number/input-number.component.ts
  projects/demo/src/modules/components/input-number/input-number.module.ts
  projects/demo/src/modules/components/input-number/input-number.template.html
  projects/demo/src/modules/directives/copy-processor/examples/1/index.html
  projects/demo/src/modules/directives/copy-processor/examples/1/index.ts
  projects/demo/src/modules/pipes/format-number/examples/1/index.html
  projects/demo/src/modules/pipes/format-number/examples/import/insert-template.md
  projects/demo/src/modules/tables/table-filters/examples/1/index.html
  projects/demo/src/modules/tables/table/examples/1/index.html
  projects/demo/src/modules/tables/table/examples/3/index.html
  projects/demo/src/modules/utils/tokens/examples/8/index.html
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/test/input-number.component.spec.ts
  projects/kit/components/input-range/test/input-range.component.spec.ts
Labels: ready to merge

#6906 chore: fix radius for `tuiCardMedium`, `tuiCardLarge`
  projects/demo-playwright/tests/deep/deep-select.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.spec.ts
  projects/demo-playwright/tests/demo/demo.spec.ts
  projects/experimental/directives/surface/surface.style.less
Labels: ready to merge
