Repository taiga-family/taiga-ui, pull requests merged in 2024-07, with the labels that each got.

#7984 feat(experimental): `ActionBar` add new component
  .cspell.json
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/action-bar/action-bar.component.ts
  projects/demo/src/modules/experimental/action-bar/action-bar.module.ts
  projects/demo/src/modules/experimental/action-bar/action-bar.template.html
  projects/demo/src/modules/experimental/action-bar/examples/1/index.html
  projects/demo/src/modules/experimental/action-bar/examples/1/index.less
  projects/demo/src/modules/experimental/action-bar/examples/1/index.ts
  projects/demo/src/modules/experimental/action-bar/examples/2/index.html
  projects/demo/src/modules/experimental/action-bar/examples/2/index.less
  projects/demo/src/modules/experimental/action-bar/examples/2/index.ts
  projects/demo/src/modules/experimental/action-bar/examples/import/import-module.md
  projects/demo/src/modules/experimental/action-bar/examples/import/insert-template.md
  projects/demo/used-icons.ts
  projects/experimental/components/action-bar/action-bar.component.ts
  projects/experimental/components/action-bar/action-bar.directive.ts
  projects/experimental/components/action-bar/action-bar.module.ts
  projects/experimental/components/action-bar/action-bar.style.less
  projects/experimental/components/action-bar/action-bar.template.html
  projects/experimental/components/action-bar/index.ts
  projects/experimental/components/action-bar/ng-package.json
  projects/experimental/components/index.ts
Labels: ready to merge, v3

#7989 refactor: add colors switch
  projects/demo/src/modules/markup/colors/index.html
  projects/demo/src/modules/markup/colors/index.ts
  projects/demo/src/styles/styles.less
  projects/demo/used-icons.ts
  projects/kit/components/block/block.directive.ts
Labels: ready to merge

#7967 chore: add schematic for tui editor
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
Labels: ready to merge

#7976 feat(addon-mobile): update `TabBar` styles
  projects/addon-mobile/components/tab-bar/tab-bar.style.less
Labels: ready to merge

#7988 chore(demo): fix security vulnerability
  projects/demo/src/index.html
  projects/demo/src/polyfills.ts
Labels: ready to merge, v3

#7990 refactor: rename input-card-group
  projects/addon-commerce/components/index.ts
  projects/addon-commerce/components/input-card-group/index.ts
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
  projects/addon-commerce/components/input-card-group/input-card-group.options.ts
  projects/addon-commerce/components/input-card-group/input-card-group.providers.ts
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/addon-commerce/components/input-card-group/input-card-group.template.html
  projects/addon-commerce/components/input-card-group/ng-package.json
  projects/addon-commerce/components/input-card-group/test/input-card-group.component.spec.ts
  projects/addon-commerce/components/input-card-grouped/index.ts
  projects/demo-playwright/tests/addon-commerce/input-card-group.spec.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-card-group.po.ts
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.less
  projects/demo/src/modules/components/input-card-group/examples/1/index.html
  projects/demo/src/modules/components/input-card-group/examples/1/index.ts
  projects/demo/src/modules/components/input-card-group/examples/2/index.html
  projects/demo/src/modules/components/input-card-group/examples/2/index.less
  projects/demo/src/modules/components/input-card-group/examples/2/index.ts
  projects/demo/src/modules/components/input-card-group/examples/3/index.html
  projects/demo/src/modules/components/input-card-group/examples/3/index.ts
  projects/demo/src/modules/components/input-card-group/examples/4/index.html
  projects/demo/src/modules/components/input-card-group/examples/4/index.ts
  projects/demo/src/modules/components/input-card-group/examples/5/index.html
  projects/demo/src/modules/components/input-card-group/examples/5/index.ts
  projects/demo/src/modules/components/input-card-group/examples/import/import.md
  projects/demo/src/modules/components/input-card-group/examples/import/template.md
  projects/demo/src/modules/components/input-card-group/index.html
  projects/demo/src/modules/components/input-card-group/index.less
  projects/demo/src/modules/components/input-card-group/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/4/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/5/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/import/template.md
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
Labels: ready to merge

#7977 feat(addon-mobile): update `TabBar` styles
  projects/addon-mobile/components/tab-bar/tab-bar.style.less
Labels: ready to merge

#8001 fix(addon-mobile): prevent touchstart after close sheet
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
Labels: v3

#7998 feat(addon-commerce): add `cvcHidden` input property
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
Labels: ready to merge, v3

#7979 feat(addon-docs): support custom tags
  projects/addon-doc/components/page/page.component.ts
  projects/addon-doc/components/page/page.template.html
  projects/demo/src/modules/experimental/appearance/appearance.template.html
Labels: ready to merge, v3

#7997 refactor: add some host directives
  projects/core/components/button/button.directive.ts
  projects/core/components/data-list/option.component.ts
  projects/core/components/link/link.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/directives/appearance/index.ts
  projects/core/directives/appearance/with-appearance.ts
  projects/core/directives/icons/index.ts
  projects/core/directives/icons/with-icons.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/pipes/flag/test/flag.pipe.spec.ts
  projects/core/tokens/assets-path.ts
  projects/core/tokens/icon-resolver.ts
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/badge/badge.directive.ts
  projects/kit/components/block/block.directive.ts
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/chip/chip.directive.ts
  projects/kit/components/files/input-files/input-files.directive.ts
  projects/kit/components/radio/radio.component.ts
  projects/kit/components/switch/switch.component.ts
  projects/kit/components/tabs/tab.directive.ts
  projects/kit/directives/tooltip/tooltip.directive.ts
Labels: ready to merge

#7993 chore: migrate card-grouped tag, some enums
  projects/cdk/schematics/ng-update/v4/steps/constants/enums.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
Labels: ready to merge

#8014 chore: fix icons for proprietary
  projects/addon-doc/components/code/index.html
  projects/addon-doc/components/code/index.ts
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.options.ts
  projects/addon-doc/components/example/example.template.html
  projects/addon-doc/tokens/doc-icons.ts
  projects/addon-mobile/styles/android/checkbox.less
  projects/addon-mobile/styles/android/switch.less
  projects/addon-mobile/styles/ios/checkbox.less
  projects/addon-table/components/reorder/reorder.options.ts
  projects/addon-table/components/reorder/reorder.style.less
  projects/addon-table/components/reorder/reorder.template.html
  projects/cdk/constants/used-icons.ts
  projects/core/tokens/common-icons.ts
  projects/core/tokens/index.ts
  projects/demo/src/modules/app/app.style.less
  projects/kit/components/accordion/accordion-item.style.less
  projects/kit/components/switch/switch.style.less
  projects/kit/directives/chevron/chevron.directive.ts
  projects/kit/directives/chevron/chevron.service.ts
  projects/kit/directives/chevron/index.ts
  projects/legacy/components/arrow/arrow.style.less
Labels: ready to merge

#7961 chore(demo): add missing @taiga-ui/ packages to stackblitz
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Labels: ready to merge

#8019 chore: drop sanitizer
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
  projects/legacy/components/multi-select/test/multi-select.component.spec.ts
  projects/testing/mocks/index.ts
  projects/testing/mocks/sanitizer.ts
Labels: ready to merge

#7980 feat(addon-doc): support custom tags
  projects/addon-doc/components/page/page.component.ts
  projects/addon-doc/components/page/page.template.html
  projects/demo/src/modules/components/experimental/navigation/index.html
Labels: ready to merge, v4

#8017 ci: publish latest version as well
  scripts/publish-canary.ts
  scripts/publish.ts
  scripts/shared/bump-version.ts
  scripts/shared/get-all-tags.ts
  scripts/shared/get-last-major-version.ts
  scripts/shared/parse-version.ts
Labels: ready to merge, v3

#8026 ci: add prepublish target
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-table/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo-cypress/project.json
  projects/demo-playwright/project.json
  projects/demo/project.json
  projects/experimental/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
  scripts/publish-canary.ts
Labels: ready to merge, v3

#8027 ci: publish with bail
  .github/workflows/test.yml
  package.json
  scripts/publish-canary.ts
Labels: ready to merge, v4

#8028 ci: publish latest version as well
  scripts/publish-canary.ts
  scripts/publish.ts
  scripts/shared/bump-version.ts
  scripts/shared/get-all-tags.ts
  scripts/shared/parse-version.ts
Labels: ready to merge, v4

#8029 chore: forgot changes
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
Labels: ready to merge, v3

#8020 fix(kit): `Badge` fix img width in Safari
  projects/kit/components/badge/badge.style.less
Labels: ready to merge, v4

#8021 fix(experimental) `Badge` fix img width in Safari
  projects/experimental/components/badge/badge.style.less
Labels: ready to merge, v3

#8033 chore: fix hostDirectives in `Select` and ng 17+
  projects/core/components/textfield/index.ts
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.directive.ts
Labels: ready to merge

#8030 chore: fix css chart migration
  projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts
  projects/cdk/schematics/ng-update/v4/migrate-css-vars/rename-css-vars.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts
Labels: ready to merge

#8011 chore: update proprietry-icons migration
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
Labels: ready to merge

#7965 chore: fix money migration, add avatar size migration
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-action.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
Labels: ready to merge

#8036 chore: fix
  projects/legacy/components/color-selector/color-selector.template.html
Labels: ready to merge

#8005 fix(addon-mobile): prevent touchstart after close sheet
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
Labels: ready to merge, v4

#8047 chore: fix action-bar night colors
  projects/demo/src/modules/experimental/action-bar/action-bar.component.ts
  projects/demo/src/modules/experimental/action-bar/examples/1/index.less
  projects/demo/src/modules/experimental/action-bar/examples/1/index.ts
  projects/experimental/components/action-bar/action-bar.style.less
Labels: v3

#8037 fix(addon-mobile): dropdown mobile arrow doesn't rotate when click on overlay
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
Labels: v4

#8063 feat(addon-table): fix for `Cell` and `Title`
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/directives/table.style.less
  projects/addon-table/components/table/td/td.component.ts
  projects/addon-table/components/table/td/td.style.less
  projects/addon-table/components/table/th/th.style.less
  projects/demo/src/modules/components/table/examples/2/index.html
  projects/demo/src/modules/components/table/examples/2/index.less
  projects/demo/src/modules/components/table/examples/2/index.ts
Labels: ready to merge

#8065 feat(kit): `Progress` add options with DI
  projects/experimental/directives/cell/cell.styles.less
  projects/kit/components/progress/index.ts
  projects/kit/components/progress/progress-bar/progress-bar.component.less
  projects/kit/components/progress/progress-bar/progress-bar.component.ts
  projects/kit/components/progress/progress-circle/progress-circle.component.ts
  projects/kit/components/progress/progress.options.ts
Labels: ready to merge

#8073 chore: fix colors
  .cspell.json
  projects/core/components/data-list/data-list.style.less
  projects/core/styles/theme/palette.less
  projects/demo/src/modules/components/data-list/examples/2/index.html
  projects/demo/src/modules/components/data-list/examples/2/index.ts
  projects/demo/used-icons.ts
Labels: ready to merge

#8090 fix(addon-mobile): display mobile calendar range
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: v4

#8101 fix(addon-mobile): `DropdownMobile` fix open status report
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/core/components/hosted-dropdown/dropdown-open-monitor.directive.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.template.html
  projects/core/components/root/root.style.less
  projects/demo/src/modules/directives/dropdown/examples/5/index.html
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
Labels: ready to merge, v3

#8092 fix(addon-mobile): display mobile calendar range
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: v3

#8103 ci: rc tag
  .github/workflows/create-release.yml
Labels: ready to merge

#8093 feat: add Maskito binding helper
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/addon-commerce/components/input-cvc/input-cvc.directive.ts
  projects/addon-commerce/components/input-expire/input-expire.directive.ts
  projects/kit/utils/index.ts
  projects/kit/utils/maskito.binding.ts
Labels: ready to merge

#8109 chore: some migration fixes
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
  projects/cdk/schematics/utils/get-named-import-references.ts
Labels: ready to merge

#8107 chore: move controller to legacy
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/providers/table.provider.ts
  projects/cdk/classes/index.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.options.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/directives/hint/hint-options.directive.ts
  projects/kit/components/items-with-more/items-with-more.directive.ts
  projects/legacy/classes/controller.ts
  projects/legacy/classes/index.ts
  projects/legacy/directives/textfield-controller/textfield-appearance.directive.ts
  projects/legacy/directives/textfield-controller/textfield-cleaner.directive.ts
  projects/legacy/directives/textfield-controller/textfield-custom-content.directive.ts
  projects/legacy/directives/textfield-controller/textfield-filler.directive.ts
  projects/legacy/directives/textfield-controller/textfield-icon-left.directive.ts
  projects/legacy/directives/textfield-controller/textfield-icon.directive.ts
  projects/legacy/directives/textfield-controller/textfield-label-outside.directive.ts
  projects/legacy/directives/textfield-controller/textfield-postfix.directive.ts
  projects/legacy/directives/textfield-controller/textfield-prefix.directive.ts
  projects/legacy/directives/textfield-controller/textfield-size.directive.ts
Labels: ready to merge

#8114 chore(schematics): save intermediate state before template migrations
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
Labels: ready to merge

#8116 chore: fix flaky e2e
  projects/demo-playwright/tests/deep/deep-select.spec.ts
  projects/demo-playwright/tests/kit/input-year/input-year.spec.ts
Labels: ready to merge

#7814 feat(core): `DropdownContext` implement for iOS
  projects/cdk/tokens/environment.ts
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge

#8111 feat(core): `HintOverflow` add new directive
  projects/core/directives/hint/hint-overflow.directive.ts
  projects/core/directives/hint/hint.ts
  projects/core/directives/hint/index.ts
  projects/core/directives/hint/test/hint.directive.spec.ts
  projects/demo-playwright/tests/core/hint/hint.spec.ts
  projects/demo/src/modules/directives/hint/examples/3/index.less
  projects/demo/src/modules/directives/hint/examples/4/index.html
  projects/demo/src/modules/directives/hint/examples/4/index.less
  projects/demo/src/modules/directives/hint/examples/4/index.ts
  projects/demo/src/modules/directives/hint/index.html
  projects/demo/src/modules/directives/hint/index.ts
Labels: ready to merge

#8121 chore(legacy): replace import of legacy `MaskitoModule` by `MaskitoDirective`
  projects/legacy/components/color-selector/color-edit/color-edit.module.ts
  projects/legacy/components/input-color/input-color.module.ts
Labels: ready to merge

#8106 chore(schematics): migrate `@tinkoff/{ng-polymorpheus|ng-event-plugins}` even if they are not installed directly
  projects/cdk/schematics/ng-update/steps/replace-package-name.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-styles.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
Labels: ready to merge

#8094 fix(addon-mobile): `DropdownMobile` fix some issues
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/core/components/root/root.style.less
  projects/core/directives/dropdown/dropdown-open-legacy.directive.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/dropdown/dropdown.ts
  projects/core/directives/dropdown/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.html
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/select/select.component.ts
  projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
Labels: ready to merge

#8113 refactor: optimize style calculation
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/test/hint.directive.spec.ts
  projects/core/services/position.service.ts
Labels: ready to merge

#8120 refactor: `Block` update to new specs
  projects/core/components/data-list/option.component.ts
  projects/core/styles/theme/variables.less
  projects/demo-playwright/tests/kit/action-bar/action-bar.mobile.spec.ts
  projects/demo-playwright/tests/kit/action-bar/action-bar.spec.ts
  projects/demo/src/modules/components/block/examples/1/index.html
  projects/demo/src/modules/components/block/examples/1/index.less
  projects/demo/src/modules/components/block/examples/1/index.ts
  projects/demo/src/modules/components/block/examples/3/index.html
  projects/demo/src/modules/components/block/examples/3/index.less
  projects/demo/src/modules/components/filter/examples/4/index.html
  projects/demo/src/modules/components/filter/examples/4/index.less
  projects/demo/src/modules/components/filter/examples/4/index.ts
  projects/demo/src/modules/components/filter/index.ts
  projects/kit/components/block/block.directive.ts
  projects/kit/components/block/block.options.ts
  projects/kit/components/block/block.style.less
  projects/kit/components/filter/filter.component.ts
  projects/kit/components/filter/filter.style.less
  projects/kit/components/filter/filter.template.html
  projects/kit/components/switch/switch.style.less
Labels: ready to merge

#8108 chore(addon-doc): add `./styles/*` to `exports` config of `package.json`
  projects/addon-doc/package.json
  projects/demo/src/modules/info/changelog/index.less
Labels: ready to merge

#8119 chore(legacy): `Input` has broken keyboard navigation
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/demo-playwright/tests/kit/input/input.spec.ts
Labels: ready to merge

#8129 refactor: move `Navigation` to layout
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/data-list/data-list.style.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/demo/src/modules/components/navigation/examples/2/index.html
  projects/demo/src/modules/components/navigation/examples/2/index.ts
  projects/demo/src/modules/components/navigation/examples/3/index.html
  projects/demo/src/modules/components/navigation/examples/3/index.ts
  projects/demo/src/modules/components/navigation/examples/import/import.md
  projects/demo/src/modules/components/navigation/examples/import/template.md
  projects/demo/src/modules/components/navigation/index.html
  projects/demo/src/modules/components/navigation/index.less
  projects/demo/src/modules/components/navigation/index.ts
  projects/demo/src/modules/components/segmented/examples/1/index.ts
  projects/demo/src/modules/components/segmented/examples/2/index.ts
  projects/demo/src/modules/components/segmented/examples/3/index.ts
  projects/demo/src/modules/components/segmented/examples/4/index.ts
  projects/demo/src/modules/components/segmented/examples/import/import.md
  projects/demo/src/modules/components/swipe-action/examples/import/import.md
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/experimental/components/navigation/ng-package.json
  projects/experimental/index.ts
  projects/kit/components/segmented/segmented.component.ts
  projects/kit/components/segmented/segmented.directive.ts
  projects/layout/components/index.ts
  projects/layout/components/navigation/aside.component.ts
  projects/layout/components/navigation/aside.style.less
  projects/layout/components/navigation/header.component.ts
  projects/layout/components/navigation/header.style.less
  projects/layout/components/navigation/hint-aside.directive.ts
  projects/layout/components/navigation/index.ts
  projects/layout/components/navigation/logo.component.ts
  projects/layout/components/navigation/logo.style.less
  projects/layout/components/navigation/main.component.ts
  projects/layout/components/navigation/main.style.less
  projects/layout/components/navigation/nav.component.ts
  projects/layout/components/navigation/nav.style.less
  projects/layout/components/navigation/navigation.ts
  projects/layout/components/navigation/ng-package.json
Labels: ready to merge

#8138 chore(core): remove quotes inside function in `taiga-ui-fonts.less`
  projects/core/styles/taiga-ui-fonts.less
Labels: ready to merge

#8142 chore: `migrations` spread component arrays inside modules
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
Labels: ready to merge

#8102 fix(legacy): `NativeSelect` add placeholder
  projects/demo/src/modules/components/select/examples/11/index.html
  projects/legacy/classes/abstract-native-select.ts
  projects/legacy/components/select/native-select/native-select-group.component.ts
  projects/legacy/components/select/native-select/native-select-group.template.html
  projects/legacy/components/select/native-select/native-select.component.ts
  projects/legacy/components/select/native-select/native-select.template.html
Labels: ready to merge, v4

#8152 chore(kit): change access modifier for property
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Labels: ready to merge

#8136 refactor(demo): use standalone approach for stackblitz
  projects/demo/src/modules/app/classes/index.ts
  projects/demo/src/modules/app/classes/ts-file-component.parser.ts
  projects/demo/src/modules/app/classes/ts-file-module.parser.ts
  projects/demo/src/modules/app/classes/ts-file.parser.ts
  projects/demo/src/modules/app/stackblitz/project-files/configs.md
  projects/demo/src/modules/app/stackblitz/project-files/src/app/@stackblitz/README.md
  projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
  projects/demo/src/modules/app/stackblitz/project-files/src/global_styles.less.md
  projects/demo/src/modules/app/stackblitz/project-files/src/index.html.md
  projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
  projects/demo/src/modules/app/stackblitz/project-files/src/polyfills.ts.md
  projects/demo/src/modules/app/stackblitz/project-files/src/styles.less.md
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
  projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
  projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
  projects/demo/src/modules/app/stackblitz/starter/files/app.component.html.md
  projects/demo/src/modules/app/stackblitz/starter/files/app.component.ts.md
  projects/demo/src/modules/app/stackblitz/starter/files/app.template.html.md
  projects/demo/src/modules/app/stackblitz/starter/files/index.html.md
  projects/demo/src/modules/app/stackblitz/starter/index.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/components/data-list/index.ts
Labels: ready to merge

#8141 feat(layout): `Navigation` simplify 2nd level aside
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.template.html
  projects/core/components/data-list/data-list.tokens.ts
  projects/core/components/data-list/option.component.ts
  projects/core/directives/dropdown/dropdown-manual.directive.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/dropdown/dropdown-position.directive.ts
  projects/core/directives/dropdown/dropdown-selection.directive.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/demo/src/modules/components/data-list/examples/2/index.html
  projects/demo/src/modules/components/data-list/examples/5/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/kit/directives/chevron/chevron.directive.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
  projects/layout/components/navigation/aside-group.component.ts
  projects/layout/components/navigation/aside-group.template.html
  projects/layout/components/navigation/aside-item.directive.ts
  projects/layout/components/navigation/aside.component.ts
  projects/layout/components/navigation/aside.style.less
  projects/layout/components/navigation/hint-aside.directive.ts
  projects/layout/components/navigation/index.ts
  projects/layout/components/navigation/navigation.ts
Labels: ready to merge

#8153 feat(core): externalize some components styles
  projects/core/components/button/button.directive.ts
  projects/core/components/icon/icon.component.ts
  projects/core/components/icon/icon.style.less
  projects/core/components/label/label.directive.ts
  projects/core/components/link/link.directive.ts
  projects/core/directives/appearance/appearance.directive.ts
  projects/core/directives/icons/icons.directive.ts
  projects/core/directives/icons/icons.styles.less
  projects/core/directives/title/title.directive.ts
  projects/core/ng-package.json
  projects/core/styles/components/appearance.less
  projects/core/styles/components/button.less
  projects/core/styles/components/icon.less
  projects/core/styles/components/icons.less
  projects/core/styles/components/label.less
  projects/core/styles/components/link.less
  projects/core/styles/components/title.less
  projects/core/styles/theme/appearance.less
  projects/core/styles/theme/appearance/accent.less
  projects/core/styles/theme/appearance/base.less
  projects/core/styles/theme/appearance/floating.less
  projects/core/styles/theme/appearance/glass.less
  projects/core/styles/theme/appearance/icon.less
  projects/core/styles/theme/appearance/opposite.less
  projects/core/styles/theme/appearance/outline.less
  projects/core/styles/theme/appearance/primary.less
  projects/core/styles/theme/appearance/secondary.less
  projects/core/styles/theme/appearance/status.less
  projects/core/styles/theme/appearance/textfield.less
  projects/core/styles/theme/wrapper.less
  projects/demo/project.json
  projects/demo/src/modules/components/icon/examples/3/index.html
  projects/demo/used-icons.ts
Labels: ready to merge

#8139 fix(addon-charts): handle divide by zero in pie-chart
  projects/addon-charts/components/pie-chart/pie-chart.component.ts
Labels: ready to merge

#8156 chore(demo): fix icons in StackBlitz
  projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
Labels: ready to merge

#8157 feat(addon-commerce): `ThumbnailCard` add DI options
  projects/addon-commerce/components/thumbnail-card/index.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.options.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
  projects/demo/src/modules/components/thumbnail-card/index.html
  projects/demo/src/modules/components/thumbnail-card/index.ts
Labels: ready to merge

#8167 chore(demo): drop outdated hack for `@ng-web-apis/resize-observer`
  projects/demo/src/main.server.ts
Labels: ready to merge

#8164 chore: import `TuiTextfieldControllerModule` from `@taiga-ui/legacy`
  projects/demo/src/modules/directives/textfield-controller/examples/import/import.md
Labels: ready to merge

#8161 fix(cdk): provided double value is non-finite
  projects/cdk/utils/focus/set-native-mouse-focused.ts
  projects/cdk/utils/focus/tests/set-native-mouse-focused.spec.ts
Labels: v3

#8100 chore(cdk): migrate button appearance
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-button-appearance.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button-appearance.spec.ts
Labels: ready to merge

#8173 chore(schematics): migration for `a[tuiIconButton]` & `button[tuiIconButton]`
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
Labels: ready to merge

#8172 chore(schematics): migration for `tuiButtonOptionsProvider` from `@taiga-ui/experimental`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
Labels: ready to merge

#8171 chore(demo): remove some outdated ignorings of SSR errors
  projects/demo/src/modules/app/server-error-handler.ts
Labels: ready to merge

#8180 chore(demo): enable `NG_EVENT_PLUGINS` in StackBlitz starter
  projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
Labels: ready to merge

#8174 chore(schematics): migrations for `TuiButtonGroupModule` & `TuiButtonVerticalModule` & `TuiIconsModule`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
Labels: ready to merge

#8155 feat(experimental): `ThumbnailCard` add DI options
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.template.html
  projects/experimental/components/thumbnail-card/index.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.component.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.options.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.template.html
Labels: ready to merge, v3

#8187 chore: migrate `capitalizeFirstLetter`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/legacy/utils/capitalize-first-letter.ts
  projects/legacy/utils/index.ts
Labels: ready to merge, v4

#8178 refactor: drop ClientRect
  projects/core/directives/hint/hint-host.directive.ts
  projects/core/directives/hint/hint-pointer.directive.ts
Labels: ready to merge, v4

#8177 refactor: drop InjectFlags
  projects/cdk/tokens/removed-element.ts
Labels: ready to merge, v4

#8179 refactor: dedupe npm deps
  package-lock.json
  package.json
  projects/addon-doc/package.json
  projects/core/package.json
  projects/layout/package.json
  projects/legacy/package.json
  projects/styles/package.json
Labels: ready to merge, v4

#8185 chore(demo): new example (`MultiSelect` with nested `DataList`)
  projects/demo/src/modules/components/multi-select/examples/12/index.html
  projects/demo/src/modules/components/multi-select/examples/12/index.ts
  projects/demo/src/modules/components/multi-select/index.html
Labels: ready to merge

#8201 refactor: use `pressSequentially`
  projects/demo-playwright/tests/kit/input-year/input-year.spec.ts
Labels: v4

#8197 chore(schematics): migration for `PrimitiveCheckbox`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-checkbox.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-checkbox.spec.ts
Labels: ready to merge

#8193 chore: migrate proprietary styles
  projects/cdk/schematics/ng-update/v4/steps/migrate-styles.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge, v4

#8205 fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>`
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
Labels: ready to merge, v4

#8206 fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>`
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
Labels: v3

#8208 chore: add progress log for identifiers migration
  projects/cdk/schematics/ng-update/steps/replace-identifier.ts
Labels: ready to merge

#8209 chore(schematics): fix migration for one line usage of `<tui-checkbox-labeled />` / `<tui-radio-labeled />`
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: ready to merge

#8212 chore(schematics): migrations `<tui-checkbox-block />` & `<tui-radio-block />`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Labels: ready to merge

#8213 chore: fix icons migration
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
Labels: ready to merge

#8207 fix(core): skip hydration for eager content
  projects/core/components/expand/expand.component.ts
Labels: ready to merge, v4

#8225 chore(addon-doc): add `marked-gfm-heading-id` extension to `tuiDocMarkdown` pipe
  package-lock.json
  projects/addon-doc/package.json
  projects/addon-doc/pipes/markdown/markdown.pipe.ts
Labels: ready to merge

#8223 fix(core): fix dropdown-context directive on touchscreen laptops
  projects/cdk/tokens/index.ts
  projects/cdk/tokens/is-touch.ts
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge, v3

#8232 chore(schematics): migrations for proprietary `TuiOperationIcon` & `TuiIllustrationName` types
  projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge

#8229 chore(schematics): add migrations for legacy types `TuiDialog` & `TuiBaseDialogContext`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8227 chore(schematics): fix progress indicator for `replacing identifiers` step
  projects/cdk/schematics/ng-update/steps/replace-identifier.ts
Labels: ready to merge

#8228 chore(schematics): add `spreadInModule: true` for `TuiProprietaryNavigation` migration
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8248 chore: fix border color
  projects/addon-doc/components/code/index.less
  projects/core/styles/theme/palette.less
  projects/demo/src/modules/app/home/home.style.less
Labels: ready to merge

#8251 chore: simplify icons
  projects/addon-doc/components/code/tests/code.component.spec.ts
  projects/addon-mobile/styles/ios/checkbox.less
  projects/core/components/icon/icon.component.ts
  projects/core/components/textfield/textfield.style.less
  projects/core/directives/icons/icons.directive.ts
  projects/core/styles/components/button.less
  projects/core/styles/components/icon.less
  projects/core/styles/components/icons.less
  projects/core/styles/components/link.less
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/kit/components/badge/badge.style.less
  projects/kit/components/switch/switch.component.ts
  projects/kit/components/switch/switch.style.less
  projects/kit/components/tabs/tabs.style.less
  projects/layout/components/navigation/nav.style.less
Labels: ready to merge

#8269 chore(schematics): migrations for style mixins `tui-space(direction, size)`
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-space-mixins.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge

#8263 chore: migrate input-number precision and decimal, fix files module migration, add todo
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
Labels: ready to merge

#8267 chore(schematics): migrations for `TuiAlertService` options (`autoClose: boolean` + `status`)
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
Labels: ready to merge

#8235 chore: add layout package if needed
  projects/cdk/package.json
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge

#8254 chore(legacy): `Date` should support native date picker even without providing of `TUI_MOBILE_CALENDAR`
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/input-date.template.html
Labels: v4

#8252 fix(kit): `Date` should support native date picker even without importing of `TuiMobileCalendarDialogModule`
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.template.html
Labels: ready to merge, v3

#8243 chore: flaky
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.html
Labels: v3

#8275 refactor: use tuple names
  projects/i18n/types/language.ts
Labels: ready to merge, v4

#8264 feat(addon-mobile): possibility drop mobile calendar header
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.html
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.less
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.module.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html
Labels: ready to merge, v3

#8236 refactor(schematics): use `findAttr` & `hasElementAttribute` everywhere
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-focusable.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-overscroll.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-thumbnail-card.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-checkbox.ts
  projects/cdk/schematics/utils/templates/elements.ts
  projects/cdk/schematics/utils/templates/inputs.ts
Labels: ready to merge

#8271 chore(schematics): migrations for `TuiAlertService` options (`hasIcon`, `hasCloseButton`, `defaultAutoCloseTime`)
  projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
Labels: ready to merge

#8276 chore(schematics): add migration comment for deleted `TuiIllustrationsModule`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge
