Repository taiga-family/taiga-ui, pull requests merged in 2024-09, with the labels that each got.

#8781 feat(core): `Textfield` add `ViewContainerRef`
  projects/core/components/textfield/index.ts
  projects/core/components/textfield/textfield-content.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/directives/appearance/appearance.bindings.ts
  projects/core/directives/appearance/appearance.directive.ts
  projects/core/directives/dropdown/dropdown.bindings.ts
  projects/core/pipes/order-week-days/order-week-days.pipe.ts
  projects/core/styles/components/icon.less
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/textfield.less
  projects/i18n/types/language.ts
  projects/kit/components/files/file/file.component.ts
  projects/kit/components/files/file/file.options.ts
  projects/kit/components/files/files.utils.ts
  projects/legacy/directives/textfield-controller/textfield-appearance.directive.ts
  projects/legacy/directives/textfield-controller/textfield-cleaner.directive.ts
  projects/legacy/directives/textfield-controller/textfield-controller.module.ts
  projects/legacy/directives/textfield-controller/textfield-controller.provider.ts
  projects/legacy/directives/textfield-controller/textfield-custom-content.directive.ts
  projects/legacy/directives/textfield-controller/textfield-filler.directive.ts
  projects/legacy/directives/textfield-controller/textfield-icon-left.directive.ts
  projects/legacy/directives/textfield-controller/textfield-icon.directive.ts
  projects/legacy/directives/textfield-controller/textfield-label-outside.directive.ts
  projects/legacy/directives/textfield-controller/textfield-postfix.directive.ts
  projects/legacy/directives/textfield-controller/textfield-prefix.directive.ts
  projects/legacy/directives/textfield-controller/textfield-size.directive.ts
  projects/legacy/directives/textfield-controller/textfield.options.ts
  projects/legacy/directives/unfinished-validator/unfinished-validator.directive.ts
  projects/legacy/directives/unfinished-validator/unfinished.validator.ts
  projects/legacy/directives/value-accessor/value-accessor.directive.ts
  projects/legacy/directives/value-accessor/value-accessor.module.ts
  projects/legacy/directives/value-accessor/value-accessor.provider.ts
Labels: ready to merge, v4

#8774 fix(kit): `CalendarRange` shows end of range
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/kit/components/calendar-range/calendar-range.component.ts
Labels: ready to merge, v4

#8779 fix(legacy): trigger transform placeholder when using autofill
  projects/legacy/components/primitive-textfield/primitive-textfield.component.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.style.less
Labels: ready to merge, v4

#8757 feat(layout): `Navigation` add `Drawer`
  projects/cdk/constants/used-icons.ts
  projects/core/components/icon/icon.component.ts
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/demo/src/modules/components/navigation/index.less
  projects/layout/components/navigation/aside-item.directive.ts
  projects/layout/components/navigation/drawer.component.ts
  projects/layout/components/navigation/drawer.style.less
  projects/layout/components/navigation/hint-aside.directive.ts
  projects/layout/components/navigation/index.ts
  projects/layout/components/navigation/navigation.ts
  projects/layout/tokens/common-icons.ts
Labels: ready to merge, v4

#8777 chore: fix lint later
  package-lock.json
  package.json
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/components/carousel/examples/5/index.ts
  projects/demo/src/modules/components/combo-box/examples/5/index.ts
  projects/demo/src/modules/components/input-slider/examples/5/index.ts
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/components/multi-select/examples/7/index.ts
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
Labels: ready to merge, v4

#8790 fix(layout): `Navigation` fix style specificity for `AsideItem`
  projects/layout/components/navigation/aside.style.less
Labels: ready to merge, v4

#8789 feat(addon-commerce): `ThumbnailCard` add `<img>` support
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
  projects/demo/src/modules/components/thumbnail-card/examples/4/index.html
  projects/demo/src/modules/components/thumbnail-card/examples/4/index.less
  projects/demo/src/modules/components/thumbnail-card/examples/4/index.ts
  projects/demo/src/modules/components/thumbnail-card/index.ts
Labels: ready to merge, v4

#8755 chore(schematics): improve editor migration
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-editor.ts
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-addon-editor.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-tinkoff-editor.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-resolve-package-type.spec.ts
Labels: ready to merge, v4

#8788 chore(demo): small refactor for original resolver
  projects/demo/src/modules/components/icon/examples/5/index.ts
Labels: ready to merge, v4

#8742 refactor(core): add `tuiZonefreeScheduler` for `TuiScrollControls`
  projects/core/components/scrollbar/scroll-controls.component.ts
  projects/core/components/scrollbar/scrollbar.directive.ts
Labels: ready to merge, v4

#8787 chore(demo): drop tinkoff word
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts
  projects/demo/src/modules/components/input-card-group/examples/2/index.ts
  projects/demo/src/modules/info/related/index.html
Labels: ready to merge, v4

#8744 refactor(cdk): add `tuiZonefreeScheduler` for `TuiObscuredService`
  projects/cdk/directives/obscured/obscured.service.ts
Labels: ready to merge, v4

#8800 chore: fix tests
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-addon-editor.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-tinkoff-editor.spec.ts
Labels: ready to merge, v4

#8765 chore(demo): use `canary` tag of Taiga UI deps for Stackblitz from `https://taiga-ui.dev/next`
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Labels: ready to merge, v4

#8804 chore: `ng-add` remove global styles
  projects/cdk/schematics/constants/taiga-styles.ts
  projects/cdk/schematics/ng-add/index.ts
  projects/cdk/schematics/ng-add/schema.json
  projects/cdk/schematics/ng-add/schema.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
Labels: ready to merge, v4

#8803 chore: `ng-add` add NG_EVENT_PLUGINS to main module providers, add plugins package
  projects/cdk/schematics/ng-add/index.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
Labels: ready to merge, v4

#8808 chore: typecheck scripts directory
  scripts/package.json
  scripts/publish.ts
  scripts/shared/argv.utils.ts
  scripts/shared/bump-tui-deps.ts
  tsconfig.spec.json
Labels: ready to merge, v4

#8811 chore: revert error parsing
  scripts/shared/argv.utils.ts
Labels: v4

#8809 fix(core): `Textfield` fix expression change error
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.directive.ts
Labels: ready to merge, v4

#8805 chore: fix some styles
  projects/core/components/alert/alert.style.less
  projects/core/directives/group/group.directive.ts
  projects/core/styles/components/group.less
Labels: ready to merge, v4

#8817 chore(schematics): drop universal mock
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/drop-universal-mock.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-universal.spec.ts
Labels: ready to merge, v4

#8794 fix(addon-commerce): `InputCardGroup` fix autofill styles
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/addon-commerce/components/input-card-group/input-card-group.template.html
  projects/core/styles/theme/appearance/textfield.less
Labels: ready to merge, v4

#8807 chore: lint
  jest.config.ts
  package-lock.json
  package.json
  projects/addon-doc/components/example/example.component.ts
  projects/cdk/utils/color/parse-gradient.ts
  projects/cdk/utils/color/rgba-to-hex.ts
  projects/cdk/utils/miscellaneous/is-valid-url.ts
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/app/landing/index.less
  projects/demo/src/modules/components/axes/examples/2/index.less
  projects/demo/src/modules/components/card-large/examples/11/index.less
  projects/demo/src/modules/components/card-medium/examples/1/index.less
  projects/demo/src/modules/components/card-medium/examples/5/index.less
  projects/demo/src/modules/components/preview/examples/4/index.less
  projects/demo/src/modules/components/surface/examples/7/surface.less
  projects/demo/src/modules/components/tabs/examples/3/index.less
  projects/demo/src/modules/components/tabs/examples/7/index.less
  projects/demo/src/modules/components/thumbnail-card/examples/2/index.less
  projects/demo/src/modules/customization/appearances/examples/1/index.less
  projects/demo/src/modules/directives/media/examples/2/index.less
  projects/demo/src/modules/directives/pan/examples/1/index.less
Labels: v4

#8773 ci: canary
  .github/workflows/publish-canary.yml
  projects/legacy/project.json
Labels: ready to merge, v4

#8702 ci: small changes
  .github/workflows/create-release.yml
  .github/workflows/publish.yml
Labels: v4

#8802 feat(experimental): `Cell` add border-radius
  projects/experimental/directives/cell/cell.styles.less
Labels: ready to merge, v3

#8745 refactor(cdk): add `tuiZonefreeScheduler` for `TuiDocScrollIntoViewLink`
  projects/addon-doc/components/navigation/scroll-into-view.directive.ts
Labels: ready to merge, v4

#8746 refactor(cdk): add `tuiZonefreeScheduler` for `TuiTileService`
  projects/kit/components/tiles/tile.service.ts
Labels: ready to merge, v4

#8747 chore(demo): add `tuiZonefreeScheduler` for `DEMO_PAGE_LOADED_PROVIDER`
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
Labels: ready to merge, v4

#8748 refactor(addon-mobile): add `tuiZonefreeScheduler` for `TuiMobileCalendar`
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: ready to merge, v4

#8749 refactor(core): add `tuiZonefreeScheduler` for `TuiRoot`
  projects/core/components/root/root.component.ts
Labels: ready to merge, v4

#8743 refactor(kit): add `tuiZonefreeScheduler` for `TuiCarouselScroll`
  projects/kit/components/carousel/carousel-scroll.directive.ts
Labels: ready to merge, v4

#8801 feat(layout): `Cell` add border-radius
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge, v4

#8818 fix(cdk): `NativeValidator` fix touched state
  projects/cdk/directives/native-validator/native-validator.directive.ts
  projects/core/components/textfield/textfield.component.ts
Labels: ready to merge, v4

#8849 chore: drop redundant mock
  projects/testing/setup-jest/index.ts
Labels: v4

#8850 chore: drop deprecated util
  projects/testing/utils/configure-test-suite.ts
  projects/testing/utils/index.ts
Labels: ready to merge, v4

#8848 chore: update get-currency-by-code.spec.ts
  projects/addon-commerce/utils/test/get-currency-by-code.spec.ts
Labels: v4

#8847 chore: update generate-demo-routes-file.ts
  scripts/generate-demo-routes-file.ts
Labels: v4

#8851 chore: compile without ts-ignore
  projects/testing/utils/helpers.ts
Labels: ready to merge, v4

#8837 fix(core): show empty content in correct detect changes cycle
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.template.html
Labels: ready to merge, v4

#8834 chore: add hipsters vscode dev infra
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
Labels: ready to merge, v4

#8859 chore: revert
  nx.json
  projects/testing/setup-jest/index.ts
Labels: ready to merge, v4

#8865 feat(experimental): `ThumbnailCard` add external `<img>` support
  projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.html
  projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.less
  projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.ts
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.module.ts
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.template.html
  projects/experimental/components/thumbnail-card/thumbnail-card.template.html
Labels: ready to merge, v3

#8866 chore(demo): update url and remove unused import
  projects/demo/src/modules/components/thumbnail-card/examples/4/index.html
  projects/demo/src/modules/components/thumbnail-card/examples/4/index.ts
Labels: v4

#8828 chore(demo): update getting started
  projects/demo/src/modules/app/home/examples/angular-json-global-single-styles.md
  projects/demo/src/modules/app/home/examples/app-standalone.md
  projects/demo/src/modules/app/home/examples/main-standalone.md
  projects/demo/src/modules/app/home/examples/styles.less.md
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/app/home/home.template.html
Labels: ready to merge, v4

#8870 refactor: use `injectContext`
  package.json
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/core/components/alert/alert.component.ts
  projects/core/components/alert/alerts.component.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/directives/hint/hint-unstyled.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/demo/src/modules/components/alert/examples/3/index.ts
  projects/demo/src/modules/components/alert/examples/4/index.ts
  projects/demo/src/modules/components/alert/examples/5/index.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content/index.ts
  projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.component.ts
  projects/kit/components/confirm/confirm.component.ts
  projects/kit/components/files/input-files/input-files.content.ts
  projects/kit/components/pdf-viewer/pdf-viewer.component.ts
  projects/kit/components/preview/preview-dialog/preview-dialog.component.ts
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/tree/components/tree-item-content/tree-item-content.component.ts
  projects/legacy/components/select-option/select-option.component.ts
  projects/legacy/components/table-bar/table-bar.component.ts
Labels: ready to merge, v4

#8862 chore(demo): fix source code links for cards
  projects/demo/src/modules/components/card-large/index.html
  projects/demo/src/modules/components/card-medium/index.html
Labels: ready to merge, v4

#8876 chore: add migration for `tuiHintAppearance`
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
Labels: ready to merge, v4

#8838 feat(addon-mobile): `InputSearch` add iOS imitating input
  .cspell.json
  projects/addon-mobile/styles/android/radio.less
  projects/addon-mobile/styles/android/switch.less
  projects/addon-mobile/styles/common/block-status.less
  projects/addon-mobile/styles/ios/search.less
  projects/addon-mobile/styles/ios/switch.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
Labels: ready to merge, v4

#8825 feat(kit): `Segmented` allow vertical orientation
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/addon-mobile/styles/common/segmented.less
  projects/addon-mobile/styles/ios/search.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
  projects/core/directives/dropdown/dropdown.style.less
  projects/core/styles/theme/palette.less
  projects/demo/src/modules/components/segmented/examples/2/index.html
  projects/demo/src/modules/components/segmented/examples/2/index.less
  projects/demo/src/modules/components/segmented/examples/3/index.html
  projects/demo/src/modules/components/segmented/examples/3/index.less
  projects/kit/components/push/push.style.less
  projects/kit/components/segmented/segmented.component.ts
  projects/kit/components/segmented/segmented.style.less
Labels: ready to merge, v4

#8909 fix(kit): `CalendarRange` revert computedMonth changes
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/calendar-range.template.html
Labels: ready to merge, v4

#8845 fix(kit): `InputFiles` fix validity and drag states
  projects/demo/src/modules/components/input-files/examples/1/index.ts
  projects/demo/src/modules/components/input-files/examples/5/index.html
  projects/demo/src/modules/components/input-files/index.html
  projects/kit/components/files/input-files/input-files.component.ts
  projects/kit/components/files/input-files/input-files.directive.ts
  projects/kit/components/files/input-files/input-files.style.less
Labels: ready to merge, v4

#8917 chore: fix some migration issues
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-text-mixins.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge, v4

#8877 chore(demo): add note to ng-add installation
  projects/demo/src/modules/app/home/home.template.html
Labels: v4

#8873 chore: add migration for active zone parent
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-active-zone.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-active-zone.spec.ts
Labels: ready to merge, v4

#8903 fix(kit): `InputTime` fix selection of the nearest value from items
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/input-time/test/input-time.component.spec.ts
Labels: ready to merge, v3

#8934 refactor: support `single-char-in-character-classes`
  package.json
  projects/demo/src/modules/components/input-tag/index.ts
  projects/legacy/utils/iso-to-country-code.ts
Labels: ready to merge, v4

#8933 refactor: support `default-param-last`
  package.json
  projects/kit/utils/toggle-day.ts
  scripts/shared/is-tui-package-name.ts
Labels: ready to merge, v4

#8942 chore: `ResizeObserver` CD trigger
  projects/addon-mobile/components/swipe-action/swipe-actions.component.ts
  projects/core/components/textfield/textfield.component.ts
  projects/kit/components/preview/preview.component.ts
Labels: ready to merge, v4

#8928 refactor: support `use-unknown-in-catch-callback-variable`
  package.json
  projects/demo/src/main.ts
Labels: ready to merge, v4

#8926 refactor: support `no-import-type-side-effects`
  package.json
  projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
Labels: ready to merge, v4

#8927 refactor: support `prefer-regexp-exec`
  package.json
  projects/addon-doc/utils/type-reference-parser.ts
  projects/cdk/schematics/ng-add/index.ts
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-month-context.ts
  projects/cdk/services/test/id.service.spec.ts
  projects/cdk/utils/color/parse-gradient.ts
  projects/cdk/utils/color/rgba-to-hex.ts
  projects/demo/src/modules/app/classes/ts-file.parser.ts
  projects/demo/src/modules/components/combo-box/index.ts
  projects/demo/src/modules/components/multi-select/index.ts
  scripts/combine-playwright-failed-screenshots.ts
  scripts/generate-demo-routes-file.ts
Labels: ready to merge, v4

#8833 feat(kit): `Copy` and `Password` add interactive icons to `Textfield`
  .cspell.json
  projects/cdk/utils/di/create-options.ts
  projects/cdk/utils/di/index.ts
  projects/cdk/utils/di/ng-package.json
  projects/cdk/utils/index.ts
  projects/core/components/error/error.component.ts
  projects/core/components/error/error.style.less
  projects/core/components/error/error.template.html
  projects/core/components/textfield/textfield.component.ts
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/textfield.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/input-copy/examples/1/index.html
  projects/demo/src/modules/components/input-copy/examples/1/index.ts
  projects/demo/src/modules/components/input-copy/examples/import/import.md
  projects/demo/src/modules/components/input-copy/examples/import/template.md
  projects/demo/src/modules/components/input-copy/index.html
  projects/demo/src/modules/components/input-copy/index.ts
  projects/demo/src/modules/components/input-password/examples/1/index.html
  projects/demo/src/modules/components/input-password/examples/2/index.html
  projects/demo/src/modules/components/input-password/examples/2/index.ts
  projects/demo/src/modules/components/input-password/examples/import/import.md
  projects/demo/src/modules/components/input-password/examples/import/template.md
  projects/demo/src/modules/components/input-password/index.html
  projects/demo/src/modules/components/input-password/index.ts
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/primitive-textfield/index.html
  projects/demo/src/modules/components/textfield/examples/4/index.html
  projects/demo/src/modules/components/textfield/examples/4/index.less
  projects/demo/src/modules/components/textfield/examples/4/index.ts
  projects/demo/src/modules/components/textfield/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/input-password/input-password.component.ts
  projects/kit/components/input-password/input-password.options.ts
  projects/kit/directives/copy/copy.directive.ts
  projects/kit/directives/copy/copy.options.ts
  projects/kit/directives/copy/index.ts
  projects/kit/directives/copy/ng-package.json
  projects/kit/directives/index.ts
  projects/kit/directives/password/index.ts
  projects/kit/directives/password/ng-package.json
  projects/kit/directives/password/password.directive.ts
  projects/kit/directives/password/password.options.ts
  projects/legacy/components/input-copy/input-copy.component.ts
  projects/legacy/components/input-copy/input-copy.directive.ts
  projects/legacy/components/input-copy/input-copy.module.ts
  projects/legacy/components/input-copy/input-copy.options.ts
  projects/legacy/components/input-password/input-password.component.ts
  projects/legacy/components/input-password/input-password.directive.ts
  projects/legacy/components/input-password/input-password.module.ts
  projects/legacy/components/input-password/input-password.options.ts
Labels: v4

#8940 refactor: support `sonar-max-params`
  package.json
  projects/legacy/components/input-number/input-number.component.ts
Labels: ready to merge, v4

#8920 chore(demo): fix problem with cdk rendering
  projects/demo/src/modules/components/combo-box/examples/5/index.html
  projects/demo/src/modules/components/multi-select/examples/7/index.html
  projects/demo/src/modules/components/pull-to-refresh/examples/3/index.html
  projects/demo/src/modules/components/scrollbar/examples/6/index.html
  projects/demo/src/modules/components/select/examples/8/index.html
  projects/demo/src/modules/components/table/examples/5/index.html
Labels: ready to merge, v4

#8963 chore: add e2e test for layout navigation
  projects/cdk/constants/used-icons.ts
  projects/demo-playwright/project.json
  projects/demo-playwright/tests/layout/navigation.spec.ts
Labels: ready to merge, v4

#8965 fix(core): rely only on `[tuiOption]` html attribute for search options
  projects/core/components/data-list/data-list.component.ts
Labels: ready to merge, v4

#8921 chore(demo): add form example for tui-checkbox
  projects/demo/src/modules/components/checkbox/examples/3/index.html
  projects/demo/src/modules/components/checkbox/examples/3/index.less
  projects/demo/src/modules/components/checkbox/examples/3/index.ts
  projects/demo/src/modules/components/checkbox/index.html
Labels: ready to merge, v4

#8890 chore: refactor test for using OnPush strategy
  projects/addon-doc/components/code/tests/highlight.spec.ts
Labels: v4

#8922 chore(demo): add form example for tui-checkbox
  projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.component.ts
  projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.module.ts
  projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.template.html
  projects/demo/src/modules/components/checkbox-labeled/examples/3/index.html
  projects/demo/src/modules/components/checkbox-labeled/examples/3/index.ts
Labels: ready to merge, v3

#8972 refactor: unsubscribe from RouterLinkActive when stepper is destroyed
  projects/kit/components/stepper/step.component.ts
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge, v4

#8904 chore(demo): improve documentation about icon
  projects/demo/src/modules/components/icon/examples/4/index.html
  projects/demo/src/modules/components/icon/examples/4/index.ts
  projects/demo/src/modules/components/icon/examples/4/server.md
  projects/demo/src/modules/components/icon/index.html
  projects/demo/src/modules/components/icon/index.ts
Labels: ready to merge, v4

#8969 ci: add github actions for e2e
  .github/workflows/e2e-playwright.yml
  package-lock.json
  package.json
  projects/demo/project.json
Labels: ready to merge, v4

#8898 refactor: add `tuiZonefreeScheduler` to `TuiScrollService`
  projects/cdk/services/scroll.service.ts
Labels: ready to merge, v4

#8897 refactor: add `tuiZonefreeScheduler` to `TUI_ACTIVE_ELEMENT`
  projects/cdk/tokens/active-element.ts
Labels: ready to merge, v4

#8896 refactor: add `tuiZonefreeScheduler` to `TuiMobileCalendar`
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: ready to merge, v4

#8895 refactor: add `tuiZonefreeScheduler` to `TuiHintDescribe`
  projects/core/directives/hint/hint-describe.directive.ts
Labels: ready to merge, v4

#8908 chore: add data-wrap-list.spec.ts
  projects/demo-playwright/tests/kit/data-wrap-list/data-wrap-list.spec.ts
Labels: v4

#8930 refactor: support `regex-complexity`
  package.json
  projects/cdk/tokens/environment.ts
Labels: ready to merge, v4

#8970 chore(schematics): remove modules from `importProvidersFrom`
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-providers-from.ts
  projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
Labels: ready to merge, v4

#8981 chore: fix by post review
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-providers-from.ts
  projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
Labels: ready to merge, v4

#8983 ci: do not error if no files are found
  package.json
Labels: ready to merge, v4

#8910 chore: add maskito and new textfield example
  projects/demo/src/modules/components/textfield/examples/5/index.html
  projects/demo/src/modules/components/textfield/examples/5/index.less
  projects/demo/src/modules/components/textfield/examples/5/index.ts
  projects/demo/src/modules/components/textfield/index.ts
Labels: v4

#8947 refactor: support `no-typeof-undefined`
  package.json
  projects/cdk/utils/browser/is-safari.ts
  projects/cdk/utils/color/hex-to-rgba.ts
  projects/legacy/tokens/is-firefox.ts
Labels: ready to merge, v4

#8846 chore: no-base-to-string
  package.json
  projects/testing/setup-jest/index.ts
Labels: ready to merge, v4

#8937 refactor: support `single-character-alternation`
  package.json
  projects/cdk/tokens/environment.ts
Labels: ready to merge, v4

#8869 chore(demo): update data-list api example
  projects/demo/src/modules/components/data-list/index.html
  projects/demo/src/modules/components/data-list/index.ts
Labels: v4

#8912 fix(kit): add overload for `TuiFilterByInputPipe`
  projects/demo/src/modules/pipes/filter-by-input/examples/2/index.ts
  projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
Labels: ready to merge, v4

#9007 fix(addon-mobile): export styles
  projects/addon-mobile/package.json
Labels: ready to merge, v4

#8918 chore: add example with routing and tuiTab
  package.json
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/tabs/examples/8/index.html
  projects/demo/src/modules/components/tabs/examples/8/index.ts
  projects/demo/src/modules/components/tabs/index.html
  projects/demo/src/modules/components/tabs/routes.ts
Labels: ready to merge, v4

#9003 ci: update playwright.config.ts
  projects/demo-playwright/playwright.config.ts
  projects/demo-playwright/tests/addon-doc/code.spec.ts
Labels: ready to merge, v4

#8900 refactor: use signal for initialized in `TuiLineClamp`
  projects/kit/components/line-clamp/line-clamp.component.ts
Labels: ready to merge, v4

#8914 chore(demo): add line clamp example with cdk virtual scroll
  projects/demo/src/modules/components/line-clamp/examples/6/index.html
  projects/demo/src/modules/components/line-clamp/examples/6/index.less
  projects/demo/src/modules/components/line-clamp/examples/6/index.ts
  projects/demo/src/modules/components/line-clamp/index.html
Labels: ready to merge, v4

#9015 feat(addon-doc): `API` add new component
  projects/addon-doc/components/api/api-item.component.ts
  projects/addon-doc/components/api/api-item.style.less
  projects/addon-doc/components/api/api-item.template.html
  projects/addon-doc/components/api/api.component.ts
  projects/addon-doc/components/api/api.style.less
  projects/addon-doc/components/api/api.template.html
  projects/addon-doc/components/index.ts
  projects/addon-doc/index.ts
  projects/addon-doc/tokens/i18n.ts
  projects/cdk/constants/used-icons.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/styles/components/textfield.less
  projects/demo/src/components/appearance/index.html
  projects/demo/src/components/appearance/index.ts
  projects/demo/src/components/icons/index.html
  projects/demo/src/components/icons/index.ts
  projects/demo/src/modules/components/block/index.html
  projects/demo/src/modules/components/block/index.ts
  projects/demo/used-icons.ts
  tsconfig.json
Labels: ready to merge, v4

#9019 chore: fix problem for proprietary
  projects/demo-playwright/tests/layout/navigation.spec.ts
  projects/demo/src/modules/components/navigation/examples/1/index.html
Labels: v4

#8961 fix(core): `Calendar` fix visual gaps in range
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.style.less
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.template.html
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
  projects/core/components/calendar/calendar-sheet.component.ts
  projects/core/components/calendar/calendar-sheet.style.less
  projects/core/components/calendar/calendar-sheet.template.html
  projects/core/components/calendar/calendar-year.component.ts
  projects/core/components/calendar/calendar-year.style.less
  projects/core/components/calendar/calendar-year.template.html
  projects/core/components/calendar/test/calendar-sheet.component.spec.ts
  projects/core/components/calendar/test/calendar-year.component.spec.ts
  projects/core/components/root/root.component.ts
  projects/core/styles/mixins/date-picker.less
  projects/core/styles/mixins/picker.less
  projects/core/styles/mixins/picker.scss
  projects/core/styles/taiga-ui-local.less
  projects/core/styles/theme/wrapper.less
  projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts
  projects/kit/components/calendar-month/calendar-month.component.ts
  projects/kit/components/calendar-month/calendar-month.style.less
  projects/kit/components/calendar-month/calendar-month.template.html
  projects/kit/components/calendar-month/test/calendar-month.component.spec.ts
  projects/kit/components/segmented/segmented.style.less
  projects/kit/directives/button-group/button-group.style.less
  projects/kit/directives/password/password.directive.ts
  projects/kit/styles/components/chip.less
  projects/testing/core/calendar-sheet.harness.ts
  projects/testing/core/calendar-year.harness.ts
Labels: ready to merge, v4

#9023 chore: failed test
  projects/core/components/root/root.component.ts
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
Labels: v4

#9040 fix(kit): `Connected` work with `CardLarge`
  projects/demo/src/modules/components/cell/examples/8/index.html
  projects/demo/src/modules/components/cell/examples/8/index.ts
  projects/kit/directives/connected/connected.style.less
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge, v4

#9039 fix(addon-doc): `TuiDocScrollIntoViewLink` should be export from root
  projects/addon-doc/components/index.ts
Labels: ready to merge, v4

#9042 feat(core): `Appearance` allow multiple modes
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-button-appearance.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button-appearance.spec.ts
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/directives/appearance/appearance.bindings.ts
  projects/core/directives/appearance/appearance.directive.ts
  projects/core/directives/appearance/with-appearance.ts
  projects/core/styles/components/appearance.less
  projects/core/styles/components/group.less
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/outline.less
  projects/core/styles/theme/appearance/primary.less
  projects/core/styles/theme/appearance/secondary.less
  projects/core/styles/theme/appearance/status.less
  projects/core/styles/theme/appearance/textfield.less
  projects/demo/src/components/appearance/index.html
  projects/demo/src/components/appearance/index.ts
  projects/demo/src/modules/components/block/index.html
  projects/demo/src/modules/components/button/examples/2/index.html
  projects/demo/src/modules/components/filter/examples/4/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/4/index.html
  projects/kit/components/input-phone-international/input-phone-international.template.html
Labels: ready to merge, v4

#9051 fix(core): `Dropdown` fix options leaking upwards
  projects/core/directives/dropdown/dropdown-options.directive.ts
  projects/core/directives/hint/hint-options.directive.ts
Labels: ready to merge, v4

#9012 chore: catch migration error
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
Labels: ready to merge, v4

#9058 chore(demo): `Button` migrate to new approach
  projects/demo/src/modules/components/button/index.html
  projects/demo/src/modules/components/button/index.ts
Labels: v4

#9044 refactor(addon-doc): use signals inside main template
  projects/addon-doc/components/main/main.component.ts
  projects/addon-doc/components/main/main.template.html
Labels: v4

#9027 refactor(legacy): drop constructor
  projects/legacy/classes/interactive.ts
  projects/legacy/components/color-selector/flat-picker/flat-picker.component.ts
  projects/legacy/components/color-selector/linear-multi-picker/linear-multi-picker.component.ts
  projects/legacy/components/color-selector/linear-picker/linear-picker.component.ts
  projects/legacy/components/color-selector/services/picker.service.ts
  projects/legacy/components/input-month-range/input-month-range.directive.ts
  projects/legacy/components/input-month/input-month.directive.ts
  projects/legacy/components/sheet/directives/sheet-stop/sheet-stop.directive.ts
  projects/legacy/components/svg/svg.component.ts
  projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
Labels: ready to merge, v4

#9025 fix(kit): do not override white-space for children of line-clamp
  projects/kit/components/line-clamp/line-clamp.style.less
Labels: ready to merge, v4

#9035 refactor: enable `arguments-order`
  package.json
  projects/demo/src/modules/components/compass/examples/2/index.ts
Labels: ready to merge, v4

#9031 fix(addon-mobile): correct height for `tui-app-bar` on ios/android
  projects/addon-mobile/styles/android/app-bar.less
  projects/addon-mobile/styles/ios/app-bar.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
Labels: ready to merge, v4

#8941 refactor: support `no-redundant-type-constituents`
  package.json
  projects/addon-doc/components/page/page-tab.directive.ts
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/cdk/classes/control.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/demo/src/modules/components/icons-group/icons-group.directive.ts
  projects/kit/components/badged-content/badged-content.directive.ts
  projects/kit/components/routable-dialog/routable-dialog.component.ts
  projects/kit/directives/copy/copy.directive.ts
  projects/layout/components/app-bar/app-bar.directive.ts
  projects/layout/components/block-status/block-status.directive.ts
  projects/legacy/classes/control.ts
  projects/legacy/directives/wrapper/wrapper.directive.ts
Labels: ready to merge, v4

#9059 fix(core): `Appearance` remove initial transition
  projects/core/directives/appearance/appearance.directive.ts
  projects/core/styles/components/appearance.less
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/layout/components/navigation/aside-item.directive.ts
Labels: ready to merge, v4

#9069 fix(cdk): unsubscribe from zoom service when directive is destroyed
  projects/cdk/directives/zoom/zoom.service.ts
Labels: ready to merge, v4

#9068 feat(cdk): add `TuiLooseUnion`
  projects/cdk/types/index.ts
  projects/cdk/types/loose-union.ts
  projects/core/directives/appearance/appearance.options.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/i18n/types/language-names.ts
  projects/kit/components/badged-content/badged-content.directive.ts
  projects/layout/components/app-bar/app-bar.directive.ts
  projects/layout/components/block-status/block-status.directive.ts
  projects/legacy/directives/wrapper/wrapper.directive.ts
Labels: ready to merge, v4

#9065 fix(core): do not override nested tui-icon styles
  projects/core/styles/components/textfield.less
  projects/demo/src/modules/components/thumbnail-card/examples/5/index.html
  projects/demo/src/modules/components/thumbnail-card/examples/5/index.less
  projects/demo/src/modules/components/thumbnail-card/examples/5/index.ts
  projects/demo/src/modules/components/thumbnail-card/index.ts
Labels: ready to merge, v4

#9045 chore: cleanup README.md
  projects/demo/src/modules/customization/i18n/app.esbuild.module.md
  projects/demo/src/modules/customization/i18n/base.md
  projects/demo/src/modules/customization/i18n/custom.md
  projects/demo/src/modules/customization/i18n/dynamic.md
  projects/demo/src/modules/customization/i18n/esbuild.md
  projects/demo/src/modules/customization/i18n/index.html
  projects/demo/src/modules/customization/i18n/index.ts
  projects/i18n/README.md
Labels: ready to merge, v4

#9073 feat(addon-doc): full prerender page for ssr and improve ux
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.style.less
  projects/addon-doc/components/example/example.template.html
Labels: ready to merge, v4

#9032 fix(kit): drop image skeleton when handle of lazy loading error
  projects/demo/src/modules/directives/lazy-loading/examples/1/index.ts
  projects/demo/src/modules/directives/lazy-loading/examples/import/import.md
  projects/kit/directives/lazy-loading/lazy-loading.directive.ts
Labels: ready to merge, v4

#9022 fix(cdk): unsubscribe from swipe service when directive is destroyed
  projects/cdk/directives/swipe/swipe.service.ts
Labels: ready to merge, v4

#9021 fix(cdk): unsubscribe from pan service when directive is destroyed
  projects/cdk/directives/pan/pan.service.ts
Labels: ready to merge, v4

#9086 chore(demo): `Button` remove unused imports
  projects/demo/src/modules/components/button/examples/1/index.ts
  projects/demo/src/modules/components/button/examples/2/index.ts
Labels: v4

#9088 fix(legacy): fix scroll jumping on readonly input focusing in safari
  projects/legacy/styles/mixins/textfield.less
Labels: v4

#9074 fix(experimental): `Segmented` fix initial radio value
  projects/demo/src/modules/experimental/segmented/examples/4/index.ts
  projects/experimental/components/segmented/segmented.component.ts
  projects/experimental/components/segmented/segmented.directive.ts
Labels: v3

#9063 fix(legacy): during serialization angular was unable to find an element in the DOM
  projects/legacy/components/arrow/arrow.component.ts
  projects/legacy/components/color-selector/color-edit/color-edit.component.ts
  projects/legacy/components/color-selector/color-picker/color-picker.component.ts
  projects/legacy/components/color-selector/color-selector.component.ts
  projects/legacy/components/color-selector/flat-picker/flat-picker.component.ts
  projects/legacy/components/color-selector/linear-multi-picker/linear-multi-picker.component.ts
  projects/legacy/components/color-selector/linear-picker/linear-picker.component.ts
  projects/legacy/components/color-selector/palette/palette.component.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-color/input-color.component.ts
  projects/legacy/components/input-copy/input-copy.component.ts
  projects/legacy/components/input-date-multi/input-date-multi.component.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-month-range/input-month-range.component.ts
  projects/legacy/components/input-month/input-month.component.ts
  projects/legacy/components/input-number/input-number.component.ts
  projects/legacy/components/input-password/input-password.component.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-range/input-range.component.ts
  projects/legacy/components/input-slider/input-slider.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-time/native-time/native-time.component.ts
  projects/legacy/components/input-year/input-year.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select-option/multi-select-option.component.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/multi-select/native-multi-select/native-multi-select-group.component.ts
  projects/legacy/components/multi-select/native-multi-select/native-multi-select.component.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.component.ts
  projects/legacy/components/primitive-textfield/textfield/textfield.component.ts
  projects/legacy/components/primitive-textfield/value-decoration/value-decoration.component.ts
  projects/legacy/components/select-option/select-option.component.ts
  projects/legacy/components/select/native-select/native-select-group.component.ts
  projects/legacy/components/select/native-select/native-select.component.ts
  projects/legacy/components/select/select.component.ts
  projects/legacy/components/sheet/components/sheet-bar/sheet-bar.component.ts
  projects/legacy/components/sheet/components/sheet-heading/sheet-heading.component.ts
  projects/legacy/components/sheet/components/sheet/sheet.component.ts
  projects/legacy/components/sheet/components/sheets-host/sheets-host.component.ts
  projects/legacy/components/svg/svg.component.ts
  projects/legacy/components/table-bar/table-bar.component.ts
  projects/legacy/components/table-bar/table-bars-host.component.ts
  projects/legacy/components/tag/tag.component.ts
  projects/legacy/components/textarea/textarea.component.ts
  projects/legacy/components/tooltip/tooltip.component.ts
Labels: ready to merge, v4

#9090 feat(kit): improve IDEA auto import for `TuiImageLoading`
  projects/demo-cypress/src/tests/lazy-loading.cy.ts
  projects/demo/src/modules/app/landing/index.html
  projects/demo/src/modules/app/landing/index.ts
  projects/demo/src/modules/directives/lazy-loading/examples/1/index.html
  projects/demo/src/modules/directives/lazy-loading/examples/import/template.md
  projects/demo/src/modules/directives/lazy-loading/index.html
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/avatar/avatar.template.html
  projects/kit/directives/lazy-loading/lazy-loading.directive.ts
Labels: ready to merge, v4

#9089 refactor: change small logic
  projects/kit/directives/lazy-loading/lazy-loading.directive.ts
Labels: ready to merge, v4

#9062 feat(cdk): support provide custom query selector for auto focus directive
  projects/cdk/directives/auto-focus/autofocus.options.ts
  projects/cdk/directives/auto-focus/handlers/abstract.handler.ts
  projects/cdk/directives/auto-focus/handlers/default.handler.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
  projects/cdk/utils/di/create-options.ts
  projects/cdk/utils/miscellaneous/create-token.ts
Labels: ready to merge, v4

#9014 fix(kit): memory leak in line-clamp
  projects/kit/components/line-clamp/line-clamp.component.ts
  projects/kit/components/line-clamp/line-clamp.template.html
Labels: ready to merge, v4

#9028 refactor(addon-charts): drop constructor in pie-chart
  projects/addon-charts/components/pie-chart/pie-chart.directive.ts
Labels: ready to merge, v4

#9026 refactor(addon-charts): use signal in arc-chart
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
  projects/addon-charts/components/arc-chart/arc-chart.template.html
Labels: ready to merge, v4

#9081 refactor(addon-doc): search input
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/components/navigation/navigation.style.less
  projects/addon-doc/components/navigation/navigation.template.html
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/textfield/textfield-dropdown.directive.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
Labels: ready to merge, v4

#9099 feat(addon-doc): add ability to disable default search-bar
  projects/addon-doc/README.md
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/components/navigation/navigation.style.less
  projects/addon-doc/components/navigation/navigation.template.html
  projects/addon-doc/tokens/i18n.ts
  projects/demo/src/modules/app/app.config.ts
Labels: ready to merge, v4

#9094 fix(core): fix scroll jumping on readonly input focusing in safari
  projects/core/styles/mixins/textfield.less
Labels: ready to merge, v3

#8984 chore(demo): color recalculate color in table
  projects/demo/src/modules/markup/colors/examples/table/index.html
  projects/demo/src/modules/markup/colors/examples/table/index.less
  projects/demo/src/modules/markup/colors/examples/table/index.ts
  projects/demo/src/modules/markup/colors/index.html
  projects/demo/src/modules/markup/colors/index.ts
Labels: ready to merge, v4

#9117 fix(addon-commerce): `InputCardGroup` fix for older Safari
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/kit/components/files/file/file.options.ts
Labels: ready to merge, v4

#8989 feat(kit): `Like` add new component
  projects/cdk/constants/used-icons.ts
  projects/demo-playwright/tests/kit/like/like.spec.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/like/examples/1/index.html
  projects/demo/src/modules/components/like/examples/1/index.ts
  projects/demo/src/modules/components/like/examples/2/index.html
  projects/demo/src/modules/components/like/examples/2/index.ts
  projects/demo/src/modules/components/like/examples/3/index.html
  projects/demo/src/modules/components/like/examples/3/index.ts
  projects/demo/src/modules/components/like/examples/4/index.html
  projects/demo/src/modules/components/like/examples/4/index.ts
  projects/demo/src/modules/components/like/examples/5/index.html
  projects/demo/src/modules/components/like/examples/5/index.ts
  projects/demo/src/modules/components/like/examples/import/import.md
  projects/demo/src/modules/components/like/examples/import/template.md
  projects/demo/src/modules/components/like/index.html
  projects/demo/src/modules/components/like/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/index.ts
  projects/kit/components/like/index.ts
  projects/kit/components/like/like.component.ts
  projects/kit/components/like/like.options.ts
  projects/kit/components/like/ng-package.json
  projects/kit/styles/components/like.less
Labels: ready to merge, v4

#9127 fix(kit): `MultiSelect` empty line when non empty `placeholder` and `valueContent`
  projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-tag/input-tag.style.less
  projects/kit/components/input-tag/input-tag.template.html
Labels: ready to merge, v3

#9123 fix(legacy): `MultiSelect` empty line when non empty `placeholder` and `valueContent`
  projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-tag/input-tag.style.less
  projects/legacy/components/input-tag/input-tag.template.html
Labels: ready to merge, v4

#8974 fix(cdk): remove global styles patching from auto-focus directive
  projects/addon-doc/components/navigation/navigation.providers.ts
  projects/addon-doc/components/navigation/navigation.style.less
  projects/addon-doc/components/navigation/navigation.template.html
  projects/cdk/directives/auto-focus/autofocus.options.ts
  projects/cdk/directives/auto-focus/handlers/default.handler.ts
  projects/cdk/directives/auto-focus/handlers/ios.handler.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.less
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.template.html
  projects/demo/src/modules/directives/auto-focus/examples/import/import.md
Labels: ready to merge, v4

#9130 chore(demo): fix re-creating main portal twice
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge, v4

#9128 chore(schematics): migrate `TUI_EDITOR_DEFAULT_EDITOR_TOOLS`
  projects/cdk/schematics/ng-update/v4/steps/migrate-editor.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-addon-editor.spec.ts
Labels: v4

#9109 ci: do not mark job as failed for expired firebase instance
  .github/workflows/delete-preview.yml
Labels: v4

#9116 chore: migrate `tuiRow`
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
Labels: ready to merge, v4

#9129 chore(core): `Textfield` remove border
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/textfield.less
  projects/kit/components/input-phone-international/input-phone-international.style.less
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Labels: ready to merge, v4

#9108 feat(addon-doc): add aria-label for dark mode button
  projects/addon-doc/components/main/main.template.html
Labels: ready to merge, v4

#9111 chore: lint changes
  package.json
  projects/cdk/schematics/ng-add/index.ts
  projects/core/directives/appearance/appearance.bindings.ts
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/app/stackblitz/utils.ts
  projects/demo/src/modules/components/abstract/control.ts
Labels: ready to merge, v4

#9110 feat(addon-doc): heading elements are not in a sequentially-descending order
  projects/addon-doc/components/example/example.template.html
Labels: ready to merge, v4

#9103 refactor: move language component to header
  projects/addon-doc/components/language-switcher/index.html
  projects/addon-doc/components/language-switcher/index.less
  projects/addon-doc/components/language-switcher/index.ts
  projects/cdk/constants/used-icons.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/app.style.less
  projects/demo/src/modules/app/app.template.html
  projects/demo/src/modules/app/search/index.less
  projects/demo/used-icons.ts
Labels: v4

#8883 refactor: add `tuiZonefreeScheduler` to `TuiInputFilesDirective`
  projects/kit/components/files/input-files/input-files.directive.ts
Labels: ready to merge, v4

#9120 chore: add some plugins for vscode
  .cspell.json
  .vscode/extensions.json
  .vscode/settings.json
Labels: ready to merge, v4

#9134 fix(addon-commerce): `InputCardGroup` fix for older Safari
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
Labels: ready to merge, v3

#9133 chore: fix `InputCard` after borders were removed
  projects/addon-commerce/components/input-card/index.ts
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/addon-commerce/components/input-card/input-card.style.less
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/styles/components/icons.less
  projects/core/styles/components/textfield.less
  projects/kit/directives/chevron/chevron.style.less
  projects/kit/directives/copy/copy.directive.ts
  projects/kit/directives/password/password.directive.ts
  projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
Labels: v4
