Repository taiga-family/taiga-ui, pull requests merged in 2024-08, with the labels that each got.

#8284 chore: migrate avatar autoColor
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
Labels: ready to merge

#8283 refactor(kit)!: rename `TuiFilterComponent` to `TuiFilter`
  projects/demo/src/modules/components/action-bar/examples/1/index.ts
  projects/demo/src/modules/components/filter/examples/1/index.ts
  projects/demo/src/modules/components/filter/examples/2/index.ts
  projects/demo/src/modules/components/filter/examples/3/index.ts
  projects/demo/src/modules/components/filter/examples/4/index.ts
  projects/demo/src/modules/components/filter/index.ts
  projects/kit/components/filter/filter.component.ts
  projects/kit/components/filter/test/filter.component.spec.ts
Labels: ready to merge

#8287 chore: correct link to editor
  projects/demo/src/modules/icons/icons-bundled/icons-bundled.template.html
  projects/demo/src/modules/info/related/related.template.html
Labels: v3

#8188 fix(kit): reuse cursor position after showing password
  projects/kit/components/input-password/input-password.component.ts
Labels: v3

#8285 chore(schematics): migrations for `<tui-notification />` (`[size]` & `[hideClose]` attributes)
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
Labels: ready to merge

#8292 chore(schematics): wrap all content projection with `<div>` if `<tui-notification>` includes children >= 2
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
Labels: ready to merge

#8222 refactor: rename `TuiPush` to `TuiPushComponent`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/kit/components/push/index.ts
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/push/push.component.ts
  projects/kit/components/push/push.ts
Labels: ready to merge, v4

#8300 chore(core): `Textfield` move to styles
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/styles/components/button.less
  projects/core/styles/components/label.less
  projects/core/styles/components/link.less
  projects/core/styles/components/notification.less
  projects/core/styles/components/textfield.less
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/button-vertical/examples/1/index.html
  projects/demo/src/modules/components/button-vertical/examples/1/index.less
  projects/demo/src/modules/components/button-vertical/examples/2/index.less
  projects/demo/src/modules/components/button-vertical/examples/2/index.ts
  projects/demo/src/modules/components/button-vertical/examples/import/import.md
  projects/demo/src/modules/components/button-vertical/examples/import/template.md
  projects/demo/src/modules/components/button-vertical/index.html
  projects/demo/src/modules/components/button-vertical/index.ts
  projects/demo/src/modules/components/button/examples/6/index.html
  projects/demo/src/modules/components/button/examples/6/index.ts
  projects/demo/src/modules/components/button/index.ts
  projects/demo/src/modules/components/cell/examples/3/index.ts
  projects/demo/src/modules/components/push/examples/1/index.ts
  projects/demo/src/modules/components/push/index.ts
  projects/kit/components/progress/progress-bar/progress-bar.component.ts
  projects/kit/directives/button-vertical/button-vertical.directive.ts
  projects/kit/directives/button-vertical/button-vertical.style.less
  projects/kit/directives/button-vertical/index.ts
  projects/kit/directives/button-vertical/ng-package.json
  projects/kit/directives/index.ts
  projects/kit/styles/components/badge.less
  projects/kit/styles/components/block.less
  projects/kit/styles/components/checkbox.less
  projects/kit/styles/components/chip.less
  projects/kit/styles/components/comment.less
  projects/kit/styles/components/progress-bar.less
  projects/kit/styles/components/radio.less
  projects/kit/styles/components/switch.less
Labels: ready to merge

#8311 chore: fix CurrencyPipe, TuiPromptModule migration. Add warning for TUI_ANIMATIONS_DURATION token
  projects/cdk/schematics/ng-update/v3/constants/warnings.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
Labels: ready to merge

#8303 chore(schematics): fix corner case of migration for `TuiAlertService` options
  projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
Labels: ready to merge

#8312 refactor(schematics): `IDENTIFIERS_TO_REPLACE` accepts array for `from` property
  projects/cdk/schematics/ng-update/interfaces/replacement-identifier.ts
  projects/cdk/schematics/ng-update/steps/replace-identifier.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8322 chore: add link to next version
  README.md
Labels: ready to merge

#8308 fix(legacy): fix inputnumber component overflowing container in row layout
  projects/legacy/components/input-number/input-number.style.less
Labels: v4

#8323 refactor: use link to native changelog
  CHANGELOG.md
  package-lock.json
  package.json
  projects/addon-doc/index.ts
  projects/addon-doc/package.json
  projects/addon-doc/pipes/index.ts
  projects/addon-doc/pipes/markdown/markdown.pipe.ts
  projects/addon-doc/pipes/ng-package.json
  projects/addon-doc/styles/index.less
  projects/addon-doc/styles/mixins/changelog.less
  projects/addon-doc/styles/mixins/markdown.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/info/changelog/index.html
  projects/demo/src/modules/info/changelog/index.less
  projects/demo/src/modules/info/changelog/index.ts
Labels: ready to merge

#8316 feat(kit): `AutoScale` add new directive
  projects/core/styles/components/textfield.less
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/customization/portals/examples/1/index.ts
  projects/demo/src/modules/customization/portals/examples/1/portal.ts
  projects/demo/src/modules/customization/portals/examples/1/portal/custom-host.component.ts
  projects/demo/src/modules/customization/portals/examples/1/portal/custom-host.style.less
  projects/demo/src/modules/customization/portals/examples/1/portal/custom-host.template.html
  projects/demo/src/modules/customization/portals/examples/1/service.ts
  projects/demo/src/modules/customization/portals/index.ts
  projects/demo/src/modules/directives/fluid-typography/examples/1/index.html
  projects/demo/src/modules/directives/fluid-typography/examples/1/index.ts
  projects/demo/src/modules/directives/fluid-typography/examples/2/index.html
  projects/demo/src/modules/directives/fluid-typography/examples/2/index.ts
  projects/demo/src/modules/directives/fluid-typography/examples/3/index.html
  projects/demo/src/modules/directives/fluid-typography/examples/3/index.ts
  projects/demo/src/modules/directives/fluid-typography/examples/import/import.md
  projects/demo/src/modules/directives/fluid-typography/examples/import/template.md
  projects/demo/src/modules/directives/fluid-typography/index.html
  projects/demo/src/modules/directives/fluid-typography/index.ts
  projects/kit/directives/fluid-typography/fluid-typography.directive.ts
  projects/kit/directives/fluid-typography/fluid-typography.options.ts
  projects/kit/directives/fluid-typography/index.ts
  projects/kit/directives/fluid-typography/ng-package.json
  projects/kit/directives/index.ts
Labels: ready to merge

#8274 ci: use default tsconfig for eslint
  package.json
  tsconfig.eslint.json
  tsconfig.json
  tsconfig.spec.json
Labels: ready to merge, v4

#8273 chore: editor
  package-lock.json
  package.json
  projects/cdk/schematics/ng-update/v3-36/index.ts
  projects/cdk/schematics/ng-update/v3-36/tests/schematic-migrate-editor.spec.ts
Labels: v3

#8334 chore: husky
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
Labels: ready to merge

#8249 fix(kit): correct present of control value from items list for input-time
  projects/demo/src/modules/components/input-time/input-time.component.ts
  projects/kit/components/input-time/input-time.component.ts
Labels: v3

#8241 feat(i18n): add hebrew
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/i18n/languages/hebrew/addon-commerce.ts
  projects/i18n/languages/hebrew/addon-editor.ts
  projects/i18n/languages/hebrew/addon-preview.ts
  projects/i18n/languages/hebrew/addon-table.ts
  projects/i18n/languages/hebrew/core.ts
  projects/i18n/languages/hebrew/countries.ts
  projects/i18n/languages/hebrew/hebrew.ts
  projects/i18n/languages/hebrew/index.ts
  projects/i18n/languages/hebrew/kit.ts
  projects/i18n/languages/hebrew/ng-package.json
  projects/i18n/languages/index.ts
Labels: ready to merge, v3

#8242 feat(i18n): add hebrew
  projects/addon-doc/components/language-switcher/index.ts
  projects/i18n/languages/hebrew/addon-commerce.ts
  projects/i18n/languages/hebrew/addon-editor.ts
  projects/i18n/languages/hebrew/addon-table.ts
  projects/i18n/languages/hebrew/core.ts
  projects/i18n/languages/hebrew/countries.ts
  projects/i18n/languages/hebrew/hebrew.ts
  projects/i18n/languages/hebrew/index.ts
  projects/i18n/languages/hebrew/kit.ts
  projects/i18n/languages/hebrew/ng-package.json
  projects/i18n/languages/index.ts
  projects/i18n/types/language-names.ts
Labels: ready to merge, v4

#8333 refactor: reuse cursor position after showing password
  projects/kit/components/input-password/input-password.component.ts
  projects/kit/components/input-password/input-password.template.html
Labels: ready to merge, v3

#8176 refactor(demo-playwright): drop deprecated method `type`
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
  projects/demo-playwright/tests/kit/input-slider/input-slider.spec.ts
  projects/demo-playwright/tests/kit/input-time/input-time.spec.ts
Labels: v4

#8246 feat(core): add `mode` for `tui-scrollbar`
  projects/core/components/scrollbar/index.ts
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.options.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/components/scrollbar/scrollbar.template.html
  projects/demo/src/modules/components/scrollbar/examples/7/index.html
  projects/demo/src/modules/components/scrollbar/examples/7/index.less
  projects/demo/src/modules/components/scrollbar/examples/7/index.ts
  projects/demo/src/modules/components/scrollbar/index.html
  projects/demo/src/modules/components/scrollbar/index.ts
Labels: ready to merge, v4

#8340 feat(core): add `mode` for `tui-scrollbar`
  projects/core/components/scrollbar/index.ts
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.options.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/components/scrollbar/scrollbar.template.html
  projects/demo/src/modules/components/scrollbar/examples/7/index.html
  projects/demo/src/modules/components/scrollbar/examples/7/index.less
  projects/demo/src/modules/components/scrollbar/examples/7/index.ts
  projects/demo/src/modules/components/scrollbar/scrollbar.component.ts
  projects/demo/src/modules/components/scrollbar/scrollbar.module.ts
  projects/demo/src/modules/components/scrollbar/scrollbar.template.html
Labels: ready to merge, v3

#8183 fix(core): it's not possible to scroll container elements on safari
  projects/core/components/dialog/dialogs.style.less
Labels: v4

#8332 fix(kit): `CalendarRange` defaultViewedMonth set to min, if min later than current month
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Labels: ready to merge

#8224 refactor: move `TuiStaticRequestService` to legacy
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/services/index.ts
  projects/demo-cypress/src/tests/static-request.cy.ts
  projects/legacy/components/svg/svg.component.ts
  projects/legacy/index.ts
  projects/legacy/services/index.ts
  projects/legacy/services/ng-package.json
  projects/legacy/services/static-request.service.ts
Labels: v4

#8230 refactor: doesn't close nested dropdown inside color-selector
  projects/cdk/constants/used-icons.ts
  projects/demo/src/modules/components/input-color/examples/2/index.html
  projects/demo/src/modules/components/input-color/examples/3/index.html
  projects/legacy/components/color-selector/color-selector.component.ts
  projects/legacy/components/color-selector/color-selector.style.less
  projects/legacy/components/color-selector/color-selector.template.html
Labels: ready to merge, v4

#8338 fix(legacy): placeholder in multiselect disappears while hovering options
  projects/legacy/components/input-tag/input-tag.style.less
  projects/legacy/components/input-tag/input-tag.template.html
Labels: ready to merge, v4

#8277 refactor: small improves
  projects/addon-doc/components/code/index.less
Labels: ready to merge, v4

#8336 chore(schematics): more identifiers migrations
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
Labels: ready to merge

#8345 fix(core): ios menu is not triggered
  projects/core/styles/mixins/mixins.less
Labels: v3

#8304 feat(addon-commerce): add `Decimal` pipe
  projects/addon-commerce/pipes/amount/amount.options.ts
  projects/addon-commerce/pipes/amount/amount.pipe.ts
  projects/addon-commerce/pipes/decimal/decimal.pipe.ts
  projects/addon-commerce/pipes/decimal/index.ts
  projects/addon-commerce/pipes/decimal/ng-package.json
  projects/addon-commerce/pipes/index.ts
  projects/core/tokens/number-format.ts
  projects/core/utils/format/test/format-number.spec.ts
  projects/demo-playwright/tests/kit/input-number/input-number.spec.ts
  projects/demo-playwright/tests/kit/input-range/input-range.spec.ts
  projects/demo/src/modules/pipes/amount/examples/4/index.html
  projects/demo/src/modules/pipes/amount/examples/4/index.less
  projects/demo/src/modules/pipes/amount/examples/4/index.ts
  projects/demo/src/modules/pipes/amount/index.ts
  projects/legacy/components/input-number/test/input-number-format.spec.ts
  projects/legacy/components/input-number/test/input-number.component.spec.ts
  projects/legacy/components/input-range/test/input-range.component.spec.ts
  projects/legacy/components/input-slider/test/input-slider.component.spec.ts
Labels: ready to merge

#8355 chore(schematics): migrations for `TuiDeepPartial` & `TuiMarkerIconMode`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
Labels: ready to merge

#8364 chore(kit): rename `TuiRatingComponent` => `TuiRating`
  projects/demo/src/modules/components/rating/examples/1/index.ts
  projects/demo/src/modules/components/rating/examples/2/index.ts
  projects/demo/src/modules/components/rating/examples/3/index.ts
  projects/kit/components/rating/rating.component.ts
Labels: ready to merge

#8371 chore: fix badged-content migration, add some identifiers migration
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
Labels: ready to merge

#8360 chore(schematics): fix migration for `TuiEditorSocketModule` (invalid `moduleSpecifier`)
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8349 Revert "fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>` (#8206)"
  CHANGELOG.md
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
Labels: ready to merge, v3

#8373 chore(schematics): migrations for shadow style mixins
  projects/cdk/schematics/ng-update/v4/steps/styles/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-shadow-mixins.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge

#8387 chore(schematics): migration for `[hasIcon]` property of `<tui-notification>` / `[tuiNotification]`
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
Labels: ready to merge

#8383 chore(demo): update component packages
  projects/demo/src/modules/components/combo-box/index.html
  projects/demo/src/modules/components/input-copy/index.html
  projects/demo/src/modules/components/input-date-multi/index.html
  projects/demo/src/modules/components/input-date-range/index.html
  projects/demo/src/modules/components/input-date-time/index.html
  projects/demo/src/modules/components/input-date/index.html
  projects/demo/src/modules/components/input-month-range/index.html
  projects/demo/src/modules/components/input-month/index.html
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-password/index.html
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/input-phone/index.html
  projects/demo/src/modules/components/input-range/index.html
  projects/demo/src/modules/components/input-slider/index.html
  projects/demo/src/modules/components/input-tag/index.html
  projects/demo/src/modules/components/input-time/index.html
  projects/demo/src/modules/components/input-year/index.html
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/multi-select/index.html
  projects/demo/src/modules/components/select/index.html
  projects/demo/src/modules/components/tag/index.html
  projects/demo/src/modules/components/tag/index.ts
Labels: ready to merge

#8379 chore: add pseudo-* inputs migration
  projects/cdk/schematics/ng-update/interfaces/replacement-attribute-value.ts
  projects/cdk/schematics/ng-update/utils/templates/replace-attr-values.ts
  projects/cdk/schematics/ng-update/v3/constants/templates.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: ready to merge

#8381 chore(demo): drop redundant tag
  projects/demo/src/modules/components/navigation/index.html
Labels: v4

#8350 chore: disable annoying zoom on safari
  projects/demo/src/index.html
Labels: ready to merge, v4

#8291 fix(legacy): reuse cursor position after showing password
  projects/legacy/components/input-password/input-password.template.html
Labels: ready to merge, v4

#8386 feat(addon-doc): input switch should be aligned right
  projects/addon-doc/components/documentation/documentation.style.less
Labels: ready to merge, v4

#8282 feat(legacy): create `TUI_TIME_VALUE_TRANSFORMER` for `tui-input-time` component
  projects/core/components/data-list/data-list.tokens.ts
  projects/demo/src/modules/components/input-time/examples/6/index.html
  projects/demo/src/modules/components/input-time/examples/6/index.ts
  projects/demo/src/modules/components/input-time/examples/7/index.html
  projects/demo/src/modules/components/input-time/examples/7/index.ts
  projects/demo/src/modules/components/input-time/index.html
  projects/kit/tokens/date-inputs-value-transformers.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-time/test/input-time.component.spec.ts
Labels: ready to merge

#8393 chore: switch preview account, delete channel on PR close
  .github/workflows/delete-preview.yml
  .github/workflows/deploy-preview.yml
Labels: ready to merge

#8394 chore: icon update
  projects/demo/src/modules/components/notification/examples/2/index.ts
  projects/demo/used-icons.ts
Labels: ready to merge

#8352 refactor: use `valueOf`
  projects/kit/components/input-time/input-time.component.ts
Labels: v4

#8351 Revert "fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>` (#8205)"
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/examples/8/index.ts
  projects/demo/src/modules/components/dialog/index.html
Labels: ready to merge, v4

#8395 chore(kit): `Stepper` vertical align set to stretch
  projects/kit/components/stepper/step.style.less
Labels: ready to merge

#8376 feat(addon-doc): set `overscroll-behavior` to `none`
  projects/addon-doc/components/main/main.style.less
  projects/addon-doc/components/navigation/navigation.providers.ts
Labels: ready to merge, v4

#8337 fix(legacy): correct present of control value from items list for input-time
  projects/demo/src/modules/components/input-time/index.ts
  projects/legacy/components/input-time/input-time.component.ts
Labels: ready to merge, v4

#8385 refactor: drop old schematics
  projects/cdk/schematics/ng-update/v3-30/constants/constants.ts
  projects/cdk/schematics/ng-update/v3-30/constants/icons.ts
  projects/cdk/schematics/ng-update/v3-30/index.ts
  projects/cdk/schematics/ng-update/v3-35/constants/constants.ts
  projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
  projects/cdk/schematics/ng-update/v3-35/index.ts
  projects/cdk/schematics/ng-update/v3-36/index.ts
  projects/cdk/schematics/ng-update/v3-40/index.ts
  projects/cdk/schematics/ng-update/v3-5/index.ts
  projects/cdk/schematics/ng-update/v3-5/steps/migrate-expand-templates.ts
  projects/cdk/schematics/ng-update/v3/constants/breakpoints.ts
  projects/cdk/schematics/ng-update/v3/constants/constants.ts
  projects/cdk/schematics/ng-update/v3/constants/deprecated-functions.ts
  projects/cdk/schematics/ng-update/v3/constants/enums.ts
  projects/cdk/schematics/ng-update/v3/constants/modules.ts
  projects/cdk/schematics/ng-update/v3/constants/services.ts
  projects/cdk/schematics/ng-update/v3/constants/templates.ts
  projects/cdk/schematics/ng-update/v3/constants/tui-interactive-selectors.ts
  projects/cdk/schematics/ng-update/v3/constants/types.ts
  projects/cdk/schematics/ng-update/v3/constants/warnings.ts
  projects/cdk/schematics/ng-update/v3/index.ts
  projects/cdk/schematics/ng-update/v3/schema.json
  projects/cdk/schematics/ng-update/v3/steps/migrate-date-time.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-polymorpheus.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-progress.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-sliders/index.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-sliders/migrate-input-range.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-sliders/migrate-input-slider.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-taiga-proprietary-icons.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v3/steps/migrate-textfield-controller.ts
  projects/cdk/schematics/ng-update/v3/steps/miscellaneous.ts
  projects/cdk/schematics/ng-update/v3/steps/replace-functions.ts
  projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
Labels: ready to merge, v4

#8245 chore: cherry pick from tui-editor repo
  projects/legacy/components/color-selector/color-selector.component.ts
  projects/legacy/components/color-selector/color-selector.options.ts
  projects/legacy/components/color-selector/color-selector.template.html
  projects/legacy/components/color-selector/index.ts
Labels: ready to merge, v4

#8025 feat(kit): add `tuiConnected` directive for `Stepper` and `Cell`
  projects/demo/src/modules/components/cell/examples/8/index.html
  projects/demo/src/modules/components/cell/examples/8/index.less
  projects/demo/src/modules/components/cell/examples/8/index.ts
  projects/demo/src/modules/components/cell/index.ts
  projects/demo/src/modules/components/stepper/examples/4/index.html
  projects/demo/src/modules/components/stepper/examples/4/index.less
  projects/demo/src/modules/components/stepper/examples/4/index.ts
  projects/demo/src/modules/components/stepper/index.ts
  projects/kit/directives/connected/connected.directive.ts
  projects/kit/directives/connected/connected.style.less
  projects/kit/directives/connected/index.ts
  projects/kit/directives/connected/ng-package.json
  projects/kit/directives/index.ts
  projects/layout/components/cell/cell.directive.ts
Labels: feature, ready to merge, v4

#8240 feat(cdk): add `TuiThemeColorService`
  projects/cdk/services/index.ts
  projects/cdk/services/theme-color.service.ts
  projects/demo/src/modules/components/dialog/examples/11/index.html
  projects/demo/src/modules/components/dialog/examples/11/index.ts
  projects/demo/src/modules/components/dialog/index.html
Labels: ready to merge, v4

#8401 chore: fix pseudo- migration
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: ready to merge

#8409 refactor(kit): rename standalone component `TuiInputPhoneInternational` (drop `Component` postfix)
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
  projects/demo/src/modules/components/input-phone-international/examples/1/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/2/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/import/import.md
  projects/demo/src/modules/components/input-phone-international/index.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Labels: ready to merge

#8382 refactor: drop `scroll-behavior()` mixin
  projects/addon-doc/components/navigation/navigation.style.less
  projects/cdk/schematics/ng-update/v4/steps/styles/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-scrollbar-behavior.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
  projects/core/components/root/root.component.ts
  projects/core/styles/mixins/mixins.less
  projects/demo-cypress/cypress.config.ts
  projects/demo/src/modules/components/tabs/examples/7/index.less
  projects/demo/src/styles/doc-global.style.less
  projects/demo/src/styles/styles.less
  projects/kit/components/stepper/stepper.style.less
  projects/legacy/components/input-tag/input-tag.style.less
Labels: ready to merge, v4

#8403 chore(kit): `Stepper` left text align
  projects/kit/components/stepper/step.style.less
Labels: ready to merge, v4

#8405 chore(kit): `Stepper` text and icon align
  projects/kit/components/stepper/step/step.style.less
Labels: ready to merge, v3

#8412 chore: small change
  projects/demo/src/modules/components/notification/examples/2/index.ts
Labels: ready to merge

#8416 chore(schematics): migration for `TuiNumberFormatSettings`
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-number-format-settings.ts
  projects/cdk/schematics/ng-update/v4/tests/migrate-number-format-settings.spec.ts
Labels: ready to merge

#8414 chore(schematics): migration for `TuiAlertOptions`
  projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
Labels: ready to merge

#8415 chore: fix unstyled hint
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint-unstyled.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/demo-cypress/src/tests/static-request.cy.ts
Labels: ready to merge

#8374 feat(i18n): add japanese
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/i18n/languages/index.ts
  projects/i18n/languages/japan/addon-commerce.ts
  projects/i18n/languages/japan/addon-editor.ts
  projects/i18n/languages/japan/addon-preview.ts
  projects/i18n/languages/japan/addon-table.ts
  projects/i18n/languages/japan/core.ts
  projects/i18n/languages/japan/countries.ts
  projects/i18n/languages/japan/index.ts
  projects/i18n/languages/japan/japan.ts
  projects/i18n/languages/japan/kit.ts
  projects/i18n/languages/japan/ng-package.json
Labels: v3

#8418 chore(schematics): add migration comment for `TuiFormatNumberPipe`
  projects/cdk/schematics/ng-update/interfaces/html-comment.ts
  projects/cdk/schematics/ng-update/utils/templates/template-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-format-settings.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge

#8423 chore(schematics): fix icon migration error
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts
Labels: ready to merge

#8425 chore: fix root module migration
  projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts
  projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
Labels: ready to merge

#8426 chore: fix link icon migration
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-links.spec.ts
Labels: ready to merge

#8431 chore(schematics): missing identifiers migration for `TuiToolbarModule`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8433 chore: add migration comments for `TUI_ANIMATIONS_DURATION` & `TUI_IS_MOBILE_RES`
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
Labels: ready to merge

#8435 chore: switch deploy branches
  .github/workflows/deploy-gh-pages.yml
  projects/demo/src/modules/app/version-manager/versions.constants.ts
Labels: ready to merge

#8437 chore(demo): fix base href for prerender
  projects/demo/project.json
Labels: ready to merge

#8442 chore(demo): fix incorrect tag in header of documentation page `InputPhoneInternational`
  projects/demo/src/modules/components/input-phone-international/index.html
Labels: ready to merge

#8443 chore(demo): fix prerender of documentation page `Media`
  projects/demo/src/modules/app/demo-routes.ts
  scripts/generate-demo-routes-file.ts
Labels: ready to merge

#8438 ci: skip announce when package is already published
  .github/workflows/publish.yml
  scripts/publish.ts
Labels: ready to merge, v4

#8446 chore: correct tag name
  scripts/publish.ts
Labels: v3

#8445 chore(demo): remove `ColorPicker` item from sidebar navigation of documentation
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#8447 chore: some fixes
  projects/addon-doc/components/demo/index.ts
  projects/addon-doc/components/documentation/documentation.component.ts
  projects/core/components/index.ts
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/directives/group/group.directive.ts
  projects/core/directives/group/group.options.ts
  projects/core/directives/group/group.style.less
  projects/core/directives/group/index.ts
  projects/core/directives/group/ng-package.json
  projects/core/directives/index.ts
  projects/core/styles/components/button.less
  projects/core/styles/components/notification.less
  projects/core/styles/components/textfield.less
  projects/core/styles/mixins/mixins.less
  projects/core/styles/theme/appearance/secondary.less
  projects/kit/components/accordion/accordion.directive.ts
  projects/kit/components/files/files/files.component.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/segmented/segmented.directive.ts
  projects/kit/styles/components/badge.less
  projects/kit/styles/components/checkbox.less
  projects/legacy/components/color-selector/color-selector.module.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
Labels: ready to merge

#8440 ci: correct npm tag name
  scripts/publish.ts
Labels: ready to merge, v4

#8448 fix(cdk): redundant assert log if hours are greater than 23
  projects/cdk/date-time/time.ts
Labels: v4

#8449 fix(cdk): redundant assert log if hours are greater than 23
  projects/cdk/date-time/time.ts
Labels: v3

#8467 chore: `filterByInputWith` add missing migration
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-filter-pipe.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts
  projects/core/components/textfield/textfield.template.html
Labels: ready to merge

#8461 fix(kit): `TuiDataListGroupWrapperComponent` is not assignable to the same property in base type
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
Labels: ready to merge, v4

#8468 fix(core): `Root` fix background
  projects/core/components/root/root.style.less
Labels: ready to merge

#8464 chore(core): `Group` move to published styles
  projects/addon-doc/components/demo/index.html
  projects/core/directives/group/group.directive.ts
  projects/core/directives/group/group.options.ts
  projects/core/directives/group/group.style.less
  projects/core/styles/components/group.less
  projects/demo/src/modules/components/group/examples/1/index.html
  projects/demo/src/modules/components/group/examples/2/index.html
  projects/demo/src/modules/components/group/examples/import/template.md
  projects/demo/src/modules/components/group/index.html
  projects/demo/src/modules/components/group/index.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.html
  projects/kit/components/files/files/files.component.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/color-selector/color-edit/color-edit.module.ts
  projects/legacy/components/color-selector/color-edit/color-edit.template.html
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-phone-international/input-phone-international.template.html
Labels: ready to merge

#8460 chore: add v4.0.0 changelog
  CHANGELOG.md
Labels: ready to merge

#8452 chore: update official maintainers
  .github/CODEOWNERS
  README.md
Labels: v4

#8457 refactor: a little bit cleanup
  .github/workflows/auto-update-icons.yml
  projects/icons/LICENSE
  projects/icons/package.json
  projects/icons/project.json
  projects/icons/scripts/prepare-icons.ts
  projects/icons/svg.d.ts
Labels: v4

#8470 chore: fix migration issues
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
Labels: ready to merge

#8471 chore: fix `ngFor` migration for blocked and labeled
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: ready to merge

#8451 chore: update README.md
  README.md
Labels: ready to merge, v4

#8473 chore: fix appearance migration
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Labels: ready to merge

#8475 chore: fix publish workflow
  .github/workflows/publish.yml
Labels: ready to merge

#8481 fix(kit): fix calendar range does not update checkbox position
  projects/kit/components/calendar-range/calendar-range.component.ts
Labels: v3

#8344 chore: upgrade editor
  .npmrc
  package-lock.json
  package.json
  projects/cdk/schematics/ng-update/v3-36/index.ts
  projects/cdk/schematics/ng-update/v3-36/tests/schematic-migrate-editor.spec.ts
Labels: ready to merge, v3

#8486 feat(i18n): add korean
  projects/addon-doc/components/language-switcher/index.ts
  projects/i18n/languages/korean/addon-commerce.ts
  projects/i18n/languages/korean/addon-editor.ts
  projects/i18n/languages/korean/addon-table.ts
  projects/i18n/languages/korean/core.ts
  projects/i18n/languages/korean/countries.ts
  projects/i18n/languages/korean/index.ts
  projects/i18n/languages/korean/kit.ts
  projects/i18n/languages/korean/korean.ts
  projects/i18n/languages/korean/ng-package.json
  projects/i18n/types/language-names.ts
Labels: ready to merge, v4

#8469 fix(kit): icon hover on readonly
  projects/core/styles/theme/wrapper/icon.less
  projects/kit/components/input-date-multi/input-date-multi.template.html
  projects/kit/components/input-date-range/input-date-range.template.html
  projects/kit/components/input-date-time/input-date-time.template.html
  projects/kit/components/input-date/input-date.template.html
Labels: ready to merge, v3

#8492 fix(legacy): `InputTime` has missing zero padding on blur for `HH:MM` mode
  projects/cdk/date-time/time.ts
  projects/demo-playwright/tests/kit/input-time/input-time.spec.ts
  projects/legacy/components/input-time/input-time.component.ts
Labels: ready to merge, v4

#8478 fix(core): ignore pointer events for disabled button
  projects/core/components/button/button.style.less
Labels: ready to merge, v3

#8400 fix(kit): `CalendarRange` defaultViewedMonth shows correct calendars months
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/calendar-range.template.html
  projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
Labels: ready to merge, v3

#8488 fix calendar range does not update checkbox position
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Labels: v4

#8498 fix(i18n): add korean
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/i18n/interfaces/language-names.ts
  projects/i18n/languages/korean/addon-commerce.ts
  projects/i18n/languages/korean/addon-editor.ts
  projects/i18n/languages/korean/addon-preview.ts
  projects/i18n/languages/korean/addon-table.ts
  projects/i18n/languages/korean/core.ts
  projects/i18n/languages/korean/countries.ts
  projects/i18n/languages/korean/index.ts
  projects/i18n/languages/korean/kit.ts
  projects/i18n/languages/korean/korean.ts
  projects/i18n/languages/korean/ng-package.json
Labels: ready to merge, v3

#8499 chore: small fixes
  projects/addon-table/components/reorder/reorder.component.ts
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/button/index.html
  projects/demo/src/modules/components/reorder/examples/1/index.ts
  projects/demo/src/modules/components/table/examples/4/index.ts
Labels: ready to merge

#8495 refactor: invalid path to compile
  projects/icons-material/ng-package.json
  projects/icons-material/project.json
Labels: ready to merge, v4

#8500 chore: fix auto-color pipe migration
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
Labels: ready to merge

#8504 chore: add `TuiItemDirective` migration
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#8502 chore: improve message for migration
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge

#8506 chore: built-in pdf viewer
  projects/demo/src/modules/components/pdf-viewer/pdf-viewer.module.ts
  projects/demo/src/modules/components/pdf-viewer/pdf-viewer.template.html
Labels: v3

#8505 chore: built-in pdf viewer
  projects/demo/src/modules/components/pdf-viewer/index.html
Labels: v4

#8329 feat(kit): prevent disabled date selection for calendar-range
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/kit/components/calendar-range/calendar-range.component.ts
Labels: ready to merge, v4

#8509 fix(core): `Group` fix edge overlay
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/directives/group/group.directive.ts
  projects/core/styles/components/group.less
Labels: ready to merge

#8482 chore(demo): `DocDemo` generates invalid urls during attempts to patch query params
  projects/addon-doc/tokens/url-state-handler.ts
  projects/demo/src/modules/app/app.config.ts
Labels: v4

#8512 chore: fix some icons migration
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
Labels: ready to merge

#8511 chore: fix some migration issues
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts
  projects/cdk/schematics/ng-update/v4/steps/utils/normalize-attr-value.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
Labels: ready to merge

#8522 ci: temporary disable automatic deploy to Github Pages
  .github/workflows/deploy-gh-pages.yml
Labels: ready to merge

#8524 chore(demo): show custom icons on page
  projects/demo/src/modules/icons/custom-icons.ts
  projects/demo/src/modules/icons/fontawesome/examples/2/index.html
  projects/demo/src/modules/icons/fontawesome/examples/2/index.less
  projects/demo/src/modules/icons/fontawesome/examples/2/index.ts
  projects/demo/src/modules/icons/fontawesome/index.html
  projects/demo/src/modules/icons/icons/examples/2/index.html
  projects/demo/src/modules/icons/icons/examples/2/index.less
  projects/demo/src/modules/icons/icons/examples/2/index.ts
  projects/demo/src/modules/icons/icons/icons.tokens.ts
  projects/demo/src/modules/icons/icons/index.html
  projects/demo/src/modules/icons/icons/index.ts
  projects/demo/src/modules/icons/material/examples/2/index.html
  projects/demo/src/modules/icons/material/examples/2/index.less
  projects/demo/src/modules/icons/material/examples/2/index.ts
  projects/demo/src/modules/icons/material/index.html
  projects/demo/used-icons.ts
Labels: ready to merge

#8531 ci: fix baseHref for `v3` inside `deploy-gh-pages.yml`
  .github/workflows/deploy-gh-pages.yml
Labels: ready to merge

#8518 chore: add licence for icons pack
  .cspell.json
  projects/icons-fontawesome/LICENSE
  projects/icons-fontawesome/project.json
  projects/icons-material/LICENSE
  projects/icons-material/project.json
  projects/icons/LICENSE
  projects/icons/project.json
Labels: ready to merge, v4

#8501 fix(i18n): redundant whitespace
  projects/i18n/languages/belarusian/kit.ts
  projects/i18n/languages/chinese/kit.ts
  projects/i18n/languages/dutch/kit.ts
  projects/i18n/languages/english/kit.ts
  projects/i18n/languages/german/kit.ts
  projects/i18n/languages/italian/kit.ts
  projects/i18n/languages/portuguese/kit.ts
  projects/i18n/languages/russian/kit.ts
  projects/i18n/languages/spanish/kit.ts
  projects/i18n/languages/turkish/kit.ts
  projects/kit/components/files/pipes/file-rejected.pipe.ts
Labels: ready to merge, v4

#8521 chore: migrate to latest editor
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
Labels: ready to merge, v4

#8420 feat(i18n): add japanese
  projects/addon-doc/components/language-switcher/index.ts
  projects/i18n/languages/index.ts
  projects/i18n/languages/japan/addon-commerce.ts
  projects/i18n/languages/japan/addon-editor.ts
  projects/i18n/languages/japan/addon-table.ts
  projects/i18n/languages/japan/core.ts
  projects/i18n/languages/japan/countries.ts
  projects/i18n/languages/japan/index.ts
  projects/i18n/languages/japan/japan.ts
  projects/i18n/languages/japan/kit.ts
  projects/i18n/languages/japan/ng-package.json
  projects/i18n/types/language-names.ts
Labels: ready to merge, v4

#8516 feat(i18n): improve literal string union
  projects/i18n/types/language-names.ts
Labels: ready to merge, v4

#8496 refactor: move type check inside project
  .github/workflows/e2e-playwright.yml
  projects/demo-playwright/project.json
  projects/demo-playwright/tsconfig.playwright.json
  tsconfig.playwright.json
Labels: ready to merge, v4

#8354 ci: add `verbatimModuleSyntax`
  projects/cdk/schematics/tsconfig.schematics.json
  projects/demo/src/modules/components/combo-box/index.ts
  tsconfig.json
Labels: ready to merge, v4

#8532 chore: fix some migration issues
  .cspell.json
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Labels: ready to merge

#8402 chore: do not put `tui-doc-code` inside `tui-notification`
  projects/demo/src/modules/components/dialog/index.html
Labels: ready to merge, v4

#8407 chore: small refactor
  projects/addon-doc/components/main/main.style.less
  projects/addon-doc/components/navigation/navigation.style.less
Labels: ready to merge, v4

#8348 fix(core): ios menu is not triggered
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/core/styles/components/textfield.less
  projects/legacy/styles/mixins/mixins.less
  projects/legacy/styles/mixins/mixins.scss
Labels: ready to merge, v4

#8534 refactor: correct prepare icons
  .github/workflows/auto-update-icons.yml
  projects/icons-fontawesome/project.json
  projects/icons-fontawesome/scripts/prepare-icons.ts
  projects/icons-material/project.json
  projects/icons-material/scripts/prepare-icons.ts
  projects/icons/project.json
  projects/icons/scripts/prepare-icons.ts
  scripts/custom-icons.ts
Labels: ready to merge

#8356 ci: add eslint consistent-return
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
  projects/demo-playwright/utils/page-objects/calendar.po.ts
  projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
  projects/kit/components/pagination/pagination.component.ts
Labels: ready to merge, v4

#8218 ci: upgrade nx
  package-lock.json
  package.json
  projects/demo-cypress/package.json
Labels: ready to merge, v4

#8526 chore(demo): use `baseHref=/` instead of `baseHref=./`
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  projects/demo/project.json
  projects/demo/src/modules/app/app.providers.ts
Labels: ready to merge

#8547 ci: use `matrix` in `deploy-gh-pages.yml` to configure base href for all documentation versions
  .github/workflows/deploy-gh-pages.yml
Labels: ready to merge

#8542 refactor: drop decorators
  projects/cdk/directives/media/media.directive.ts
  projects/cdk/directives/resizer/resizer.directive.ts
  projects/kit/components/files/file/file.component.ts
  projects/kit/components/files/input-files/input-files-validator.directive.ts
  projects/kit/components/tiles/tiles.component.ts
Labels: ready to merge

#8550 chore(demo): use `baseHref=/` instead of `baseHref=./`
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e-playwright.yml
  package.json
  projects/demo-cypress/cypress.config.ts
  projects/demo/project.json
  projects/demo/src/404.html
Labels: ready to merge, v4

#8553 ci: delete outdated step in `e2e-playwright.yml` + enable deploy on release again
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#8557 chore(addon-doc): improve ssr hydration for `TuiDocPage`
  projects/addon-doc/components/page/page.style.less
  projects/demo/src/modules/app/logo/logo.style.less
Labels: ready to merge

#8544 ci: move `codecov.yml` to `.github` directory
  .github/codecov.yml
  .github/workflows/test.yml
Labels: ready to merge

#8558 ci: add auto label
  .github/workflows/auto-add-version-label.yml
Labels: v3

#8556 ci: add label for version
  .github/workflows/auto-add-version-label.yml
Labels: v4

#8543 ci: enable canary for v4.x
  .github/workflows/publish-canary.yml
Labels: ready to merge, v4

#8570 refactor(addon-doc): use only CSS media queries for breakpoints
  projects/addon-doc/components/code/index.less
  projects/addon-doc/components/demo/index.less
  projects/addon-doc/components/documentation/documentation.style.less
  projects/addon-doc/components/example/example.style.less
Labels: v4

#8568 fix(legacy): prevent add/remove suffixes while InputNumber is readonly
  projects/legacy/components/input-number/input-number.component.ts
Labels: v4

#8571 fix(kit): prevent add/remove suffixes while InputNumber is readonly
  projects/kit/components/input-number/input-number.component.ts
Labels: v3

#8265 feat(addon-mobile): possibility drop mobile calendar header
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.html
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.less
  projects/demo/src/modules/components/mobile-calendar/examples/6/index.ts
  projects/demo/src/modules/components/mobile-calendar/index.html
  projects/demo/src/modules/components/mobile-calendar/index.ts
Labels: v4
