Repository taiga-family/taiga-ui, pull requests merged in 2024-06, with the labels that each got.

#7594 fix(cdk): `Scrollbar` fix scroll behaviour
  projects/cdk/components/scroll-controls/scrollbar.directive.ts
Labels: ready to merge, v3

#7593 fix(core): close `Hint` and `Dropdown` when host is detached from dom
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
Labels: ready to merge, v3

#7592 fix(kit): collision with input-date-multi
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/input-date.directive.ts
Labels: ready to merge, v4

#7588 fix(kit): set nullish border in `tui-textarea`
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge, v3

#7602 chore(demo): drop tinkoff logo
  projects/demo/src/assets/images/by.svg
  projects/demo/src/index.html
  projects/demo/src/modules/app/landing/landing.template.html
  projects/demo/src/modules/app/logo/logo.template.html
Labels: ready to merge, v3

#7603 chore(core): add `cursor: pointer` for `<select tuiTextfield />`
  projects/core/components/textfield/textfield.style.less
Labels: ready to merge

#7596 feat(kit): emails pipe from proprietary
  .cspell.json
  package-lock.json
  package.json
  projects/core/components/hosted-dropdown/hosted-dropdown.template.html
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/icons/icons-group/icons-group.template.html
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.html
  projects/demo/src/modules/components/sheet-dialog/index.html
  projects/demo/src/modules/customization/routable/eager/examples/2/index.html
  projects/demo/src/modules/pipes/emails/examples/1/index.html
  projects/demo/src/modules/pipes/emails/examples/1/index.ts
  projects/demo/src/modules/pipes/emails/examples/import/import.md
  projects/demo/src/modules/pipes/emails/examples/import/template.md
  projects/demo/src/modules/pipes/emails/index.html
  projects/demo/src/modules/pipes/emails/index.less
  projects/demo/src/modules/pipes/emails/index.ts
  projects/kit/pipes/emails/emails.options.ts
  projects/kit/pipes/emails/emails.pipe.spec.ts
  projects/kit/pipes/emails/emails.pipe.ts
  projects/kit/pipes/emails/index.ts
  projects/kit/pipes/emails/ng-package.json
  projects/kit/pipes/index.ts
Labels: ready to merge

#7605 fix(kit): set nullish border in `tui-textarea` and add example
  projects/demo/src/modules/components/textarea/examples/4/index.html
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge

#7604 fix(legacy): set nullish border in `tui-textarea`
  projects/demo/src/modules/components/textarea/examples/4/index.html
  projects/legacy/components/textarea/textarea.style.less
Labels: ready to merge

#7608 chore: close `Hint` and `Dropdown` when host is detached from dom
  projects/core/directives/hint/hint.component.ts
Labels: v3

#7606 refactor(core): `Textfield` should not shift all content if empty `label[tuiLabel]` is passed
  projects/core/components/textfield/textfield.component.ts
Labels: ready to merge

#7615 chore: include inputs/outputs of host directive `ActiveZone` in `DropdownOpen`'s API
  projects/core/directives/dropdown/dropdown-open.directive.ts
Labels: ready to merge

#7614 fix(core): close `Hint` and `Dropdown` when host is detached from dom
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/demo-cypress/src/tests/hint.cy.ts
Labels: ready to merge, v4

#7611 feat(cdk): `DirectiveBinding` / `DirectiveListener` add utils
  projects/cdk/utils/miscellaneous/directive-binding.ts
  projects/cdk/utils/miscellaneous/directive-listener.ts
  projects/cdk/utils/miscellaneous/index.ts
  projects/experimental/components/navigation/hint-aside.directive.ts
  projects/kit/components/files/input-files/input-files.directive.ts
Labels: ready to merge

#7636 fix(kit): `InputDateTime` with `[min]` / `[max]` distorts value on click
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: ready to merge, v3

#7620 refactor: drop `tuiGenerateRoutes` util
  projects/addon-doc/addon-doc.module.ts
  projects/addon-doc/utils/generate-routes.ts
  projects/addon-doc/utils/index.ts
  projects/addon-doc/utils/test/generate-routes.spec.ts
Labels: ready to merge, v4

#7624 chore: drop `TODO` in legacy package
  projects/legacy/components/input-phone/test/input-phone.component.spec.ts
  projects/legacy/components/tag/tag.component.ts
  projects/legacy/components/tag/test/tag.component.spec.ts
  projects/legacy/utils/get-safe-area-size.ts
Labels: ready to merge, v4

#7628 chore: drop logo module
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.component.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.module.ts
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.style.less
  projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.template.html
  projects/demo/src/modules/app/logo/logo.component.ts
  projects/demo/src/modules/app/logo/logo.module.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.module.ts
  projects/demo/src/modules/components/range/examples/import/import.md
  projects/demo/src/modules/components/services/table-bars-service/examples/import/lazy-module.md
  projects/demo/used-icons.ts
Labels: ready to merge, v4

#7635 chore: drop Tinkoff name
  README.md
  package.json
  projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
  projects/demo/src/assets/images/by.svg
  projects/demo/src/index.html
  projects/demo/src/modules/app/landing/index.html
  projects/demo/src/modules/app/logo/logo.template.html
  projects/experimental/README.md
Labels: ready to merge, v4

#7648 feat!: `ProgressCircle` uses `new`-mode as default one
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/demo/src/modules/components/cell/examples/3/index.html
  projects/demo/src/modules/components/progress-circle/examples/2/index.html
  projects/demo/src/modules/components/progress-circle/examples/7/index.html
  projects/demo/src/modules/components/progress-circle/index.html
  projects/demo/src/modules/components/progress-circle/index.ts
  projects/kit/components/progress/progress-circle/progress-circle.style.less
  projects/kit/components/progress/progress-circle/progress-circle.template.html
Labels: ready to merge

#7651 refactor(core): `Appearance` switch to data-mode
  projects/cdk/classes/signal-control.ts
  projects/cdk/directives/hovered/hovered.service.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/components/textfield/textfield.style.less
  projects/core/styles/theme/appearance/textfield.less
Labels: ready to merge

#7654 fix(legacy): fix `InputNumber` buttons styles priority for Safari
  projects/legacy/components/input-number/input-number.style.less
Labels: ready to merge

#7652 fix(kit): fix `InputNumber` buttons styles priority for Safari
  projects/kit/components/input-number/input-number.style.less
Labels: ready to merge, v3

#7655 fix(kit): `InputTag` fix scrolling to input
  projects/kit/components/input-tag/input-tag.component.ts
Labels: v3

#7647 fix(core): fix text selection in nested hint
  projects/core/directives/hint/hint.component.ts
Labels: ready to merge, v3

#7626 fix(core): `DropdownSelection` fix selection error in textarea
  projects/core/directives/dropdown/dropdown-selection.directive.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
Labels: v3

#7665 fix(core): `DropdownSelection` fix selection error in textarea (#7626)
  projects/core/directives/dropdown/dropdown-selection.directive.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
Labels: ready to merge, v4

#7662 refactor(kit): use signals inside `InputPhoneInternational`
  projects/kit/components/input-phone-international/get-country-calling-code.pipe.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.options.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Labels: ready to merge

#7667 feat(core): add ability to use nested hints (#7647)
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/demo/src/modules/directives/hint/examples/3/index.html
  projects/demo/src/modules/directives/hint/examples/3/index.ts
  projects/demo/src/modules/directives/hint/index.html
Labels: v4

#7664 fix(core): `Hint` fix content vertical centering with reduced line-height
  projects/core/directives/hint/hint.style.less
Labels: v4

#7668 chore: move design-tokens to core
  package-lock.json
  projects/cdk/utils/dom/test/get-element-obscurers.spec.ts
  projects/core/package.json
  projects/kit/package.json
Labels: ready to merge

#7645 fix(core): fix incorrect copy hint in inputCopy
  projects/legacy/components/input-copy/input-copy.component.ts
Labels: v4

#7659 fix(kit): `InputDateTime` should format textfield value on blur
  projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: v3

#7675 chore: move design-tokens to dev dependencies
  package-lock.json
  package.json
  projects/core/package.json
Labels: ready to merge

#7676 refactor(core): move legacy mixins to legacy
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/addon-doc/components/documentation/documentation.template.html
  projects/addon-doc/components/page/page.template.html
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.template.html
  projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.style.less
  projects/cdk/classes/signal-control.ts
  projects/cdk/directives/active-zone/active-zone.directive.ts
  projects/core/styles/mixins/mixins.scss
  projects/core/styles/taiga-ui-local.less
  projects/core/styles/taiga-ui-local.scss
  projects/demo/src/modules/customization/wrapper/examples/1/index.less
  projects/legacy/components/input-tag/input-tag.style.less
  projects/legacy/components/primitive-textfield/primitive-textfield.style.less
  projects/legacy/components/primitive-textfield/textfield/textfield.style.less
  projects/legacy/components/textarea/textarea.style.less
  projects/legacy/styles/mixins/textfield.less
  projects/legacy/styles/mixins/textfield.scss
  projects/legacy/styles/mixins/wrapper.less
  projects/legacy/styles/mixins/wrapper.scss
  projects/legacy/styles/taiga-ui-local.less
  projects/legacy/styles/taiga-ui-local.scss
  projects/legacy/styles/wrapper/accent.less
  projects/legacy/styles/wrapper/base.less
  projects/legacy/styles/wrapper/floating.less
  projects/legacy/styles/wrapper/glass.less
  projects/legacy/styles/wrapper/icon.less
  projects/legacy/styles/wrapper/mono.less
  projects/legacy/styles/wrapper/opposite.less
  projects/legacy/styles/wrapper/outline.less
  projects/legacy/styles/wrapper/primary.less
  projects/legacy/styles/wrapper/secondary-destructive.less
  projects/legacy/styles/wrapper/secondary.less
  projects/legacy/styles/wrapper/table.less
  projects/legacy/styles/wrapper/textfield.less
  projects/legacy/styles/wrapper/whiteblock.less
Labels: ready to merge

#7670 refactor(addon-commerce): `InputCardGrouped` move things to hostDirectives
  projects/addon-commerce/components/input-card-grouped/abstract-input-card.ts
  projects/addon-commerce/components/input-card-grouped/index.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/addon-commerce/components/input-card/input-card.options.ts
  projects/addon-commerce/components/input-cvc/input-cvc.directive.ts
  projects/addon-commerce/components/input-expire/input-expire.directive.ts
  projects/addon-commerce/constants/card-mask.ts
  projects/addon-commerce/constants/index.ts
  projects/addon-commerce/constants/mask-card-holder.ts
  projects/addon-commerce/constants/mask-card.ts
  projects/addon-commerce/constants/mask-cvc.ts
  projects/addon-commerce/constants/mask-expire.ts
  projects/addon-commerce/constants/tests/mask-card-holder.spec.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
  projects/demo/src/modules/components/input-card-grouped/examples/1/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.less
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/3/index.html
  projects/demo/src/modules/components/input-card-grouped/examples/5/index.ts
  projects/demo/src/modules/components/input-card-grouped/index.html
  projects/demo/src/modules/components/input-card-grouped/index.ts
Labels: ready to merge

#7689 refactor: drop `.shadow` mixin
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
Labels: ready to merge

#7690 refactor: drop `processIcons`
  projects/icons/scripts/process-icons.ts
Labels: ready to merge

#7688 refactor: drop `TUI_LOADED`
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts
Labels: ready to merge

#7686 refactor: drop `tuiItemsQueryListObservable`
  projects/cdk/observables/query-list-observable.ts
Labels: ready to merge

#7685 refactor: drop `TuiCardHarness`
  projects/testing/core/card.harness.ts
Labels: ready to merge

#7683 refactor: drop `TUI_DOC_SCROLL_BEHAVIOR` token
  projects/addon-doc/tokens/index.ts
  projects/addon-doc/tokens/scroll-behavior.ts
Labels: ready to merge

#7687 refactor: drop `TUI_ENSURE_BASE_HREF`
  projects/cdk/tokens/ensure-base-href.ts
  projects/cdk/tokens/index.ts
Labels: ready to merge

#7684 refactor: drop `tuiCreateOptions`
  projects/cdk/utils/miscellaneous/create-options.ts
  projects/cdk/utils/miscellaneous/index.ts
Labels: ready to merge

#7693 feat(core): `WithDataList` add host directive
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/cdk/utils/miscellaneous/directive-binding.ts
  projects/cdk/utils/miscellaneous/directive-listener.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.tokens.ts
  projects/core/components/data-list/index.ts
  projects/core/components/data-list/option.component.ts
  projects/core/components/data-list/with-data-list.directive.ts
  projects/core/components/label/label.directive.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.style.less
  projects/core/tokens/index.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/select/select.component.ts
Labels: ready to merge

#7682 refactor: drop `tuiPrepareExternalUrl`
  projects/addon-charts/utils/index.ts
  projects/addon-charts/utils/prepare-external-url.ts
Labels: ready to merge

#7696 refactor: remove unnecessary entities and entry points
  projects/addon-charts/components/axes/axes.component.ts
  projects/addon-charts/constants/index.ts
  projects/addon-charts/constants/line-handlers.ts
  projects/addon-charts/index.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
  projects/addon-commerce/pipes/amount/amount.options.ts
  projects/addon-commerce/pipes/amount/amount.pipe.ts
  projects/addon-commerce/pipes/amount/amount.types.ts
  projects/addon-commerce/pipes/amount/amount.utils.ts
  projects/addon-commerce/pipes/amount/index.ts
  projects/addon-commerce/pipes/amount/ng-package.json
  projects/addon-commerce/pipes/currency/index.ts
  projects/addon-commerce/pipes/currency/ng-package.json
  projects/addon-commerce/pipes/format-card/index.ts
  projects/addon-commerce/pipes/format-card/ng-package.json
  projects/addon-commerce/pipes/index.ts
  projects/addon-commerce/tokens/index.ts
  projects/addon-commerce/tokens/payment-system-icons.ts
  projects/addon-commerce/types/card.ts
  projects/addon-commerce/types/code-length.ts
  projects/addon-commerce/types/index.ts
  projects/addon-commerce/utils/index.ts
  projects/addon-mobile/components/index.ts
  projects/addon-mobile/components/mobile-calendar-dialog/index.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.style.less
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.template.html
  projects/addon-mobile/components/mobile-calendar-dialog/ng-package.json
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.template.html
  projects/addon-mobile/components/mobile-calendar-sheet/index.ts
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.style.less
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.template.html
  projects/addon-mobile/components/mobile-calendar-sheet/ng-package.json
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
  projects/addon-mobile/directives/touchable/touchable.directive.ts
  projects/addon-mobile/index.ts
  projects/addon-mobile/internal/index.ts
  projects/addon-mobile/internal/primitive-calendar-mobile/index.ts
  projects/addon-mobile/internal/primitive-calendar-mobile/ng-package.json
  projects/addon-mobile/types/index.ts
  projects/addon-mobile/types/touch-mode.ts
  projects/addon-mobile/utils/find-touch-index.ts
  projects/addon-mobile/utils/index.ts
  projects/addon-table/components/table/directives/resized.directive.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/core/tokens/element-ref.ts
  projects/core/tokens/index.ts
  projects/demo/src/modules/components/input-card-grouped/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts
Labels: ready to merge

#7698 chore: cleanup before copy
  .github/workflows/auto-update-icons.yml
Labels: ready to merge

#7701 chore(demo): add `API` section for documentation page `Icon`
  projects/demo/src/modules/components/icon/index.html
  projects/demo/src/modules/components/icon/index.ts
Labels: ready to merge

#7700 fix(kit): round closable button
  projects/kit/components/push/push.template.html
Labels: ready to merge

#7705 fix(kit): `Carousel` fix scrolling with touchpad when itemsCount more than 1
  projects/kit/components/carousel/carousel.component.ts
Labels: ready to merge, v4

#7706 fix(kit): `Carousel` fix scrolling with touchpad when itemsCount more than 1
  projects/kit/components/carousel/carousel.component.ts
Labels: ready to merge, v3

#7708 chore(demo): improve documentation page `Flag`
  projects/addon-doc/components/documentation/documentation.template.html
  projects/demo/src/modules/pipes/flag/examples/1/index.html
  projects/demo/src/modules/pipes/flag/examples/1/index.ts
  projects/demo/src/modules/pipes/flag/examples/import/import.md
  projects/demo/src/modules/pipes/flag/index.html
  projects/demo/src/modules/pipes/flag/index.ts
Labels: ready to merge

#7713 chore(demo-playwright): delete legacy spec-files (temporary files for debug of screenshot testing)
  projects/demo-playwright/tests/example.spec.ts
  projects/demo-playwright/tests/nested-folder/nested-folder-example.spec.ts
Labels: ready to merge

#7714 refactor(legacy): `Svg` migrate to `Icon`
  projects/addon-doc/components/navigation/navigation.style.less
  projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
  projects/demo/src/modules/components/primitive-textfield/index.ts
  projects/legacy/components/arrow/arrow.component.ts
  projects/legacy/components/arrow/arrow.style.less
  projects/legacy/components/arrow/arrow.template.html
  projects/legacy/components/input-copy/input-copy.module.ts
  projects/legacy/components/input-copy/input-copy.style.less
  projects/legacy/components/input-copy/input-copy.template.html
  projects/legacy/components/input-date-multi/input-date-multi.module.ts
  projects/legacy/components/input-date-multi/input-date-multi.template.html
  projects/legacy/components/input-date-range/input-date-range.module.ts
  projects/legacy/components/input-date-range/input-date-range.style.less
  projects/legacy/components/input-date-range/input-date-range.template.html
  projects/legacy/components/input-date-time/input-date-time.module.ts
  projects/legacy/components/input-date-time/input-date-time.style.less
  projects/legacy/components/input-date-time/input-date-time.template.html
  projects/legacy/components/input-date/input-date.module.ts
  projects/legacy/components/input-date/input-date.style.less
  projects/legacy/components/input-date/input-date.template.html
  projects/legacy/components/input-month-range/input-month-range.module.ts
  projects/legacy/components/input-month/input-month.module.ts
  projects/legacy/components/input-password/input-password.module.ts
  projects/legacy/components/input-password/input-password.style.less
  projects/legacy/components/input-password/input-password.template.html
  projects/legacy/components/input-tag/input-tag.module.ts
  projects/legacy/components/input-tag/input-tag.style.less
  projects/legacy/components/input-tag/input-tag.template.html
  projects/legacy/components/input-time/input-time.module.ts
  projects/legacy/components/input-time/input-time.style.less
  projects/legacy/components/input-time/input-time.template.html
  projects/legacy/components/multi-select/multi-select.module.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.module.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.style.less
  projects/legacy/components/primitive-textfield/primitive-textfield.template.html
  projects/legacy/components/select-option/select-option.module.ts
  projects/legacy/components/select-option/select-option.style.less
  projects/legacy/components/select-option/select-option.template.html
  projects/legacy/components/tag/tag.module.ts
  projects/legacy/components/tag/tag.style.less
  projects/legacy/components/tag/tag.template.html
  projects/legacy/components/textarea/textarea.module.ts
  projects/legacy/components/textarea/textarea.style.less
  projects/legacy/components/textarea/textarea.template.html
  projects/legacy/styles/mixins/textfield.less
  projects/legacy/styles/wrapper/icon.less
  projects/testing/core/tag.harness.ts
Labels: ready to merge

#7658 refactor!: use `tui-icon` instead `tui-svg`
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/components/navigation/navigation.template.html
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.style.less
  projects/addon-mobile/components/tab-bar/tab-bar-item.template.html
  projects/addon-table/components/reorder/reorder.component.ts
  projects/addon-table/components/reorder/reorder.style.less
  projects/addon-table/components/reorder/reorder.template.html
  projects/addon-table/components/table-pagination/table-pagination.component.ts
  projects/addon-table/components/table-pagination/table-pagination.style.less
  projects/addon-table/components/table-pagination/table-pagination.template.html
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/components/table/th/th.style.less
  projects/addon-table/components/table/th/th.template.html
  projects/core/components/tooltip/tooltip.module.ts
  projects/core/components/tooltip/tooltip.style.less
  projects/core/components/tooltip/tooltip.template.html
  projects/icons/all.ts
  projects/icons/src/tuiIconDragOutline.svg
  projects/icons/src/tuiIconMastercardMonoOutline.svg
  projects/icons/src/tuiIconSortOffOutline.svg
  projects/legacy/components/combo-box/test/combo-box.component.spec.ts
Labels: ready to merge

#7666 refactor(kit): use `getCountries` from `libphonenumber-js` instead of `TUI_ALL_COUNTRIES_ISO_CODES`
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-all-country-iso-codes.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-all-country-iso-codes.spec.ts
  projects/demo/src/modules/components/input-phone-international/examples/2/index.ts
  projects/demo/src/modules/components/input-phone-international/index.ts
  projects/demo/src/modules/pipes/flag/index.ts
  projects/kit/components/input-phone-international/all-countries-iso-codes.ts
  projects/kit/components/input-phone-international/index.ts
Labels: ready to merge

#7737 fix(legacy): show native calendar for desktop
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/input-date.template.html
Labels: ready to merge, v4

#7735 chore: correct link
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge, v3

#7707 ci: update `renovate.json`
  .github/renovate.json
Labels: ready to merge

#7729 ci: update `deploy-gh-pages.yml` for upcoming 4.x release
  .github/workflows/deploy-gh-pages.yml
Labels: ready to merge

#7719 ci: prerender demo application for production
  .github/workflows/snapshots.yml
Labels: ready to merge

#7734 fix(kit): ignore native calendar for desktop
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.template.html
Labels: ready to merge, v3

#7694 chore: revert table declarations
  projects/addon-table/components/table/directives/cell.directive.ts
  projects/addon-table/components/table/directives/direction-order.directive.ts
  projects/addon-table/components/table/directives/head.directive.ts
  projects/addon-table/components/table/directives/resized.directive.ts
  projects/addon-table/components/table/directives/row.directive.ts
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/sortable.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/directives/thead.directive.ts
  projects/addon-table/components/table/pipes/table-sort.pipe.ts
  projects/addon-table/components/table/table.module.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/components/table/td/td.component.ts
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/demo/src/modules/pipes/field-error/examples/6/index.ts
Labels: ready to merge

#7748 chore(core): `Select` fix for ios
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.style.less
Labels: ready to merge

#7741 fix(cdk): visible control for `tui-scroll-controls` on iOS
  projects/cdk/components/scroll-controls/scroll-controls.component.ts
  projects/cdk/components/scroll-controls/scroll-controls.template.html
Labels: ready to merge, v3

#7744 fix(core)!: nested `Dropdown` no longer needs manual active zone
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/components/card-large/examples/7/index.html
  projects/demo/src/modules/components/cell/examples/6/index.html
  projects/demo/src/modules/components/data-list/examples/2/index.html
  projects/demo/src/modules/components/data-list/examples/2/index.ts
  projects/demo/src/modules/components/data-list/examples/5/index.html
  projects/demo/src/modules/components/data-list/examples/5/index.ts
  projects/demo/src/modules/components/data-list/index.html
  projects/demo/src/modules/components/input-date/examples/2/index.html
  projects/demo/src/modules/components/input-date/examples/2/index.ts
  projects/demo/src/modules/components/line-clamp/examples/4/index.html
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/components/tabs/examples/3/index.html
  projects/demo/src/modules/components/tabs/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-context/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-context/examples/import/template.md
  projects/demo/src/modules/directives/dropdown-hover/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-hover/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/1/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.less
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.ts
Labels: ready to merge

#7771 refactor: rename `TuiTouchableDirective` to `TuiTouchable`
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/directives/touchable/touchable.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/directives/touchable/examples/1/index.ts
  projects/demo/src/modules/directives/touchable/examples/import/import.md
Labels: ready to merge

#7766 refactor: rename `TuiZoomDirective` to `TuiZoom`
  projects/cdk/directives/zoom/zoom.directive.ts
  projects/cdk/directives/zoom/zoom.service.ts
  projects/cdk/directives/zoom/zoom.types.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo-cypress/src/tests/zoom.cy.ts
  projects/demo/src/modules/directives/zoom/examples/1/index.ts
  projects/demo/src/modules/directives/zoom/examples/import/import.md
  projects/kit/components/preview/preview.component.ts
Labels: ready to merge

#7763 refactor: rename `TuiRepeatTimesDirective` to `TuiRepeatTimes`
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
  projects/addon-charts/components/axes/axes.component.ts
  projects/addon-charts/components/pie-chart/pie-chart.component.ts
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar.component.ts
  projects/cdk/directives/repeat-times/repeat-times.directive.ts
  projects/cdk/directives/repeat-times/test/repeat-times.directive.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/calendar/calendar-sheet.component.ts
  projects/core/components/calendar/calendar-year.component.ts
  projects/demo/src/modules/app/landing/index.ts
  projects/demo/src/modules/components/badge/examples/1/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts
  projects/demo/src/modules/components/card-large/examples/4/index.ts
  projects/demo/src/modules/components/card-large/examples/5/index.ts
  projects/demo/src/modules/components/card-large/examples/6/index.ts
  projects/demo/src/modules/components/card-large/examples/7/index.ts
  projects/demo/src/modules/components/carousel/index.ts
  projects/demo/src/modules/components/chip/examples/3/index.ts
  projects/demo/src/modules/components/elastic-container/examples/3/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/progress-circle/examples/7/index.ts
  projects/demo/src/modules/components/surface/examples/5/index.ts
  projects/demo/src/modules/components/tag/examples/2/index.ts
  projects/kit/components/pagination/pagination.module.ts
  projects/kit/components/progress/progress.module.ts
  projects/kit/components/rating/rating.component.ts
Labels: ready to merge

#7762 refactor: rename `TuiCardMediumDirective` and `TuiCardLargeDirective` to `TuiCardMedium` and `TuiCardLarge`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-action.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-checkbox.spec.ts
  projects/demo/src/modules/components/card-large/examples/1/index.ts
  projects/demo/src/modules/components/card-large/examples/10/index.ts
  projects/demo/src/modules/components/card-large/examples/11/index.ts
  projects/demo/src/modules/components/card-large/examples/12/index.ts
  projects/demo/src/modules/components/card-large/examples/2/index.ts
  projects/demo/src/modules/components/card-large/examples/3/index.ts
  projects/demo/src/modules/components/card-large/examples/4/index.ts
  projects/demo/src/modules/components/card-large/examples/5/index.ts
  projects/demo/src/modules/components/card-large/examples/6/index.ts
  projects/demo/src/modules/components/card-large/examples/7/index.ts
  projects/demo/src/modules/components/card-large/examples/8/index.ts
  projects/demo/src/modules/components/card-large/examples/9/index.ts
  projects/demo/src/modules/components/card-large/examples/import/import.md
  projects/demo/src/modules/components/card-medium/examples/1/index.ts
  projects/demo/src/modules/components/card-medium/examples/2/index.ts
  projects/demo/src/modules/components/card-medium/examples/3/index.ts
  projects/demo/src/modules/components/card-medium/examples/4/index.ts
  projects/demo/src/modules/components/card-medium/examples/5/index.ts
  projects/demo/src/modules/components/card-medium/examples/6/index.ts
  projects/demo/src/modules/components/card-medium/examples/7/index.ts
  projects/demo/src/modules/components/card-medium/examples/import/import.md
  projects/demo/src/modules/components/cell/examples/7/index.html
  projects/demo/src/modules/components/cell/examples/7/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/island/examples/3/index.ts
  projects/demo/src/modules/components/range/examples/2/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/components/swipe-action/examples/1/index.ts
  projects/demo/src/modules/components/swipe-action/examples/3/index.ts
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
  projects/demo/src/modules/components/swipe-action/examples/5/index.ts
  projects/demo/src/modules/customization/variables/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/touchable/examples/1/index.ts
  projects/demo/src/modules/info/related/index.ts
  projects/layout/directives/card/card.directive.ts
Labels: ready to merge

#7778 refactor: rename `TuiSwipeDirective` to `TuiSwipe`
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/cdk/directives/swipe/swipe.directive.ts
  projects/cdk/directives/swipe/swipe.service.ts
  projects/cdk/directives/swipe/swipe.types.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo-cypress/src/tests/swipe.cy.ts
  projects/demo/src/modules/components/preview/examples/1/index.ts
  projects/demo/src/modules/components/preview/examples/2/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
  projects/demo/src/modules/directives/swipe/examples/1/index.ts
  projects/demo/src/modules/directives/swipe/examples/2/index.ts
  projects/demo/src/modules/directives/swipe/examples/import/import.md
  projects/kit/components/carousel/carousel.component.ts
Labels: ready to merge

#7772 refactor: rename `TuiRootComponent` to `TuiRoot`
  projects/addon-doc/components/main/main.component.ts
  projects/addon-mobile/components/mobile-dialog/test/mobile-dialog.component.spec.ts
  projects/cdk/schematics/ng-add/constants/modules.ts
  projects/cdk/schematics/ng-add/setup-project.ts
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/dialog/test/dialog.component.spec.ts
  projects/core/components/root/root.component.ts
  projects/core/components/root/test/root.component.spec.ts
  projects/core/directives/dropdown/test/dropdown.directive.spec.ts
  projects/core/directives/hint/test/hint.directive.spec.ts
  projects/demo-cypress/src/tests/hint.cy.ts
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
  projects/demo/src/modules/app/home/examples/app-standalone.md
  projects/demo/src/modules/info/related/index.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/components/pdf-viewer/test/pdf-viewer.component.spec.ts
  projects/kit/components/push/test/push.component.spec.ts
  projects/kit/pipes/field-error/test/field-error-content-pipe.spec.ts
  projects/legacy/components/combo-box/test/combo-box.component.spec.ts
  projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
  projects/legacy/components/input-date-time/test/input-date-time.component.spec.ts
  projects/legacy/components/input-date/test/input-date.component.spec.ts
  projects/legacy/components/input-month/test/input-month.component.spec.ts
  projects/legacy/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/legacy/components/input-phone/test/input-phone.component.spec.ts
  projects/legacy/components/input-slider/test/input-slider.component.spec.ts
  projects/legacy/components/input-tag/test/input-tag.component.spec.ts
  projects/legacy/components/input-time/test/input-time.component.spec.ts
  projects/legacy/components/input/test/input.component.spec.ts
  projects/legacy/components/multi-select/test/multi-select.component.spec.ts
  projects/legacy/components/select/test/select.component.spec.ts
Labels: ready to merge

#7777 refactor: rename `TuiLoaderComponent` to `TuiLoader`
  projects/addon-doc/components/example/example.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/expand/expand.component.ts
  projects/core/components/loader/loader.component.ts
  projects/core/components/loader/test/loader-options.spec.ts
  projects/core/components/loader/test/loader.component.spec.ts
  projects/demo/src/modules/app/stackblitz/starter/index.ts
  projects/demo/src/modules/components/carousel/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/4/index.ts
  projects/demo/src/modules/components/combo-box/examples/2/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/experimental/tooltip/examples/1/index.ts
  projects/demo/src/modules/components/loader/examples/1/index.ts
  projects/demo/src/modules/components/loader/examples/2/index.ts
  projects/demo/src/modules/components/loader/examples/3/index.ts
  projects/demo/src/modules/components/loader/examples/4/index.ts
  projects/demo/src/modules/components/loader/examples/5/index.ts
  projects/demo/src/modules/components/loader/examples/import/import.md
  projects/demo/src/modules/components/loader/index.ts
  projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content/index.ts
  projects/demo/src/modules/components/preview/examples/4/index.ts
  projects/demo/src/modules/components/select/examples/5/index.ts
  projects/demo/src/modules/components/table/examples/4/index.ts
  projects/demo/src/modules/components/tooltip/examples/1/index.ts
  projects/demo/src/modules/components/tree/examples/7/index.ts
  projects/kit/components/button-loading/button-loading.component.ts
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/kit/components/files/file/file.component.ts
  projects/legacy/components/tag/tag.module.ts
Labels: ready to merge

#7742 chore: pin alpha before publish
  package-lock.json
  package.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-table/package.json
  projects/cdk/package.json
  projects/core/package.json
  projects/experimental/package.json
  projects/i18n/package.json
  projects/icons/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/legacy/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge

#7783 refactor: rename `TuiTooltipModule` to `TuiTooltip`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/tooltip/tooltip.module.ts
  projects/demo/src/modules/components/block/examples/3/index.ts
  projects/demo/src/modules/components/tooltip/examples/1/index.ts
  projects/demo/src/modules/components/tooltip/examples/3/index.ts
  projects/demo/src/modules/components/tooltip/examples/4/index.ts
  projects/demo/src/modules/components/tooltip/index.ts
  projects/demo/src/modules/directives/hint-describe/examples/1/index.ts
  projects/legacy/components/input-tag/input-tag.module.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.module.ts
  projects/legacy/components/textarea/textarea.module.ts
Labels: ready to merge

#7751 fix(kit): `InputNumber` fix lost value
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge, v3

#7782 refactor: rename `TuiMobileCalendarComponent` to `TuiMobileCalendar`
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
  projects/demo/src/modules/components/input-date-multi/index.ts
  projects/demo/src/modules/components/input-date-range/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/3/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/import/import.md
  projects/demo/src/modules/components/mobile-calendar/index.ts
Labels: ready to merge

#7776 refactor: rename `TuiChipDirective` to `TuiChip`
  projects/addon-doc/components/page/page.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/chip/examples/1/index.ts
  projects/demo/src/modules/components/chip/examples/2/index.ts
  projects/demo/src/modules/components/chip/examples/3/index.ts
  projects/demo/src/modules/components/chip/examples/4/index.ts
  projects/demo/src/modules/components/chip/examples/import/import.md
  projects/demo/src/modules/components/items-with-more/examples/1/index.ts
  projects/demo/src/modules/components/items-with-more/index.ts
  projects/demo/src/modules/components/table/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/kit/components/chip/chip.directive.ts
Labels: ready to merge

#7784 refactor: rename `TuiPullToRefresh`, `TuiSwipeActions`, `TuiSwipeActionsAutoClose`
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/addon-mobile/components/swipe-action/swipe-actions.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/pull-to-refresh/examples/1/index.ts
  projects/demo/src/modules/components/pull-to-refresh/examples/2/index.ts
  projects/demo/src/modules/components/pull-to-refresh/examples/import/import.md
  projects/demo/src/modules/components/swipe-action/examples/1/index.ts
  projects/demo/src/modules/components/swipe-action/examples/2/index.ts
  projects/demo/src/modules/components/swipe-action/examples/3/index.ts
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
  projects/demo/src/modules/components/swipe-action/examples/5/index.ts
Labels: ready to merge

#7775 refactor: rename `TuiScrollIntoViewLinkDirective` to `TuiScrollIntoViewLink`
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/directives/scroll-into-view/scroll-into-view.directive.ts
  projects/cdk/schematics/ng-update/v3/constants/types.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#7774 refactor: rename `TuiPlatformDirective` to `TuiPlatform`
  projects/cdk/directives/platform/platform.directive.ts
  projects/cdk/tokens/environment.ts
  projects/cdk/types/index.ts
  projects/cdk/types/platform.ts
  projects/demo/src/modules/components/app-bar/examples/1/index.ts
  projects/demo/src/modules/components/app-bar/examples/3/index.ts
  projects/demo/src/modules/components/badge-notification/examples/1/index.ts
  projects/demo/src/modules/components/badge/examples/3/index.ts
  projects/demo/src/modules/components/block-status/examples/5/index.ts
  projects/demo/src/modules/components/card-large/examples/1/index.ts
  projects/demo/src/modules/components/card-large/examples/12/index.ts
  projects/demo/src/modules/components/card-large/examples/2/index.ts
  projects/demo/src/modules/components/checkbox/examples/1/index.ts
  projects/demo/src/modules/components/radio/examples/1/index.ts
  projects/demo/src/modules/components/radio/examples/2/index.ts
  projects/demo/src/modules/components/switch/examples/1/index.ts
  projects/experimental/components/tooltip/tooltip.options.ts
Labels: ready to merge

#7773 refactor: rename `TuiAutoFocusDirective` to `TuiAutoFocus`
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/dialog/dialog.module.ts
  projects/demo/src/modules/app/landing/index.ts
  projects/demo/src/modules/components/data-list/examples/4/custom-list/index.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/6/index.ts
  projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/icons/icons-group/icons-group.component.ts
  projects/demo/src/modules/components/input-inline/examples/2/index.ts
  projects/demo/src/modules/components/select/examples/3/index.ts
  projects/demo/src/modules/directives/auto-focus/examples/1/index.ts
  projects/demo/src/modules/directives/auto-focus/examples/import/import.md
  projects/kit/components/confirm/confirm.component.ts
Labels: ready to merge

#7770 refactor: rename `TuiRippleDirective` to `TuiRipple`
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/card-medium/examples/7/index.ts
  projects/demo/src/modules/directives/ripple/examples/1/index.ts
  projects/demo/src/modules/directives/ripple/examples/2/index.ts
  projects/demo/src/modules/directives/ripple/examples/import/import.md
Labels: ready to merge

#7765 refactor: rename `TuiAppearanceDirective` to `TuiAppearance`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/core/components/button/button.directive.ts
  projects/core/components/link/link.directive.ts
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/components/tooltip/tooltip.module.ts
  projects/core/directives/appearance/appearance.directive.ts
  projects/demo/src/modules/components/card-large/examples/3/index.ts
  projects/demo/src/modules/components/card-large/examples/7/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/experimental/tooltip/examples/3/index.ts
  projects/demo/src/modules/components/surface/examples/1/index.ts
  projects/demo/src/modules/directives/appearance/examples/1/index.ts
  projects/demo/src/modules/directives/appearance/examples/2/index.ts
  projects/demo/src/modules/directives/appearance/examples/3/index.ts
  projects/experimental/components/tooltip/tooltip.component.ts
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/badge/badge.directive.ts
  projects/kit/components/block/block.directive.ts
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/chip/chip.directive.ts
  projects/kit/components/files/file/file.component.ts
  projects/kit/components/files/input-files/input-files.directive.ts
  projects/kit/components/radio/radio.component.ts
  projects/kit/components/switch/switch.component.ts
  projects/legacy/components/input-copy/input-copy.module.ts
  projects/legacy/components/input-date-multi/input-date-multi.module.ts
  projects/legacy/components/input-date-range/input-date-range.module.ts
  projects/legacy/components/input-date-time/input-date-time.module.ts
  projects/legacy/components/input-date/input-date.module.ts
  projects/legacy/components/input-password/input-password.module.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-tag/input-tag.module.ts
  projects/legacy/components/input-time/input-time.module.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.module.ts
  projects/legacy/components/textarea/textarea.module.ts
Labels: ready to merge

#7792 refactor: rename `TuiUnmaskHandlerDirective` to `TuiUnmaskHandler`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/input/examples/3/index.ts
  projects/demo/src/modules/components/input/index.html
  projects/kit/directives/unmask-handler/unmask-handler.directive.ts
Labels: ready to merge

#7802 refactor: rename `TuiAxesComponent` to `TuiAxes`
  projects/addon-charts/components/axes/axes.component.ts
  projects/addon-charts/components/axes/test/axes.component.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/axes/examples/1/index.ts
  projects/demo/src/modules/components/axes/examples/2/index.ts
  projects/demo/src/modules/components/axes/examples/3/index.ts
  projects/demo/src/modules/components/axes/examples/import/import.md
  projects/demo/src/modules/components/axes/index.ts
  projects/demo/src/modules/components/bar-chart/examples/1/index.ts
  projects/demo/src/modules/components/bar-chart/examples/2/index.ts
  projects/demo/src/modules/components/line-chart/examples/1/index.ts
  projects/demo/src/modules/components/line-chart/examples/2/index.ts
  projects/demo/src/modules/components/line-chart/examples/3/index.ts
  projects/demo/src/modules/components/line-chart/examples/4/index.ts
  projects/demo/src/modules/components/line-chart/examples/5/index.ts
  projects/demo/src/modules/components/line-chart/index.ts
  projects/demo/src/modules/components/line-days-chart/examples/1/index.ts
  projects/demo/src/modules/components/line-days-chart/examples/2/index.ts
  projects/demo/src/modules/components/line-days-chart/index.ts
Labels: ready to merge

#7801 refactor: rename `TuiArcChartComponent` to `TuiArcChart`
  projects/addon-charts/components/arc-chart/arc-chart.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/arc-chart/examples/1/index.ts
  projects/demo/src/modules/components/arc-chart/examples/2/index.ts
  projects/demo/src/modules/components/arc-chart/examples/import/import.md
  projects/demo/src/modules/components/arc-chart/index.ts
Labels: ready to merge

#7798 refactor: rename `TuiDateFormatDirective` to `TuiDateFormat`
  projects/core/directives/date-format/date-format.directive.ts
  projects/demo/src/modules/directives/date-format/examples/1/index.ts
  projects/demo/src/modules/directives/date-format/examples/import/import.md
Labels: ready to merge

#7797 refactor: groupped inside TuiPreview
  projects/kit/components/preview/pagination/preview-pagination.component.ts
  projects/kit/components/preview/preview-action/preview-action.directive.ts
  projects/kit/components/preview/preview.component.ts
  projects/kit/components/preview/preview.module.ts
  projects/kit/components/preview/title/preview-title.component.ts
  projects/kit/components/preview/zoom/preview-zoom.component.ts
Labels: ready to merge

#7794 refactor: rename `TuiControlDirective` to `TuiNgControl`
  projects/cdk/directives/control/control.directive.ts
  projects/cdk/directives/control/test/control.directive.spec.ts
Labels: ready to merge

#7791 refactor: rename `TuiDataListDropdownManagerDirective` to `TuiDataListDropdownManager`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/data-list/examples/2/index.ts
  projects/demo/src/modules/components/data-list/examples/5/index.ts
  projects/demo/src/modules/components/data-list/index.html
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown-context/examples/2/index.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
Labels: ready to merge

#7769 refactor: rename `TuiActiveZoneDirective` to `TuiActiveZone`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-doc/components/internal/header/index.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/sidebar/sidebar.module.ts
  projects/cdk/directives/active-zone/active-zone.directive.ts
  projects/cdk/directives/active-zone/tests/active-zone.directive.spec.ts
  projects/cdk/directives/obscured/obscured.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/directives/dropdown/dropdown-context.directive.ts
  projects/core/directives/dropdown/dropdown-hover.directive.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/directives/hint/hints.component.ts
  projects/core/types/portal-item.ts
  projects/demo/src/modules/directives/active-zone/examples/1/index.ts
  projects/demo/src/modules/directives/active-zone/examples/import/import.md
  projects/demo/src/modules/directives/dropdown/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown/index.ts
  projects/demo/src/modules/directives/sidebar/examples/1/index.ts
  projects/demo/src/modules/directives/sidebar/examples/import/import.md
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-range/input-range.module.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/select/select.component.ts
Labels: ready to merge

#7747 chore(demo): new documentation for `InputPhoneInternational`
  projects/demo/src/modules/components/input-phone-international/examples/1/index.html
  projects/demo/src/modules/components/input-phone-international/examples/1/index.less
  projects/demo/src/modules/components/input-phone-international/examples/1/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/2/index.html
  projects/demo/src/modules/components/input-phone-international/examples/2/index.less
  projects/demo/src/modules/components/input-phone-international/examples/2/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/3/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/import/import-module.md
  projects/demo/src/modules/components/input-phone-international/examples/import/import.md
  projects/demo/src/modules/components/input-phone-international/examples/import/template.md
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/input-phone-international/index.ts
  projects/legacy/pipes/format-phone/format-phone.pipe.ts
Labels: ready to merge

#7809 fix(kit): `InputNumber` should emit form control change if value is less/more than `min`/`max`
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge, v3

#7796 refactor: rename `TuiHeaderDirective` to `TuiHeader`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/card-large/examples/1/index.ts
  projects/demo/src/modules/components/card-large/examples/10/index.ts
  projects/demo/src/modules/components/card-large/examples/11/index.ts
  projects/demo/src/modules/components/card-large/examples/12/index.ts
  projects/demo/src/modules/components/card-large/examples/2/index.ts
  projects/demo/src/modules/components/card-large/examples/3/index.ts
  projects/demo/src/modules/components/card-large/examples/4/index.ts
  projects/demo/src/modules/components/card-large/examples/5/index.ts
  projects/demo/src/modules/components/card-large/examples/6/index.ts
  projects/demo/src/modules/components/card-large/examples/7/index.ts
  projects/demo/src/modules/components/card-large/examples/8/index.ts
  projects/demo/src/modules/components/card-large/examples/9/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/sheet/examples/3/index.ts
  projects/demo/src/modules/directives/header/examples/1/index.ts
  projects/demo/src/modules/directives/header/examples/2/index.ts
  projects/demo/src/modules/directives/header/examples/3/index.ts
  projects/demo/src/modules/directives/header/examples/import/import-module.md
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/layout/directives/header/header.directive.ts
Labels: ready to merge

#7806 feat(kit): `Avatar` add colored icons mode
  projects/demo/src/modules/components/avatar/examples/1/index.html
  projects/demo/src/modules/components/avatar/examples/1/index.less
  projects/demo/src/modules/components/avatar/examples/1/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/avatar/avatar.style.less
Labels: ready to merge

#7795 refactor: rename `TuiTitleDirective` to `TuiTitle`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/directives/title/title.directive.ts
  projects/demo/src/modules/components/app-bar/examples/1/index.ts
  projects/demo/src/modules/components/app-bar/examples/2/index.ts
  projects/demo/src/modules/components/app-bar/examples/3/index.ts
  projects/demo/src/modules/components/block-details/examples/1/index.ts
  projects/demo/src/modules/components/block-details/examples/2/index.ts
  projects/demo/src/modules/components/block/examples/3/index.ts
  projects/demo/src/modules/components/card-large/examples/11/index.ts
  projects/demo/src/modules/components/card-large/examples/3/index.ts
  projects/demo/src/modules/components/card-large/examples/6/index.ts
  projects/demo/src/modules/components/card-large/examples/8/index.ts
  projects/demo/src/modules/components/card-medium/examples/1/index.ts
  projects/demo/src/modules/components/card-medium/examples/2/index.ts
  projects/demo/src/modules/components/card-medium/examples/3/index.ts
  projects/demo/src/modules/components/card-medium/examples/4/index.ts
  projects/demo/src/modules/components/card-medium/examples/5/index.ts
  projects/demo/src/modules/components/card-medium/examples/6/index.ts
  projects/demo/src/modules/components/cell/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/5/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/group/examples/4/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts
  projects/demo/src/modules/components/label/examples/1/index.ts
  projects/demo/src/modules/components/radio/examples/3/index.ts
  projects/demo/src/modules/components/select/examples/7/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.ts
  projects/demo/src/modules/components/sheet-dialog/index.ts
  projects/demo/src/modules/components/sheet/examples/3/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/components/swipe-action/examples/1/index.ts
  projects/demo/src/modules/components/swipe-action/examples/2/index.ts
  projects/demo/src/modules/components/swipe-action/examples/3/index.ts
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
  projects/demo/src/modules/components/swipe-action/examples/5/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
  projects/demo/src/modules/directives/header/examples/1/index.ts
  projects/demo/src/modules/directives/header/examples/2/index.ts
  projects/demo/src/modules/directives/header/examples/3/index.ts
  projects/demo/src/modules/directives/progress-segmented/examples/4/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/title/examples/1/index.ts
  projects/demo/src/modules/directives/title/examples/2/index.ts
  projects/demo/src/modules/directives/title/examples/3/index.ts
  projects/demo/src/modules/directives/title/examples/import/import.md
Labels: ready to merge

#7811 fix(legacy): `InputNumber` has change detection problems when value is less/more than `min`/`max`
  projects/demo-playwright/tests/kit/input-number/input-number.spec.ts
  projects/demo/src/modules/components/input-number/examples/8/index.html
  projects/demo/src/modules/components/input-number/examples/8/index.ts
  projects/demo/src/modules/components/input-number/index.html
  projects/legacy/components/input-number/input-number.component.ts
Labels: ready to merge

#7816 chore: fix avatar example
  projects/demo/src/modules/components/avatar/examples/1/index.ts
Labels: ready to merge

#7815 chore: do not run prettier for all packages
  .github/workflows/auto-update-icons.yml
Labels: ready to merge

#7790 refactor: use only `TuiTextfield`
  projects/addon-doc/components/documentation/documentation.component.ts
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/core/components/label/label.directive.ts
  projects/core/components/textfield/index.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.module.ts
  projects/core/components/textfield/textfield.ts
  projects/demo/src/modules/components/badge-notification/index.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/9/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/error/examples/1/index.ts
  projects/demo/src/modules/components/experimental/tooltip/examples/2/index.ts
  projects/demo/src/modules/components/input-phone-international/index.ts
  projects/demo/src/modules/components/input/examples/2/index.ts
  projects/demo/src/modules/components/input/examples/5/index.ts
  projects/demo/src/modules/components/input/examples/6/index.ts
  projects/demo/src/modules/components/input/examples/9/index.ts
  projects/demo/src/modules/components/input/index.ts
  projects/demo/src/modules/components/label/examples/1/index.ts
  projects/demo/src/modules/components/label/examples/2/index.ts
  projects/demo/src/modules/components/label/examples/3/index.ts
  projects/demo/src/modules/components/radio/examples/2/index.ts
  projects/demo/src/modules/components/sheet/examples/6/index.ts
  projects/demo/src/modules/components/tab-bar/index.ts
  projects/demo/src/modules/components/textarea/examples/3/index.ts
  projects/demo/src/modules/components/textarea/examples/4/index.ts
  projects/demo/src/modules/components/tooltip/examples/3/index.ts
  projects/demo/src/modules/components/tree/examples/6/index.ts
  projects/demo/src/modules/customization/variables/examples/1/index.ts
  projects/demo/src/modules/customization/wrapper/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
  projects/demo/src/modules/directives/sensitive/examples/1/index.ts
  projects/demo/src/modules/directives/sensitive/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/skeleton/examples/2/index.ts
  projects/demo/src/modules/directives/textfield-controller/examples/1/index.ts
  projects/demo/src/modules/directives/textfield-controller/index.ts
  projects/demo/src/modules/markup/form/examples/1/index.ts
  projects/demo/src/modules/pipes/field-error/examples/1/index.ts
  projects/demo/src/modules/pipes/field-error/examples/2/index.ts
  projects/demo/src/modules/pipes/field-error/examples/3/index.ts
  projects/demo/src/modules/pipes/field-error/examples/4/index.ts
Labels: ready to merge

#7817 refactor: use only `TuiHint`
  projects/core/components/tooltip/tooltip.module.ts
  projects/core/directives/hint/hint-describe.directive.ts
  projects/core/directives/hint/hint-host.directive.ts
  projects/core/directives/hint/hint-manual.directive.ts
  projects/core/directives/hint/hint-options.directive.ts
  projects/core/directives/hint/hint-pointer.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.module.ts
  projects/core/directives/hint/hint.ts
  projects/core/directives/hint/index.ts
  projects/demo/src/modules/components/dialog/examples/9/index.ts
  projects/demo/src/modules/components/group/examples/1/index.ts
  projects/demo/src/modules/components/input-date-multi/index.ts
  projects/demo/src/modules/components/input-date-range/index.ts
  projects/demo/src/modules/components/input-date-time/index.ts
  projects/demo/src/modules/components/input-month-range/index.ts
  projects/demo/src/modules/components/input-number/examples/1/index.ts
  projects/demo/src/modules/components/input-number/examples/4/index.ts
  projects/demo/src/modules/components/input-number/index.ts
  projects/demo/src/modules/components/input-password/examples/2/index.ts
  projects/demo/src/modules/components/input-password/index.ts
  projects/demo/src/modules/components/input-phone/index.ts
  projects/demo/src/modules/components/input-slider/examples/1/index.ts
  projects/demo/src/modules/components/input-slider/examples/4/index.ts
  projects/demo/src/modules/components/input-slider/index.ts
  projects/demo/src/modules/components/input-tag/examples/5/index.ts
  projects/demo/src/modules/components/input-tag/examples/6/index.ts
  projects/demo/src/modules/components/input-tag/index.ts
  projects/demo/src/modules/components/input-time/index.ts
  projects/demo/src/modules/components/multi-select/examples/10/index.ts
  projects/demo/src/modules/components/multi-select/index.ts
  projects/demo/src/modules/components/primitive-textfield/examples/2/index.ts
  projects/demo/src/modules/components/primitive-textfield/index.ts
  projects/demo/src/modules/components/select/index.ts
  projects/demo/src/modules/components/textarea/examples/4/index.ts
  projects/demo/src/modules/components/textarea/examples/6/index.ts
  projects/demo/src/modules/components/textarea/index.ts
  projects/demo/src/modules/directives/hint-describe/examples/1/index.ts
  projects/demo/src/modules/directives/hint-describe/index.ts
  projects/demo/src/modules/directives/hint-manual/examples/1/index.ts
  projects/demo/src/modules/directives/hint-manual/index.ts
  projects/demo/src/modules/directives/hint-pointer/index.ts
  projects/experimental/components/tooltip/tooltip.module.ts
  projects/kit/components/preview/preview.module.ts
  projects/legacy/components/input-copy/input-copy.module.ts
  projects/legacy/components/input-password/input-password.module.ts
Labels: ready to merge

#7788 refactor: rename `TuiScrollbarComponent` to `TuiScrollbar`
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/core/components/calendar/calendar.component.ts
  projects/core/components/dialog/dialogs.component.ts
  projects/core/components/root/root.component.ts
  projects/core/components/scrollbar/scroll-controls.component.ts
  projects/core/components/scrollbar/scroll-ref.directive.ts
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/demo/src/modules/components/combo-box/examples/5/index.ts
  projects/demo/src/modules/components/multi-select/examples/7/index.ts
  projects/demo/src/modules/components/pull-to-refresh/index.ts
  projects/demo/src/modules/components/scrollbar/examples/1/index.ts
  projects/demo/src/modules/components/scrollbar/examples/2/index.ts
  projects/demo/src/modules/components/scrollbar/examples/3/index.ts
  projects/demo/src/modules/components/scrollbar/examples/4/index.ts
  projects/demo/src/modules/components/scrollbar/examples/5/index.ts
  projects/demo/src/modules/components/scrollbar/examples/6/index.ts
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/components/services/scroll-service/examples/1/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/components/table/examples/3/index.ts
  projects/demo/src/modules/components/table/examples/5/index.ts
  projects/demo/src/modules/components/tabs/examples/7/index.ts
  projects/demo/src/modules/directives/elastic-sticky/examples/1/index.ts
  projects/demo/src/modules/directives/fade/examples/1/index.ts
  projects/demo/src/modules/directives/fade/examples/3/index.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/kit/components/calendar-month/calendar-month.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-tag/input-tag.module.ts
  projects/legacy/components/input-year/input-year.module.ts
  projects/legacy/components/sheet/sheet.module.ts
  projects/legacy/components/textarea/textarea.module.ts
Labels: ready to merge

#7823 refactor: rename `TuiChevronDirective` to `TuiChevron`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-doc/components/demo/index.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-links.spec.ts
  projects/demo/src/modules/components/data-list/examples/1/index.ts
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/data-list/examples/6/index.ts
  projects/demo/src/modules/components/elastic-container/examples/4/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/components/table/examples/4/index.ts
  projects/demo/src/modules/components/tabs/examples/3/index.ts
  projects/demo/src/modules/components/textfield/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown/examples/1/index.ts
  projects/kit/components/accordion/accordion-item.component.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/kit/directives/chevron/chevron.directive.ts
Labels: ready to merge

#7818 chore: drop comment
  projects/core/components/textfield/index.ts
Labels: ready to merge

#7829 refactor: use only `TuiDataList`
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.module.ts
  projects/core/components/data-list/opt-group.directive.ts
  projects/core/components/data-list/option.component.ts
  projects/demo/src/modules/app/version-manager/version-manager.component.ts
  projects/demo/src/modules/components/data-list/examples/1/index.ts
  projects/demo/src/modules/components/data-list/examples/2/index.ts
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/data-list/examples/4/custom-list/index.ts
  projects/demo/src/modules/components/data-list/examples/4/index.ts
  projects/demo/src/modules/components/data-list/examples/5/index.ts
  projects/demo/src/modules/components/data-list/examples/6/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/input-phone/examples/3/index.ts
  projects/demo/src/modules/components/input-tag/examples/2/index.ts
  projects/demo/src/modules/components/input-tag/examples/4/index.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.ts
  projects/demo/src/modules/components/line-clamp/examples/4/index.ts
  projects/demo/src/modules/components/multi-select/examples/1/index.ts
  projects/demo/src/modules/components/multi-select/examples/11/index.ts
  projects/demo/src/modules/components/multi-select/examples/2/index.ts
  projects/demo/src/modules/components/multi-select/examples/3/index.ts
  projects/demo/src/modules/components/multi-select/examples/4/index.ts
  projects/demo/src/modules/components/multi-select/examples/5/index.ts
  projects/demo/src/modules/components/multi-select/examples/6/index.ts
  projects/demo/src/modules/components/multi-select/examples/7/index.ts
  projects/demo/src/modules/components/multi-select/examples/8/index.ts
  projects/demo/src/modules/components/multi-select/examples/9/index.ts
  projects/demo/src/modules/components/multi-select/index.ts
  projects/demo/src/modules/components/select/examples/1/index.ts
  projects/demo/src/modules/components/select/examples/10/index.ts
  projects/demo/src/modules/components/select/examples/2/index.ts
  projects/demo/src/modules/components/select/examples/3/index.ts
  projects/demo/src/modules/components/select/examples/4/index.ts
  projects/demo/src/modules/components/select/examples/5/index.ts
  projects/demo/src/modules/components/select/examples/6/index.ts
  projects/demo/src/modules/components/select/examples/7/index.ts
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/components/select/examples/9/index.ts
  projects/demo/src/modules/components/select/index.ts
  projects/demo/src/modules/components/swipe-action/examples/5/index.ts
  projects/demo/src/modules/components/tabs/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-context/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.ts
  projects/demo/src/modules/pipes/emails/examples/1/index.ts
  projects/demo/src/modules/pipes/emails/examples/import/import.md
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.module.ts
  projects/legacy/components/input-time/input-time.module.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.component.ts
  projects/legacy/components/multi-select/multi-select.module.ts
  projects/legacy/components/select-option/select-option.component.ts
  projects/legacy/components/select/select.module.ts
Labels: ready to merge

#7827 refactor: rename `TuiSwitchComponent` to `TuiSwitch`
  projects/addon-doc/components/demo/index.ts
  projects/addon-doc/components/documentation/documentation.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-toggle.spec.ts
  projects/demo/src/modules/components/block/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/2/index.ts
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/error/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/input-time/examples/5/index.ts
  projects/demo/src/modules/components/island/examples/2/index.ts
  projects/demo/src/modules/components/label/examples/3/index.ts
  projects/demo/src/modules/components/swipe-action/examples/2/index.ts
  projects/demo/src/modules/components/switch/examples/1/index.ts
  projects/demo/src/modules/components/switch/examples/2/index.ts
  projects/demo/src/modules/components/switch/examples/import/import.md
  projects/demo/src/modules/components/table-filters/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown/examples/2/index.ts
  projects/demo/src/modules/directives/dropdown/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
  projects/demo/src/modules/directives/sensitive/examples/1/index.ts
  projects/demo/src/modules/directives/sensitive/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/skeleton/examples/2/index.ts
  projects/demo/src/modules/directives/theme/examples/1/index.ts
  projects/kit/components/switch/switch.component.ts
Labels: ready to merge

#7832 refactor: rename `TuiItemDirective` to `TuiItem`
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/page/page.component.ts
  projects/cdk/directives/item/item.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/breadcrumbs/examples/1/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/import/import.md
  projects/demo/src/modules/components/breadcrumbs/index.ts
  projects/demo/src/modules/components/carousel/examples/1/index.ts
  projects/demo/src/modules/components/carousel/examples/2/index.ts
  projects/demo/src/modules/components/carousel/examples/3/index.ts
  projects/demo/src/modules/components/carousel/examples/4/index.ts
  projects/demo/src/modules/components/carousel/examples/5/index.ts
  projects/demo/src/modules/components/carousel/examples/import/import.md
  projects/demo/src/modules/components/carousel/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/input-files/examples/3/index.ts
  projects/demo/src/modules/components/input-files/examples/4/index.ts
  projects/demo/src/modules/components/input-files/index.ts
  projects/demo/src/modules/components/items-with-more/examples/1/index.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.ts
  projects/demo/src/modules/components/items-with-more/index.ts
  projects/demo/src/modules/components/tabs/examples/2/index.ts
  projects/demo/src/modules/components/tabs/examples/3/index.ts
  projects/demo/src/modules/components/tabs/examples/5/index.ts
  projects/demo/src/modules/components/tabs/index.ts
  projects/kit/components/breadcrumbs/breadcrumbs.component.ts
  projects/kit/components/breadcrumbs/test/breadcrumbs.component.spec.ts
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/files/files.module.ts
  projects/kit/components/files/files/files.component.ts
  projects/kit/components/items-with-more/items-with-more.component.ts
  projects/kit/components/items-with-more/items-with-more.module.ts
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/kit/components/tabs/tabs.module.ts
Labels: ready to merge

#7830 refactor: rename `TuiElementDirective` to `TuiElement`
  projects/cdk/directives/element/element.directive.ts
  projects/cdk/directives/resizer/resizeable.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/services/scroll-service/examples/1/index.ts
  projects/demo/src/modules/directives/element/examples/1/index.ts
  projects/demo/src/modules/directives/element/examples/import/import.md
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
Labels: ready to merge

#7821 refactor: drop some postfixes
  projects/addon-charts/components/bar-chart/bar-chart.component.ts
  projects/addon-charts/components/line-chart/line-chart.component.ts
  projects/core/components/root/root.component.ts
  projects/core/directives/hint/hint-driver.directive.ts
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint-manual.directive.ts
  projects/core/directives/hint/hint-pointer.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint-unstyled.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/core/directives/hint/hint.ts
  projects/core/directives/hint/hints.component.ts
  projects/core/directives/tooltip/tooltip.directive.ts
  projects/legacy/components/tooltip/tooltip.component.ts
Labels: ready to merge

#7842 refactor: rename `TuiAlertComponent` to `TuiAlert`
  projects/core/components/alert/alert.component.ts
  projects/core/components/alert/alert.service.ts
  projects/core/components/alert/alerts.component.ts
  projects/core/components/root/root.component.ts
Labels: ready to merge

#7828 refactor: rename `TuiNumberFormatDirective` to `TuiNumberFormat`
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
  projects/core/directives/number-format/number-format.directive.ts
  projects/demo/src/modules/components/abstract/number-format-documentation/index.html
  projects/demo/src/modules/components/dialog/examples/4/index.ts
  projects/demo/src/modules/components/input-number/examples/3/index.ts
  projects/demo/src/modules/components/input-number/examples/5/index.ts
  projects/demo/src/modules/components/input-number/index.ts
  projects/demo/src/modules/components/input-range/index.ts
  projects/demo/src/modules/components/input-slider/index.ts
  projects/demo/src/modules/components/select/examples/9/account/index.ts
  projects/demo/src/modules/components/utils/math/examples/1/index.ts
  projects/demo/src/modules/directives/number-format/examples/1/index.ts
  projects/demo/src/modules/directives/number-format/examples/import/import.md
  projects/demo/src/modules/pipes/amount/examples/2/index.ts
  projects/legacy/components/input-number/test/input-number-format.spec.ts
  projects/legacy/components/input-number/test/input-number.component.spec.ts
  projects/legacy/components/input-range/input-range.module.ts
  projects/legacy/components/input-slider/input-slider.module.ts
Labels: ready to merge

#7836 refactor: rename `TuiBlockDirective` to `TuiBlock`
  projects/demo/src/modules/components/block/examples/1/index.ts
  projects/demo/src/modules/components/block/examples/2/index.ts
  projects/demo/src/modules/components/block/examples/3/index.ts
  projects/demo/src/modules/components/block/examples/import/import.md
  projects/demo/src/modules/components/group/examples/3/index.ts
  projects/demo/src/modules/components/group/examples/4/index.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.ts
  projects/demo/src/modules/markup/form/examples/1/index.ts
  projects/kit/components/block/block.directive.ts
  projects/kit/components/filter/filter.component.ts
Labels: ready to merge

#7839 refactor: rename `TuiBadgeDirective` to `TuiBadge`
  projects/addon-doc/components/documentation/documentation.component.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badge.spec.ts
  projects/demo/src/modules/components/badge-notification/examples/1/index.ts
  projects/demo/src/modules/components/badge-notification/examples/2/index.ts
  projects/demo/src/modules/components/badge-notification/index.ts
  projects/demo/src/modules/components/badge/examples/1/index.ts
  projects/demo/src/modules/components/badge/examples/2/index.ts
  projects/demo/src/modules/components/badge/examples/3/index.ts
  projects/demo/src/modules/components/badge/examples/4/index.ts
  projects/demo/src/modules/components/badge/examples/5/index.ts
  projects/demo/src/modules/components/badge/examples/6/index.ts
  projects/demo/src/modules/components/badge/index.ts
  projects/demo/src/modules/components/badged-content/examples/1/index.ts
  projects/demo/src/modules/components/badged-content/examples/2/index.ts
  projects/demo/src/modules/components/badged-content/examples/3/index.ts
  projects/demo/src/modules/components/badged-content/index.ts
  projects/demo/src/modules/components/block-details/examples/1/index.ts
  projects/demo/src/modules/components/block-details/examples/2/index.ts
  projects/demo/src/modules/components/card-medium/examples/3/index.ts
  projects/demo/src/modules/components/card-medium/examples/5/index.ts
  projects/demo/src/modules/components/cell/examples/2/index.ts
  projects/demo/src/modules/components/cell/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/4/index.ts
  projects/demo/src/modules/components/cell/examples/5/index.ts
  projects/demo/src/modules/components/chip/examples/4/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/icons/icons-group/icons-group.component.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.ts
  projects/demo/src/modules/components/segmented/examples/1/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/directives/header/examples/1/index.ts
  projects/demo/src/modules/directives/header/examples/2/index.ts
  projects/demo/src/modules/directives/hint/examples/3/index.ts
  projects/demo/src/modules/directives/let/examples/1/index.ts
  projects/demo/src/modules/directives/let/examples/2/index.ts
  projects/demo/src/modules/directives/present/examples/1/index.ts
  projects/demo/src/modules/directives/sensitive/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/kit/components/badge-notification/badge-notification.component.ts
  projects/kit/components/badge/badge.directive.ts
  projects/kit/components/badged-content/badge-content.ts
  projects/kit/components/badged-content/index.ts
  projects/kit/components/filter/filter.component.ts
Labels: ready to merge

#7850 refactor: use `TuiFiles`
  projects/demo/src/modules/components/input-files/examples/1/index.ts
  projects/demo/src/modules/components/input-files/examples/2/index.ts
  projects/demo/src/modules/components/input-files/examples/3/index.ts
  projects/demo/src/modules/components/input-files/examples/4/index.ts
  projects/demo/src/modules/components/input-files/examples/5/index.ts
  projects/demo/src/modules/components/input-files/examples/6/index.ts
  projects/demo/src/modules/components/input-files/examples/7/index.ts
  projects/demo/src/modules/components/input-files/index.ts
  projects/kit/components/files/file/file.component.ts
  projects/kit/components/files/files.module.ts
  projects/kit/components/files/files.ts
  projects/kit/components/files/index.ts
  projects/kit/components/files/input-files/input-files-validator.directive.ts
  projects/kit/components/files/input-files/input-files.component.ts
  projects/kit/components/files/input-files/input-files.content.ts
  projects/kit/components/files/input-files/input-files.directive.ts
Labels: ready to merge

#7844 refactor: use `TuiItemsWithMore`
  projects/demo/src/modules/components/items-with-more/examples/1/index.ts
  projects/demo/src/modules/components/items-with-more/examples/2/index.ts
  projects/demo/src/modules/components/items-with-more/index.ts
  projects/kit/components/items-with-more/index.ts
  projects/kit/components/items-with-more/items-with-more.component.ts
  projects/kit/components/items-with-more/items-with-more.module.ts
  projects/kit/components/items-with-more/items-with-more.ts
  projects/kit/components/items-with-more/more.directive.ts
Labels: ready to merge

#7854 refactor: drop accordion module
  projects/kit/components/accordion/accordion-item-content.directive.ts
  projects/kit/components/accordion/accordion-item-eager-content.directive.ts
  projects/kit/components/accordion/accordion-item.component.ts
  projects/kit/components/accordion/accordion.directive.ts
  projects/kit/components/accordion/accordion.module.ts
  projects/kit/components/accordion/accordion.ts
  projects/kit/components/accordion/index.ts
  projects/kit/components/accordion/test/accordion.component.spec.ts
Labels: ready to merge

#7851 refactor: use `TuiTree`
  projects/demo/src/modules/components/tree/examples/5/content.ts
  projects/kit/components/tree/components/tree-item-content/tree-item-content.component.ts
  projects/kit/components/tree/components/tree-item/tree-item.component.ts
  projects/kit/components/tree/components/tree/tree.component.ts
  projects/kit/components/tree/directives/tree-children.directive.ts
  projects/kit/components/tree/directives/tree-controller.directive.ts
  projects/kit/components/tree/directives/tree-item-controller.directive.ts
  projects/kit/components/tree/directives/tree-node.directive.ts
  projects/kit/components/tree/index.ts
  projects/kit/components/tree/misc/tree.constants.ts
  projects/kit/components/tree/misc/tree.interfaces.ts
  projects/kit/components/tree/tree.module.ts
  projects/kit/components/tree/tree.ts
Labels: ready to merge

#7857 refactor(addon-commerce): use deep entry points for imports of other Taiga packages
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.options.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/addon-commerce/components/input-card/input-card.options.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
  projects/addon-commerce/constants/default-card-validator.ts
  projects/addon-commerce/constants/mask-card.ts
  projects/addon-commerce/constants/mask-cvc.ts
  projects/addon-commerce/pipes/amount/amount.options.ts
  projects/addon-commerce/pipes/amount/amount.pipe.ts
  projects/addon-commerce/pipes/amount/amount.types.ts
  projects/addon-commerce/pipes/amount/amount.utils.ts
  projects/addon-commerce/tokens/i18n.ts
  projects/addon-commerce/tokens/payment-system-icons.ts
  projects/addon-commerce/utils/format-currency.ts
  projects/addon-commerce/utils/is-card-number-valid.ts
  projects/addon-commerce/utils/is-expire-valid.ts
  projects/addon-commerce/validators/card-expire.validator.ts
  projects/addon-commerce/validators/card-number.validator.ts
  projects/addon-commerce/validators/luhn.validator.ts
Labels: ready to merge

#7865 refactor(addon-mobile): use deep entry points for imports of other Taiga packages
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.const.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.options.ts
  projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.directive.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.service.ts
  projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts
  projects/addon-mobile/components/tab-bar/tab-bar.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/addon-mobile/directives/sidebar/sidebar.component.ts
  projects/addon-mobile/directives/sidebar/sidebar.directive.ts
  projects/addon-mobile/directives/touchable/touchable.directive.ts
  projects/addon-mobile/services/keyboard.service.ts
Labels: ready to merge

#7869 refactor: drop expand module
  projects/core/components/expand/expand.module.ts
  projects/core/components/expand/expand.ts
  projects/core/components/expand/index.ts
Labels: ready to merge

#7855 refactor: cleanup addon-doc
  projects/addon-doc/README.md
  projects/addon-doc/addon-doc.module.ts
  projects/addon-doc/components/internal/header/index.ts
  projects/addon-doc/components/internal/see-also/index.ts
  projects/addon-doc/components/internal/source-code/source-code.component.ts
  projects/addon-doc/components/language-switcher/index.ts
  projects/addon-doc/components/language-switcher/tests/language-switcher.component.spec.ts
  projects/addon-doc/components/main/main.component.ts
  projects/addon-doc/components/page/page.component.ts
  projects/addon-doc/index.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/customization/i18n/index.ts
  projects/i18n/switch/language-switcher.providers.ts
  projects/i18n/switch/language-switcher.service.ts
Labels: ready to merge

#7867 refactor(addon-table): use deep entry points for imports of other Taiga packages
  projects/addon-table/components/reorder/reorder.component.ts
  projects/addon-table/components/reorder/reorder.options.ts
  projects/addon-table/components/table-pagination/table-pagination.component.ts
  projects/addon-table/components/table-pagination/table-pagination.options.ts
  projects/addon-table/components/table/directives/resized.directive.ts
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/stuck.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/pipes/table-sort.pipe.ts
  projects/addon-table/components/table/providers/table.provider.ts
  projects/addon-table/components/table/table.options.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/addon-table/directives/table-filters/generic-filter.directive.ts
  projects/addon-table/directives/table-filters/table-filter.directive.ts
  projects/addon-table/tokens/i18n.ts
  projects/addon-table/types/row-context.ts
Labels: ready to merge

#7848 refactor: use `TuiPin`, `TuiPulse`
  projects/demo/src/modules/components/compass/examples/1/index.ts
  projects/demo/src/modules/components/compass/examples/2/index.ts
  projects/demo/src/modules/components/compass/examples/import/import.md
  projects/demo/src/modules/components/compass/index.ts
  projects/demo/src/modules/components/pin/examples/1/index.ts
  projects/demo/src/modules/components/pin/examples/2/index.ts
  projects/demo/src/modules/components/pin/examples/3/index.ts
  projects/demo/src/modules/components/pin/examples/import/import.md
  projects/demo/src/modules/components/pulse/examples/1/index.ts
  projects/demo/src/modules/components/pulse/examples/import/import.md
  projects/kit/components/compass/compass.component.ts
  projects/kit/components/pin/pin.component.ts
  projects/kit/components/pulse/pulse.component.ts
Labels: ready to merge

#7873 refactor(experimental,layout,testing): use deep entry points for imports of other Taiga packages
  projects/experimental/components/navigation/aside.component.ts
  projects/experimental/components/navigation/header.component.ts
  projects/experimental/components/navigation/hint-aside.directive.ts
  projects/experimental/components/navigation/nav.component.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/layout/components/app-bar/app-bar.component.ts
  projects/layout/components/app-bar/app-bar.providers.ts
  projects/layout/directives/block-details/block-details.directive.ts
  projects/layout/directives/card/card.directive.ts
  projects/layout/directives/cell/cell.directive.ts
  projects/layout/directives/header/header.directive.ts
  projects/testing/core/island.harness.ts
  projects/testing/mocks/sanitizer.ts
  projects/testing/utils/date.ts
  projects/testing/utils/replace-nbsp.ts
Labels: ready to merge

#7846 refactor: use `TuiRadio`
  projects/demo/src/modules/components/badge/index.ts
  projects/demo/src/modules/components/block/examples/1/index.ts
  projects/demo/src/modules/components/block/examples/2/index.ts
  projects/demo/src/modules/components/block/examples/3/index.ts
  projects/demo/src/modules/components/block/examples/import/import.md
  projects/demo/src/modules/components/cell/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/4/index.ts
  projects/demo/src/modules/components/checkbox/examples/1/index.ts
  projects/demo/src/modules/components/checkbox/examples/2/index.ts
  projects/demo/src/modules/components/checkbox/examples/import/import.md
  projects/demo/src/modules/components/chip/examples/3/index.ts
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/group/examples/3/index.ts
  projects/demo/src/modules/components/group/examples/4/index.ts
  projects/demo/src/modules/components/input-card/examples/2/index.ts
  projects/demo/src/modules/components/label/examples/1/index.ts
  projects/demo/src/modules/components/label/examples/2/index.ts
  projects/demo/src/modules/components/label/examples/import/import.md
  projects/demo/src/modules/components/legend-item/examples/2/index.ts
  projects/demo/src/modules/components/radio/examples/1/index.ts
  projects/demo/src/modules/components/radio/examples/2/index.ts
  projects/demo/src/modules/components/radio/examples/3/index.ts
  projects/demo/src/modules/components/radio/examples/import/import.md
  projects/demo/src/modules/components/swipe-action/examples/4/index.ts
  projects/demo/src/modules/components/tab-bar/index.ts
  projects/demo/src/modules/components/tree/examples/6/index.ts
  projects/demo/src/modules/customization/variables/examples/1/index.ts
  projects/demo/src/modules/customization/wrapper/examples/1/index.ts
  projects/demo/src/modules/markup/form/examples/1/index.ts
  projects/demo/src/modules/markup/tables/examples/1/index.ts
  projects/demo/src/modules/pipes/field-error/examples/3/index.ts
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/radio-list/radio-list.component.ts
  projects/kit/components/radio/index.ts
  projects/kit/components/radio/radio.ts
  projects/legacy/components/multi-select-option/multi-select-option.module.ts
Labels: ready to merge

#7866 refactor: drop table filters module
  projects/addon-table/directives/table-filters/generic-filter.directive.ts
  projects/addon-table/directives/table-filters/index.ts
  projects/addon-table/directives/table-filters/table-filters.module.ts
  projects/addon-table/directives/table-filters/table-filters.ts
Labels: ready to merge

#7856 refactor: rename `TuiResizeableDirective` to `TuiResizeable`
  projects/addon-doc/components/demo/index.ts
  projects/cdk/directives/resizer/resizeable.directive.ts
  projects/cdk/directives/resizer/resizer.directive.ts
  projects/demo/src/modules/directives/resizer/examples/1/index.ts
Labels: ready to merge

#7843 feat(core): `Icon` allow bundling named icons
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/core/components/icon/icon.component.ts
  projects/core/components/icon/icon.pipe.ts
  projects/core/directives/icons/icons.directive.ts
  projects/core/tokens/icon-resolver.ts
  projects/core/tokens/icons.ts
  projects/core/tokens/index.ts
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/switch/switch.component.ts
Labels: ready to merge

#7871 refactor: use `TuiCarousel`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/carousel/examples/1/index.ts
  projects/demo/src/modules/components/carousel/examples/2/index.ts
  projects/demo/src/modules/components/carousel/examples/3/index.ts
  projects/demo/src/modules/components/carousel/examples/4/index.ts
  projects/demo/src/modules/components/carousel/examples/5/index.ts
  projects/demo/src/modules/components/carousel/examples/import/import.md
  projects/demo/src/modules/components/carousel/index.ts
  projects/kit/components/carousel/carousel-autoscroll.directive.ts
  projects/kit/components/carousel/carousel-buttons.directive.ts
  projects/kit/components/carousel/carousel-scroll.directive.ts
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/carousel/carousel.ts
  projects/kit/components/carousel/index.ts
Labels: ready to merge

#7881 refactor: drop some postfix
  projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.directive.ts
  projects/addon-table/components/table-pagination/table-pagination.component.ts
  projects/addon-table/components/table-pagination/test/table-pagination.component.spec.ts
  projects/core/components/calendar/calendar-sheet.component.ts
  projects/core/components/calendar/calendar-spin.component.ts
  projects/core/components/calendar/calendar-year.component.ts
  projects/core/components/calendar/calendar.component.ts
  projects/core/components/calendar/test/calendar-sheet.component.spec.ts
  projects/core/components/calendar/test/calendar-year.component.spec.ts
  projects/demo-cypress/src/tests/elastic-sticky.cy.ts
  projects/demo/src/modules/components/dialog/examples/4/index.ts
  projects/demo/src/modules/components/sheet/examples/4/index.ts
  projects/demo/src/modules/components/table-pagination/examples/1/index.ts
  projects/demo/src/modules/components/table-pagination/examples/2/index.ts
  projects/demo/src/modules/components/table-pagination/examples/3/index.ts
  projects/demo/src/modules/components/table-pagination/index.ts
  projects/demo/src/modules/components/table/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
  projects/demo/src/modules/directives/elastic-sticky/examples/1/index.ts
  projects/kit/components/calendar-month/calendar-month.component.ts
  projects/legacy/components/input-year/input-year.module.ts
Labels: ready to merge

#7870 refactor: drop dialog module
  projects/cdk/schematics/ng-add/constants/modules.ts
  projects/cdk/schematics/ng-add/schema.ts
  projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
  projects/cdk/schematics/ng-update/v3/constants/constants.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.directive.ts
  projects/core/components/dialog/dialog.module.ts
  projects/core/components/dialog/dialog.ts
  projects/core/components/dialog/index.ts
  projects/demo/src/modules/components/carousel/examples/4/index.ts
  projects/demo/src/modules/components/dialog/examples/6/index.ts
Labels: ready to merge

#7877 refactor: rename `TuiNavigationModule` to `TuiNavigation`
  projects/core/components/calendar/calendar-year.component.ts
  projects/core/components/scrollbar/scroll-into-view.directive.ts
  projects/core/components/scrollbar/scrollable.directive.ts
  projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts
  projects/demo/src/modules/components/experimental/navigation/examples/import/import.md
  projects/demo/src/modules/components/scrollbar/examples/6/index.ts
  projects/experimental/components/navigation/aside.component.ts
  projects/experimental/components/navigation/header.component.ts
  projects/experimental/components/navigation/hint-aside.directive.ts
  projects/experimental/components/navigation/logo.component.ts
  projects/experimental/components/navigation/main.component.ts
  projects/experimental/components/navigation/nav.component.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/legacy/components/select-option/select-option.module.ts
Labels: ready to merge

#7889 chore: enable eslint rule `@taiga-ui/experience/prefer-deep-imports`
  package.json
  projects/core/components/dialog/dialog.component.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/tokens/i18n.ts
  projects/core/tokens/icons.ts
  projects/demo-playwright/tests/demo/get-demo-paths.ts
  projects/experimental/components/navigation/aside.component.ts
  projects/kit/components/carousel/carousel.ts
  projects/kit/components/tabs/tabs.ts
Labels: ready to merge

#7838 fix(addon-doc): `Navigation` fix invalid two-way binding error in Angular v18
  projects/addon-doc/components/navigation/navigation.template.html
Labels: v4

#7837 fix(addon-doc): `Navigation` fix invalid two-way binding error in Angular v18
  projects/addon-doc/components/navigation/navigation.template.html
Labels: v3

#7886 ci: show only error in test job
  jest.config.ts
Labels: ready to merge

#7888 feat(addon-table): support nullable values in `tuiTableSort`
  projects/addon-table/components/table/pipes/table-sort.pipe.ts
  projects/demo/src/modules/components/table/examples/2/index.html
  projects/demo/src/modules/components/table/examples/2/index.ts
Labels: ready to merge, v4

#7822 fix(kit): `CalendarRange` should not distinguish ranges with same dates and different names
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Labels: ready to merge, v4

#7894 refactor: drop `tuiRow`
  projects/addon-table/components/table/directives/row.directive.ts
  projects/addon-table/components/table/index.ts
  projects/addon-table/components/table/table.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/components/table/tbody/tbody.template.html
  projects/addon-table/components/table/tr/tr.component.ts
Labels: ready to merge

#7900 refactor: directive rename
  projects/addon-doc/components/demo/index.html
  projects/addon-doc/components/demo/index.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/addon-table/types/index.ts
  projects/addon-table/types/row-context.ts
  projects/cdk/directives/resizer/index.ts
  projects/cdk/directives/resizer/resizable.directive.ts
  projects/cdk/directives/resizer/resizer.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint.directive.ts
  projects/demo/src/modules/directives/resizer/examples/1/index.html
  projects/demo/src/modules/directives/resizer/examples/1/index.ts
  projects/demo/src/modules/directives/resizer/examples/import/import.md
  projects/demo/src/modules/directives/resizer/examples/import/template.md
Labels: ready to merge

#7898 chore: fix lint
  projects/core/components/calendar/calendar.component.ts
  projects/core/components/data-list/option.component.ts
  projects/core/directives/date-format/date-format.directive.ts
  projects/core/directives/number-format/number-format.directive.ts
  projects/core/pipes/format-number/format-number.pipe.ts
  projects/core/services/breakpoint.service.ts
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/components/accordion/index.ts
  projects/demo/src/modules/components/alert/examples/3/index.ts
  projects/demo/src/modules/components/alert/examples/4/index.ts
  projects/demo/src/modules/components/alert/examples/5/index.ts
  projects/demo/src/modules/components/badge/index.ts
  projects/demo/src/modules/components/breadcrumbs/index.ts
  projects/demo/src/modules/components/calendar/examples/3/index.ts
  projects/demo/src/modules/customization/dialogs/examples/1/index.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/kit/components/input-phone-international/get-country-calling-code.pipe.ts
  projects/kit/components/routable-dialog/generate-dialogable-route.ts
Labels: ready to merge

#7903 ci: add prepublish target
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-table/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo-cypress/project.json
  projects/demo-playwright/project.json
  projects/demo/project.json
  projects/experimental/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/legacy/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
Labels: ready to merge

#7905 ci: do not generate release body for prerelease
  .github/workflows/create-release.yml
  projects/demo/project.json
Labels: ready to merge

#7907 chore: fix e2e matrix status check
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#7910 chore: remove redundant
  .github/workflows/auto-approve.yml
Labels: ready to merge

#7911 chore: invalid test
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Labels: ready to merge

#7915 fix(kit): phone international dropdown open
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.template.html
Labels: ready to merge

#7919 fix(core): add styles to exports
  projects/core/package.json
Labels: ready to merge
