Repository taiga-family/taiga-ui, pull requests merged in 2024-05, with the labels that each got.

#7341 fix(core): fix loading defaultErrorMessage for tui-error (#7303)
  projects/core/components/error/error.module.ts
  projects/core/components/error/error.template.html
Labels: ready to merge

#7345 refactor: rename destroy$ to destroyRef
  projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
  projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts
  projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
  projects/addon-doc/components/documentation/documentation.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts
  projects/addon-mobile/components/sheet/directives/sheet-stop/sheet-stop.directive.ts
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/cdk/classes/control.ts
  projects/cdk/directives/auto-focus/autofocus.directive.ts
  projects/core/abstract/abstract-driver.directive.ts
  projects/core/components/alert/alert.component.ts
  projects/core/components/expand/expand.component.ts
  projects/core/components/hints-host/hints-host.component.ts
  projects/core/directives/scroll-into-view/scroll-into-view.directive.ts
  projects/core/internal/svg-defs-host/svg-defs-host.component.ts
  projects/demo/src/modules/components/accordion/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
  projects/demo/src/modules/components/input-inline/examples/3/component.ts
  projects/demo/src/modules/icons/icons-group/icons-group.component.ts
  projects/kit/components/accordion/accordion.component.ts
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/input-tag/input-tag.component.ts
  projects/kit/components/input-time/input-time.component.ts
  projects/kit/components/segmented/segmented.directive.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
  projects/kit/directives/lazy-loading/lazy-loading.service.ts
Labels: ready to merge

#7336 fix(kit): `Textarea` incorrectly highlights extra characters for long words with hyphen in Safari/FF
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge, v3

#7344 fix(core): fix loading defaultErrorMessage for tui-error (#7303)
  projects/core/components/error/error.module.ts
  projects/core/components/error/error.template.html
Labels: ready to merge

#7322 refactor: drop group class names constant
  projects/kit/constants/group-class-names.ts
  projects/kit/constants/index.ts
Labels: ready to merge

#7324 chore(demo): format page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/utils/format/examples/1/index.ts
  projects/demo/src/modules/utils/format/examples/2/index.ts
  projects/demo/src/modules/utils/format/examples/3/index.ts
  projects/demo/src/modules/utils/format/examples/4/index.ts
  projects/demo/src/modules/utils/format/examples/5/index.ts
  projects/demo/src/modules/utils/format/examples/import/import-component.md
  projects/demo/src/modules/utils/format/format.component.ts
  projects/demo/src/modules/utils/format/format.module.ts
  projects/demo/src/modules/utils/format/index.html
  projects/demo/src/modules/utils/format/index.ts
Labels: ready to merge

#7349 ci: revert disabling of playwright bumps for renovate bot
  .github/renovate.json
  package-lock.json
  projects/demo-playwright/package.json
Labels: ready to merge

#7357 chore(demo-playwright): make `slider.spec.ts` locale-independent
  projects/demo-playwright/tests/kit/slider/slider.spec.ts
Labels: ready to merge

#7299 refactor: drop deprecated svg tokens
  projects/core/components/svg/svg-options.ts
  projects/core/components/svg/test/svg-options.component.spec.ts
  projects/core/tokens/icon-place.ts
  projects/core/tokens/icons-path.ts
  projects/core/tokens/index.ts
  projects/core/tokens/svg-content-processor.ts
  projects/core/tokens/svg-src-processor.ts
Labels: ready to merge

#7330 refactor: drop `TUI_PHONE_MASK`
  projects/kit/constants/index.ts
  projects/kit/constants/masks.ts
Labels: ready to merge

#7360 chore: remove failing test
  projects/demo-cypress/cypress/tests/kit/input-files/input-files.cy.ts
Labels: ready to merge

#7353 refactor: drop `TuiLetModule`
  projects/addon-charts/components/line-chart/line-chart.module.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-doc/components/navigation/navigation.module.ts
  projects/addon-mobile/components/sheet/sheet.module.ts
  projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.module.ts
  projects/cdk/directives/let/index.ts
  projects/cdk/directives/let/let.directive.ts
  projects/cdk/directives/let/let.module.ts
  projects/cdk/directives/let/test/let.directive.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/components/error/error.module.ts
  projects/core/components/hosted-dropdown/hosted-dropdown.module.ts
  projects/core/components/primitive-calendar/primitive-calendar.module.ts
  projects/core/components/primitive-year-picker/primitive-year-picker.module.ts
  projects/core/components/svg/svg.component.ts
  projects/core/internal/svg-defs-host/svg-defs-host.module.ts
  projects/demo/src/modules/animations/animations.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/combo-box/examples/1/index.ts
  projects/demo/src/modules/components/combo-box/examples/2/index.ts
  projects/demo/src/modules/components/combo-box/examples/5/index.ts
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.module.ts
  projects/demo/src/modules/components/input-phone/input-phone.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/demo/src/modules/components/multi-select/multi-select.module.ts
  projects/demo/src/modules/components/select/select.module.ts
  projects/demo/src/modules/components/tooltip/tooltip.module.ts
  projects/demo/src/modules/directives/let/examples/1/index.ts
  projects/demo/src/modules/directives/let/examples/2/index.ts
  projects/demo/src/modules/directives/let/examples/import/import.md
  projects/demo/src/modules/directives/let/examples/import/template.md
  projects/demo/src/modules/directives/let/index.html
  projects/demo/src/modules/directives/let/index.ts
  projects/demo/src/modules/directives/let/let.component.ts
  projects/demo/src/modules/directives/let/let.module.ts
  projects/demo/src/modules/directives/present/present.module.ts
  projects/demo/src/modules/experimental/tooltip/tooltip.module.ts
  projects/demo/src/modules/icons/icons-group/icons-group.module.ts
  projects/demo/src/modules/pipes/is-present/examples/1/index.ts
  projects/demo/src/modules/tables/table/table.module.ts
  projects/kit/components/calendar-month/calendar-month.module.ts
  projects/kit/components/input-date-range/input-date-range.module.ts
  projects/kit/components/input-date/input-date.module.ts
  projects/kit/components/input-phone-international/input-phone-international.module.ts
  projects/kit/components/items-with-more/items-with-more.module.ts
  projects/kit/components/line-clamp/line-clamp.module.ts
  projects/kit/components/multi-select/multi-select.module.ts
  projects/kit/components/pagination/pagination.module.ts
  projects/kit/components/tree/tree.module.ts
Labels: ready to merge

#7369 fix(experimental): `tuiCell` conflicts
  projects/experimental/directives/cell/cell.directive.ts
Labels: ready to merge, v3

#7370 fix(layout): `tuiCell` conflicts
  projects/layout/directives/cell/cell.directive.ts
Labels: ready to merge, v4

#7361 chore(demo): add example `Concurrency limit` to documentation page `Alert`
  projects/demo/src/modules/components/alert/alert.component.ts
  projects/demo/src/modules/components/alert/alert.template.html
  projects/demo/src/modules/components/alert/examples/7/index.html
  projects/demo/src/modules/components/alert/examples/7/index.ts
Labels: ready to merge

#7371 ci: independent monorepo sub path
  .github/workflows/e2e-playwright.yml
  package-lock.json
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/project.json
  projects/addon-table/project.json
  projects/addon-tablebars/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo-cypress/project.json
  projects/demo-playwright/project.json
  projects/demo/project.json
  projects/experimental/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/styles/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
Labels: ready to merge

#7316 fix(schematics): upgrade editor dependency
  package-lock.json
  package.json
  projects/cdk/schematics/ng-update/v3-36/index.ts
  projects/cdk/schematics/ng-update/v3-36/tests/schematic-migrate-editor.spec.ts
Labels: ready to merge, v3

#7307 chore: drop unused configurations
  CONTRIBUTING.md
  package.json
  projects/demo/project.json
Labels: ready to merge

#7304 refactor: drop `TuiDragModule`
  projects/addon-preview/components/preview/preview.component.ts
  projects/addon-preview/components/preview/preview.module.ts
  projects/cdk/directives/drag/drag.directive.ts
  projects/cdk/directives/drag/drag.module.ts
  projects/cdk/directives/drag/index.ts
  projects/cdk/directives/drag/ng-package.json
  projects/cdk/directives/index.ts
  projects/cdk/observables/drag-and-drop-from.ts
  projects/cdk/observables/test/drag-and-drop.spec.ts
Labels: ready to merge

#7334 refactor: move payment system icons into its own token
  projects/addon-commerce/components/input-card/abstract-input-card.ts
  projects/addon-commerce/components/input-card/input-card.options.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
  projects/addon-commerce/utils/payment-system-icons.ts
Labels: ready to merge

#7381 feat(cdk): add `tuiTakeUntilDestroyed` helper
  projects/cdk/directives/native-validator/native-validator.directive.ts
  projects/cdk/observables/index.ts
  projects/cdk/observables/take-until-destroyed.ts
  projects/core/services/position.service.ts
  projects/demo/src/modules/directives/appearance/appearance.template.html
  projects/demo/src/modules/services/table-bar/table-bar.component.ts
Labels: ready to merge

#7383 fix(layout): fix `tuiTitle` bold inside `tuiCell`
  projects/layout/directives/card/card.styles.less
Labels: ready to merge, v4

#7380 fix(cdk): `Destroy` fix post-destroy subscriptions
  projects/cdk/services/destroy.service.ts
Labels: ready to merge

#7382 fix(experimental): fix `tuiTitle` bold inside `tuiCell`
  projects/experimental/directives/card/card.styles.less
Labels: ready to merge, v3

#7358 fix(addon-mobile): `DropdownMobile` fix cleaner buttons
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/demo/src/modules/directives/dropdown/examples/5/index.html
Labels: ready to merge, v3

#7376 feat(core): add ability to use nested hints
  projects/core/directives/hint/hint-hover.directive.ts
  projects/demo-cypress/cypress/tests/core/hint/hint.cy.ts
  projects/demo-playwright/tests/core/hint/hint.spec.ts
  projects/demo/src/modules/directives/hint/examples/3/index.html
  projects/demo/src/modules/directives/hint/examples/3/index.ts
  projects/demo/src/modules/directives/hint/hint.component.ts
  projects/demo/src/modules/directives/hint/hint.module.ts
  projects/demo/src/modules/directives/hint/hint.template.html
Labels: ready to merge, v3

#7254 feat(addon-mobile): `MobileCalendar` switch to dropdown
  projects/addon-mobile/components/mobile-calendar-dialog/index.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.module.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.style.less
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.template.html
  projects/core/animations/animations.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/core/styles/mixins/textfield.less
  projects/core/styles/mixins/textfield.scss
  projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts
  projects/demo/src/modules/components/input-date/examples/2/index.html
  projects/demo/src/modules/components/input-date/input-date.module.ts
  projects/kit/components/accordion/accordion.style.less
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/input-date-range.template.html
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/input-tag/input-tag.style.less
Labels: ready to merge

#7384 fix(core): `Dialogs` fix page scrolling under dialogs
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
  projects/addon-mobile/components/sheet/components/sheet/sheet.style.less
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html
  projects/addon-mobile/components/sheet/sheet.module.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.component.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.style.less
  projects/addon-preview/components/preview-dialog/preview-dialog.template.html
  projects/addon-preview/components/preview/preview-action/preview-action.directive.ts
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/directives/focus-trap/focus-trap.module.ts
  projects/cdk/directives/focus-trap/index.ts
  projects/cdk/directives/index.ts
  projects/cdk/directives/overscroll/index.ts
  projects/cdk/directives/overscroll/ng-package.json
  projects/cdk/directives/overscroll/overscroll.directive.ts
  projects/cdk/directives/overscroll/overscroll.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/types/index.ts
  projects/cdk/types/overscroll-mode.ts
  projects/core/components/dialog/dialogs.component.ts
  projects/core/components/dialog/dialogs.style.less
  projects/core/components/dialog/dialogs.template.html
  projects/core/components/root/root.style.less
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.style.less
  projects/core/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/block-status/examples/4/index.html
  projects/demo/src/modules/components/block-status/examples/4/index.ts
  projects/demo/src/modules/components/dialog/examples/5/index.html
  projects/demo/src/modules/components/pdf-viewer/examples/1/index.html
  projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content.component.html
  projects/demo/src/modules/components/sheet-dialog/examples/1/index.ts
  projects/demo/src/modules/components/sheet/examples/1/index.ts
  projects/demo/src/modules/directives/overscroll/examples/1/index.html
  projects/demo/src/modules/directives/overscroll/examples/1/index.less
  projects/demo/src/modules/directives/overscroll/examples/1/index.ts
  projects/demo/src/modules/directives/overscroll/examples/2/index.html
  projects/demo/src/modules/directives/overscroll/examples/2/index.less
  projects/demo/src/modules/directives/overscroll/examples/2/index.ts
  projects/demo/src/modules/directives/overscroll/examples/3/index.html
  projects/demo/src/modules/directives/overscroll/examples/3/index.less
  projects/demo/src/modules/directives/overscroll/examples/3/index.ts
  projects/demo/src/modules/directives/overscroll/examples/import/import-module.md
  projects/demo/src/modules/directives/overscroll/examples/import/insert-template.md
  projects/demo/src/modules/directives/overscroll/overscroll.component.ts
  projects/demo/src/modules/directives/overscroll/overscroll.module.ts
  projects/demo/src/modules/directives/overscroll/overscroll.template.html
Labels: ready to merge, v4

#7226 refactor(addon-mobile): drop `TuiMobileCalendarModule` and `TuiMobileCalendarDialogModule`
  projects/addon-mobile/components/mobile-calendar-dialog/index.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.module.ts
  projects/addon-mobile/components/mobile-calendar/index.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
  projects/demo-playwright/tests/addon-mobile/mobile-calendar/mobile-calendar.spec.ts
  projects/demo-playwright/tests/example.spec.ts
  projects/demo-playwright/tests/nested-folder/nested-folder-example.spec.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/input-date-multi/input-date-multi.module.ts
  projects/demo/src/modules/components/input-date-multi/input-date-multi.template.html
  projects/demo/src/modules/components/input-date-range/input-date-range.module.ts
  projects/demo/src/modules/components/input-date-range/input-date-range.template.html
  projects/demo/src/modules/components/input-date/index.html
  projects/demo/src/modules/components/input-date/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/3/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/import/import-dialog-module.md
  projects/demo/src/modules/components/mobile-calendar/examples/import/import-module.md
  projects/demo/src/modules/components/mobile-calendar/examples/import/import.md
  projects/demo/src/modules/components/mobile-calendar/examples/import/template.md
  projects/demo/src/modules/components/mobile-calendar/index.html
  projects/demo/src/modules/components/mobile-calendar/index.less
  projects/demo/src/modules/components/mobile-calendar/index.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts
  projects/demo/src/modules/components/mobile-calendar/mobile-calendar.module.ts
Labels: ready to merge

#7387 chore(demo): move amount page to standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/pipes/amount/amount.component.ts
  projects/demo/src/modules/pipes/amount/amount.module.ts
  projects/demo/src/modules/pipes/amount/amount.template.html
  projects/demo/src/modules/pipes/amount/examples/1/index.ts
  projects/demo/src/modules/pipes/amount/examples/2/index.ts
  projects/demo/src/modules/pipes/amount/examples/3/index.ts
  projects/demo/src/modules/pipes/amount/examples/import/import.md
  projects/demo/src/modules/pipes/amount/examples/import/template.md
  projects/demo/src/modules/pipes/amount/index.html
  projects/demo/src/modules/pipes/amount/index.ts
Labels: ready to merge

#7402 fix(core): fix tuiGroup styles
  projects/core/components/group/group.style.less
Labels: ready to merge, v3

#7389 refactor: drop TuiAxesModule
  projects/addon-charts/components/axes/axes.component.ts
  projects/addon-charts/components/axes/axes.module.ts
  projects/addon-charts/components/axes/index.ts
  projects/addon-charts/components/axes/test/axes.component.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/charts/axes/axes.module.ts
  projects/demo/src/modules/charts/bar-chart/bar-chart.module.ts
  projects/demo/src/modules/charts/line-chart/line-chart.module.ts
  projects/demo/src/modules/charts/line-days-chart/line-days-chart.module.ts
  projects/demo/src/modules/components/axes/examples/1/index.html
  projects/demo/src/modules/components/axes/examples/1/index.less
  projects/demo/src/modules/components/axes/examples/1/index.ts
  projects/demo/src/modules/components/axes/examples/2/index.html
  projects/demo/src/modules/components/axes/examples/2/index.less
  projects/demo/src/modules/components/axes/examples/2/index.ts
  projects/demo/src/modules/components/axes/examples/3/index.html
  projects/demo/src/modules/components/axes/examples/3/index.less
  projects/demo/src/modules/components/axes/examples/3/index.ts
  projects/demo/src/modules/components/axes/examples/import/import.md
  projects/demo/src/modules/components/axes/examples/import/template.md
  projects/demo/src/modules/components/axes/index.html
  projects/demo/src/modules/components/axes/index.less
  projects/demo/src/modules/components/axes/index.ts
Labels: ready to merge

#7405 chore(demo-playwright): mock network request `fonts.gstatic.com`
  projects/demo-playwright/stubs/manrope-fonts.ttf
  projects/demo-playwright/utils/goto.ts
Labels: ready to merge

#7406 feat(addon-mobile): `MobileCalendar` switch to dropdown
  projects/addon-mobile/components/index.ts
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/index.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.style.less
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.template.html
  projects/addon-mobile/components/mobile-calendar-dropdown/ng-package.json
  projects/core/animations/animations.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/core/styles/mixins/textfield.less
  projects/core/styles/mixins/textfield.scss
  projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts
  projects/demo/src/modules/components/input-date-multi/input-date-multi.module.ts
  projects/demo/src/modules/components/input-date-multi/input-date-multi.template.html
  projects/demo/src/modules/components/input-date-range/input-date-range.module.ts
  projects/demo/src/modules/components/input-date-range/input-date-range.template.html
  projects/demo/src/modules/components/input-date/examples/2/index.html
  projects/demo/src/modules/components/input-date/examples/2/index.ts
  projects/demo/src/modules/components/input-date/index.html
  projects/demo/src/modules/components/input-date/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/import/import.md
  projects/demo/src/modules/components/mobile-calendar/index.html
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/input-date-multi.template.html
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/input-date-range.template.html
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.template.html
  projects/kit/components/input-tag/input-tag.style.less
  projects/kit/tokens/mobile-calendar.ts
Labels: ready to merge

#7408 chore: add `projects/demo-playwright/tests-report` to `exclude` of root `tsconfig.json`
  tsconfig.json
Labels: ready to merge

#7425 chore(demo-playwright): make `InputPhone` tests be compatible both Chromium & Firefox
  projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts
Labels: ready to merge

#7426 chore(demo-playwright): make `DropdownContext` tests be compatible both Chromium & Firefox
  projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
Labels: ready to merge

#7427 chore(demo-playwright): make `TuiPrimitiveTextfield` tests compatible with both Chromium & Firefox
  projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts
Labels: ready to merge

#7399 feat(schematics): add experimental migration
  .cspell.json
  projects/cdk/schematics/migration.json
  projects/cdk/schematics/ng-add/schema.ts
  projects/cdk/schematics/ng-update/v3-78/constants/icons.ts
  projects/cdk/schematics/ng-update/v3-78/index.ts
  projects/cdk/schematics/ng-update/v3-78/tests/schematic-migrate-logos-icons.spec.ts
Labels: ready to merge, v3

#7441 chore(deps): revert `rollup` version to stabilize playwright tests
  .github/renovate.json
  package-lock.json
  package.json
  projects/icons/package.json
Labels: ready to merge

#7414 ci: add `npx envinfo --preset playwright` to `e2e-playwright.yml`
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#7451 chore(demo-playwright): `tuiGoto` should mock both `.ttf` and `.woff2` fonts
  projects/demo-playwright/utils/goto.ts
Labels: ready to merge

#7455 ci: fix canary
  .github/workflows/auto-approve.yml
  .github/workflows/auto-author-assign.yml
  .github/workflows/auto-dependency-review.yml
  .github/workflows/auto-label.yml
  .github/workflows/auto-remove-label.yml
  .github/workflows/auto-update-icons.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-playwright.yml
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .github/workflows/schematics.yml
  .github/workflows/snapshots.yml
  .github/workflows/test.yml
Labels: ready to merge

#7445 refactor: rename TuiTabBarModule to TuiTabBar
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts
  projects/addon-mobile/components/tab-bar/tab-bar.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/tab-bar/examples/1/index.ts
  projects/demo/src/modules/components/tab-bar/examples/2/index.ts
  projects/demo/src/modules/components/tab-bar/examples/3/index.ts
  projects/demo/src/modules/components/tab-bar/examples/4/index.ts
  projects/demo/src/modules/components/tab-bar/examples/import/import.md
  projects/demo/src/modules/components/tab-bar/examples/import/template.md
  projects/demo/src/modules/components/tab-bar/index.html
  projects/demo/src/modules/components/tab-bar/index.less
  projects/demo/src/modules/components/tab-bar/index.ts
  projects/demo/src/modules/components/tab-bar/tab-bar.component.ts
  projects/demo/src/modules/components/tab-bar/tab-bar.module.ts
Labels: ready to merge

#7476 fix(kit): `Tree` fix control chevron rotation programmatically
  projects/kit/components/tree/components/tree-item-content/tree-item-content.component.ts
  projects/kit/components/tree/components/tree-item-content/tree-item-content.template.html
Labels: v3

#7486 refactor: drop $any in tree
  projects/kit/components/tree/components/tree/tree.template.html
Labels: ready to merge

#7485 refactor: remove $any in 4.0
  projects/core/components/data-list/data-list.component.ts
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.template.html
Labels: ready to merge

#7487 refactor: drop $any in example
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.template.html
Labels: ready to merge

#7488 refactor: drop $any in pdf-viewer
  projects/kit/components/pdf-viewer/pdf-viewer.template.html
Labels: ready to merge

#7501 feat: create new package `@taiga-ui/legacy`
  package-lock.json
  projects/cdk/package.json
  projects/legacy/LICENSE
  projects/legacy/README.md
  projects/legacy/components/index.ts
  projects/legacy/components/ng-package.json
  projects/legacy/index.ts
  projects/legacy/ng-package.json
  projects/legacy/package.json
  projects/legacy/project.json
  tsconfig.json
Labels: ready to merge

#7507 refactor(cdk): convert enum `TuiCountryIsoCode` to type
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/addon-doc/components/language-switcher/tests/language-switcher.component.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/enums.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/pipes/flag/test/flag.pipe.spec.ts
  projects/demo/src/modules/components/input-phone-international/examples/1/index.ts
  projects/demo/src/modules/components/input-phone-international/examples/2/index.ts
  projects/demo/src/modules/components/input-phone-international/input-phone-international.component.ts
  projects/demo/src/modules/pipes/flag/examples/1/index.ts
  projects/i18n/enums/country-iso-code.ts
  projects/i18n/languages/belarusian/countries.ts
  projects/i18n/languages/chinese/countries.ts
  projects/i18n/languages/dutch/countries.ts
  projects/i18n/languages/english/countries.ts
  projects/i18n/languages/french/countries.ts
  projects/i18n/languages/italian/countries.ts
  projects/i18n/languages/kazakh/countries.ts
  projects/i18n/languages/malay/countries.ts
  projects/i18n/languages/polish/countries.ts
  projects/i18n/languages/portuguese/countries.ts
  projects/i18n/languages/russian/countries.ts
  projects/i18n/languages/spanish/countries.ts
  projects/i18n/languages/vietnamese/countries.ts
  projects/kit/components/input-phone-international/all-countries-iso-codes.ts
  projects/kit/components/input-phone-international/index.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.options.ts
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/pipes/iso-to-country-code/test/iso-to-country-code.pipe.spec.ts
  projects/kit/pipes/to-country-code/test/to-country-code.pipe.spec.ts
  projects/kit/pipes/to-country-code/to-country-code.pipe.ts
  projects/kit/tokens/countries-masks.ts
  projects/kit/utils/miscellaneous/test/get-max-allowed-phone-length.spec.ts
Labels: ready to merge

#7505 chore(all): add copying LICENSE to every package
  projects/addon-charts/project.json
  projects/addon-commerce/LICENSE
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-preview/LICENSE
  projects/addon-preview/project.json
  projects/addon-table/LICENSE
  projects/addon-table/project.json
  projects/addon-tablebars/LICENSE
  projects/addon-tablebars/project.json
  projects/cdk/LICENSE
  projects/cdk/project.json
  projects/core/LICENSE
  projects/core/project.json
  projects/experimental/LICENSE
  projects/experimental/project.json
  projects/i18n/LICENSE
  projects/i18n/project.json
  projects/icons/LICENSE
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/LICENSE
  projects/layout/project.json
  projects/styles/project.json
  projects/taiga-schematics/LICENSE
  projects/taiga-schematics/project.json
  projects/testing/project.json
Labels: ready to merge

#7499 refactor: drop TuiScrollIntoViewLinkModule
  projects/addon-doc/components/navigation/navigation.module.ts
  projects/addon-doc/directives/index.ts
  projects/addon-doc/directives/scroll-into-view/scroll-into-view.directive.ts
  projects/addon-doc/directives/scroll-into-view/scroll-into-view.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#7467 chore: ignore flaky
  projects/demo-playwright/tests/demo/is-flaky-examples.ts
Labels: ready to merge

#7498 refactor: drop TuiTextCodeModule
  projects/addon-doc/directives/index.ts
  projects/addon-doc/directives/text-code/text-code.directive.ts
  projects/addon-doc/directives/text-code/text-code.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/components/alert/index.ts
  projects/demo/src/modules/components/dialog/dialog.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/demo/src/modules/components/progress-bar/progress-bar.module.ts
  projects/demo/src/modules/components/progress-circle/progress-circle.module.ts
  projects/demo/src/modules/components/slider/slider.module.ts
  projects/demo/src/modules/components/textarea/textarea.module.ts
  projects/demo/src/modules/markup/spaces/spaces.module.ts
  projects/demo/src/modules/services/scroll/scroll.module.ts
Labels: ready to merge

#7500 chore(demo): update outdated organization info
  projects/demo/src/index.html
  projects/demo/src/modules/directives/sidebar/examples/1/index.html
  projects/demo/src/modules/directives/sidebar/examples/1/index.ts
  projects/demo/src/modules/info/related/index.html
Labels: ready to merge

#7496 refactor: drop TuiPreviewDialogModule
  projects/addon-preview/components/preview-dialog/index.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.component.ts
  projects/addon-preview/components/preview-dialog/preview-dialog.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#7479 chore: remove redundant
  projects/layout/components/block-status/block-status.module.ts
Labels: ready to merge

#7464 chore: nx repair
  nx.json
  projects/demo-cypress/project.json
Labels: ready to merge

#7503 refactor: drop TuiSidebarModule
  projects/addon-doc/components/internal/header/header.module.ts
  projects/addon-mobile/directives/sidebar/index.ts
  projects/addon-mobile/directives/sidebar/sidebar.component.ts
  projects/addon-mobile/directives/sidebar/sidebar.directive.ts
  projects/addon-mobile/directives/sidebar/sidebar.module.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/directives/sidebar/examples/1/index.ts
  projects/demo/src/modules/directives/sidebar/examples/import/component.md
  projects/demo/src/modules/directives/sidebar/examples/import/import-module.md
  projects/demo/src/modules/directives/sidebar/examples/import/import.md
  projects/demo/src/modules/directives/sidebar/examples/import/template.md
  projects/demo/src/modules/directives/sidebar/index.html
  projects/demo/src/modules/directives/sidebar/index.ts
  projects/demo/src/modules/directives/sidebar/sidebar.component.ts
  projects/demo/src/modules/directives/sidebar/sidebar.module.ts
  projects/demo/src/modules/directives/sidebar/sidebar.template.html
  projects/demo/src/modules/directives/swipe/examples/2/index.ts
Labels: ready to merge

#7481 refactor: drop `tuiDefaultSort` from `addon-table`
  projects/addon-table/index.ts
  projects/addon-table/utils/default-sort.ts
  projects/addon-table/utils/index.ts
  projects/addon-table/utils/ng-package.json
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#7471 chore(schematics): proprietary navigation
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
Labels: ready to merge

#7510 feat(addon-commerce): update currencies
  projects/addon-commerce/enums/currency-code.ts
  projects/addon-commerce/enums/currency.ts
  projects/addon-commerce/utils/get-code-by-currency.ts
  projects/addon-commerce/utils/get-currency-by-code.ts
  projects/addon-commerce/utils/get-currency-symbol.ts
Labels: v4

#7516 fix(i18n): add some missing country iso codes (extend `TuiCountryIsoCode` type)
  projects/i18n/enums/country-iso-code.ts
  projects/i18n/languages/belarusian/countries.ts
  projects/i18n/languages/chinese/countries.ts
  projects/i18n/languages/dutch/countries.ts
  projects/i18n/languages/english/countries.ts
  projects/i18n/languages/french/countries.ts
  projects/i18n/languages/italian/countries.ts
  projects/i18n/languages/kazakh/countries.ts
  projects/i18n/languages/malay/countries.ts
  projects/i18n/languages/polish/countries.ts
  projects/i18n/languages/portuguese/countries.ts
  projects/i18n/languages/russian/countries.ts
  projects/i18n/languages/spanish/countries.ts
  projects/i18n/languages/vietnamese/countries.ts
  projects/kit/tokens/countries-masks.ts
Labels: ready to merge

#7480 refactor: drop TuiStringifyPipeModule
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/version-manager/version-manager.module.ts
  projects/demo/src/modules/pipes/stringify/examples/1/index.ts
  projects/demo/src/modules/pipes/stringify/examples/import/import.md
  projects/demo/src/modules/pipes/stringify/examples/import/template.md
  projects/demo/src/modules/pipes/stringify/index.html
  projects/demo/src/modules/pipes/stringify/index.ts
  projects/demo/src/modules/pipes/stringify/stringify.component.ts
  projects/demo/src/modules/pipes/stringify/stringify.module.ts
  projects/kit/pipes/stringify/index.ts
  projects/kit/pipes/stringify/stringify.module.ts
  projects/kit/pipes/stringify/stringify.pipe.ts
Labels: ready to merge

#7466 refactor: drop modules inside addon-commerce
  projects/addon-commerce/components/input-card-grouped/index.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
  projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
  projects/addon-commerce/components/input-card/index.ts
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/addon-commerce/components/input-card/input-card.directive.ts
  projects/addon-commerce/components/input-card/input-card.module.ts
  projects/addon-commerce/components/input-card/test/input-card.component.spec.ts
  projects/addon-commerce/components/input-cvc/index.ts
  projects/addon-commerce/components/input-cvc/input-cvc.component.ts
  projects/addon-commerce/components/input-cvc/input-cvc.module.ts
  projects/addon-commerce/components/input-cvc/test/input-cvc.component.spec.ts
  projects/addon-commerce/components/input-expire/index.ts
  projects/addon-commerce/components/input-expire/input-expire.component.ts
  projects/addon-commerce/components/input-expire/input-expire.module.ts
  projects/addon-commerce/components/input-expire/test/input-expire.component.spec.ts
  projects/addon-commerce/enums/currency-code.ts
  projects/addon-commerce/enums/currency.ts
  projects/addon-commerce/pipes/currency/currency.module.ts
  projects/addon-commerce/pipes/currency/currency.pipe.ts
  projects/addon-commerce/pipes/format-card/format-card.module.ts
  projects/addon-commerce/pipes/format-card/format-card.pipe.ts
  projects/addon-commerce/pipes/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.module.ts
  projects/demo/src/modules/components/group/group.module.ts
  projects/demo/src/modules/components/input-card-grouped/examples/1/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/3/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/4/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/5/index.ts
  projects/demo/src/modules/components/input-card-grouped/examples/import/import.md
  projects/demo/src/modules/components/input-card-grouped/examples/import/template.md
  projects/demo/src/modules/components/input-card-grouped/index.html
  projects/demo/src/modules/components/input-card-grouped/index.less
  projects/demo/src/modules/components/input-card-grouped/index.ts
  projects/demo/src/modules/components/input-card-grouped/input-card-grouped.module.ts
  projects/demo/src/modules/components/input-card/examples/1/index.ts
  projects/demo/src/modules/components/input-card/examples/import/import-module.md
  projects/demo/src/modules/components/input-card/examples/import/import.md
  projects/demo/src/modules/components/input-card/examples/import/template.md
  projects/demo/src/modules/components/input-card/index.html
  projects/demo/src/modules/components/input-card/index.less
  projects/demo/src/modules/components/input-card/index.ts
  projects/demo/src/modules/components/input-card/input-card.module.ts
  projects/demo/src/modules/components/input-number/input-number.module.ts
  projects/demo/src/modules/components/input/input.module.ts
  projects/demo/src/modules/markup/form/examples/1/index.ts
  projects/demo/src/modules/pipes/currency/currency.module.ts
  projects/demo/src/modules/pipes/currency/currency.template.html
  projects/demo/src/modules/pipes/currency/examples/import/import-module.md
  projects/demo/src/modules/pipes/field-error/field-error.module.ts
Labels: ready to merge

#7404 feat(cdk): add design tokens package
  package-lock.json
  projects/kit/package.json
Labels: ready to merge

#7517 refactor: refactor datalist
  projects/addon-doc/components/language-switcher/index.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.style.less
  projects/core/components/data-list/data-list.template.html
  projects/core/components/data-list/data-list.types.ts
  projects/core/components/data-list/mixin.style.less
  projects/core/components/data-list/option.component.ts
  projects/core/components/data-list/option.style.less
  projects/core/components/data-list/option.template.html
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.template.html
  projects/core/utils/dom/get-viewport-width.ts
  projects/core/utils/dom/get-viewport.ts
  projects/core/utils/dom/index.ts
  projects/core/utils/format/capitalize-first-letter.ts
  projects/core/utils/format/capitalize.ts
  projects/core/utils/format/index.ts
  projects/core/utils/format/test/capitalize-first-letter.spec.ts
  projects/core/utils/format/test/capitalize.spec.ts
  projects/demo-playwright/tests/core/data-list/data-list.spec.ts
  projects/demo/src/modules/components/data-list-wrapper/examples/1/index.html
  projects/demo/src/modules/components/data-list/data-list.component.ts
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/data-list/data-list.template.html
  projects/demo/src/modules/components/data-list/examples/3/index.html
  projects/demo/src/modules/components/data-list/examples/3/index.less
  projects/demo/src/modules/components/data-list/examples/3/index.ts
  projects/demo/src/modules/components/data-list/examples/4/custom-list/custom-list.component.ts
  projects/demo/src/modules/components/data-list/examples/4/custom-list/custom-list.template.html
  projects/demo/src/modules/utils/format/examples/3/index.html
  projects/demo/src/modules/utils/format/examples/3/index.ts
  projects/demo/src/modules/utils/format/examples/4/index.html
  projects/demo/src/modules/utils/format/examples/4/index.ts
  projects/demo/src/modules/utils/format/examples/5/index.html
  projects/demo/src/modules/utils/format/examples/5/index.less
  projects/demo/src/modules/utils/format/examples/5/index.ts
  projects/demo/src/modules/utils/format/index.html
  projects/kit/components/data-list-wrapper/data-list-wrapper.ts
  projects/legacy/components/index.ts
  projects/legacy/index.ts
  projects/legacy/utils/get-safe-area-size.ts
  projects/legacy/utils/index.ts
  projects/legacy/utils/ng-package.json
Labels: ready to merge

#7536 refactor(kit): delete deprecated entities in `InputPhoneInternational`
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/demo/src/modules/components/input-phone-international/examples/import/import-module.md
  projects/demo/src/modules/components/input-phone-international/input-phone-international.module.ts
  projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/index.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.module.ts
  projects/kit/components/input-phone-international/input-phone-international.style.less
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/pipes/iso-to-country-code/index.ts
  projects/kit/pipes/iso-to-country-code/iso-to-country-code.module.ts
  projects/kit/pipes/iso-to-country-code/iso-to-country-code.pipe.ts
Labels: ready to merge

#7540 chore: fix build
  projects/demo/src/modules/components/icons/icons-mapping/index.html
Labels: ready to merge

#7534 feat(experimental): add padding when use nested colored icons in`TuiAvatar` ng-content
  projects/demo/src/modules/experimental/avatar/avatar.component.ts
  projects/demo/src/modules/experimental/avatar/avatar.module.ts
  projects/demo/src/modules/experimental/avatar/avatar.template.html
  projects/demo/src/modules/experimental/avatar/examples/8/index.html
  projects/demo/src/modules/experimental/avatar/examples/8/index.ts
  projects/experimental/components/avatar/avatar.component.ts
  projects/experimental/components/avatar/avatar.style.less
  projects/experimental/components/icon/icon.pipe.ts
  projects/experimental/constants/events.ts
  projects/experimental/constants/index.ts
  projects/experimental/constants/ng-package.json
  projects/experimental/index.ts
  projects/icons/all.ts
  projects/icons/src/tuiIconVisaOutline.svg
Labels: ready to merge

#7554 fix(kit): collision with input-date-multi
  projects/kit/components/input-date/input-date.component.ts
  projects/kit/components/input-date/input-date.directive.ts
Labels: ready to merge, v3

#7567 refactor(kit): dump `tuiNotKzRegion` & `tuiGetMaxAllowedPhoneLength` utils to `@taiga-ui/legacy`
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/kit/utils/index.ts
  projects/kit/utils/phone/get-max-allowed-phone-length.ts
  projects/kit/utils/phone/index.ts
  projects/kit/utils/phone/ng-package.json
  projects/kit/utils/phone/not-kz-region.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/pipes/to-country-code/to-country-code.pipe.ts
  projects/legacy/utils/get-max-allowed-phone-length.ts
  projects/legacy/utils/index.ts
  projects/legacy/utils/not-kz-region.ts
  projects/legacy/utils/tests/get-max-allowed-phone-length.spec.ts
Labels: ready to merge

#7570 chore(demo): standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/tabs/examples/1/index.ts
  projects/demo/src/modules/components/tabs/examples/2/index.ts
  projects/demo/src/modules/components/tabs/examples/3/index.ts
  projects/demo/src/modules/components/tabs/examples/4/index.ts
  projects/demo/src/modules/components/tabs/examples/5/index.ts
  projects/demo/src/modules/components/tabs/examples/6/index.ts
  projects/demo/src/modules/components/tabs/examples/7/index.ts
  projects/demo/src/modules/components/tabs/index.html
  projects/demo/src/modules/components/tabs/index.ts
  projects/demo/src/modules/components/tabs/tabs.module.ts
  projects/demo/src/modules/components/textarea/examples/1/index.ts
  projects/demo/src/modules/components/textarea/examples/2/index.ts
  projects/demo/src/modules/components/textarea/examples/3/index.ts
  projects/demo/src/modules/components/textarea/examples/4/index.ts
  projects/demo/src/modules/components/textarea/examples/5/index.ts
  projects/demo/src/modules/components/textarea/examples/6/index.ts
  projects/demo/src/modules/components/textarea/examples/import/declare-form.md
  projects/demo/src/modules/components/textarea/examples/import/import.md
  projects/demo/src/modules/components/textarea/examples/import/template.md
  projects/demo/src/modules/components/textarea/index.html
  projects/demo/src/modules/components/textarea/index.ts
  projects/demo/src/modules/components/textarea/textarea.component.ts
  projects/demo/src/modules/components/textarea/textarea.module.ts
Labels: ready to merge

#7577 chore(demo-cypress): add component tests for `InputPhoneInternational`
  package.json
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
Labels: ready to merge

#7574 refactor(testing): improve flexibility of `TuiNativeInputPO`
  projects/legacy/components/input-range/test/input-range.component.spec.ts
  projects/testing/utils/native-input.page-object.ts
Labels: ready to merge

#7583 chore(core): use `[tuiTextfieldLegacy]` selector (instead of `[tuiTextfield]`) for `TextfieldLegacy`
  projects/addon-commerce/components/input-cvc/input-cvc.template.html
  projects/addon-commerce/components/input-expire/input-expire.template.html
  projects/addon-doc/components/documentation/documentation.template.html
  projects/core/components/primitive-textfield/test/primitive-textfield.component.spec.ts
  projects/core/components/primitive-textfield/test/textfield.component.spec.ts
  projects/core/components/primitive-textfield/textfield/textfield.component.ts
  projects/demo-playwright/tests/kit/combo-box/combobox.spec.ts
  projects/demo-playwright/tests/kit/input/input.spec.ts
  projects/demo/src/modules/components/accordion/examples/2/index.html
  projects/demo/src/modules/components/combo-box/examples/1/index.html
  projects/demo/src/modules/components/combo-box/examples/2/index.html
  projects/demo/src/modules/components/combo-box/examples/3/index.html
  projects/demo/src/modules/components/combo-box/examples/4/index.html
  projects/demo/src/modules/components/combo-box/examples/6/index.html
  projects/demo/src/modules/components/combo-box/examples/7/index.html
  projects/demo/src/modules/components/dialog/examples/9/index.html
  projects/demo/src/modules/components/experimental/tooltip/examples/2/index.html
  projects/demo/src/modules/components/group/examples/1/index.html
  projects/demo/src/modules/components/group/examples/import/template.md
  projects/demo/src/modules/components/input-card/examples/1/index.html
  projects/demo/src/modules/components/input-copy/examples/1/index.html
  projects/demo/src/modules/components/input-date-range/examples/1/index.html
  projects/demo/src/modules/components/input-date-time/examples/1/index.html
  projects/demo/src/modules/components/input-date-time/examples/5/index.html
  projects/demo/src/modules/components/input-date/examples/4/index.html
  projects/demo/src/modules/components/input-date/examples/import/template.md
  projects/demo/src/modules/components/input-month-range/examples/1/index.html
  projects/demo/src/modules/components/input-month/examples/1/index.html
  projects/demo/src/modules/components/input-month/examples/3/index.html
  projects/demo/src/modules/components/input-number/examples/2/index.html
  projects/demo/src/modules/components/input-password/examples/1/index.html
  projects/demo/src/modules/components/input-phone/examples/1/index.html
  projects/demo/src/modules/components/input-year/examples/1/index.html
  projects/demo/src/modules/components/input/examples/1/index.html
  projects/demo/src/modules/components/input/examples/10/index.html
  projects/demo/src/modules/components/input/examples/2/index.html
  projects/demo/src/modules/components/input/examples/3/index.html
  projects/demo/src/modules/components/input/examples/4/index.html
  projects/demo/src/modules/components/input/examples/5/index.html
  projects/demo/src/modules/components/input/examples/6/index.html
  projects/demo/src/modules/components/input/examples/9/index.html
  projects/demo/src/modules/components/input/examples/import/template.md
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/primitive-textfield/examples/1/index.html
  projects/demo/src/modules/components/primitive-textfield/examples/2/index.html
  projects/demo/src/modules/components/select/examples/1/index.html
  projects/demo/src/modules/components/select/examples/11/index.html
  projects/demo/src/modules/components/textarea/examples/5/index.html
  projects/demo/src/modules/components/textarea/examples/6/index.html
  projects/demo/src/modules/components/textarea/index.html
  projects/demo/src/modules/directives/date-format/examples/1/index.html
  projects/demo/src/modules/directives/dropdown/examples/6/index.html
  projects/demo/src/modules/directives/number-format/examples/1/index.html
  projects/demo/src/modules/directives/textfield-controller/examples/1/index.html
  projects/demo/src/modules/markup/form/examples/1/index.html
  projects/demo/src/modules/pipes/field-error/examples/4/index.html
  projects/legacy/components/input-phone-international/input-phone-international.template.html
  projects/legacy/components/input-time/input-time.template.html
  projects/testing/core/textfield.harness.ts
Labels: ready to merge

#7578 feat(experimental): `HintAside` add automatic hint directive for navigation
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint.directive.ts
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/experimental/components/navigation/hint-aside.directive.ts
  projects/experimental/components/navigation/index.ts
  projects/experimental/components/navigation/navigation.module.ts
  projects/icons/all.ts
  projects/icons/src/tuiIconCheckCircleOutline.svg
Labels: ready to merge, v3
