Repository taiga-family/taiga-ui, pull requests merged in 2024-11, with the labels that each got.

#9651 feat(layout): `BlockStatus` add desktop "m" size
  projects/demo/src/modules/components/block-status/examples/2/index.html
  projects/demo/src/modules/components/block-status/examples/6/index.html
  projects/demo/src/modules/components/block-status/examples/6/index.ts
  projects/demo/src/modules/components/block-status/index.html
  projects/demo/src/modules/components/block-status/index.ts
  projects/layout/components/block-status/block-status.component.ts
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge

#9658 fix(kit): `Switch` should have dark knob for the dark theme in web platform
  projects/kit/styles/components/switch.less
Labels: ready to merge

#9009 fix(kit): `CalendarRange` shows actual `defaultViewedMonth`
  projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
  projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
Labels: v3

#9643 fix(legacy): `InputTime` & `InputDateTime` should switch `inputMode` for time modes with AM / PM
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date-time/input-date-time.directive.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-time/input-time.directive.ts
  projects/legacy/components/input-time/input-time.template.html
Labels: ready to merge

#9633 fix(core): do not hide scrollbars on desktop when dialog is open
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.template.html
Labels: ready to merge

#9640 fix(kit): `Stepper` fix flashing styles
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge, v3

#9638 fix(kit): `Stepper` fix flashing styles
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#9673 chore: extend meta for tui-db
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#9665 fix(kit): `CalendarRange` switch months if any input updated, when date range selected
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Labels: ready to merge

#9623 fix(kit): `InputDate` hold initial value with min/max defined
  projects/demo-cypress/tsconfig.json
  projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
  projects/kit/components/input-date/input-date.component.ts
Labels: ready to merge, v3

#9667 chore(demo): `Chip` add autocolor example, add api page
  projects/demo/src/modules/components/chip/examples/5/index.html
  projects/demo/src/modules/components/chip/examples/5/index.less
  projects/demo/src/modules/components/chip/examples/5/index.ts
  projects/demo/src/modules/components/chip/index.html
  projects/demo/src/modules/components/chip/index.ts
Labels: ready to merge

#9657 fix(addon-mobile): `TuiElasticStickyService` teardown observable zone fix
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
Labels: ready to merge

#9650 fix(legacy): `InputDate` incorrect value after backspace
  projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/test/input-date.component.spec.ts
Labels: ready to merge

#9668 chore: explicit run e2e type check
  .github/workflows/e2e.yml
  projects/demo-playwright/project.json
Labels: ready to merge

#9648 feat(kit): new `tuiProgressFixedGradient` for `ProgressBar`
  projects/demo/src/modules/components/progress-bar/examples/2/index.html
  projects/kit/components/progress/index.ts
  projects/kit/components/progress/progress-bar/fixed-gradient/progress-fixed-gradient.directive.ts
  projects/kit/components/progress/progress-bar/fixed-gradient/progress-fixed-gradient.style.less
  projects/kit/components/progress/progress.ts
Labels: community contribution

#9689 ci: add shard matrix
  .github/workflows/e2e.yml
Labels: ready to merge

#9693 chore(demo): update `Textfield` + `Maskito` example
  projects/demo/src/modules/components/textfield/examples/5/index.html
  projects/demo/src/modules/components/textfield/examples/5/index.less
  projects/demo/src/modules/components/textfield/examples/5/index.ts
  projects/demo/src/modules/components/textfield/index.html
  projects/demo/src/modules/components/textfield/index.ts
Labels: ready to merge

#9706 chore(demo): prevent DDoS github api from e2e tests
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge

#9696 feat(core): add readable media aliases
  projects/addon-mobile/components/swipe-action/swipe-actions.style.less
  projects/core/directives/surface/surface.style.less
  projects/core/styles/components/icon.less
  projects/core/styles/mixins/appearance.less
  projects/core/styles/mixins/appearance.scss
  projects/core/styles/mixins/date-picker.less
  projects/core/styles/mixins/wrapper.less
  projects/core/styles/mixins/wrapper.scss
  projects/core/styles/variables/media.less
  projects/core/styles/variables/media.scss
  projects/demo/src/modules/components/surface/examples/1/index.less
  projects/demo/src/modules/components/swipe-action/examples/5/index.less
  projects/kit/components/files/file/file.style.less
  projects/kit/components/segmented/segmented.style.less
  projects/kit/components/tabs/tabs.style.less
  projects/kit/directives/tooltip/tooltip.style.less
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge

#9712 feat(core): `Dialog` move close button inside dialog
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.style.less
  projects/core/components/dialog/dialog.template.html
  projects/demo/src/modules/components/dialog/dialog.component.ts
  projects/demo/src/modules/components/dialog/examples/8/index.ts
Labels: ready to merge, v3

#9715 feat(layout): `AppBarBack` add ability to use custom appearance
  projects/layout/components/app-bar/app-bar-back.component.ts
Labels: ready to merge

#9703 chore: update meta for db
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#9702 chore: do not split previous diff png file
  scripts/visual-testing/combine-playwright-failed-screenshots.ts
Labels: ready to merge

#9723 fix(layout): `Navigation` fix various style issues
  projects/demo/src/modules/components/navigation/index.less
  projects/layout/components/navigation/aside.style.less
  projects/layout/components/navigation/header.style.less
  projects/layout/components/navigation/main.style.less
Labels: ready to merge

#9707 fix(legacy): `InputDateRange` double backspace to clear textfield
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
  projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
Labels: ready to merge

#9740 chore: pagination fix qualified name
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#9694 feat(kit): `Message` add component
  projects/addon-mobile/styles/common/message.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/message/examples/1/index.html
  projects/demo/src/modules/components/message/examples/1/index.less
  projects/demo/src/modules/components/message/examples/1/index.ts
  projects/demo/src/modules/components/message/examples/2/index.html
  projects/demo/src/modules/components/message/examples/2/index.less
  projects/demo/src/modules/components/message/examples/2/index.ts
  projects/demo/src/modules/components/message/examples/3/index.html
  projects/demo/src/modules/components/message/examples/3/index.ts
  projects/demo/src/modules/components/message/examples/4/index.html
  projects/demo/src/modules/components/message/examples/4/index.less
  projects/demo/src/modules/components/message/examples/4/index.ts
  projects/demo/src/modules/components/message/examples/5/index.html
  projects/demo/src/modules/components/message/examples/5/index.less
  projects/demo/src/modules/components/message/examples/5/index.ts
  projects/demo/src/modules/components/message/examples/import/import.md
  projects/demo/src/modules/components/message/examples/import/template.md
  projects/demo/src/modules/components/message/index.html
  projects/demo/src/modules/components/message/index.ts
  projects/kit/components/index.ts
  projects/kit/components/message/index.ts
  projects/kit/components/message/message.directive.ts
  projects/kit/components/message/ng-package.json
  projects/kit/styles/components/message.less
Labels: ready to merge

#9742 fix(layout): tui-block-status remove margins for empty t-block-image
  projects/layout/components/block-status/block-status.style.less
Labels: v3

#9746 chore: revert cypress changes
  projects/demo-cypress/cypress.config.ts
Labels: ready to merge

#9727 chore: avoid force by eslint plugin
  projects/demo-playwright/tests/addon-commerce/input-card-group.pw.spec.ts
  projects/demo-playwright/tests/legacy/combo-box/combobox.pw.spec.ts
Labels: ready to merge

#9708 ci: use another way for drop cache from pull request
  .github/workflows/cleanup-resources.yml
Labels: ready to merge

#9733 fix(kit): correctly loose box shadow on tile after dragged
  projects/demo-playwright/tests/kit/tiles/tiles.pw.spec.ts
  projects/demo-playwright/utils/goto.ts
  projects/kit/components/tiles/tile.component.ts
  projects/kit/components/tiles/tiles.component.ts
Labels: ready to merge

#9736 fix(addon-mobile): `DropdownMobile` is not compatible with `DropdownHover`
  projects/core/directives/dropdown/dropdown-hover.directive.ts
  projects/demo-playwright/tests/kit/dropdown-hover/dropdown-hover.pw.spec.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/mobile-dropdown.po.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/5/index.html
  projects/demo/src/modules/directives/dropdown-hover/examples/5/index.ts
  projects/demo/src/modules/directives/dropdown-hover/index.html
Labels: ready to merge

#9754 chore: add stars badge
  README.md
Labels: ready to merge

#9748 chore: investigate threshold
  .github/workflows/e2e.yml
  projects/demo-playwright/playwright.config.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-select.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts
  projects/demo-playwright/tests/demo/demo.pw.spec.ts
  projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
  scripts/visual-testing/combine-playwright-failed-screenshots.ts
Labels: ready to merge

#9774 feat(addon-doc): use only one property on route for expose input prop value
  projects/addon-doc/components/documentation/documentation-property-connector.directive.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
Labels: ready to merge

#9759 fix(cdk): `FocusTrap` has race condition problems
  package-lock.json
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/demo-cypress/package.json
  projects/demo-cypress/src/support/component.ts
  projects/demo-cypress/src/tests/focus-trap.cy.ts
Labels: ready to merge

#9781 ci: add e2e report
  .firebaserc
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  .gitignore
  firebase.json
  projects/demo-playwright/playwright.config.ts
Labels: ready to merge

#9772 chore: flaky e2e
  projects/demo-playwright/tests/kit/tiles/tiles.pw.spec.ts
  projects/demo-playwright/tests/kit/tree/tree.pw.spec.ts
Labels: ready to merge

#9787 ci: pin firebase channels
  .github/workflows/cleanup-resources.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
Labels: ready to merge

#9776 fix(core): fix custom hint
  projects/core/directives/hint/hint-unstyled.component.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
  projects/demo/src/modules/directives/hint/examples/2/index.html
Labels: ready to merge

#9779 chore: use prettier plugin by default formatter
  .vscode/settings.json
Labels: ready to merge

#9773 ci: add community contribute label after merged
  .github/workflows/after-close-pr.yml
Labels: ready to merge

#9800 fix(cdk): missing migration schematic for `createStackingContext` mixin
  projects/cdk/schematics/ng-update/v4/steps/styles/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-mixins.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-scrollbar-behavior.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge

#9765 chore(demo-cypress): mock fonts to fix flaky Cypress tests
  projects/demo-cypress/src/fixtures/manrope-fonts.ttf
  projects/demo-cypress/src/support/component.ts
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
Labels: ready to merge

#9804 fix(addon-mobile): drop close button for sheet dialog
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
Labels: ready to merge, v3

#9802 fix(cdk): missing migration schematic for mixins from `@taiga-ui/legacy/styles/taiga-ui-local`
  projects/cdk/schematics/ng-update/v4/steps/styles/index.ts
  projects/cdk/schematics/ng-update/v4/steps/styles/migrate-legacy-mixins.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Labels: ready to merge

#9821 fix(addon-mobile): update font of large buttons on mobile
  projects/addon-mobile/styles/common/button.less
Labels: ready to merge, v3

#9840 chore(demo-cypress): hide caret for screenshot component testing
  projects/demo-cypress/src/support/component-index.html
Labels: ready to merge

#9833 chore(demo): improve icon API page with shape elements
  projects/demo/src/modules/components/icon/index.html
  projects/demo/src/modules/components/icon/index.ts
  projects/demo/used-icons.ts
Labels: ready to merge

#9832 chore(demo): drop redundant empty files
  package.json
  projects/demo/src/modules/components/avatar/examples/4/index.less
  projects/demo/src/modules/components/avatar/examples/5/index.less
  projects/demo/src/modules/components/block-status/examples/1/index.less
  projects/demo/src/modules/components/block-status/examples/1/index.ts
  projects/demo/src/modules/components/block-status/examples/2/index.less
  projects/demo/src/modules/components/block-status/examples/2/index.ts
  projects/demo/src/modules/components/calendar/examples/1/index.less
  projects/demo/src/modules/components/calendar/examples/1/index.ts
  projects/demo/src/modules/components/calendar/examples/4/index.less
  projects/demo/src/modules/components/calendar/examples/4/index.ts
  projects/demo/src/modules/components/calendar/examples/6/index.less
  projects/demo/src/modules/components/calendar/examples/6/index.ts
  projects/demo/src/modules/components/calendar/examples/7/index.less
  projects/demo/src/modules/components/calendar/examples/7/index.ts
  projects/demo/src/modules/components/card-large/examples/12/index.less
  projects/demo/src/modules/components/card-large/examples/13/index.less
  projects/demo/src/modules/components/card-large/examples/2/index.less
  projects/demo/src/modules/components/card-large/examples/5/index.less
  projects/demo/src/modules/components/card-large/examples/8/index.less
  projects/demo/src/modules/components/icon/examples/3/index.less
  projects/demo/src/modules/components/preview/examples/2/index.less
  projects/demo/src/modules/components/preview/examples/2/index.ts
  projects/demo/src/modules/components/rating/examples/3/index.less
  projects/demo/src/modules/components/stepper/examples/1/index.less
  projects/demo/src/modules/components/stepper/examples/2/index.less
  projects/demo/src/modules/components/stepper/examples/4/index.less
  projects/demo/src/modules/components/table/examples/7/index.less
  projects/demo/src/modules/components/table/examples/7/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.less
  projects/demo/src/modules/directives/hint/examples/3/index.less
  projects/demo/src/modules/directives/progress-segmented/examples/1/index.less
Labels: ready to merge

#9838 fix(legacy): `InputDateTime` validators not triggered when value change
  projects/demo-playwright/tests/legacy/input-date-time/input-date-time.pw.spec.ts
  projects/demo/src/modules/components/input-date-time/examples/7/index.html
  projects/demo/src/modules/components/input-date-time/examples/7/index.ts
  projects/demo/src/modules/components/input-date-time/index.html
  projects/legacy/components/input-date-time/input-date-time.component.ts
Labels: ready to merge

#9850 chore(demo): do not ddos free github api from localhost
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge

#9852 ci: do not forward params by default
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-table/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/experimental/project.json
  projects/i18n/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/legacy/project.json
  projects/taiga-schematics/project.json
  projects/testing/project.json
Labels: ready to merge

#9846 fix(kit): `InputDateTime` validators not triggered when value change
  projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
  projects/demo/src/modules/components/input-date-time/examples/6/index.html
  projects/demo/src/modules/components/input-date-time/examples/6/index.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.component.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.module.ts
  projects/demo/src/modules/components/input-date-time/input-date-time.template.html
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: ready to merge, v3

#9820 fix(layout): `Navigation` fix aside width according to spec
  projects/experimental/components/navigation/aside.style.less
Labels: ready to merge, v3

#9866 chore: exclude broken unit test
  projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
Labels: ready to merge

#9868 chore: make StackBlitz great again for `v3` documentation
  package-lock.json
  projects/demo/package.json
Labels: v3

#9864 fix(kit): `Carousel` fix dragging in chrome
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/carousel/carousel.style.less
  projects/kit/components/carousel/carousel.template.html
Labels: ready to merge
