Repository taiga-family/taiga-ui, pull requests merged in 2024-01, with the labels that each got.

#6409 fix(i18n): fix Chinese translation of country names
  projects/i18n/languages/chinese/countries.ts
Labels: v4

#6417 feat(kit): `File` add ability to customize icons
  projects/cdk/constants/used-icons.ts
  projects/kit/components/files/file/file-options.ts
  projects/kit/components/files/file/file.component.ts
  projects/kit/components/files/file/file.template.html
Labels: v4

#6422 chore: hide warnings
  projects/demo/tsconfig.app.json
  tsconfig.json
Labels: ready to merge

#6433 chore(kit): `InputYear` fix max-height
  projects/kit/components/input-year/input-year.style.less
Labels: v3

#6459 fix(addon-mobile): add smooth opacity change for `MobileCalendar` to hide blinking initial view
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
  projects/cdk/constants/version.ts
Labels: v3

#6491 feat(kit): `Sensitive` increase number of rows for larger sizes
  projects/demo/src/modules/experimental/sensitive/examples/1/index.html
  projects/demo/src/modules/experimental/sensitive/examples/1/index.less
  projects/demo/src/modules/experimental/sensitive/examples/1/index.ts
  projects/demo/src/modules/experimental/sensitive/examples/2/index.html
  projects/demo/src/modules/experimental/sensitive/sensitive.component.ts
  projects/experimental/directives/sensitive/sensitive.directive.ts
  projects/experimental/directives/sensitive/sensitive.style.less
Labels: ready to merge

#6492 feat(kit): Sensitive increase number of rows for larger sizes
  projects/demo/src/modules/experimental/sensitive/examples/1/index.html
  projects/demo/src/modules/experimental/sensitive/examples/1/index.less
  projects/demo/src/modules/experimental/sensitive/examples/1/index.ts
  projects/demo/src/modules/experimental/sensitive/examples/2/index.html
  projects/demo/src/modules/experimental/sensitive/sensitive.component.ts
  projects/experimental/directives/sensitive/sensitive.directive.ts
  projects/experimental/directives/sensitive/sensitive.style.less
Labels: v3

#6487 chore: remove unused packages
  package-lock.json
  package.json
  projects/demo-cypress/cypress/support/e2e.ts
  projects/demo-cypress/tsconfig.json
Labels: ready to merge

#6480 refactor!: move new `BadgedContent` to kit, turn to standalone, add migration
  .cspell.json
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
  projects/cdk/schematics/ng-update/v4/steps/utils/remove-attrs.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
  projects/cdk/schematics/utils/templates/inputs.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/badged-content/badged-content.component.ts
  projects/demo/src/modules/components/badged-content/badged-content.module.ts
  projects/demo/src/modules/components/badged-content/badged-content.template.html
  projects/demo/src/modules/components/badged-content/examples/1/index.html
  projects/demo/src/modules/components/badged-content/examples/1/index.less
  projects/demo/src/modules/components/badged-content/examples/1/index.ts
  projects/demo/src/modules/components/badged-content/examples/2/index.html
  projects/demo/src/modules/components/badged-content/examples/2/index.less
  projects/demo/src/modules/components/badged-content/examples/2/index.ts
  projects/demo/src/modules/components/badged-content/examples/3/index.html
  projects/demo/src/modules/components/badged-content/examples/3/index.less
  projects/demo/src/modules/components/badged-content/examples/3/index.ts
  projects/demo/src/modules/components/badged-content/examples/import/import-module.md
  projects/demo/src/modules/components/badged-content/examples/import/insert-template.md
  projects/demo/src/modules/experimental/badged-content/badged-content.component.ts
  projects/demo/src/modules/experimental/badged-content/badged-content.module.ts
  projects/demo/src/modules/experimental/badged-content/badged-content.template.html
  projects/demo/src/modules/experimental/badged-content/examples/1/index.html
  projects/demo/src/modules/experimental/badged-content/examples/1/index.ts
  projects/demo/src/modules/experimental/badged-content/examples/2/index.html
  projects/demo/src/modules/experimental/badged-content/examples/2/index.less
  projects/demo/src/modules/experimental/badged-content/examples/2/index.ts
  projects/demo/src/modules/experimental/badged-content/examples/3/index.html
  projects/demo/src/modules/experimental/badged-content/examples/3/index.ts
  projects/demo/src/modules/experimental/badged-content/examples/import/import-module.md
  projects/demo/src/modules/experimental/badged-content/examples/import/insert-template.md
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/chip/chip.module.ts
  projects/demo/used-icons.ts
  projects/experimental/components/badged-content/badged-content.component.ts
  projects/experimental/components/badged-content/badged-content.module.ts
  projects/experimental/components/badged-content/badged-content.style.less
  projects/experimental/components/badged-content/badged-content.template.html
  projects/experimental/components/badged-content/index.ts
  projects/experimental/components/badged-content/ng-package.json
  projects/experimental/components/index.ts
  projects/kit/components/badged-content/badged-content.component.ts
  projects/kit/components/badged-content/badged-content.directive.ts
  projects/kit/components/badged-content/badged-content.module.ts
  projects/kit/components/badged-content/badged-content.style.less
  projects/kit/components/badged-content/badged-content.template.html
  projects/kit/components/badged-content/index.ts
Labels: ready to merge

#6494 chore: use caret symbol to fixate `@taiga-ui/*` peer deps (instead of `>=`)
  package-lock.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-preview/package.json
  projects/addon-table/package.json
  projects/addon-tablebars/package.json
  projects/core/package.json
  projects/experimental/package.json
  projects/icons/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge, v3

#6496 chore: use caret symbol to fixate `@taiga-ui/*` peer deps (instead of `>=`)
  package-lock.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-preview/package.json
  projects/addon-table/package.json
  projects/addon-tablebars/package.json
  projects/core/package.json
  projects/experimental/package.json
  projects/icons/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge

#6500 fix(core): prevent TuiRoot from applying CSS syles to the body element without Taiga UI context - v3
  projects/core/components/root/root.style.less
Labels: community contribution

#6506 ci: add `networkidle` for stable flaky tests
  .cspell.json
  projects/demo-playwright/tests/core/dialogs/dialog-browser-back.spec.ts
  projects/demo-playwright/tests/deep/deep-select.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.spec.ts
  projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
Labels: ready to merge

#6511 feat(experimental): `Segmented` add new component
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.module.ts
  projects/addon-doc/components/example/example.template.html
  projects/cdk/utils/dom/element-checks.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/segmented/examples/1/index.html
  projects/demo/src/modules/experimental/segmented/examples/1/index.less
  projects/demo/src/modules/experimental/segmented/examples/1/index.ts
  projects/demo/src/modules/experimental/segmented/examples/2/index.html
  projects/demo/src/modules/experimental/segmented/examples/2/index.less
  projects/demo/src/modules/experimental/segmented/examples/2/index.ts
  projects/demo/src/modules/experimental/segmented/examples/3/index.html
  projects/demo/src/modules/experimental/segmented/examples/3/index.less
  projects/demo/src/modules/experimental/segmented/examples/3/index.ts
  projects/demo/src/modules/experimental/segmented/examples/4/index.html
  projects/demo/src/modules/experimental/segmented/examples/4/index.less
  projects/demo/src/modules/experimental/segmented/examples/4/index.ts
  projects/demo/src/modules/experimental/segmented/examples/import/import-module.md
  projects/demo/src/modules/experimental/segmented/examples/import/insert-template.md
  projects/demo/src/modules/experimental/segmented/segmented.component.ts
  projects/demo/src/modules/experimental/segmented/segmented.module.ts
  projects/demo/src/modules/experimental/segmented/segmented.template.html
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/experimental/components/segmented/index.ts
  projects/experimental/components/segmented/ng-package.json
  projects/experimental/components/segmented/segmented.component.ts
  projects/experimental/components/segmented/segmented.directive.ts
  projects/experimental/components/segmented/segmented.module.ts
  projects/experimental/components/segmented/segmented.style.less
  projects/kit/components/tabs/tab/tab.component.ts
  projects/kit/components/tabs/tab/tab.style.less
Labels: ready to merge

#6502 chore: fix eslint
  scripts/shared/overwrite-version.ts
Labels: ready to merge, v4

#6504 chore: fix eslint
  scripts/shared/overwrite-version.ts
Labels: ready to merge, v3

#6501 chore(demo): remove `next` configuration
  projects/demo/project.json
Labels: ready to merge

#6519 chore: cleanup CHANGELOG.md
  CHANGELOG.md
Labels: v3

#6528 refactor(addon-mobile): use `TuiLoaderModule` inside `TUI_ANDROID_LOADER`
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less
  projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.template.html
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.module.ts
Labels: ready to merge

#6534 fix(core): `HostedDropdown` fix binding error in test environment
  projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
Labels: v3

#6523 feat(experimental): add `tui-avatar-labeled`
  projects/demo/src/modules/experimental/avatar/avatar.component.ts
  projects/demo/src/modules/experimental/avatar/avatar.module.ts
  projects/demo/src/modules/experimental/avatar/avatar.template.html
  projects/demo/src/modules/experimental/avatar/examples/6/index.html
  projects/demo/src/modules/experimental/avatar/examples/6/index.less
  projects/demo/src/modules/experimental/avatar/examples/6/index.ts
  projects/experimental/components/avatar-labelled/avatar-labeled.component.ts
  projects/experimental/components/avatar-labelled/avatar-labeled.module.ts
  projects/experimental/components/avatar-labelled/avatar-labeled.styles.less
  projects/experimental/components/avatar-labelled/index.ts
  projects/experimental/components/avatar-labelled/ng-package.json
  projects/experimental/components/index.ts
Labels: v3

#6540 feat(experimental): add `tui-avatar-labeled`
  projects/demo/src/modules/experimental/avatar/avatar.component.ts
  projects/demo/src/modules/experimental/avatar/avatar.module.ts
  projects/demo/src/modules/experimental/avatar/avatar.template.html
  projects/demo/src/modules/experimental/avatar/examples/6/index.html
  projects/demo/src/modules/experimental/avatar/examples/6/index.less
  projects/demo/src/modules/experimental/avatar/examples/6/index.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.component.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.styles.less
  projects/experimental/components/avatar-labeled/index.ts
  projects/experimental/components/avatar-labeled/ng-package.json
  projects/experimental/components/index.ts
Labels: v4

#6541 refactor: rename directory
  projects/experimental/components/avatar-labeled/avatar-labeled.component.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.module.ts
  projects/experimental/components/avatar-labeled/avatar-labeled.styles.less
  projects/experimental/components/avatar-labeled/index.ts
  projects/experimental/components/avatar-labeled/ng-package.json
  projects/experimental/components/index.ts
Labels: v3

#6527 feat(experimental): `Segmented` add new component
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.module.ts
  projects/addon-doc/components/example/example.template.html
  projects/cdk/utils/dom/element-checks.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/segmented/examples/1/index.html
  projects/demo/src/modules/experimental/segmented/examples/1/index.less
  projects/demo/src/modules/experimental/segmented/examples/1/index.ts
  projects/demo/src/modules/experimental/segmented/examples/2/index.html
  projects/demo/src/modules/experimental/segmented/examples/2/index.less
  projects/demo/src/modules/experimental/segmented/examples/2/index.ts
  projects/demo/src/modules/experimental/segmented/examples/3/index.html
  projects/demo/src/modules/experimental/segmented/examples/3/index.less
  projects/demo/src/modules/experimental/segmented/examples/3/index.ts
  projects/demo/src/modules/experimental/segmented/examples/4/index.html
  projects/demo/src/modules/experimental/segmented/examples/4/index.less
  projects/demo/src/modules/experimental/segmented/examples/4/index.ts
  projects/demo/src/modules/experimental/segmented/examples/import/import-module.md
  projects/demo/src/modules/experimental/segmented/examples/import/insert-template.md
  projects/demo/src/modules/experimental/segmented/segmented.component.ts
  projects/demo/src/modules/experimental/segmented/segmented.module.ts
  projects/demo/src/modules/experimental/segmented/segmented.template.html
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/experimental/components/segmented/index.ts
  projects/experimental/components/segmented/ng-package.json
  projects/experimental/components/segmented/segmented.component.ts
  projects/experimental/components/segmented/segmented.directive.ts
  projects/experimental/components/segmented/segmented.style.less
  projects/kit/components/tabs/tab/tab.component.ts
  projects/kit/components/tabs/tab/tab.style.less
Labels: ready to merge, v4

#6538 feat(core): `Loader` has new animation
  projects/core/components/loader/loader.style.less
  projects/core/components/loader/loader.template.html
Labels: ready to merge, v4

#6542 refactor(core)!: replace `TUI_ANIMATIONS_DURATION` with `TUI_ANIMATIONS_SPEED`
  projects/addon-charts/components/pie-chart/pie-chart.directive.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts
  projects/addon-mobile/components/tab-bar/tab-bar-item.template.html
  projects/addon-mobile/directives/sidebar/sidebar.component.ts
  projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts
  projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html
  projects/core/components/alert/alert.component.ts
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/error/error.component.ts
  projects/core/components/error/error.template.html
  projects/core/components/root/root.component.ts
  projects/core/components/scroll-controls/scroll-controls.component.ts
  projects/core/components/scroll-controls/scroll-controls.template.html
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/interfaces/animation-options.ts
  projects/core/interfaces/index.ts
  projects/core/tokens/animation-options.ts
  projects/core/tokens/animations-duration.ts
  projects/core/tokens/animations-speed.ts
  projects/core/tokens/index.ts
  projects/core/utils/miscellaneous/index.ts
  projects/core/utils/miscellaneous/to-animation-options.ts
  projects/experimental/components/badge-notification/badge-notification.component.ts
  projects/kit/components/pdf-viewer/pdf-viewer.component.ts
  projects/kit/components/push/push-alert.component.ts
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#6552 chore(demo): set landing as standalone
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/landing/landing.component.ts
  projects/demo/src/modules/app/landing/landing.module.ts
  projects/demo/src/modules/app/landing/landing.style.less
  projects/demo/src/modules/app/landing/landing.template.html
Labels: ready to merge

#6554 fix(cdk): when the consumer unsubscribes, clean up data ready for next subscription
  projects/cdk/observables/control-value.ts
Labels: ready to merge, v4

#6558 ci: fail fast
  .github/workflows/test.yml
  package.json
Labels: ready to merge

#6563 chore(demo): set browser page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/browsers/browsers.component.ts
  projects/demo/src/modules/info/browsers/browsers.module.ts
Labels: ready to merge

#6555 refactor(cdk)!: `Autofill` remove directive
  projects/cdk/directives/autofilled/autofilled-style.component.ts
  projects/cdk/directives/autofilled/autofilled.directive.ts
  projects/cdk/directives/autofilled/autofilled.module.ts
  projects/cdk/directives/autofilled/autofilled.style.less
  projects/cdk/directives/autofilled/index.ts
  projects/cdk/directives/autofilled/ng-package.json
  projects/cdk/directives/autofilled/test/autofilled.directive.spec.ts
  projects/cdk/directives/for-async/for-async.directive.ts
  projects/cdk/directives/for-async/for-async.module.ts
  projects/cdk/directives/for-async/index.ts
  projects/cdk/directives/for-async/ng-package.json
  projects/cdk/directives/for-async/test/for.directive.spec.ts
  projects/cdk/directives/high-dpi/high-dpi.directive.ts
  projects/cdk/directives/high-dpi/high-dpi.module.ts
  projects/cdk/directives/high-dpi/index.ts
  projects/cdk/directives/index.ts
  projects/cdk/directives/media/index.ts
  projects/cdk/directives/media/media.directive.ts
  projects/cdk/directives/media/media.module.ts
  projects/core/components/primitive-textfield/primitive-textfield.module.ts
  projects/core/components/primitive-textfield/primitive-textfield.template.html
  projects/demo/src/modules/directives/media/examples/import/import-module.md
  projects/demo/src/modules/directives/media/media.module.ts
  projects/demo/src/modules/directives/media/media.template.html
Labels: ready to merge

#6549 ci: add prerender e2e asserts
  .cspell.json
  .github/workflows/e2e.yml
  .github/workflows/snapshots.yml
  projects/demo-playwright/tests/ssg.spec.ts
Labels: ready to merge

#6483 feat(core): applies styles only inside taiga context
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.style.less
Labels: ready to merge

#6569 chore(core): `Loader` uses `em` units for `<circle />` (Safari workaround)
  projects/core/components/loader/loader.style.less
Labels: ready to merge

#6566 chore(demo): set ssr page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/ssr/ssr.component.ts
  projects/demo/src/modules/info/ssr/ssr.module.ts
Labels: ready to merge

#6565 chore(demo): set changelog page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/changelog/changelog.component.ts
  projects/demo/src/modules/info/changelog/changelog.module.ts
Labels: ready to merge

#6561 chore(demo): set getting-started as standalone
  projects/demo/src/modules/app/app.browser.module.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/getting-started/getting-started.component.ts
  projects/demo/src/modules/app/getting-started/getting-started.module.ts
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/app/home/home.module.ts
Labels: ready to merge

#6548 chore(demo): explicit `ng-dev-mode`
  package-lock.json
  package.json
  projects/addon-doc/utils/to-flat-map-pages.ts
  projects/addon-tablebars/services/table-bars.service.ts
  projects/cdk/abstract/control.ts
  projects/cdk/classes/assert.ts
  projects/cdk/date-time/day-range.ts
  projects/cdk/date-time/day.ts
  projects/cdk/date-time/month-range.ts
  projects/cdk/date-time/month.ts
  projects/cdk/date-time/time.ts
  projects/cdk/date-time/year.ts
  projects/cdk/decorators/default-prop.ts
  projects/cdk/exceptions/computed-document.exception.ts
  projects/cdk/exceptions/document-selection.exception.ts
  projects/cdk/exceptions/invalid-day.exception.ts
  projects/cdk/exceptions/invalid-year.exception.ts
  projects/cdk/exceptions/no-host.exception.ts
  projects/cdk/exceptions/owner-document.exception.ts
  projects/cdk/exceptions/pure.exception.ts
  projects/cdk/exceptions/table-sort-key.exception.ts
  projects/cdk/exceptions/ts-parser.exception.ts
  projects/cdk/exceptions/value-changes.exception.ts
  projects/cdk/exceptions/xml-parsing.exception.ts
  projects/cdk/schematics/tsconfig.schematics.json
  projects/cdk/services/scroll.service.ts
  projects/cdk/utils/dom/get-element-offset.ts
  projects/cdk/utils/format/px.ts
  projects/cdk/utils/math/clamp.ts
  projects/cdk/utils/math/in-range.ts
  projects/cdk/utils/math/normalize-to-int-number.ts
  projects/cdk/utils/math/quantize.ts
  projects/cdk/utils/math/round.ts
  projects/cdk/utils/miscellaneous/ease-in-out-quad.ts
  projects/core/components/svg/svg.component.ts
  projects/core/pipes/calendar-sheet/utils.ts
  projects/core/pipes/format-phone/format-phone.pipe.ts
  projects/core/services/svg.service.ts
  projects/core/utils/mask/create-auto-corrected-money-pipe.ts
  projects/core/utils/mask/create-correction-mask.ts
  projects/core/utils/mask/create-number-mask.ts
  projects/demo-cypress/tsconfig.json
  projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.component.ts
  tsconfig.json
Labels: ready to merge

#6591 chore: export `TUI_ANIMATIONS_DEFAULT_DURATION`
  projects/core/utils/miscellaneous/to-animation-options.ts
Labels: ready to merge

#6581 fix(cdk): `endWith` should be pass after `takeUntil`
  projects/cdk/services/scroll.service.ts
Labels: ready to merge, v3

#6550 feat(core)!: `Loader` has new algorithm to calculate `stroke-width`
  projects/core/components/loader/loader.component.ts
  projects/core/components/loader/loader.style.less
  projects/core/components/loader/loader.template.html
  projects/demo/src/modules/components/loader/examples/5/index.html
  projects/demo/src/modules/components/loader/examples/5/index.less
  projects/demo/src/modules/components/loader/examples/5/index.ts
  projects/demo/src/modules/components/loader/loader.component.ts
  projects/demo/src/modules/components/loader/loader.module.ts
  projects/demo/src/modules/components/loader/loader.template.html
Labels: ready to merge

#6570 chore(demo): set doc page as standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/info/doc/doc.component.ts
  projects/demo/src/modules/info/doc/doc.module.ts
Labels: ready to merge

#6595 feat(kit): use the full height for input files label
  projects/kit/components/input-files/input-files.style.less
Labels: v3

#6606 fix(addon-table): `tuiCell` conflicts
  projects/addon-table/components/table/directives/cell.directive.ts
Labels: v3

#6605 chore: revert regression
  package-lock.json
  package.json
Labels: ready to merge

#6611 feat(core): notification content by default should be break by word
  .cspell.json
  projects/core/components/notification/notification.style.less
  projects/demo-playwright/tests/kit/notification/notification.spec.ts
Labels: v3

#6594 feat(kit): use the full height for input files label
  projects/kit/components/input-files/input-files.style.less
Labels: v4

#6624 feat(cdk): scroll controls should be visible only inside tui-root area
  projects/cdk/components/dialog-host/dialog-host.component.ts
  projects/cdk/components/scroll-controls/scroll-controls.style.less
  projects/core/components/root/root.component.ts
Labels: ready to merge, v3

#6593 chore(demo): fix icons for Safari
  projects/demo/src/assets/icons/html.svg
  projects/demo/src/assets/icons/npm.svg
  projects/demo/src/assets/icons/nx.svg
Labels: v3

#6526 feat(experimental): `SwipeActions` add new component
  projects/addon-doc/components/internal/header/header.component.ts
  projects/core/styles/mixins/mixins.less
  projects/demo/src/modules/app/app.providers.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/experimental/swipe-action/examples/1/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/1/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/1/index.ts
  projects/demo/src/modules/experimental/swipe-action/examples/2/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/2/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/2/index.ts
  projects/demo/src/modules/experimental/swipe-action/examples/3/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/3/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/3/index.ts
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/4/index.ts
  projects/demo/src/modules/experimental/swipe-action/examples/5/index.html
  projects/demo/src/modules/experimental/swipe-action/examples/5/index.less
  projects/demo/src/modules/experimental/swipe-action/examples/5/index.ts
  projects/demo/src/modules/experimental/swipe-action/examples/import/import-module.md
  projects/demo/src/modules/experimental/swipe-action/examples/import/insert-template.md
  projects/demo/src/modules/experimental/swipe-action/swipe-actions.component.ts
  projects/demo/src/modules/experimental/swipe-action/swipe-actions.module.ts
  projects/demo/src/modules/experimental/swipe-action/swipe-actions.template.html
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/experimental/components/swipe-action/index.ts
  projects/experimental/components/swipe-action/ng-package.json
  projects/experimental/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/experimental/components/swipe-action/swipe-actions.component.ts
  projects/experimental/components/swipe-action/swipe-actions.module.ts
  projects/experimental/components/swipe-action/swipe-actions.style.less
  projects/experimental/components/swipe-action/swipe-actions.template.html
  projects/experimental/directives/cell/cell.styles.less
Labels: ready to merge, v3

#6623 feat(cdk): scroll controls should be visible only inside tui-root area
  projects/cdk/components/dialog-host/dialog-host.component.ts
  projects/cdk/components/scroll-controls/scroll-controls.style.less
  projects/core/components/root/root.component.ts
Labels: v4

#6610 feat(core): notification content by default should be break by word
  projects/core/components/notification/notification.style.less
  projects/demo-playwright/tests/kit/notification/notification.spec.ts
Labels: v4
