Repository taiga-family/taiga-ui, pull requests merged in 2024-04, with the labels that each got.

#7136 chore: fix proprietary build for feed-item
  projects/kit/components/checkbox/checkbox.component.ts
Labels: ready to merge

#7135 chore: fix proprietary build
  projects/demo/src/modules/app/server-error-handler.ts
Labels: ready to merge

#7141 feat(core): support override dropdown selection
  projects/core/directives/dropdown/dropdown-selection.directive.ts
Labels: ready to merge

#7145 fix(kit): `InputDate` fix opening mobile calendar in read-only mode
  projects/kit/components/input-date/input-date.component.ts
Labels: v4

#7144 fix(kit): `InputDate` fix opening mobile calendar in read-only mode
  projects/kit/components/input-date/input-date.component.ts
Labels: v3

#7147 chore: bump editor version
  package-lock.json
  package.json
Labels: v3

#7146 feat(core): support override dropdown selection
  projects/core/directives/dropdown/dropdown-selection.directive.ts
Labels: v4

#7148 chore(demo): cleanup
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/getting-started/index.html
  projects/demo/src/modules/app/getting-started/index.ts
  projects/demo/src/modules/app/landing/index.html
  projects/demo/src/modules/app/landing/index.less
  projects/demo/src/modules/app/landing/index.ts
  projects/demo/src/modules/components/accordion/index.html
  projects/demo/src/modules/components/accordion/index.ts
  projects/demo/src/modules/components/action/index.html
  projects/demo/src/modules/components/action/index.ts
  projects/demo/src/modules/components/avatar/index.ts
  projects/demo/src/modules/components/badge/index.html
  projects/demo/src/modules/components/badge/index.ts
  projects/demo/src/modules/components/compass/index.ts
  projects/demo/src/modules/components/pin/index.ts
  projects/demo/src/modules/components/rating/index.ts
  projects/demo/src/modules/components/stepper/stepper.component.ts
  projects/demo/src/modules/customization/dialogs/index.html
  projects/demo/src/modules/customization/dialogs/index.ts
  projects/demo/src/modules/customization/i18n/index.html
  projects/demo/src/modules/customization/i18n/index.ts
  projects/demo/src/modules/customization/portals/index.html
  projects/demo/src/modules/customization/portals/index.ts
  projects/demo/src/modules/customization/routable/eager/index.html
  projects/demo/src/modules/customization/routable/eager/index.ts
  projects/demo/src/modules/customization/routable/eager/routes.ts
  projects/demo/src/modules/customization/routable/lazy/index.html
  projects/demo/src/modules/customization/routable/lazy/index.ts
  projects/demo/src/modules/customization/routable/lazy/routes.ts
  projects/demo/src/modules/customization/variables/index.html
  projects/demo/src/modules/customization/variables/index.ts
  projects/demo/src/modules/customization/viewport/index.html
  projects/demo/src/modules/customization/viewport/index.ts
  projects/demo/src/modules/customization/wrapper/index.html
  projects/demo/src/modules/customization/wrapper/index.ts
  projects/demo/src/modules/directives/date-format/index.ts
  projects/demo/src/modules/directives/header/index.ts
  projects/demo/src/modules/directives/progress-segmented/index.ts
  projects/demo/src/modules/info/browsers/index.html
  projects/demo/src/modules/info/browsers/index.ts
  projects/demo/src/modules/info/changelog/index.html
  projects/demo/src/modules/info/changelog/index.less
  projects/demo/src/modules/info/changelog/index.ts
  projects/demo/src/modules/info/doc/index.html
  projects/demo/src/modules/info/doc/index.ts
  projects/demo/src/modules/info/related/index.html
  projects/demo/src/modules/info/related/index.less
  projects/demo/src/modules/info/related/index.ts
  projects/demo/src/modules/info/ssr/index.html
  projects/demo/src/modules/info/ssr/index.ts
  projects/demo/src/modules/info/testing/disable-animation/index.html
  projects/demo/src/modules/info/testing/disable-animation/index.less
  projects/demo/src/modules/info/testing/disable-animation/index.ts
  projects/demo/src/modules/info/testing/jest/index.html
  projects/demo/src/modules/info/testing/jest/index.ts
  projects/demo/src/modules/info/testing/screenshot-github-bot/index.html
  projects/demo/src/modules/info/testing/screenshot-github-bot/index.less
  projects/demo/src/modules/info/testing/screenshot-github-bot/index.ts
  projects/demo/used-icons.ts
Labels: ready to merge

#7151 fix(core): fix custom position accessors
  projects/core/abstract/accessors.ts
  projects/core/abstract/index.ts
  projects/core/abstract/position-accessor.ts
  projects/core/abstract/rect-accessor.ts
  projects/core/directives/dropdown/dropdown-position.directive.ts
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
  projects/kit/components/line-clamp/line-clamp-position.directive.ts
  projects/kit/components/line-clamp/line-clamp.template.html
Labels: ready to merge

#7155 fix(cdk): `ActiveZone` fix event handling for IOS Safari
  projects/cdk/directives/active-zone/active-zone.directive.ts
Labels: ready to merge, v3

#7152 chore: refactor accessors
  projects/core/abstract/accessors.ts
  projects/core/abstract/index.ts
  projects/core/abstract/position-accessor.ts
  projects/core/abstract/rect-accessor.ts
  projects/core/directives/dropdown/dropdown-position.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/demo/src/modules/directives/dropdown-open/examples/5/index.html
Labels: ready to merge

#7153 feat(kit): `Chevron` add new directive
  projects/core/components/button/button.style.less
  projects/core/components/link/link.component.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/demo/src/modules/components/data-list/data-list.module.ts
  projects/demo/src/modules/components/data-list/data-list.template.html
  projects/demo/src/modules/components/data-list/examples/1/index.html
  projects/demo/src/modules/components/data-list/examples/3/index.html
  projects/demo/src/modules/components/data-list/examples/6/index.html
  projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html
  projects/demo/src/modules/components/line-clamp/examples/4/index.html
  projects/demo/src/modules/components/tabs/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-open/dropdown-open.module.ts
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.less
  projects/demo/src/modules/directives/dropdown-open/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/4/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown/dropdown.module.ts
  projects/demo/src/modules/directives/dropdown/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/examples/1/index.html
  projects/demo/src/modules/experimental/navigation/examples/2/index.html
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/demo/src/modules/experimental/textfield/examples/3/index.html
  projects/demo/src/modules/experimental/textfield/textfield.module.ts
  projects/demo/src/modules/tables/table/examples/4/index.html
  projects/demo/src/modules/tables/table/table.module.ts
  projects/kit/directives/chevron/chevron.component.ts
  projects/kit/directives/chevron/chevron.directive.ts
  projects/kit/directives/chevron/chevron.service.ts
  projects/kit/directives/chevron/chevron.style.less
  projects/kit/directives/chevron/index.ts
  projects/kit/directives/chevron/ng-package.json
  projects/kit/directives/index.ts
Labels: ready to merge

#7158 chore: remove code which doesn't work properly
  projects/demo-playwright/tests/addon-doc/code.spec.ts
  projects/demo-playwright/tests/deep/deep-select.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.spec.ts
  projects/demo-playwright/tests/demo/demo.spec.ts
  projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
  projects/demo-playwright/tests/kit/dropdown-selection/dropdown-selection.spec.ts
  projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
Labels: ready to merge

#7159 chore: add missing icons for editor
  projects/icons/all.ts
  projects/icons/src/tuiIconAddRowOutline.svg
  projects/icons/src/tuiIconCheckCircleOutline.svg
  projects/icons/src/tuiIconClearFormatOutline.svg
  projects/icons/src/tuiIconColorOutline.svg
  projects/icons/src/tuiIconFontOutline.svg
  projects/icons/src/tuiIconFormatOutline.svg
  projects/icons/src/tuiIconHiliteOutline.svg
  projects/icons/src/tuiIconHrOutline.svg
  projects/icons/src/tuiIconIndentOutline.svg
  projects/icons/src/tuiIconOLOutline.svg
  projects/icons/src/tuiIconOutdentOutline.svg
  projects/icons/src/tuiIconPaintOutline.svg
  projects/icons/src/tuiIconQuoteOutline.svg
  projects/icons/src/tuiIconRedoOutline.svg
  projects/icons/src/tuiIconSpoilerDeleteOutline.svg
  projects/icons/src/tuiIconSpoilerOutline.svg
  projects/icons/src/tuiIconStrikeThroughOutline.svg
  projects/icons/src/tuiIconSubscriptOutline.svg
  projects/icons/src/tuiIconTeXOutline.svg
  projects/icons/src/tuiIconUndoOutline.svg
  projects/icons/src/tuiIconUnlinkOutline.svg
Labels: ready to merge

#7163 chore: forgot add two icons
  projects/icons/all.ts
  projects/icons/src/tuiIconSuperscriptOutline.svg
  projects/icons/src/tuiIconTableSplitOutline.svg
Labels: ready to merge

#7096 chore: remove redundant imports
  projects/demo/src/modules/app/home/examples/main-standalone-optional.md
  projects/demo/src/modules/app/home/examples/main-standalone.md
  projects/demo/src/modules/app/home/home.component.ts
  projects/demo/src/modules/app/home/home.template.html
Labels: ready to merge, v4

#7177 refactor(kit): `Tabs` use `Icons`
  projects/demo/src/modules/components/tabs/examples/1/index.html
  projects/demo/src/modules/components/tabs/examples/2/index.html
  projects/demo/src/modules/components/tabs/examples/3/index.html
  projects/demo/src/modules/components/tabs/examples/4/index.html
  projects/demo/src/modules/components/tabs/examples/4/index.less
  projects/demo/src/modules/components/tabs/examples/5/index.html
  projects/demo/src/modules/components/tabs/tabs.module.ts
  projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.module.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/2/index.html
  projects/kit/components/tabs/tab.directive.ts
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/kit/components/tabs/tabs-with-more.template.html
  projects/kit/components/tabs/tabs.style.less
Labels: ready to merge

#7161 chore: fix changelog
  CHANGELOG.md
Labels: ready to merge, v3

#7162 chore: specify the branch for action
  .github/workflows/create-release.yml
Labels: ready to merge, v3

#7192 refactor!: `Segmented` move to `kit` package
  package.json
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/segmented/examples/1/index.html
  projects/demo/src/modules/components/segmented/examples/1/index.less
  projects/demo/src/modules/components/segmented/examples/1/index.ts
  projects/demo/src/modules/components/segmented/examples/2/index.html
  projects/demo/src/modules/components/segmented/examples/2/index.less
  projects/demo/src/modules/components/segmented/examples/2/index.ts
  projects/demo/src/modules/components/segmented/examples/3/index.html
  projects/demo/src/modules/components/segmented/examples/3/index.less
  projects/demo/src/modules/components/segmented/examples/3/index.ts
  projects/demo/src/modules/components/segmented/examples/4/index.html
  projects/demo/src/modules/components/segmented/examples/4/index.less
  projects/demo/src/modules/components/segmented/examples/4/index.ts
  projects/demo/src/modules/components/segmented/examples/import/import.md
  projects/demo/src/modules/components/segmented/examples/import/template.md
  projects/demo/src/modules/components/segmented/index.html
  projects/demo/src/modules/components/segmented/index.ts
  projects/demo/src/modules/experimental/segmented/examples/2/index.ts
  projects/demo/src/modules/experimental/segmented/segmented.component.ts
  projects/demo/src/modules/experimental/segmented/segmented.module.ts
  projects/demo/src/modules/experimental/segmented/segmented.template.html
  projects/demo/used-icons.ts
  projects/experimental/components/index.ts
  projects/kit/components/index.ts
  projects/kit/components/segmented/index.ts
  projects/kit/components/segmented/ng-package.json
  projects/kit/components/segmented/segmented.component.ts
  projects/kit/components/segmented/segmented.directive.ts
  projects/kit/components/segmented/segmented.style.less
Labels: ready to merge, v4

#7198 chore(demo): reuse styles between proprietary repo
  projects/demo/project.json
  projects/demo/src/styles/doc-global.style.less
  projects/demo/src/styles/normalize.less
  projects/demo/src/styles/styles.less
  projects/demo/src/styles/styles.scss
Labels: ready to merge

#7194 chore(demo): migrate documentation page `Breadcrumbs` to standalone components
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/breadcrumbs/breadcrumbs.module.ts
  projects/demo/src/modules/components/breadcrumbs/examples/1/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/1/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/import/import.md
  projects/demo/src/modules/components/breadcrumbs/examples/import/template.md
  projects/demo/src/modules/components/breadcrumbs/index.html
  projects/demo/src/modules/components/breadcrumbs/index.ts
Labels: ready to merge

#7200 chore: update LICENSE holder
  .cspell.json
  LICENSE
Labels: ready to merge

#7207 refactor(cdk): deprecate `Interactive`
  projects/core/components/primitive-spin-button/primitive-spin-button.component.ts
  projects/core/components/primitive-spin-button/primitive-spin-button.template.html
  projects/core/components/primitive-spin-button/test/primitive-spin-button.component.spec.ts
  projects/kit/components/accordion/accordion-item/accordion-item.component.ts
  projects/kit/components/accordion/accordion-item/accordion-item.style.less
  projects/kit/components/accordion/accordion-item/accordion-item.template.html
  projects/kit/components/pagination/pagination.component.ts
  projects/kit/components/pagination/pagination.module.ts
  projects/kit/components/pagination/pagination.template.html
Labels: ready to merge

#7205 fix(kit): `CheckboxLabeled` fix line-height
  projects/kit/components/checkbox-labeled/checkbox-labeled.style.less
Labels: ready to merge

#7203 fix(addon-commerce): fix hidden card
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
Labels: ready to merge

#7197 fix(kit): `Carousel` fix dragging in chrome
  projects/demo/src/modules/components/carousel/examples/4/index.ts
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/carousel/carousel.style.less
  projects/kit/components/carousel/carousel.template.html
Labels: ready to merge

#7189 chore: fix changelog
  CHANGELOG.md
Labels: ready to merge, v3

#7179 chore(schematics): add proprietary migrations
  projects/cdk/package.json
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-tds.spec.ts
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-proprietary.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
  projects/cdk/schematics/utils/make-angular-json-with-assets.ts
Labels: ready to merge

#7196 refactor: use `TuiFlagPipe` as standalone
  projects/addon-doc/components/language-switcher/language-switcher.component.ts
  projects/addon-doc/components/language-switcher/tests/language-switcher.component.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/pipes/flag/flag.module.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/pipes/flag/index.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/pipes/flag/examples/1/index.html
  projects/demo/src/modules/pipes/flag/examples/1/index.ts
  projects/demo/src/modules/pipes/flag/examples/import/import.md
  projects/demo/src/modules/pipes/flag/examples/import/template.md
  projects/demo/src/modules/pipes/flag/flag.component.ts
  projects/demo/src/modules/pipes/flag/flag.module.ts
  projects/demo/src/modules/pipes/flag/flag.template.html
  projects/demo/src/modules/pipes/flag/index.html
  projects/demo/src/modules/pipes/flag/index.ts
  projects/kit/components/input-phone-international/input-phone-international.module.ts
Labels: ready to merge

#7164 refactor!: move `Surface` to core package
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/core/directives/index.ts
  projects/core/directives/surface/index.ts
  projects/core/directives/surface/ng-package.json
  projects/core/directives/surface/surface.component.ts
  projects/core/directives/surface/surface.directive.ts
  projects/core/directives/surface/surface.style.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/button-group/examples/1/index.ts
  projects/demo/src/modules/components/button-group/examples/2/index.ts
  projects/demo/src/modules/components/button-group/examples/3/index.ts
  projects/demo/src/modules/components/surface/examples/1/base.less
  projects/demo/src/modules/components/surface/examples/1/index.html
  projects/demo/src/modules/components/surface/examples/1/index.less
  projects/demo/src/modules/components/surface/examples/1/index.ts
  projects/demo/src/modules/components/surface/examples/2/index.html
  projects/demo/src/modules/components/surface/examples/2/index.less
  projects/demo/src/modules/components/surface/examples/2/index.ts
  projects/demo/src/modules/components/surface/examples/3/index.html
  projects/demo/src/modules/components/surface/examples/3/index.less
  projects/demo/src/modules/components/surface/examples/3/index.ts
  projects/demo/src/modules/components/surface/examples/4/index.html
  projects/demo/src/modules/components/surface/examples/4/index.less
  projects/demo/src/modules/components/surface/examples/4/index.ts
  projects/demo/src/modules/components/surface/examples/5/index.html
  projects/demo/src/modules/components/surface/examples/5/index.less
  projects/demo/src/modules/components/surface/examples/5/index.ts
  projects/demo/src/modules/components/surface/examples/6/index.html
  projects/demo/src/modules/components/surface/examples/6/index.less
  projects/demo/src/modules/components/surface/examples/6/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.html
  projects/demo/src/modules/components/surface/examples/7/index.less
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/components/surface/examples/7/surface.less
  projects/demo/src/modules/components/surface/examples/import/import.md
  projects/demo/src/modules/components/surface/examples/import/template.md
  projects/demo/src/modules/components/surface/index.html
  projects/demo/src/modules/components/surface/index.ts
  projects/demo/src/modules/components/swipe-action/swipe-actions.module.ts
  projects/demo/src/modules/directives/dropdown/dropdown.module.ts
  projects/demo/src/modules/directives/skeleton/skeleton.module.ts
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/navigation/navigation.module.ts
  projects/demo/src/modules/experimental/surface/examples/1/index.ts
  projects/demo/src/modules/experimental/surface/examples/7/index.ts
  projects/demo/src/modules/experimental/surface/examples/import/import-module.md
  projects/demo/src/modules/experimental/surface/surface.component.ts
  projects/demo/src/modules/experimental/surface/surface.module.ts
  projects/demo/src/modules/experimental/surface/surface.template.html
  projects/demo/used-icons.ts
  projects/experimental/directives/index.ts
  projects/experimental/directives/surface/surface.module.ts
Labels: v4

#7204 chore: fixup
  jest.config.ts
Labels: ready to merge

#7229 chore(demo): `InputCard` fix example
  projects/demo/src/modules/components/input-card/examples/1/index.html
  projects/demo/src/modules/components/input-card/input-card.template.html
Labels: ready to merge, v3

#7232 chore(demo): documentation pages `FormatDate` & `Animations` have infinite SSR
  projects/demo/src/modules/animations/examples/fade-in/index.ts
  projects/demo/src/modules/pipes/format-date/examples/1/service.ts
Labels: ready to merge

#7233 chore(demo): use `@nx/angular:webpack-server` instead of `@angular-builders/custom-webpack:server`
  package-lock.json
  package.json
  projects/demo/package.json
  projects/demo/project.json
Labels: ready to merge

#7180 ci: add CI-job to check if prerender of demo-application is successful
  .github/workflows/build.yml
  .gitignore
  projects/demo/project.json
  projects/demo/routes.txt
  projects/demo/src/modules/app/server-error-handler.ts
  projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.ts
  scripts/generate-demo-routes-file.ts
Labels: ready to merge

#7238 chore(demo): fix source code links
  projects/demo/src/modules/app/app.providers.ts
Labels: ready to merge, v3

#7243 ci: temporarily disable prerender of documentation for Github Pages
  .github/workflows/snapshots.yml
Labels: ready to merge

#7240 ci: use CSR for e2e tests (to improve screenshot tests stability)
  .github/workflows/e2e-playwright.yml
Labels: ready to merge

#7244 feat(core): add `tuiIcon` pipe
  projects/core/components/icon/icon.pipe.ts
  projects/core/components/icon/index.ts
  projects/demo/src/modules/components/icon/examples/1/index.html
  projects/demo/src/modules/components/icon/examples/1/index.less
  projects/demo/src/modules/components/icon/examples/1/index.ts
  projects/demo/src/modules/components/icon/icon.module.ts
Labels: ready to merge

#7251 chore(demo): fix `Setup` section of documentation page `CopyProcessor`
  projects/demo/src/modules/directives/copy-processor/examples/import/template.md
Labels: ready to merge

#7246 chore(demo): small improve ui
  projects/addon-doc/components/demo/demo.style.less
Labels: ready to merge

#7253 chore(demo-playwright): flaky example exclusion works again
  projects/demo-playwright/tests/demo/is-flaky-examples.ts
Labels: ready to merge

#7230 chore(demo): `InputCard` fix example
  projects/demo/src/modules/components/input-card/examples/1/index.html
  projects/demo/src/modules/components/input-card/input-card.template.html
Labels: ready to merge, v4

#7235 refactor!: `Cell` move to layout package
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/cell/examples/1/index.html
  projects/demo/src/modules/components/cell/examples/1/index.less
  projects/demo/src/modules/components/cell/examples/1/index.ts
  projects/demo/src/modules/components/cell/examples/2/index.html
  projects/demo/src/modules/components/cell/examples/2/index.less
  projects/demo/src/modules/components/cell/examples/2/index.ts
  projects/demo/src/modules/components/cell/examples/3/index.html
  projects/demo/src/modules/components/cell/examples/3/index.less
  projects/demo/src/modules/components/cell/examples/3/index.ts
  projects/demo/src/modules/components/cell/examples/4/index.html
  projects/demo/src/modules/components/cell/examples/4/index.less
  projects/demo/src/modules/components/cell/examples/4/index.ts
  projects/demo/src/modules/components/cell/examples/5/index.html
  projects/demo/src/modules/components/cell/examples/5/index.less
  projects/demo/src/modules/components/cell/examples/5/index.ts
  projects/demo/src/modules/components/cell/examples/6/index.html
  projects/demo/src/modules/components/cell/examples/6/index.less
  projects/demo/src/modules/components/cell/examples/6/index.ts
  projects/demo/src/modules/components/cell/examples/7/index.html
  projects/demo/src/modules/components/cell/examples/7/index.less
  projects/demo/src/modules/components/cell/examples/7/index.ts
  projects/demo/src/modules/components/cell/examples/import/import.md
  projects/demo/src/modules/components/cell/examples/import/template.md
  projects/demo/src/modules/components/cell/index.html
  projects/demo/src/modules/components/cell/index.less
  projects/demo/src/modules/components/cell/index.ts
  projects/demo/src/modules/components/surface/examples/7/index.ts
  projects/demo/src/modules/components/swipe-action/swipe-actions.module.ts
  projects/demo/src/modules/experimental/card-large/card-large.module.ts
  projects/demo/src/modules/experimental/card-medium/card-medium.module.ts
  projects/demo/src/modules/experimental/cell/cell.component.ts
  projects/demo/src/modules/experimental/cell/cell.module.ts
  projects/demo/src/modules/experimental/cell/cell.template.html
  projects/demo/src/modules/experimental/cell/examples/2/index.ts
  projects/demo/src/modules/experimental/cell/examples/3/index.ts
  projects/demo/src/modules/experimental/cell/examples/4/index.ts
  projects/demo/src/modules/experimental/cell/examples/5/index.ts
  projects/demo/src/modules/experimental/cell/examples/7/index.ts
  projects/demo/src/modules/experimental/cell/examples/import/import-module.md
  projects/demo/used-icons.ts
  projects/experimental/directives/cell/cell.module.ts
  projects/experimental/directives/index.ts
  projects/layout/directives/cell/cell.component.ts
  projects/layout/directives/cell/cell.directive.ts
  projects/layout/directives/cell/cell.styles.less
  projects/layout/directives/cell/index.ts
  projects/layout/directives/cell/ng-package.json
  projects/layout/directives/index.ts
Labels: ready to merge, v4

#7252 chore(all): update CODEOWNERS
  .cspell.json
  .github/CODEOWNERS
Labels: ready to merge

#7255 chore(demo): fix `See also` section and standardize all route usages
  projects/addon-doc/utils/provide-route-page-tab.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/components/input-number/input-number.component.ts
  projects/demo/src/modules/components/input-number/input-number.template.html
  scripts/generate-demo-routes-file.ts
Labels: ready to merge

#7193 feat(experimental): `DropdownMobile` add new dropdown behavior
  package-lock.json
  package.json
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.module.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
  projects/addon-mobile/directives/dropdown-mobile/index.ts
  projects/addon-mobile/directives/dropdown-mobile/ng-package.json
  projects/addon-mobile/directives/index.ts
  projects/cdk/package.json
  projects/cdk/utils/dom/get-element-obscurers.ts
  projects/core/components/data-list/option/option.component.ts
  projects/core/components/root/root.style.less
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/package.json
  projects/core/services/visual-viewport.service.ts
  projects/demo/src/modules/components/combo-box/examples/5/index.html
  projects/demo/src/modules/components/combo-box/examples/5/index.less
  projects/demo/src/modules/directives/dropdown/dropdown.component.ts
  projects/demo/src/modules/directives/dropdown/dropdown.module.ts
  projects/demo/src/modules/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/directives/dropdown/examples/5/index.html
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
  projects/kit/components/input-tag/input-tag.component.ts
Labels: ready to merge

#7256 fix(cdk): `Dialog` fix jumping to top on closing
  projects/cdk/components/dialog-host/dialog-host.component.ts
  projects/cdk/components/dialog-host/dialog-host.style.less
Labels: ready to merge

#7264 refactor: drop `ng update` schematics tests for `v3`
  projects/cdk/schematics/collection.json
  projects/cdk/schematics/migration.json
  projects/cdk/schematics/ng-update/v3-30/index.ts
  projects/cdk/schematics/ng-update/v3-30/tests/schematic-migrate-icons.spec.ts
  projects/cdk/schematics/ng-update/v3-35/index.ts
  projects/cdk/schematics/ng-update/v3-35/tests/schematic-migrate-icons.spec.ts
  projects/cdk/schematics/ng-update/v3-36/index.ts
  projects/cdk/schematics/ng-update/v3-36/tests/schematic-migrate-editor.spec.ts
  projects/cdk/schematics/ng-update/v3-40/index.ts
  projects/cdk/schematics/ng-update/v3-40/tests/schematic-migrate-textarea.spec.ts
  projects/cdk/schematics/ng-update/v3-5/index.ts
  projects/cdk/schematics/ng-update/v3-5/tests/schematic-migrate-templates.spec.ts
  projects/cdk/schematics/ng-update/v3/index.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-date-time.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-hints.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-polymorpheus.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-progress.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-sliders.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-tds.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-textfields.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-miscellaneous.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-rename-types.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-consts.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deep-imports.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deprecated-functions.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-enums.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-functions.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-html.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-proprietary-consts.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-services.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-replace-styles.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-textfield-icon.spec.ts
  projects/cdk/schematics/ng-update/v3/tests/schematic-warnings.spec.ts
Labels: ready to merge

#7270 fix: non strict peer dependencies
  package-lock.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-preview/package.json
  projects/addon-table/package.json
  projects/addon-tablebars/package.json
  projects/core/package.json
  projects/experimental/package.json
  projects/i18n/package.json
  projects/icons/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge, v3

#7272 chore(all): update CODEOWNERS
  .cspell.json
  .github/CODEOWNERS
Labels: ready to merge

#7265 refactor: drop `cypress` route
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/cypress/cypress.component.ts
  projects/demo/src/modules/cypress/cypress.module.ts
  projects/demo/src/modules/cypress/cypress.template.html
  projects/demo/src/modules/cypress/examples/1-input-date-initialization/index.html
  projects/demo/src/modules/cypress/examples/1-input-date-initialization/index.ts
Labels: ready to merge

#7274 feat(addon-mobile): `DropdownMobile` add sheet view
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.module.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
  projects/demo/src/modules/directives/dropdown/dropdown.module.ts
  projects/demo/src/modules/directives/dropdown/dropdown.template.html
  projects/demo/src/modules/directives/dropdown/examples/2/index.html
  projects/demo/src/modules/directives/dropdown/examples/5/index.html
  projects/demo/src/modules/directives/dropdown/examples/5/index.ts
  projects/experimental/directives/title/title.style.less
Labels: ready to merge, v3

#7271 feat(addon-table): reorder add possibility to transfer a template
  projects/addon-table/components/reorder/reorder.component.ts
  projects/addon-table/components/reorder/reorder.module.ts
  projects/addon-table/components/reorder/reorder.template.html
Labels: ready to merge, v3

#7285 fix(kit): redesign focus to focus-visible in `TuiAccordion`
  projects/core/styles/theme/variables.less
  projects/kit/components/accordion/accordion-item/accordion-item.component.ts
  projects/kit/components/accordion/accordion-item/accordion-item.style.less
  projects/kit/components/accordion/accordion-item/accordion-item.template.html
Labels: ready to merge, v3

#7283 chore(demo): migrated `Confirm` to standalone
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/confirm/confirm.module.ts
  projects/demo/src/modules/components/confirm/examples/1/index.ts
  projects/demo/src/modules/components/confirm/index.html
  projects/demo/src/modules/components/confirm/index.ts
Labels: ready to merge

#7224 feat(addon-mobile): reduce zone.js in `tuiElasticSticky`
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
Labels: ready to merge

#7295 chore: `MarkerIcon`, `Action` add migrations
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-action.spec.ts
  projects/layout/directives/header/header.styles.less
Labels: ready to merge

#7301 chore: update husky command
  .husky/pre-commit
  package.json
Labels: ready to merge

#7287 fix(cdk): `Dialog` fix jumping to top on closing
  projects/core/animations/animations.ts
Labels: ready to merge, v4

#7294 refactor: rename `textfield-placeholder` to `label`
  projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
  projects/core/styles/mixins/textfield.less
  projects/core/styles/mixins/textfield.scss
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge

#7293 refactor: rename `TuiTablePaginationModule` to `TuiTablePaginationComponent`
  projects/addon-table/components/table-pagination/index.ts
  projects/addon-table/components/table-pagination/table-pagination.component.ts
  projects/addon-table/components/table-pagination/table-pagination.module.ts
  projects/addon-table/components/table-pagination/test/table-pagination.component.spec.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/components/table-pagination/examples/1/index.html
  projects/demo/src/modules/components/table-pagination/examples/1/index.ts
  projects/demo/src/modules/components/table-pagination/examples/2/index.html
  projects/demo/src/modules/components/table-pagination/examples/2/index.ts
  projects/demo/src/modules/components/table-pagination/examples/3/index.html
  projects/demo/src/modules/components/table-pagination/examples/3/index.ts
  projects/demo/src/modules/components/table-pagination/examples/import/import.md
  projects/demo/src/modules/components/table-pagination/examples/import/template.md
  projects/demo/src/modules/components/table-pagination/index.html
  projects/demo/src/modules/components/table-pagination/index.ts
  projects/demo/src/modules/tables/table-pagination/examples/1/index.ts
  projects/demo/src/modules/tables/table-pagination/examples/2/index.ts
  projects/demo/src/modules/tables/table-pagination/examples/import/import-module.md
  projects/demo/src/modules/tables/table-pagination/table-pagination.component.ts
  projects/demo/src/modules/tables/table-pagination/table-pagination.module.ts
  projects/demo/src/modules/tables/table/examples/4/index.html
  projects/demo/src/modules/tables/table/examples/4/index.ts
  projects/demo/src/modules/tables/table/table.module.ts
Labels: ready to merge

#7290 refactor: drop `TuiInteractiveStateT`
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/enums.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-enums.spec.ts
  projects/core/components/primitive-calendar/primitive-calendar.component.ts
  projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts
  projects/core/components/primitive-year-picker/primitive-year-picker.component.ts
  projects/core/components/primitive-year-picker/test/primitive-year-picker.component.spec.ts
  projects/core/directives/appearance/appearance.directive.ts
  projects/core/directives/wrapper/wrapper.directive.ts
  projects/core/enums/index.ts
  projects/core/enums/interactive-state.ts
  projects/core/interfaces/index.ts
  projects/core/interfaces/interactive-state.ts
  projects/demo/src/modules/directives/appearance/appearance.component.ts
  projects/experimental/components/textfield/textfield.directive.ts
  projects/kit/components/calendar-month/calendar-month.component.ts
  projects/kit/components/calendar-month/test/calendar-month.component.spec.ts
Labels: ready to merge

#7325 ci(demo-playwright): fix flaky screenshot tests
  .github/renovate.json
  package-lock.json
  projects/demo-playwright/package.json
Labels: ready to merge

#7326 chore: `Button` add migration
  projects/cdk/schematics/ng-update/interfaces/replacement-attribute-value.ts
  projects/cdk/schematics/ng-update/utils/templates/replace-attr-values.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
  projects/cdk/schematics/utils/templates/elements.ts
Labels: ready to merge

#7291 refactor: drop some styles in slider
  projects/demo/src/modules/components/slider/examples/2/index.less
  projects/kit/components/range/range.style.less
  projects/kit/components/slider/slider.style.less
Labels: ready to merge

#7320 refactor: drop fallback for Firefox 55 and 56
  projects/cdk/services/static-request.service.ts
Labels: ready to merge

#7321 refactor: drop old mixins
  projects/core/styles/variables/media.scss
Labels: ready to merge

#7319 refactor: drop destroy service
  projects/cdk/services/destroy.service.ts
  projects/cdk/services/index.ts
Labels: ready to merge

#7335 fix(kit): `Textarea` incorrectly highlights extra characters for long words with hyphen in Safari/FF
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge, v4
