Repository taiga-family/taiga-ui, pull requests merged in 2024-12, with the labels that each got.

#9874 chore: update jest preset
  nx.json
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#9867 fix(core): `Dropdown` fix initial width
  projects/core/directives/dropdown/dropdown.style.less
  projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
Labels: ready to merge

#9883 refactor: support nested diff directories
  .github/workflows/e2e.yml
  projects/demo-playwright/merge.config.ts
  scripts/visual-testing/combine-playwright-failed-screenshots.ts
Labels: ready to merge

#9887 chore(demo): fix `tuiFadeIn` in demo
  projects/demo/src/modules/components/animations/examples/3/index.ts
Labels: community contribution

#9879 chore: fix wrong yml syntax
  .github/workflows/after-close-pr.yml
Labels: ready to merge

#9881 fix(core): `Input` with `DataList` never shows dropdown after its 1st closing
  projects/core/components/hosted-dropdown/dropdown-open-monitor.directive.ts
Labels: ready to merge, v3

#9890 chore: disable animation on E2E mode for stabilizing more tests
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge

#9865 fix(cdk): optional chaining for tuiControlValue subscription
  projects/cdk/observables/control-value.ts
  projects/cdk/observables/test/control-value.spec.ts
Labels: community contribution, v3

#9888 fix(core): `DropdownOpen` has CD problems after switching of `tuiDropdownEnabled` (`false`=>`true`)
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/demo-cypress/src/support/component.ts
  projects/demo-cypress/src/tests/input-with-datalist.cy.ts
Labels: ready to merge

#9882 refactor: drop `ngStyle`
  .gitignore
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
  projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/carousel/carousel.template.html
  projects/legacy/components/sheet/components/sheet-bar/sheet-bar.template.html
Labels: ready to merge

#9891 fix(core): focus first element in data-list
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/utils/focus/get-closest-focusable.ts
  projects/demo-playwright/tests/core/data-list/data-list.pw.spec.ts
  projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
Labels: ready to merge

#9893 chore(demo): `ThumbnailCard` with `blur` effect should have semi-transparent white overlay
  projects/demo/src/modules/components/thumbnail-card/examples/3/index.less
Labels: ready to merge

#9898 chore: revert
  projects/demo/src/modules/app/app.component.ts
Labels: ready to merge

#9912 fix(addon-mobile): `Card` fix paddings on mobile devices
  projects/addon-mobile/styles/common/card-large.less
  projects/demo/src/modules/experimental/card-large/card-large.template.html
  projects/demo/src/modules/experimental/card-large/examples/12/index.html
Labels: v3

#9917 fix(core): `Icon` fix for old safari
  projects/core/styles/components/icon.less
  projects/kit/directives/icon-badge/icon-badge.style.less
Labels: ready to merge

#9916 fix(kit): removed redundant space
  projects/kit/components/action-bar/action-bar.style.less
Labels: ready to merge

#9918 ci: failed to create comment for codecov
  .github/workflows/test.yml
  codecov.yml
Labels: ready to merge

#9900 fix(legacy): `MultiSelect` fix pristine and updateOn: blur issues
  projects/legacy/classes/control.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
  projects/legacy/components/primitive-textfield/textfield/textfield.style.less
  projects/legacy/components/select-option/select-option.component.ts
Labels: ready to merge

#9905 fix(core): transform breaks fixed position in tiles
  projects/core/components/expand/expand.style.less
  projects/demo/src/modules/components/tree/examples/8/index.html
  projects/demo/src/modules/components/tree/examples/8/index.less
  projects/demo/src/modules/components/tree/examples/8/index.ts
  projects/demo/src/modules/components/tree/index.html
Labels: ready to merge

#9923 chore(layout): `Navigation` prepare for proprietary new year theme
  projects/kit/components/avatar/avatar.style.less
  projects/layout/components/navigation/aside.style.less
  projects/layout/components/navigation/header.style.less
Labels: ready to merge

#9910 feat(legacy): `MultiSelect` allow checkbox on the right side
  projects/demo/src/modules/components/multi-select/examples/5/index.html
  projects/demo/src/modules/components/multi-select/examples/6/index.html
  projects/legacy/components/multi-select-option/multi-select-option.style.less
  projects/legacy/components/multi-select-option/multi-select-option.template.html
Labels: ready to merge

#9911 feat(legacy): `MultiSelect` allow checkbox on the right side
  projects/demo/src/modules/components/multi-select/examples/5/index.html
  projects/kit/components/multi-select-option/multi-select-option.style.less
  projects/kit/components/multi-select-option/multi-select-option.template.html
Labels: ready to merge, v3

#9914 feat(core): add margin right for left icons in small textfield
  projects/core/styles/mixins/textfield.less
Labels: ready to merge, v3

#9931 fix(kit): `Segmented` fix shadow clipping in Safari
  projects/kit/components/segmented/segmented.style.less
Labels: ready to merge

#9908 feat(legacy): add `itemsHidden` prop to `tui-input-time`
  projects/demo/src/modules/components/input-time/index.html
  projects/demo/src/modules/components/input-time/index.ts
  projects/legacy/components/input-time/input-time.component.ts
Labels: ready to merge

#9909 feat(kit): add `itemsHidden` prop to `tui-input-time`
  projects/demo/src/modules/components/input-time/input-time.component.ts
  projects/demo/src/modules/components/input-time/input-time.template.html
  projects/kit/components/input-time/input-time.component.ts
Labels: ready to merge, v3

#9818 fix(kit): `InputInline` has broken scroll in Safari & Firefox
  projects/demo/src/modules/components/input-inline/examples/4/index.html
  projects/demo/src/modules/components/input-inline/examples/4/index.less
  projects/demo/src/modules/components/input-inline/examples/4/index.ts
  projects/demo/src/modules/components/input-inline/index.ts
  projects/kit/components/input-inline/input-inline.component.ts
  projects/kit/components/input-inline/input-inline.style.less
  projects/kit/components/input-inline/input-inline.template.html
Labels: ready to merge

#9934 fix(kit): `Tabs` fix multiple emitting of activeItemIndexChange
  projects/kit/components/tabs/tab.directive.ts
  projects/kit/components/tabs/test/tabs.component.spec.ts
Labels: ready to merge

#9896 chore: mock date in jest
  .github/workflows/test.yml
  projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#9933 feat(layout): `Form` add new component
  .cspell.json
  projects/cdk/utils/di/create-options.ts
  projects/cdk/utils/miscellaneous/provide-options.ts
  projects/core/components/button/button.options.ts
  projects/core/components/notification/notification.options.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/form/examples/1/index.html
  projects/demo/src/modules/components/form/examples/1/index.ts
  projects/demo/src/modules/components/form/examples/import/import.md
  projects/demo/src/modules/components/form/examples/import/template.md
  projects/demo/src/modules/components/form/index.html
  projects/demo/src/modules/components/form/index.less
  projects/demo/src/modules/components/form/index.ts
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/kit/components/segmented/segmented.component.ts
  projects/layout/components/card/card.styles.less
  projects/layout/components/form/form.directive.ts
  projects/layout/components/form/form.styles.less
  projects/layout/components/form/index.ts
  projects/layout/components/form/ng-package.json
  projects/layout/components/header/header.directive.ts
  projects/layout/components/index.ts
  projects/layout/components/navigation/main.style.less
Labels: ready to merge

#9904 fix(addon-table): sort icons are reversed
  projects/addon-table/components/table/directives/direction-order.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/directives/test/direction-order.directive.spec.ts
  projects/addon-table/components/table/pipes/table-sort.pipe.ts
  projects/addon-table/components/table/table.options.ts
  projects/addon-table/components/table/th/th.component.ts
Labels: community contribution

#9894 chore: rename screenshots
  projects/demo-playwright/tests/core/breakpoint-service/breakpoint-service.pw.spec.ts
  projects/demo-playwright/tests/core/dialogs/dialogs.pw.spec.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-select.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts
  projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
  projects/demo-playwright/tests/kit/input-table/input-table.pw.spec.ts
  projects/demo-playwright/tests/kit/line-clamp/line-clamp.pw.spec.ts
  projects/demo-playwright/tests/kit/range/range.pw.spec.ts
  projects/demo-playwright/tests/kit/slider/slider.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-time/input-time.pw.spec.ts
Labels: ready to merge

#9932 fix(legacy): `InputDate{Range|Time}` + `input[tuiTextfieldLegacy]` + `tuiTextfieldFiller` has CD problems
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-date-time/input-date-time.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts
  projects/demo-playwright/utils/page-objects/input-date-range.po.ts
  projects/demo-playwright/utils/page-objects/input-date.po.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
  projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date-time/test/input-date-time.component.spec.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/input-date.directive.ts
  projects/legacy/components/input-date/test/input-date.component.spec.ts
Labels: ready to merge

#9943 chore(demo): fix example
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
Labels: ready to merge

#9886 feat(legacy): limit `tui-tag` width to `80%` to avoid wrapping in selects
  projects/demo/src/modules/components/multi-select/examples/1/index.ts
  projects/demo/src/modules/pipes/filter-by-input/examples/3/index.ts
  projects/legacy/components/input-tag/input-tag.style.less
Labels: ready to merge

#9947 fix(kit): `InputInline` has broken scroll in Safari & Firefox
  projects/demo/src/modules/components/input-inline/examples/4/index.html
  projects/demo/src/modules/components/input-inline/examples/4/index.less
  projects/demo/src/modules/components/input-inline/examples/4/index.ts
  projects/demo/src/modules/components/input-inline/input-inline.component.ts
  projects/demo/src/modules/components/input-inline/input-inline.module.ts
  projects/demo/src/modules/components/input-inline/input-inline.template.html
  projects/kit/components/input-inline/input-inline.component.ts
  projects/kit/components/input-inline/input-inline.style.less
  projects/kit/components/input-inline/input-inline.template.html
Labels: ready to merge, v3

#9952 fix(kit): strange behavior in Safari when working with tiles
  projects/kit/components/tiles/tile-handle.directive.ts
Labels: community contribution

#9969 feat(addon-commerce): `ThumbnailCard` has new `xs` size
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.options.ts
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
  projects/demo-playwright/tests/addon-commerce/thumbnail-card.pw.spec.ts
  projects/demo/src/modules/components/thumbnail-card/examples/1/index.ts
  projects/demo/src/modules/components/thumbnail-card/index.html
  projects/demo/src/modules/components/thumbnail-card/index.ts
Labels: ready to merge

#9972 chore: enable IDE breakpoints for jest tests
  tsconfig.spec.json
Labels: ready to merge

#9554 ci: add webkit
  .github/workflows/e2e.yml
  projects/demo-playwright/playwright.config.ts
  projects/demo-playwright/stubs/angular-logo.mp4
  projects/demo-playwright/tests/addon-commerce/input-card-group.pw.spec.ts
  projects/demo-playwright/tests/addon-doc/navigation.pw.spec.ts
  projects/demo-playwright/tests/core/data-list/data-list.pw.spec.ts
  projects/demo-playwright/tests/core/dialogs/dialogs.pw.spec.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
  projects/demo-playwright/tests/core/surface/surface.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-select.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts
  projects/demo-playwright/tests/demo/demo.pw.spec.ts
  projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
  projects/demo-playwright/tests/kit/carousel/carousel.pw.spec.ts
  projects/demo-playwright/tests/kit/dropdown-hover/dropdown-hover.pw.spec.ts
  projects/demo-playwright/tests/kit/range/range.pw.spec.ts
  projects/demo-playwright/tests/kit/slider/slider.pw.spec.ts
  projects/demo-playwright/tests/kit/tabs/tabs.pw.spec.ts
  projects/demo-playwright/tests/kit/tiles/tiles.pw.spec.ts
  projects/demo-playwright/tests/layout/navigation.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-time/input-time.pw.spec.ts
  projects/demo-playwright/tests/legacy/input/input.pw.spec.ts
  projects/demo-playwright/tests/legacy/multi-select/multi-select.pw.spec.ts
  projects/demo-playwright/utils/goto.ts
  projects/demo-playwright/utils/index.ts
  projects/demo-playwright/utils/mock-images.ts
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
  projects/demo-playwright/utils/wait-icons.ts
Labels: ready to merge

#9946 fix(legacy): reset cached active period in `tui-input-date-range`
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/demo/src/modules/components/input-date-range/examples/5/index.html
  projects/demo/src/modules/components/input-date-range/examples/5/index.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
Labels: ready to merge

#9949 refactor: reuse method to destroy view
  projects/cdk/classes/portals.ts
Labels: ready to merge

#9956 fix(kit): strange behavior in Safari when working with tiles
  projects/kit/components/tiles/tile-handle.directive.ts
Labels: community contribution, v3

#9973 chore(demo): use `TUI_PAYMENT_SYSTEM_ICONS` token for documentation page `ThumbnailCard`
  projects/demo/src/modules/components/thumbnail-card/examples/3/index.html
  projects/demo/src/modules/components/thumbnail-card/index.ts
Labels: ready to merge

#9975 chore(demo): update `Setup` section of `InputPhoneInternational` documentation
  projects/demo/src/modules/components/input-phone-international/examples/import/import.md
Labels: ready to merge

#9974 fix(kit): `InputNumber` has rounding problems on blur with float large numbers
  .cspell.json
  projects/cdk/utils/math/round.ts
  projects/core/utils/format/test/format-number.spec.ts
  projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
  projects/legacy/components/input-number/input-number.component.ts
Labels: ready to merge

#9979 chore: slow operations on deep tests and improve stability
  projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.pw.spec.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
  projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-select.pw.spec.ts
  projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts
  projects/demo-playwright/tests/demo/demo.pw.spec.ts
  projects/demo-playwright/tests/kit/dropdown-selection/dropdown-selection.pw.spec.ts
  projects/demo-playwright/utils/is-flaky-examples.ts
Labels: ready to merge

#10002 chore(demo): fix gap
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
Labels: ready to merge

#10004 feat(kit): safety change active index in stepper
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#9961 feat(addon-table): allow resize more than 100% width of table
  .cspell.json
  projects/addon-table/components/table/th/th.component.ts
  projects/demo/src/modules/components/table/examples/8/index.html
  projects/demo/src/modules/components/table/examples/8/index.ts
  projects/demo/src/modules/components/table/index.ts
Labels: ready to merge

#10008 fix(experimental): `Fade` fix mask-position
  projects/experimental/directives/fade/fade.style.less
Labels: ready to merge, v3

#10009 fix(kit): `Carousel` fix scrolling page on mobile devices
  projects/kit/components/carousel/carousel.style.less
Labels: ready to merge

#9997 chore(addon-mobile): fix disable button appearance on mobile
  projects/addon-mobile/styles/common/button.less
Labels: ready to merge

#10012 fix(core): dialog has padding for close button event when not closeable
  projects/core/components/dialog/dialog.interfaces.ts
  projects/core/components/dialog/dialog.style.less
  projects/core/components/dialog/dialog.template.html
Labels: ready to merge

#10020 fix(cdk): fix tuiFocusedIn error when focus events happened in reactive context
  projects/cdk/observables/index.ts
  projects/cdk/observables/untracked-scheduler.ts
  projects/cdk/utils/focus/focused-in.ts
  projects/cdk/utils/focus/tests/focused-in.spec.ts
Labels: ready to merge

#10018 fix(core): dialog has padding for close button event when not closeable
  projects/core/components/dialog/dialog.style.less
  projects/core/components/dialog/dialog.template.html
Labels: ready to merge, v3

#10021 chore(demo): fix duration
  projects/kit/directives/skeleton/skeleton.directive.ts
Labels: ready to merge

#10032 #9966 - Fix documentation Name & Description, Type columns overlapping.
  projects/addon-doc/components/documentation/documentation.style.less
  projects/addon-doc/components/documentation/documentation.template.html
Labels: ready to merge

#10034 chore(demo): use modern API page approach for documentation about `[tuiNumberFormat]`
  projects/demo/src/components/number-format/index.html
  projects/demo/src/components/number-format/index.ts
  projects/demo/src/modules/components/abstract/inherited-documentation/index.html
  projects/demo/src/modules/components/abstract/inherited-documentation/index.ts
  projects/demo/src/modules/components/abstract/number-format-documentation/index.html
  projects/demo/src/modules/components/abstract/number-format-documentation/index.ts
  projects/demo/src/modules/components/abstract/number-format.ts
  projects/demo/src/modules/components/abstract/supporting-documentation-component.ts
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-number/index.ts
  projects/demo/src/modules/components/input-range/index.html
  projects/demo/src/modules/components/input-range/index.ts
  projects/demo/src/modules/components/input-slider/index.html
  projects/demo/src/modules/components/input-slider/index.ts
  projects/demo/src/modules/pipes/format-number/index.html
  projects/demo/src/modules/pipes/format-number/index.ts
Labels: ready to merge

#10023 fix(addon-mobile): virtual-scroll flickers during scroll in zoneless mode
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
Labels: ready to merge

#10037 chore(demo): improve form example
  projects/demo/src/modules/components/form/examples/2/index.html
  projects/demo/src/modules/components/form/examples/2/index.less
  projects/demo/src/modules/components/form/examples/2/index.ts
  projects/demo/src/modules/components/form/index.ts
Labels: ready to merge

#9996 chore: fix block migration
  .cspell.json
  projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Labels: ready to merge

#10033 feat(addon-commerce): `InputCardGroup` add `inputs` option
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
  projects/addon-commerce/components/input-card-group/input-card-group.options.ts
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/addon-commerce/components/input-card-group/input-card-group.template.html
  projects/addon-doc/components/api/api-item.template.html
  projects/demo/src/modules/components/input-card-group/index.html
  projects/demo/src/modules/components/input-card-group/index.ts
Labels: ready to merge

#10041 feat(layout): `Navigation` add `Subheader` component
  .cspell.json
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/demo/src/modules/components/navigation/examples/2/index.html
  projects/demo/src/modules/components/navigation/examples/2/index.ts
  projects/demo/src/modules/components/navigation/examples/3/index.html
  projects/demo/src/modules/components/navigation/examples/3/index.ts
  projects/demo/src/modules/components/navigation/index.ts
  projects/layout/components/navigation/drawer.style.less
  projects/layout/components/navigation/index.ts
  projects/layout/components/navigation/main.style.less
  projects/layout/components/navigation/navigation.ts
  projects/layout/components/navigation/subheader.component.ts
  projects/layout/components/navigation/subheader.style.less
Labels: ready to merge

#10049 feat(experimental): `ThumbnailCard` has new `xs` size
  projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.component.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.options.ts
  projects/experimental/components/thumbnail-card/thumbnail-card.style.less
  projects/experimental/components/thumbnail-card/thumbnail-card.template.html
Labels: ready to merge, v3

#10045 fix(legacy): wrong prefix placement in table context
  projects/demo/src/modules/components/table/examples/8/index.html
  projects/demo/src/modules/components/table/examples/8/index.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.component.ts
Labels: ready to merge

#10031 refactor(kit): new version of `InputNumber`
  projects/cdk/classes/value-transformer.ts
  projects/demo-cypress/src/tests/input-number/dynamic-postfix.cy.ts
  projects/demo-playwright/tests/kit/input-number/input-number.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/input-number-legacy/examples/1/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/1/index.less
  projects/demo/src/modules/components/input-number-legacy/examples/1/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/2/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/2/index.less
  projects/demo/src/modules/components/input-number-legacy/examples/2/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/3/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/3/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/4/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/4/index.less
  projects/demo/src/modules/components/input-number-legacy/examples/4/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/5/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/5/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/6/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/6/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/7/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/7/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/8/index.html
  projects/demo/src/modules/components/input-number-legacy/examples/8/index.ts
  projects/demo/src/modules/components/input-number-legacy/examples/import/import.md
  projects/demo/src/modules/components/input-number-legacy/examples/import/template.md
  projects/demo/src/modules/components/input-number-legacy/index.html
  projects/demo/src/modules/components/input-number-legacy/index.ts
  projects/demo/src/modules/components/input-number/examples/import/import.md
  projects/demo/src/modules/components/input-number/examples/import/template.md
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-number/index.ts
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/utils/tokens/examples/5/index.html
  projects/demo/src/modules/pipes/currency/index.html
  projects/kit/components/index.ts
  projects/kit/components/input-number/index.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.options.ts
  projects/kit/components/input-number/ng-package.json
Labels: ready to merge

#10050 fix(legacy): `TuiMultiSelect` fix arrow
  projects/legacy/components/arrow/arrow.component.ts
  projects/legacy/components/arrow/arrow.template.html
  projects/legacy/components/input-tag/input-tag.component.ts
Labels: ready to merge

#10058 chore: add test on windows
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: ready to merge

#10054 fix(experimental): `ButtonVertical` fix style priority
  projects/experimental/directives/button-vertical/button-vertical.style.less
Labels: ready to merge, v3

#10053 chore(schematics): drop redundant editor providers
  projects/cdk/schematics/ng-update/v4/index.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-providers-from.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-tinkoff-editor.spec.ts
Labels: ready to merge

#10051 feat(experimental): `Hint` add new component with updated styles
  projects/demo/src/modules/components/card-large/examples/14/index.html
  projects/demo/src/modules/components/card-large/examples/14/index.less
  projects/demo/src/modules/components/card-large/examples/14/index.ts
  projects/demo/src/modules/components/card-large/index.html
  projects/demo/src/modules/components/card-large/index.ts
  projects/demo/src/modules/components/pulse/examples/2/index.html
  projects/demo/src/modules/components/pulse/examples/2/index.less
  projects/demo/src/modules/components/pulse/examples/2/index.ts
  projects/demo/src/modules/components/pulse/index.html
  projects/demo/src/modules/components/pulse/index.ts
  projects/demo/src/modules/components/push/examples/3/index.ts
  projects/demo/src/modules/components/push/index.html
  projects/demo/src/modules/components/push/index.ts
  projects/experimental/components/hint/hint.component.ts
  projects/experimental/components/hint/hint.style.less
  projects/experimental/components/hint/index.ts
  projects/experimental/components/hint/ng-package.json
  projects/experimental/components/index.ts
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
  projects/experimental/components/input-phone-international/test/input-phone-international.component.spec.ts
  projects/kit/components/avatar/avatar.template.html
  projects/kit/components/pulse/pulse.component.ts
  projects/kit/components/pulse/pulse.style.less
Labels: ready to merge

#10066 fix(core): `Textfield` with `[content]` property has invalid behavior for `<input />`
  projects/core/styles/components/textfield.less
  projects/demo-cypress/src/tests/textfield.cy.ts
Labels: ready to merge

#10070 fix(kit): `LineClamp` fix initial transition
  projects/kit/components/line-clamp/line-clamp.component.ts
Labels: ready to merge

#10065 fix(cdk): `TuiTime.shift` doesn't shift higher order units
  projects/cdk/date-time/test/time.spec.ts
  projects/cdk/date-time/time.ts
Labels: community contribution

#10063 fix(legacy): `InputPhone` incorrectly parses paste of the shorten phone number
  projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts
Labels: ready to merge

#10077 chore(schematics): valid migration for badged content
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
Labels: ready to merge

#10073 refactor(kit): new version of `InputNumber` has `[step]` feature
  projects/cdk/constants/allow-signal-writes.ts
  projects/cdk/constants/index.ts
  projects/cdk/constants/used-icons.ts
  projects/cdk/utils/miscellaneous/directive-binding.ts
  projects/demo-playwright/playwright.config.ts
  projects/demo-playwright/tests/kit/input-number/input-number.pw.spec.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-number.po.ts
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-number/index.ts
  projects/kit/components/input-number/input-number.component.ts
  projects/kit/components/input-number/input-number.options.ts
  projects/kit/components/input-number/input-number.style.less
  projects/kit/components/input-number/input-number.template.html
Labels: ready to merge

#10093 chore(kit): new `InputNumber` has too large button icons for `l`-size
  projects/kit/components/input-number/input-number.style.less
  projects/kit/components/input-number/input-number.template.html
Labels: ready to merge

#10099 feat(kit): introduce new version of `InputNumber`
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/input-number-legacy/index.html
  projects/demo/src/modules/components/input-number/examples/1/index.html
  projects/demo/src/modules/components/input-number/examples/1/index.ts
  projects/demo/src/modules/components/input-number/examples/2/index.html
  projects/demo/src/modules/components/input-number/examples/2/index.ts
  projects/demo/src/modules/components/input-number/examples/3/index.html
  projects/demo/src/modules/components/input-number/examples/3/index.ts
  projects/demo/src/modules/components/input-number/examples/4/index.html
  projects/demo/src/modules/components/input-number/examples/4/index.ts
  projects/demo/src/modules/components/input-number/examples/5/index.html
  projects/demo/src/modules/components/input-number/examples/5/index.ts
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-number/index.less
  projects/demo/src/modules/components/input-number/index.ts
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/utils/tokens/examples/5/index.html
  projects/demo/src/modules/pipes/currency/index.html
  projects/demo/used-icons.ts
  projects/legacy/components/input-number/input-number.component.ts
  projects/legacy/components/input-number/input-number.directive.ts
  projects/legacy/components/input-number/input-number.module.ts
  projects/legacy/components/input-number/input-number.options.ts
Labels: ready to merge

#10094 fix(core): `Group` fix overlayed border in collapsed mode
  projects/core/directives/group/group.directive.ts
  projects/core/styles/components/group.less
  projects/core/styles/theme/appearance/outline.less
  projects/demo/src/modules/components/navigation/examples/3/index.html
  projects/kit/components/files/files/files.component.ts
  projects/kit/components/files/files/files.styles.less
  projects/kit/components/files/files/files.template.html
  projects/kit/directives/chevron/chevron.style.less
Labels: ready to merge

#10084 feat(kit): `InputPin` add new component
  projects/core/components/textfield/textfield-content.directive.ts
  projects/core/styles/components/textfield.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/input-pin/examples/1/index.html
  projects/demo/src/modules/components/input-pin/examples/1/index.ts
  projects/demo/src/modules/components/input-pin/examples/2/index.html
  projects/demo/src/modules/components/input-pin/examples/2/index.ts
  projects/demo/src/modules/components/input-pin/examples/3/index.html
  projects/demo/src/modules/components/input-pin/examples/3/index.ts
  projects/demo/src/modules/components/input-pin/examples/import/import.md
  projects/demo/src/modules/components/input-pin/examples/import/template.md
  projects/demo/src/modules/components/input-pin/index.html
  projects/demo/src/modules/components/input-pin/index.ts
  projects/kit/components/index.ts
  projects/kit/components/input-pin/index.ts
  projects/kit/components/input-pin/input-pin.component.ts
  projects/kit/components/input-pin/input-pin.style.less
  projects/kit/components/input-pin/input-pin.template.html
  projects/kit/components/input-pin/ng-package.json
Labels: ready to merge
