Repository taiga-family/taiga-ui, pull requests merged in 2024-10, with the labels that each got.

#9287 fix(core): fix open DropdownContext after single touch on iOS
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge

#9277 ci: set two approvals
  .github/workflows/ready-to-merge.yml
Labels: ready to merge

#9290 chore(demo-cypress): screenshot testing for component tests
  .github/screenshot-bot.config.toml
  .github/workflows/e2e-playwright.yml
  .gitignore
  package-lock.json
  package.json
  projects/demo-cypress/cypress-image-diff.config.js
  projects/demo-cypress/cypress.config.ts
  projects/demo-cypress/package.json
  projects/demo-cypress/src/support/component-index.html
  projects/demo-cypress/src/support/component.ts
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
  projects/demo-cypress/tsconfig.json
  projects/demo/package.json
  projects/demo/src/modules/components/chip/examples/4/index.html
  scripts/visual-testing/combine-cypress-failed-screenshots.ts
  scripts/visual-testing/combine-playwright-failed-screenshots.ts
  scripts/visual-testing/combine-snapshots.ts
Labels: ready to merge

#9286 fix(core): fix open DropdownContext after single touch on iOS
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge, v3

#9308 chore(demo): invalid initial value
  projects/addon-doc/components/copy/index.ts
Labels: ready to merge

#9302 chore: remove redundant
  .npmrc
  package.json
Labels: ready to merge

#9315 feat(core): add `color-scheme` by default for `tuiTheme`
  projects/core/styles/theme/palette.less
Labels: ready to merge

#9312 feat(core): add animation params
  projects/core/animations/animations.ts
Labels: ready to merge

#9310 feat(kit): `ActionBar` add `s` size and update according to spec
  projects/demo-playwright/tests/kit/action-bar/action-bar.mobile.spec.ts
  projects/demo-playwright/tests/kit/action-bar/action-bar.spec.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/action-bar/examples/1/index.html
  projects/demo/src/modules/components/action-bar/examples/1/index.less
  projects/demo/src/modules/components/action-bar/examples/1/index.ts
  projects/demo/src/modules/components/action-bar/examples/2/index.html
  projects/demo/src/modules/components/action-bar/examples/2/index.less
  projects/demo/src/modules/components/action-bar/examples/2/index.ts
  projects/demo/src/modules/components/action-bar/index.html
  projects/demo/src/modules/components/action-bar/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/action-bar/action-bar.component.ts
  projects/kit/components/action-bar/action-bar.style.less
  projects/kit/components/items-with-more/items-with-more.style.less
Labels: ready to merge

#9327 ci: revert schematic.yml
  .github/workflows/schematic.yml
  .github/workflows/test.yml
Labels: ready to merge

#9320 fix(legacy): revert `ngSkipHydration`
  projects/legacy/components/arrow/arrow.component.ts
  projects/legacy/components/color-selector/color-edit/color-edit.component.ts
  projects/legacy/components/color-selector/color-picker/color-picker.component.ts
  projects/legacy/components/color-selector/color-selector.component.ts
  projects/legacy/components/color-selector/flat-picker/flat-picker.component.ts
  projects/legacy/components/color-selector/linear-multi-picker/linear-multi-picker.component.ts
  projects/legacy/components/color-selector/linear-picker/linear-picker.component.ts
  projects/legacy/components/color-selector/palette/palette.component.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-color/input-color.component.ts
  projects/legacy/components/input-copy/input-copy.component.ts
  projects/legacy/components/input-date-multi/input-date-multi.component.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-month-range/input-month-range.component.ts
  projects/legacy/components/input-month/input-month.component.ts
  projects/legacy/components/input-number/input-number.component.ts
  projects/legacy/components/input-password/input-password.component.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-range/input-range.component.ts
  projects/legacy/components/input-slider/input-slider.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-time/native-time/native-time.component.ts
  projects/legacy/components/input-year/input-year.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select-option/multi-select-option.component.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/multi-select/native-multi-select/native-multi-select-group.component.ts
  projects/legacy/components/multi-select/native-multi-select/native-multi-select.component.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.component.ts
  projects/legacy/components/primitive-textfield/textfield/textfield.component.ts
  projects/legacy/components/primitive-textfield/value-decoration/value-decoration.component.ts
  projects/legacy/components/select-option/select-option.component.ts
  projects/legacy/components/select/native-select/native-select-group.component.ts
  projects/legacy/components/select/native-select/native-select.component.ts
  projects/legacy/components/select/select.component.ts
  projects/legacy/components/sheet/components/sheet-bar/sheet-bar.component.ts
  projects/legacy/components/sheet/components/sheet-heading/sheet-heading.component.ts
  projects/legacy/components/sheet/components/sheet/sheet.component.ts
  projects/legacy/components/sheet/components/sheets-host/sheets-host.component.ts
  projects/legacy/components/svg/svg.component.ts
  projects/legacy/components/table-bar/table-bar.component.ts
  projects/legacy/components/table-bar/table-bars-host.component.ts
  projects/legacy/components/tag/tag.component.ts
  projects/legacy/components/textarea/textarea.component.ts
  projects/legacy/components/tooltip/tooltip.component.ts
Labels: ready to merge

#9333 chore: cleanup e2e
  .github/screenshot-bot.config.toml
  .github/workflows/e2e-playwright.yml
  .github/workflows/snapshots.yml
  projects/demo-playwright/tests/ssg.spec.ts
Labels: ready to merge

#9330 fix(cdk): `Control` react to `markAsTouched` on Angular 18+
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/cdk/classes/control.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/demo/src/modules/components/breadcrumbs/examples/1/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/3/index.html
  projects/demo/src/modules/components/breadcrumbs/examples/3/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/3/index.ts
  projects/demo/src/modules/components/breadcrumbs/index.ts
  projects/kit/components/breadcrumbs/breadcrumbs.component.ts
  projects/kit/components/breadcrumbs/breadcrumbs.style.less
  projects/kit/components/breadcrumbs/breadcrumbs.template.html
  projects/legacy/classes/control.ts
Labels: ready to merge

#9329 chore: do not use defaultView
  projects/core/components/root/root.component.ts
  projects/demo/src/modules/app/search/index.ts
Labels: ready to merge

#9328 chore(demo): add auto generating sitemap xml
  .cspell.json
  projects/demo/project.json
  scripts/generate-sitemap.ts
Labels: ready to merge

#9291 fix(core): `Hint` fix change detection when changing content programmatically
  projects/core/directives/hint/hint-unstyled.component.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.directive.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
Labels: ready to merge

#9339 chore(cdk): fix dompurify version
  projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
Labels: ready to merge

#9340 fix(legacy): `InputTag` fix pasting multiple invalid tags
  projects/legacy/components/input-tag/input-tag.component.ts
Labels: ready to merge

#9344 chore: add sitemap.xml to gitignore
  .gitignore
Labels: ready to merge

#9342 feat(kit): add `tuiValidationErrorsProvider`
  projects/demo/src/modules/components/error/index.html
  projects/demo/src/modules/components/textarea/examples/4/index.ts
  projects/demo/src/modules/pipes/field-error/examples/2/index.ts
  projects/demo/src/modules/pipes/field-error/examples/6/index.ts
  projects/demo/src/modules/pipes/field-error/index.html
  projects/kit/pipes/field-error/test/field-error-content-pipe.spec.ts
  projects/kit/tokens/validation-errors.ts
Labels: ready to merge

#9293 ci: attach Cypress CT diff-snapshots to CI report
  .github/screenshot-bot.config.toml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e.yml
  projects/demo-cypress/cypress-image-diff.config.js
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
  projects/demo/src/modules/components/chip/examples/4/index.html
  scripts/visual-testing/combine-snapshots.ts
Labels: ready to merge

#9346 chore(demo): small changes in header
  projects/demo/src/modules/app/search/index.less
Labels: ready to merge

#8546 feat(kit): added search function in international phone component
  projects/core/components/data-list/data-list.component.ts
  projects/core/tokens/common-icons.ts
  projects/demo/src/modules/components/input-phone-international/examples/2/index.html
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/input-phone-international/index.ts
  projects/i18n/languages/belarusian/kit.ts
  projects/i18n/languages/chinese/kit.ts
  projects/i18n/languages/dutch/kit.ts
  projects/i18n/languages/english/kit.ts
  projects/i18n/languages/french/kit.ts
  projects/i18n/languages/german/kit.ts
  projects/i18n/languages/hebrew/kit.ts
  projects/i18n/languages/italian/kit.ts
  projects/i18n/languages/japan/kit.ts
  projects/i18n/languages/kazakh/kit.ts
  projects/i18n/languages/korean/kit.ts
  projects/i18n/languages/lithuanian/kit.ts
  projects/i18n/languages/malay/kit.ts
  projects/i18n/languages/polish/kit.ts
  projects/i18n/languages/portuguese/kit.ts
  projects/i18n/languages/russian/kit.ts
  projects/i18n/languages/spanish/kit.ts
  projects/i18n/languages/turkish/kit.ts
  projects/i18n/languages/ukrainian/kit.ts
  projects/i18n/languages/vietnamese/kit.ts
  projects/i18n/types/language.ts
  projects/kit/components/input-phone-international/get-country-calling-code.pipe.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.style.less
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/tokens/i18n.ts
  projects/kit/utils/index.ts
  projects/kit/utils/phone.ts
Labels: ready to merge

#9352 chore(demo-cypress): improve Cypress snapshots quality
  projects/demo-cypress/cypress.config.ts
  projects/demo-cypress/project.json
Labels: ready to merge

#9348 fix(core): fix overriding default dropdown options
  projects/core/components/textfield/textfield.component.ts
  projects/core/directives/dropdown/dropdown-fixed.directive.ts
  projects/core/directives/dropdown/index.ts
  projects/demo/src/modules/components/textfield/examples/3/index.html
  projects/demo/src/modules/components/textfield/examples/3/index.ts
  projects/legacy/components/combo-box/combo-box.component.ts
  projects/legacy/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input/input.component.ts
  projects/legacy/components/multi-select/multi-select.component.ts
  projects/legacy/components/select/select.component.ts
Labels: ready to merge

#9341 fix(addon-doc): glitch width content between value from DOM and sandbox width from url
  projects/addon-doc/components/demo/index.html
  projects/addon-doc/components/demo/index.ts
Labels: ready to merge

#9363 feat(kit): `ItemsWithMore` add `side` option
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.style.less
  projects/core/styles/components/icon.less
  projects/demo/src/modules/components/items-with-more/examples/3/index.html
  projects/demo/src/modules/components/items-with-more/examples/3/index.ts
  projects/demo/src/modules/components/items-with-more/index.html
  projects/demo/src/modules/components/items-with-more/index.ts
  projects/kit/components/items-with-more/items-with-more.component.ts
  projects/kit/components/items-with-more/items-with-more.directive.ts
  projects/kit/components/items-with-more/items-with-more.service.ts
  projects/kit/components/items-with-more/items-with-more.template.html
Labels: ready to merge

#9373 fix(addon-table): drop legacy package dependency
  projects/addon-table/components/table/td/td.component.ts
  projects/legacy/classes/control.ts
Labels: ready to merge

#9370 feat(kit): `Breadcrumbs` add `itemsLimit` option
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/addon-doc/components/navigation/navigation.style.less
  projects/addon-table/components/reorder/reorder.style.less
  projects/addon-table/components/table/th/th.style.less
  projects/cdk/constants/used-icons.ts
  projects/core/tokens/common-icons.ts
  projects/demo/src/modules/components/animations/examples/4/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.html
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.less
  projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts
  projects/demo/src/modules/components/breadcrumbs/examples/3/index.html
  projects/demo/src/modules/components/breadcrumbs/examples/3/index.ts
  projects/demo/src/modules/components/breadcrumbs/index.html
  projects/demo/src/modules/components/breadcrumbs/index.ts
  projects/demo/src/modules/components/combo-box/index.less
  projects/demo/src/modules/components/data-list/examples/1/index.less
  projects/demo/src/modules/components/input-range/examples/4/index.less
  projects/demo/src/modules/components/legend-item/examples/2/index.less
  projects/demo/src/modules/components/range/examples/3/index.less
  projects/demo/src/modules/components/tree/examples/3/index.less
  projects/demo/src/modules/directives/dropdown-context/examples/2/index.less
  projects/demo/used-icons.ts
  projects/kit/components/accordion/accordion-item.style.less
  projects/kit/components/breadcrumbs/breadcrumbs.component.ts
  projects/kit/components/breadcrumbs/breadcrumbs.options.ts
  projects/kit/components/breadcrumbs/breadcrumbs.style.less
  projects/kit/components/breadcrumbs/breadcrumbs.template.html
  projects/kit/components/files/input-files/input-files.style.less
  projects/kit/directives/tooltip/tooltip.style.less
  projects/legacy/components/arrow/arrow.style.less
  projects/legacy/components/input-copy/input-copy.style.less
  projects/legacy/components/input-date-range/input-date-range.style.less
  projects/legacy/components/input-date-time/input-date-time.style.less
  projects/legacy/components/input-date/input-date.style.less
  projects/legacy/components/input-password/input-password.style.less
  projects/legacy/components/input-time/input-time.style.less
  projects/legacy/components/primitive-textfield/primitive-textfield.style.less
  projects/legacy/components/select-option/select-option.style.less
  projects/legacy/components/textarea/textarea.style.less
  projects/legacy/components/tooltip/tooltip.style.less
  projects/legacy/styles/mixins/textfield.less
Labels: ready to merge

#9366 refactor: drop deprecated `TuiImgLazyLoading`
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/avatar/avatar.template.html
Labels: ready to merge

#9371 chore: commitlint
  .husky/commit-msg
  .husky/pre-commit
Labels: ready to merge

#9385 chore(demo-cypress): delete forbidden character `:` from snapshot names
  projects/demo-cypress/src/tests/textfield.cy.ts
Labels: ready to merge

#9381 feat(addon-doc): allow adding extra tabs with DI
  projects/addon-doc/components/page/page.component.ts
  projects/addon-doc/components/page/page.providers.ts
  projects/addon-doc/components/page/page.template.html
  projects/addon-doc/components/page/tests/page.component.spec.ts
Labels: ready to merge

#9276 feat(core): support using native scrollbar
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.style.less
  projects/core/components/scrollbar/scroll-controls.component.ts
  projects/core/components/scrollbar/scroll-controls.template.html
  projects/core/components/scrollbar/scrollbar.component.ts
  projects/core/components/scrollbar/scrollbar.options.ts
  projects/core/components/scrollbar/scrollbar.template.html
  projects/demo/src/modules/components/scrollbar/examples/8/index.html
  projects/demo/src/modules/components/scrollbar/examples/8/index.less
  projects/demo/src/modules/components/scrollbar/examples/8/index.ts
  projects/demo/src/modules/components/scrollbar/index.ts
Labels: ready to merge

#9367 fix(addon-doc): add `legacy` package as peer dependency
  package-lock.json
  projects/addon-doc/package.json
Labels: ready to merge

#9374 fix(addon-table): hydration error while configuring table
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/addon-table/components/table/tr/tr.component.ts
  projects/core/components/expand/expand.component.ts
Labels: ready to merge

#9376 feat(legacy): support fieldset disable
  projects/legacy/components/color-selector/color-selector.style.less
  projects/legacy/components/combo-box/combo-box.style.less
  projects/legacy/components/input-color/input-color.style.less
  projects/legacy/components/input-copy/input-copy.style.less
  projects/legacy/components/input-date-range/input-date-range.style.less
  projects/legacy/components/input-date-time/input-date-time.style.less
  projects/legacy/components/input-date/input-date.style.less
  projects/legacy/components/input-month-range/input-month-range.style.less
  projects/legacy/components/input-month/input-month.style.less
  projects/legacy/components/input-number/input-number.style.less
  projects/legacy/components/input-password/input-password.style.less
  projects/legacy/components/input-phone-international/input-phone-international.style.less
  projects/legacy/components/input-phone/input-phone.style.less
  projects/legacy/components/input-range/input-range.style.less
  projects/legacy/components/input-slider/input-slider.style.less
  projects/legacy/components/input-tag/input-tag.style.less
  projects/legacy/components/input-time/input-time.style.less
  projects/legacy/components/input-year/input-year.style.less
  projects/legacy/components/input/input.style.less
  projects/legacy/components/multi-select/multi-select.style.less
  projects/legacy/components/select/select.style.less
  projects/legacy/components/tag/tag.style.less
  projects/legacy/components/textarea/textarea.style.less
  projects/legacy/styles/mixins/textfield.less
Labels: ready to merge

#9384 feat(addon-table): `Sortable` make dynamic
  projects/addon-table/components/table/directives/sortable.directive.ts
  projects/demo/src/modules/components/table/examples/4/index.html
  projects/demo/src/modules/components/table/examples/4/index.less
  projects/demo/src/modules/components/table/examples/4/index.ts
Labels: ready to merge

#9237 chore(demo): `Textfield` add reuse component & migrate `TextfieldController` to new approach
  projects/demo/src/components/control/index.html
  projects/demo/src/components/control/index.ts
  projects/demo/src/components/textfield/index.html
  projects/demo/src/components/textfield/index.ts
  projects/demo/src/modules/components/textfield/index.html
  projects/demo/src/modules/components/textfield/index.ts
  projects/demo/src/modules/directives/textfield-controller/index.html
Labels: ready to merge, v4

#9388 chore(demo): add base64 example
  projects/demo/src/modules/components/icon/index.ts
Labels: ready to merge

#9368 chore(demo): add example with form fieldset
  projects/demo/src/modules/components/textfield/examples/6/index.html
  projects/demo/src/modules/components/textfield/examples/6/index.less
  projects/demo/src/modules/components/textfield/examples/6/index.ts
  projects/demo/src/modules/components/textfield/index.ts
Labels: ready to merge

#9414 fix: allow to install the same cdk of peer dependencies
  package-lock.json
  projects/addon-charts/package.json
  projects/addon-commerce/package.json
  projects/addon-doc/package.json
  projects/addon-mobile/package.json
  projects/addon-table/package.json
  projects/cdk/package.json
  projects/core/package.json
  projects/demo/package.json
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
  projects/experimental/package.json
  projects/i18n/package.json
  projects/kit/package.json
  projects/layout/package.json
  projects/legacy/package.json
  projects/styles/package.json
  projects/taiga-schematics/package.json
  projects/testing/package.json
Labels: ready to merge

#9416 refactor: the word-wrap property was renamed to overflow-wrap in CSS3
  projects/addon-doc/components/code/index.less
  projects/core/components/dialog/dialog.style.less
  projects/core/components/error/error.style.less
  projects/core/directives/hint/hint.style.less
  projects/demo/src/modules/components/dialog/examples/4/index.less
  projects/kit/components/accordion/accordion-item.style.less
  projects/kit/components/files/input-files/input-files.style.less
  projects/kit/components/line-clamp/line-clamp-box.style.less
  projects/legacy/components/textarea/textarea.style.less
  projects/styles/markup/tui-island.less
  projects/styles/markup/tui-list.less
  projects/styles/markup/tui-table.less
Labels: ready to merge

#9413 Labeled checkbox and radio bug fix
  projects/kit/components/checkbox-labeled/checkbox-labeled.component.ts
  projects/kit/components/checkbox-labeled/checkbox-labeled.template.html
  projects/kit/components/radio-labeled/radio-labeled.component.ts
  projects/kit/components/radio-labeled/radio-labeled.template.html
Labels: v3

#9408 fix(core): support provide empty icon value
  projects/core/tokens/icon-resolver.ts
Labels: ready to merge

#9411 fix(addon-mobile): `InputDateRange` throws error on single date selection
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-date-range.po.ts
  projects/demo-playwright/utils/page-objects/mobile-calendar.po.ts
Labels: ready to merge

#9245 chore(demo-playwright): move tests for legacy components to `legacy`
  projects/demo-playwright/tests/legacy/combo-box/combobox.spec.ts
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.spec.ts
  projects/demo-playwright/tests/legacy/input-date-time/input-date-time.spec.ts
  projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
  projects/demo-playwright/tests/legacy/input-month-range/input-month-range.spec.ts
  projects/demo-playwright/tests/legacy/input-month/input-month.spec.ts
  projects/demo-playwright/tests/legacy/input-number/input-number.spec.ts
  projects/demo-playwright/tests/legacy/input-phone-international/input-phone-international.spec.ts
  projects/demo-playwright/tests/legacy/input-phone/input-phone.spec.ts
  projects/demo-playwright/tests/legacy/input-range/input-range.spec.ts
  projects/demo-playwright/tests/legacy/input-slider/input-slider.spec.ts
  projects/demo-playwright/tests/legacy/input-tag/input-tag.spec.ts
  projects/demo-playwright/tests/legacy/input-time/input-time.spec.ts
  projects/demo-playwright/tests/legacy/input-year/input-year.spec.ts
  projects/demo-playwright/tests/legacy/input/input.spec.ts
  projects/demo-playwright/tests/legacy/multi-select/multi-select.spec.ts
  projects/demo-playwright/tests/legacy/primitive-textfield/primitive-textfield.spec.ts
  projects/demo-playwright/tests/legacy/select/select.mobile.spec.ts
  projects/demo-playwright/tests/legacy/select/select.spec.ts
Labels: ready to merge, v4

#9422 fix(addon-doc): `DocDemo` remove `timer` and `tuiZonefreeScheduler`
  projects/addon-doc/components/demo/index.ts
Labels: ready to merge

#9427 chore: add test
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/demo-playwright/tests/core/surface/surface.spec.ts
  projects/demo/src/modules/components/surface/index.html
Labels: ready to merge

#9428 chore: add contributors image
  README.md
Labels: ready to merge

#9406 refactor: `tuiParseColor`
  projects/cdk/utils/color/parse-color.ts
Labels: ready to merge

#9409 refactor: prefer nullish
  projects/kit/components/filter/test/filter.component.spec.ts
  projects/legacy/components/tag/tag.component.ts
Labels: ready to merge

#9433 fix(legacy): `Select` fix hydration
  projects/legacy/components/select/select.template.html
Labels: ready to merge

#9418 feat(testing): use jest-preset-angular by default
  jest.config.ts
  package-lock.json
  projects/demo/src/modules/info/testing/jest/examples/setup-jest.md
  projects/testing/package.json
  projects/testing/setup-jest/index.ts
  setup-jest.ts
Labels: ready to merge

#9452 fix(kit): `InputPhoneInternational` signal `countries`
  projects/kit/components/input-phone-international/input-phone-international.component.ts
Labels: ready to merge

#9453 fix(kit): `Accordion` fix hydration issue
  projects/core/components/expand/expand.component.ts
  projects/kit/components/accordion/accordion-item.template.html
Labels: ready to merge

#9455 chore(demo): remove table markup demo
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/markup/tables/examples/1/index.html
  projects/demo/src/modules/markup/tables/examples/1/index.ts
  projects/demo/src/modules/markup/tables/index.html
  projects/demo/src/modules/markup/tables/index.less
  projects/demo/src/modules/markup/tables/index.ts
Labels: ready to merge

#9460 fix(addon-table): `tr`, `thGroup` fix hydration issues
  projects/addon-table/components/table/th-group/th-group.component.ts
  projects/addon-table/components/table/th-group/th-group.template.html
  projects/addon-table/components/table/tr/tr.component.ts
  projects/addon-table/components/table/tr/tr.template.html
Labels: ready to merge

#9404 refactor: add `@ng-web-apis/platform`
  package-lock.json
  projects/cdk/package.json
  projects/cdk/tokens/environment.ts
  projects/cdk/utils/browser/is-ios.ts
  projects/legacy/tokens/is-apple.ts
  projects/legacy/utils/is-apple.ts
Labels: ready to merge

#9464 fix(legacy): `InputDateTime` fix native option for empty value
  projects/legacy/components/input-date-time/input-date-time.directive.ts
Labels: ready to merge

#9470 refactor: stricter checks in `tuiIsHTMLElement`
  projects/cdk/utils/dom/element-checks.ts
Labels: ready to merge

#9441 chore(demo): small refactor metrika.service.ts
  projects/demo/src/modules/app/metrika/metrika.service.ts
Labels: ready to merge

#9419 ci: add code owner alias
  .github/CODEOWNERS
Labels: ready to merge

#9481 chore(demo): show github star in runtime
  projects/demo/src/environments/environment.prod.ts
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/app.style.less
  projects/demo/src/modules/app/app.template.html
  projects/demo/used-icons.ts
Labels: ready to merge

#9438 chore(demo): `InputPhoneInternational` update `API` page
  projects/addon-doc/components/api/api-item.style.less
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/input-phone-international/index.ts
Labels: ready to merge

#9451 chore: improve vscode dx
  .vscode/settings.json
Labels: ready to merge

#9506 chore(demo-playwright): update `@playwright/test` to `1.48.0`
  package-lock.json
  package.json
  projects/demo-playwright/package.json
Labels: ready to merge, v3

#9459 feat(addon-mobile): `ResponsiveDialog` add new service and refactor `SheetDialog` to new spec
  package-lock.json
  projects/addon-doc/components/language-switcher/index.ts
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.service.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
  projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts
  projects/addon-mobile/directives/index.ts
  projects/addon-mobile/directives/responsive-dialog/index.ts
  projects/addon-mobile/directives/responsive-dialog/ng-package.json
  projects/addon-mobile/directives/responsive-dialog/responsive-dialog.directive.ts
  projects/addon-mobile/directives/responsive-dialog/responsive-dialog.service.ts
  projects/addon-mobile/styles/android/app-bar.less
  projects/addon-mobile/styles/common/search.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
  projects/addon-table/components/table/directives/stuck.directive.ts
  projects/addon-table/components/table/providers/table.provider.ts
  projects/cdk/directives/click-outside/click-outside.directive.ts
  projects/cdk/directives/hovered/hovered.service.ts
  projects/cdk/directives/index.ts
  projects/cdk/directives/visual-viewport/index.ts
  projects/cdk/directives/visual-viewport/ng-package.json
  projects/cdk/directives/visual-viewport/visual-viewport.directive.ts
  projects/cdk/observables/watch.ts
  projects/cdk/package.json
  projects/cdk/services/popover.service.ts
  projects/core/components/root/root.component.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/pipes/flag/flag.pipe.ts
  projects/core/styles/components/title.less
  projects/core/styles/mixins/mixins.less
  projects/demo/src/modules/components/card-large/examples/import/import.md
  projects/demo/src/modules/components/card-large/examples/import/template.md
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/5/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/5/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/5/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.ts
  projects/demo/src/modules/components/sheet-dialog/index.ts
  projects/i18n/types/language-names.ts
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/progress/progress-bar/progress-color-segments.directive.ts
  projects/kit/components/slider/slider.component.ts
  projects/kit/directives/lazy-loading/lazy-loading.service.ts
  projects/kit/directives/sensitive/sensitive.directive.ts
  projects/kit/directives/tooltip/tooltip.directive.ts
  projects/layout/components/app-bar/app-bar-back.style.less
  projects/layout/components/app-bar/app-bar.providers.ts
  projects/layout/components/app-bar/app-bar.style.less
Labels: ready to merge

#9523 chore: enable core team
  .github/CODEOWNERS
Labels: ready to merge

#9443 refactor: simplify configuration code
  jest.config.ts
  projects/cdk/schematics/utils/is-ci.ts
  projects/cdk/schematics/utils/progress.ts
  projects/icons-fontawesome/scripts/prepare-icons.ts
  projects/icons-material/scripts/prepare-icons.ts
  projects/icons/scripts/prepare-icons.ts
Labels: ready to merge

#9450 chore: enable i18n lint
  package.json
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/pipes/field-error/examples/5/index.ts
Labels: ready to merge

#9471 refactor: add typing for `focused` constant
  projects/addon-mobile/services/keyboard.service.ts
Labels: ready to merge

#9445 ci: investigate how work gh cli after close pr
  .github/workflows/cleanup-resources.yml
Labels: ready to merge

#9482 chore: use GitHub online editor instead of StackBlitz resources
  README.md
Labels: ready to merge

#9472 refactor: use `unknown` instead of `any` for `isMultiValue` util
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
Labels: ready to merge

#9434 fix(legacy): `InputNumber` fix hydration
  projects/legacy/components/primitive-textfield/primitive-textfield.style.less
  projects/legacy/components/primitive-textfield/primitive-textfield.template.html
Labels: ready to merge

#9502 fix(addon-mobile): `InputDateRange` + `MobileCalendar` throw error on single date selection
  projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.component.ts
Labels: ready to merge, v3

#9527 chore(demo): add components metadata
  .cspell.json
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#9510 feat(addon-doc): improve active zone for copy button
  projects/addon-doc/components/code/index.html
  projects/addon-doc/components/code/tests/code.component.spec.ts
Labels: ready to merge

#9462 ci: reuse jest config between taiga-family projects
  jest.config.ts
  package-lock.json
  package.json
  projects/addon-charts/project.json
  projects/addon-commerce/project.json
  projects/addon-doc/project.json
  projects/addon-mobile/project.json
  projects/addon-table/project.json
  projects/cdk/project.json
  projects/core/project.json
  projects/demo/project.json
  projects/experimental/project.json
  projects/i18n/project.json
  projects/icons/project.json
  projects/kit/project.json
  projects/layout/project.json
  projects/legacy/project.json
  projects/testing/project.json
Labels: ready to merge

#9496 chore(demo): add angular press kit logo
  projects/demo/src/modules/app/landing/index.html
  projects/demo/src/modules/app/landing/index.less
Labels: ready to merge

#9446 feat(core): add dialog-factory
  projects/core/components/dialog/dialog.factory.ts
  projects/core/components/dialog/index.ts
  projects/core/components/dialog/test/dialog.factory.spec.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/2/index.ts
  projects/demo/src/modules/components/dialog/examples/7/index.ts
  projects/demo/src/modules/components/dialog/examples/9/index.ts
  projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
Labels: ready to merge

#9541 refactor(legacy): `InputTime` uses built-in feature `step` from `Time` Maskito mask
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-time/input-time.template.html
  projects/legacy/components/input-time/test/input-time.component.spec.ts
Labels: ready to merge

#9528 chore(demo): add deps for stackblitz
  package-lock.json
  projects/cdk/package.json
  projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Labels: ready to merge

#9546 chore(demo): change spelling
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#9487 feat(addon-table): add requiredSort option to table
  projects/addon-table/components/table/table.options.ts
  projects/addon-table/components/table/th/th.component.ts
  projects/demo/src/modules/tables/table/examples/4/index.html
Labels: v3

#9522 chore(styles): `tui-space` increase specifity
  projects/styles/markup/tui-space.less
Labels: ready to merge

#9520 fix(addon-commerce): `InputCardGroup` safari autofill focus
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
Labels: ready to merge

#9551 chore: wait font status
  projects/demo-cypress/src/support/component.ts
Labels: ready to merge

#9548 chore: drop redundant code for mobile
  projects/addon-doc/components/code/index.less
Labels: ready to merge

#9550 chore: provide github token
  .github/workflows/cleanup-resources.yml
Labels: ready to merge

#9549 fix(cdk): support `:` inside path segment in url
  projects/cdk/utils/miscellaneous/is-valid-url.ts
  projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
Labels: ready to merge

#9545 chore(testing): incorrect resolving peer dependency
  package-lock.json
  projects/testing/package.json
Labels: ready to merge

#9547 feat(core): `Hint` add mobile behavior
  projects/core/animations/animations.ts
  projects/core/classes/accessors.ts
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint-position.directive.ts
  projects/core/directives/hint/hint.component.ts
  projects/core/directives/hint/hint.style.less
  projects/core/services/position.service.ts
  projects/core/styles/components/notification.less
  projects/core/utils/miscellaneous/to-animation-options.ts
  projects/demo/src/modules/directives/hint-describe/examples/1/index.html
  projects/kit/directives/tooltip/tooltip.directive.ts
  projects/legacy/components/input-date-time/native-date-time/native-date-time.directive.ts
  projects/legacy/components/input-date/native-date/native-date.component.ts
  projects/legacy/components/tooltip/tooltip.component.ts
Labels: ready to merge

#9557 chore(addon-mobile): improve StackBlitz support for `taiga-ui-mobile.less`
  projects/addon-mobile/styles/taiga-ui-mobile.less
Labels: ready to merge

#9562 chore(demo): show default search if algolia is not available
  projects/addon-doc/components/navigation/navigation.template.html
  projects/addon-doc/tokens/i18n.ts
  projects/demo/src/modules/app/app.config.ts
Labels: ready to merge

#9561 chore(addon-mobile): stackblitz error for import of `taiga-ui-mobile.less`
  projects/addon-mobile/styles/taiga-ui-mobile.less
Labels: ready to merge

#9571 feat(kit): `Tooltip` add DI options
  projects/core/directives/hint/hint-options.directive.ts
  projects/core/directives/hint/hint.style.less
  projects/kit/directives/tooltip/index.ts
  projects/kit/directives/tooltip/tooltip.directive.ts
  projects/kit/directives/tooltip/tooltip.options.ts
  projects/kit/directives/tooltip/tooltip.style.less
  projects/legacy/components/tooltip/tooltip.component.ts
Labels: ready to merge

#9569 fix(kit): `InputPhoneInternational` fix dropdown issues
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
  projects/demo/src/modules/components/sheet-dialog/index.html
  projects/demo/src/modules/components/sheet-dialog/index.ts
  projects/kit/components/files/files.validators.ts
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.style.less
  projects/kit/components/input-phone-international/input-phone-international.template.html
  projects/kit/components/rating/rating.options.ts
  projects/kit/components/rating/rating.style.less
  projects/kit/components/rating/rating.template.html
Labels: ready to merge

#9580 fix(core): `Notification` remove flex layout
  projects/addon-doc/components/main/main.style.less
  projects/core/components/alert/alert.style.less
  projects/core/components/alert/alert.template.html
  projects/core/styles/components/notification.less
  projects/demo/src/modules/app/home/home.template.html
  projects/demo/src/modules/app/styles-info/index.html
  projects/demo/src/modules/components/bar-chart/index.html
  projects/demo/src/modules/components/cell/examples/7/index.html
  projects/demo/src/modules/components/cell/examples/8/index.html
  projects/demo/src/modules/components/checkbox/index.html
  projects/demo/src/modules/components/combo-box/index.html
  projects/demo/src/modules/components/confirm/index.html
  projects/demo/src/modules/components/data-list/index.html
  projects/demo/src/modules/components/dialog/index.html
  projects/demo/src/modules/components/input-color/index.html
  projects/demo/src/modules/components/input-date-range/index.html
  projects/demo/src/modules/components/input-date-time/index.html
  projects/demo/src/modules/components/input-date/examples/4/index.html
  projects/demo/src/modules/components/input-month-range/index.html
  projects/demo/src/modules/components/input-month/index.html
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/input-phone/index.html
  projects/demo/src/modules/components/input-range/index.html
  projects/demo/src/modules/components/input-slider/index.html
  projects/demo/src/modules/components/input-year/index.html
  projects/demo/src/modules/components/input/examples/10/index.html
  projects/demo/src/modules/components/input/index.html
  projects/demo/src/modules/components/island/index.html
  projects/demo/src/modules/components/line-clamp/examples/1/index.html
  projects/demo/src/modules/components/line-days-chart/examples/2/index.html
  projects/demo/src/modules/components/notification/examples/1/index.html
  projects/demo/src/modules/components/pdf-viewer/index.html
  projects/demo/src/modules/components/pie-chart/index.html
  projects/demo/src/modules/components/primitive-textfield/index.html
  projects/demo/src/modules/components/pull-to-refresh/index.html
  projects/demo/src/modules/components/radio/index.html
  projects/demo/src/modules/components/range/index.html
  projects/demo/src/modules/components/scrollbar/index.html
  projects/demo/src/modules/components/select/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.html
  projects/demo/src/modules/components/sheet/index.html
  projects/demo/src/modules/components/slider/index.html
  projects/demo/src/modules/components/surface/index.html
  projects/demo/src/modules/components/switch/index.html
  projects/demo/src/modules/components/tab-bar/index.html
  projects/demo/src/modules/components/tabs/index.html
  projects/demo/src/modules/components/tag/index.html
  projects/demo/src/modules/components/textarea/index.html
  projects/demo/src/modules/directives/hint/index.html
  projects/demo/src/modules/directives/resizer/index.html
  projects/demo/src/modules/directives/sensitive/index.html
  projects/demo/src/modules/info/browsers/index.html
  projects/demo/src/modules/info/migration-guide/index.html
  projects/demo/src/modules/markup/typography/index.html
  projects/demo/src/modules/pipes/stringify-content/index.html
  projects/demo/src/modules/pipes/stringify/index.html
Labels: ready to merge

#9582 fix(kit): `InputDate` click any day after `Until today` selected
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
  projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
  projects/demo-playwright/utils/page-objects/calendar.po.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-date.po.ts
  projects/kit/components/input-date/input-date.component.ts
Labels: ready to merge, v3

#9588 chore(demo-playwright): `InputDate` add test click any day after `Until today`
  projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
  projects/demo-playwright/utils/page-objects/calendar.po.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-date.po.ts
Labels: ready to merge

#9581 fix(core): `DropdownOpen` fix initial open state
  projects/core/classes/driver.ts
  projects/core/components/dialog/dialog.style.less
  projects/core/components/dialog/dialog.template.html
  projects/core/directives/dropdown/dropdown.driver.ts
  projects/demo/src/modules/app/app.style.less
  projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
Labels: ready to merge

#9594 fix(layout): `Navigation` fix drawer positioning
  projects/demo/src/modules/components/navigation/index.less
  projects/demo/src/styles/styles.less
  projects/layout/components/navigation/drawer.component.ts
  projects/layout/components/navigation/drawer.style.less
  projects/layout/components/navigation/header.style.less
Labels: ready to merge

#9560 chore: disable squash automerge in release branch
  .github/workflows/auto-merge.yml
Labels: ready to merge

#9579 chore(demo): hide search button if algolia is not available
  projects/demo/src/modules/app/app.component.ts
  projects/demo/src/modules/app/app.template.html
Labels: ready to merge

#9593 fix(kit): `Badge` fix font size on desktop
  projects/kit/styles/components/badge.less
Labels: ready to merge

#9596 chore(demo): update description to improve search
  projects/demo/src/modules/components/textfield/index.html
Labels: ready to merge

#9587 feat(core): `Calendar` not switch to large date
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/cdk/date-time/date-time.ts
  projects/cdk/date-time/days.const.ts
  projects/core/components/calendar/calendar.component.ts
  projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
  projects/legacy/components/input-date/input-date.component.ts
Labels: ready to merge

#9605 feat(core): `Popup` add service for arbitrary portal items
  projects/addon-mobile/directives/sidebar/sidebar.directive.ts
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.style.less
  projects/core/components/root/root.template.html
  projects/core/directives/dropdown/dropdowns.component.ts
  projects/core/services/index.ts
  projects/core/services/popup.service.ts
  projects/demo/src/modules/components/label/examples/1/index.html
  projects/demo/src/modules/components/label/examples/1/index.ts
  projects/demo/src/styles/styles.less
  projects/kit/directives/tooltip/tooltip.style.less
Labels: ready to merge

#9604 fix(addon-commerce): `ThumbnailCard` with blur effect should keep its initial border-radius
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less
Labels: ready to merge

#9612 refactor(addon-commerce): simplify html-structure of `ThumbnailCard`
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less
  projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
Labels: ready to merge

#9601 feat(kit): `TuiInputPhoneInternational` has separator customization
  projects/demo/src/modules/components/input-phone-international/examples/5/index.html
  projects/demo/src/modules/components/input-phone-international/examples/5/index.ts
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-phone-international/input-phone-international.options.ts
  projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Labels: community contribution

#9603 chore(cdk): fix migration issues
  projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts
  projects/cdk/schematics/ng-update/v4/migrate-css-vars/rename-css-vars.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
Labels: ready to merge

#9602 chore(cdk): fix labeled migration
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Labels: ready to merge

#9573 chore: add `@taiga-ui/jest-config` to `IGNORABLE_TAIGA_PACKAGES`
  scripts/shared/ignorable-packages.ts
Labels: ready to merge

#9635 fix(kit): `Files` fix link styles
  projects/demo-playwright/tests/kit/input-files/input-files.spec.ts
  projects/demo/src/modules/components/input-files/examples/3/index.html
  projects/demo/src/modules/components/input-files/examples/4/index.html
  projects/kit/components/files/files/files.styles.less
Labels: ready to merge
