Repository taiga-family/taiga-ui, pull requests merged in 2025-01, with the labels that each got.

#10056 feat(core): add `injector` to tuiDialog options
  projects/core/components/dialog/dialog.factory.ts
Labels: ready to merge

#10078 chore(schematics): valid migration for size of `tui-data-list-wrapper`
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts
Labels: ready to merge

#10087 chore(schematics): valid migration for icons
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
Labels: ready to merge

#10090 chore(schematics): valid migration for `tui-primitive-textfield`
  projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Labels: ready to merge

#10088 chore(schematics): valid migration for resizable module
  projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-resizer.spec.ts
Labels: ready to merge

#10089 chore(schematics): valid migration for tree references
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-tree.spec.ts
Labels: ready to merge

#10096 chore(schematics): valid migration for error pipe module
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-error.spec.ts
Labels: ready to merge

#10121 fix(layout): `BlockStatus` fix image height
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge

#10123 chore(schematics): valid migration for expandable in template
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-expandable.spec.ts
Labels: ready to merge

#10125 chore(schematics): valid migration for scrollbar
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-scrollbar.spec.ts
Labels: ready to merge

#10082 fix(cdk): `TuiTime.shift` doesn't shift higher order units
  projects/cdk/date-time/test/time.spec.ts
  projects/cdk/date-time/time.ts
Labels: community contribution, v3

#10126 fix(experimental): `Header` fix subtitle padding on mobile
  projects/experimental/directives/header/header.styles.less
Labels: ready to merge, v3

#10115 chore(schematics): valid migration for NG_EVENT_PLUGINS
  projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts
  projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
Labels: ready to merge

#10117 #9057 - Migrate `tui-bar-chart` docs API to new API
  projects/demo/src/modules/components/bar/index.html
Labels: ready to merge

#10116 #9057 - Migrate `tui-badged-content` doc API to new API
  projects/demo/src/modules/components/badged-content/index.html
Labels: ready to merge

#10113 #9057 - Migrate `tui-badage-notification` docs API to new API
  projects/demo/src/modules/components/badge-notification/index.html
Labels: ready to merge

#10079 #9057 - Migrate `tui-arc-chart` API docs to new API
  projects/demo/src/modules/components/arc-chart/index.html
Labels: ready to merge

#10112 #9057 - Migrate `tui-badge` docs API to new API
  projects/demo/src/modules/components/badge/index.html
Labels: ready to merge

#10083 #9057 - Migrate `tui-alert` API docs to new API
  projects/demo/src/modules/components/alert/index.html
Labels: ready to merge

#10149 chore(demo): remove redundant `inputmode=decimal` from documentation examples of new `InputNumber`
  projects/demo/src/modules/components/input-number/examples/1/index.html
  projects/demo/src/modules/components/input-number/examples/2/index.html
  projects/demo/src/modules/components/input-number/examples/3/index.html
  projects/demo/src/modules/components/input-number/examples/4/index.html
  projects/demo/src/modules/components/input-number/examples/5/index.html
Labels: ready to merge

#10135 fix(legacy): use transformed value in `tui-input-date-range` for find active period
  projects/demo/src/modules/components/input-date-range/examples/4/index.html
  projects/demo/src/modules/components/input-date-range/examples/4/index.ts
  projects/legacy/components/input-date-range/input-date-range.component.ts
Labels: ready to merge

#10128 chore(schematics): valid migration for anchor
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/inputs-to-remove.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
Labels: ready to merge

#10130 chore(schematics): valid migration for `TuiStepState`
  projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
Labels: ready to merge

#10153 chore(demo): add animation
  projects/core/utils/miscellaneous/to-animation-options.ts
  projects/demo/src/modules/components/card-large/examples/14/index.html
  projects/demo/src/modules/components/card-large/examples/14/index.ts
Labels: ready to merge

#10141 chore(schematics): valid migration for tuiProvideRoutePageTab
  projects/cdk/schematics/ng-update/v4/migrate-addon-doc/index.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-doc.spec.ts
Labels: ready to merge

#10133 chore(schematics): valid migration for legacy
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-legacy-textfields.spec.ts
Labels: ready to merge

#10156 chore(schematics): add providers for proprietary
  projects/cdk/schematics/ng-update/v4/steps/migrate-editor.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-addon-editor.spec.ts
Labels: ready to merge

#10165 fix(experimental): `SwipeActions` fix actions in IOS safari
  projects/experimental/components/swipe-action/swipe-actions.style.less
Labels: ready to merge, v3

#10171 fix(kit,legacy): all textfield controls should handle initial `ngModel` phantom `null` value
  projects/kit/components/input-phone-international/input-phone-international.component.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-phone/input-phone.component.ts
  projects/legacy/components/input-time/input-time.component.ts
  projects/legacy/components/input-year/input-year.component.ts
Labels: ready to merge

#10166 chore(demo): use new version of `InputNumber` for documentation page `Tabs`
  projects/demo/src/modules/components/tabs/examples/1/index.html
  projects/demo/src/modules/components/tabs/examples/1/index.ts
  projects/demo/src/modules/components/tabs/examples/2/index.html
  projects/demo/src/modules/components/tabs/examples/2/index.ts
  projects/demo/src/modules/components/tabs/examples/4/index.html
  projects/demo/src/modules/components/tabs/examples/4/index.ts
  projects/demo/src/modules/components/tabs/examples/5/index.html
  projects/demo/src/modules/components/tabs/examples/5/index.ts
  projects/demo/src/modules/components/tabs/examples/7/index.html
  projects/demo/src/modules/components/tabs/examples/7/index.less
  projects/demo/src/modules/components/tabs/examples/7/index.ts
Labels: ready to merge

#10160 chore(demo): use new version of `InputNumber` for documentation page `Currency`
  projects/demo/src/modules/pipes/currency/examples/2/index.html
  projects/demo/src/modules/pipes/currency/examples/2/index.ts
  projects/demo/src/modules/pipes/currency/examples/import/template.md
  projects/demo/src/modules/pipes/currency/index.html
  projects/demo/src/modules/pipes/currency/index.ts
Labels: ready to merge

#10158 chore(demo): update migration guide
  projects/demo/src/modules/info/migration-guide/index.html
Labels: ready to merge

#10173 fix(layout): get view only on demand in `tuiAsideItem`
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/demo/src/modules/components/navigation/examples/1/index.ts
  projects/layout/components/navigation/hint-aside.directive.ts
Labels: ready to merge

#10176 fix(kit): new version of `InputNumber` should provide `TuiControl` for DI
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge

#10108 #9057 - chore(demo): Migrate `tui-axes-chart` docs API to new API
  projects/demo/src/modules/components/axes/index.html
Labels: ready to merge

#10100 #9057 - chore(demo): Migrate `tui-avatar` docs API to new API
  projects/demo/src/modules/components/avatar/index.html
Labels: ready to merge

#10139 chore(schematics): valid migration for hosted dropdown
  projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/dropdown-ref-comment.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-hosted-dropdown.spec.ts
Labels: ready to merge

#10182 fix(experimental): `Accordion` fix error with dynamic items
  projects/demo/src/modules/components/accordion/examples/1/index.html
  projects/demo/src/modules/components/accordion/examples/1/index.ts
  projects/experimental/components/accordion/accordion.component.ts
  projects/experimental/components/accordion/accordion.directive.ts
  projects/experimental/components/expand/expand.component.ts
Labels: ready to merge

#10188 fix(kit): debounce `overflownChange` event
  projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
  projects/demo/src/modules/components/line-clamp/examples/3/index.html
  projects/demo/src/modules/components/line-clamp/examples/3/index.ts
  projects/demo/src/modules/components/line-clamp/index.html
  projects/kit/components/line-clamp/line-clamp.component.ts
Labels: ready to merge

#10189 chore(demo): use new version of `InputNumber` for documentation examples
  projects/demo/src/modules/components/dialog/examples/9/index.html
  projects/demo/src/modules/components/dialog/examples/9/index.ts
  projects/demo/src/modules/components/services/scroll-service/examples/1/index.html
  projects/demo/src/modules/components/services/scroll-service/examples/1/index.less
  projects/demo/src/modules/components/services/scroll-service/examples/1/index.ts
  projects/demo/src/modules/directives/copy-processor/examples/1/index.html
  projects/demo/src/modules/directives/copy-processor/examples/1/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.html
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
  projects/demo/src/modules/directives/number-format/examples/1/index.html
  projects/demo/src/modules/directives/number-format/examples/1/index.ts
  projects/demo/src/modules/directives/theme/examples/1/index.html
  projects/demo/src/modules/directives/theme/examples/1/index.ts
  projects/demo/src/modules/directives/value-changes/examples/2/index.html
  projects/demo/src/modules/directives/value-changes/examples/2/index.ts
  projects/demo/src/modules/pipes/format-number/index.html
  projects/demo/src/modules/pipes/format-number/index.ts
Labels: ready to merge

#10204 feat(addon-mobile): new android/ios icon behaviour for checkbox
  projects/addon-mobile/styles/android/checkbox.less
  projects/addon-mobile/styles/ios/checkbox.less
  projects/demo/src/modules/components/checkbox/examples/1/index.html
  projects/demo/src/modules/components/checkbox/examples/1/index.less
  projects/demo/src/modules/components/checkbox/examples/1/index.ts
  projects/kit/styles/components/checkbox.less
Labels: ready to merge

#10213 fix(addon-mobile): `DataList` inside `DropdownMobile` should not have built-in horizontal indent
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/core/components/data-list/data-list.style.less
  projects/demo-playwright/playwright.options.ts
  projects/demo-playwright/tests/addon-mobile/mobile-dropdown/mobile-dropdown-with-textfield.pw.spec.ts
  projects/demo-playwright/tests/kit/action-bar/action-bar.mobile.pw.spec.ts
  projects/demo-playwright/tests/kit/dropdown-hover/dropdown-hover.pw.spec.ts
  projects/demo-playwright/tests/kit/input-phone-international/phone-i18n-with-mobile-dropdown.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/demo-playwright/tests/legacy/select/select.mobile.pw.spec.ts
  projects/demo-playwright/utils/page-objects/textfield-with-data-list.po.ts
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.less
Labels: ready to merge

#10205 feat(core): `DataList` update labels design according to specs
  projects/addon-table/components/table/directives/table.style.less
  projects/core/components/data-list/data-list.style.less
  projects/demo/src/modules/components/pulse/examples/1/index.html
  projects/demo/src/modules/components/pulse/examples/1/index.ts
  projects/demo/src/modules/components/pulse/examples/2/index.less
  projects/kit/components/pulse/pulse.component.ts
  projects/kit/components/pulse/pulse.style.less
Labels: ready to merge

#10212 feat(layout): `Header` add body-l and body-m sizes
  projects/addon-mobile/styles/common/header.less
  projects/demo/src/modules/components/header/examples/1/index.html
  projects/demo/src/modules/components/header/examples/2/index.html
  projects/demo/src/modules/components/header/examples/2/index.ts
  projects/demo/src/modules/components/header/examples/3/index.html
  projects/layout/components/header/header.directive.ts
  projects/layout/components/header/header.styles.less
Labels: ready to merge

#10214 fix(kit): regression style in radio button
  projects/demo/src/modules/components/checkbox/index.html
  projects/demo/src/modules/components/radio/examples/1/index.html
  projects/demo/src/modules/components/radio/examples/1/index.less
  projects/demo/src/modules/components/radio/examples/1/index.ts
  projects/kit/styles/components/checkbox.less
  projects/kit/styles/components/radio.less
  projects/kit/styles/components/switch.less
Labels: ready to merge

#10222 chore: change `Manrope` font for e2e
  projects/demo-cypress/src/fixtures/manrope-fonts.ttf
  projects/demo-playwright/stubs/manrope-fonts.ttf
Labels: ready to merge

#10209 feat(layout): add new height modes on `tuiCell`
  projects/demo/src/modules/components/cell/examples/1/index.ts
  projects/demo/src/modules/components/cell/examples/2/index.ts
  projects/demo/src/modules/components/cell/examples/6/index.ts
  projects/demo/src/modules/components/cell/examples/7/index.ts
  projects/demo/src/modules/components/cell/index.html
  projects/demo/src/modules/components/cell/index.less
  projects/demo/src/modules/components/cell/index.ts
  projects/layout/components/cell/cell.directive.ts
  projects/layout/components/cell/cell.options.ts
  projects/layout/components/cell/cell.styles.less
  projects/layout/components/cell/index.ts
Labels: ready to merge

#9847 fix(kit): `CalendarRange` should not require extra click to start new range after same day range
  projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
  projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
  projects/cdk/date-time/day-range.ts
  projects/cdk/date-time/test/day-range.spec.ts
  projects/core/components/calendar/calendar-sheet.component.ts
  projects/core/components/calendar/calendar-sheet.options.ts
  projects/core/components/calendar/index.ts
  projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/demo-playwright/utils/page-objects/calendar-range.po.ts
  projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
  projects/demo-playwright/utils/page-objects/calendar.po.ts
  projects/demo/src/modules/components/mobile-calendar/examples/2/index.html
  projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts
  projects/demo/src/modules/components/mobile-calendar/examples/import/template.md
  projects/demo/src/modules/components/mobile-calendar/index.html
  projects/demo/src/modules/components/mobile-calendar/index.less
  projects/kit/components/calendar-range/calculate-disabled-item-handler.ts
  projects/kit/components/calendar-range/calendar-range.component.ts
  projects/kit/components/calendar-range/day-caps-mapper.ts
Labels: ready to merge

#10231 feat(experimental): add new styles to `tuiCell`
  projects/experimental/directives/cell/cell.directive.ts
  projects/experimental/directives/cell/cell.options.ts
  projects/experimental/directives/cell/cell.styles.less
  projects/experimental/directives/cell/index.ts
Labels: ready to merge, v3

#10237 fix(kit): increase css-specificity for step button's styles inside `TuiInputNumber`
  projects/kit/components/input-number/input-number.style.less
Labels: ready to merge

#10240 fix(kit): `InputDate` show actual min/max in `Calendar`
  projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
  projects/demo/src/modules/components/input-date/examples/1/index.html
  projects/demo/src/modules/components/input-date/examples/1/index.ts
  projects/kit/components/input-date/input-date.template.html
Labels: ready to merge, v3

#10242 feat(demo): `Button` add example with two labels
  projects/demo/src/modules/components/button/examples/7/index.html
  projects/demo/src/modules/components/button/examples/7/index.less
  projects/demo/src/modules/components/button/examples/7/index.ts
  projects/demo/src/modules/components/button/index.ts
Labels: ready to merge

#10244 fix(addon-mobile): background blackout do not disappear on mobile after longtap event
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/demo/src/modules/components/sheet-dialog/index.html
Labels: ready to merge, v4

#10245 fix(addon-mobile): background blackout do not disappear on mobile after longtap event
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
Labels: ready to merge, v3

#10215 chore(demo): fix typo
  projects/demo/src/modules/components/icon/index.html
Labels: ready to merge

#10220 fix: inputs with `extends TuiControl` has CD problems for `writeValue` of empty value
  projects/cdk/utils/dom/index.ts
  projects/cdk/utils/dom/value-binding.ts
  projects/demo-cypress/src/tests/input-number/write-value-empty-string.cy.ts
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge

#10241 chore(legacy): `InputDate` add test show actual min/max in `Calendar`
  projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts
  projects/demo/src/modules/components/input-date/examples/1/index.html
  projects/demo/src/modules/components/input-date/examples/1/index.ts
Labels: ready to merge

#10250 fix(kit): `InputDateRange` not reset initial value to min/max and show actual in calendar
  projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
  projects/demo/src/modules/components/input-date-range/examples/1/index.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/input-date-range.template.html
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
Labels: ready to merge, v3

#10255 chore: update readme
  README.md
Labels: ready to merge

#10265 fix(kit): `Connected` make compatible with `Chevron`
  projects/kit/directives/connected/connected.style.less
Labels: ready to merge

#10271 fix(layout): `CardLarge` fix title boldness
  projects/layout/components/card/card.styles.less
Labels: ready to merge

#10276 fix(kit): `InputNumber` should handle programmatic control update with `NaN` as empty textfield
  projects/demo/src/modules/components/arc-chart/examples/1/index.html
  projects/demo/src/modules/components/arc-chart/examples/1/index.ts
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge

#10280 chore(demo): use new version of `InputNumber` for all documentation examples
  projects/demo/src/modules/components/form/examples/2/index.html
  projects/demo/src/modules/components/form/examples/2/index.ts
  projects/demo/src/modules/components/table/examples/4/index.html
  projects/demo/src/modules/components/table/examples/4/index.ts
  projects/demo/src/modules/directives/number-format/examples/import/template.md
  projects/demo/src/modules/pipes/field-error/examples/2/index.html
  projects/demo/src/modules/pipes/field-error/examples/2/index.ts
Labels: ready to merge

#10278 fix(core): `tuiDropdownContext` menu remains open after long tap
  projects/core/directives/dropdown/dropdown-context.directive.ts
Labels: ready to merge, v3
