Repository taiga-family/taiga-ui, pull requests merged in 2025-03, with the labels that each got.

#10495 chore(demo-playwright): fix invalid order of actions for `InputNumber` test
  projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
Labels: ready to merge

#10486 feat(layout): `BlockStatus` add extra-description and status blocks
  projects/demo/src/modules/components/block-details/examples/1/index.html
  projects/demo/src/modules/components/block-details/examples/1/index.ts
  projects/demo/used-icons.ts
  projects/layout/components/block-details/block-details.style.less
Labels: ready to merge

#10493 fix(kit): add additional overload to `tuiFilterByInput` pipe
  projects/demo/src/modules/pipes/filter-by-input/examples/4/index.html
  projects/demo/src/modules/pipes/filter-by-input/examples/4/index.ts
  projects/demo/src/modules/pipes/filter-by-input/index.html
  projects/demo/src/modules/pipes/filter-by-input/index.ts
  projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
Labels: ready to merge

#10500 fix(kit): `Comment` add min-width
  projects/kit/styles/components/comment.less
Labels: ready to merge

#10499 chore(demo-playwright): fix invalid order of actions for `InputNumber` test (again)
  projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
Labels: ready to merge

#10506 chore: disable webkit
  .github/workflows/e2e.yml
Labels: ready to merge

#10501 chore(demo): `TuiForm` add grouped example
  projects/demo/src/modules/components/form/examples/2/index.html
  projects/demo/src/modules/components/form/examples/2/index.less
  projects/demo/src/modules/components/form/examples/2/index.ts
  projects/demo/src/modules/components/form/examples/3/index.html
  projects/demo/src/modules/components/form/examples/3/index.less
  projects/demo/src/modules/components/form/examples/3/index.ts
  projects/demo/src/modules/components/form/index.ts
Labels: ready to merge

#10515 ci: bump actions
  .github/workflows/auto-add-to-project.yml
  .github/workflows/auto-approve.yml
  .github/workflows/auto-author-assign.yml
  .github/workflows/auto-dependency-review.yml
  .github/workflows/auto-label.yml
  .github/workflows/auto-remove-label.yml
  .github/workflows/auto-update-icons.yml
  .github/workflows/build.yml
  .github/workflows/bundle-size-tracking.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .github/workflows/snapshots.yml
  .github/workflows/test.yml
  package-lock.json
Labels: ready to merge, v3

#10520 feat(nx-cloud): set up nx workspace
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/schematic.yml
  .github/workflows/snapshots.yml
  .github/workflows/test.yml
  nx.json
Labels: ready to merge

#10528 chore: drop nx cloud
  .env
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/schematic.yml
  .github/workflows/snapshots.yml
  .github/workflows/test.yml
  nx.json
Labels: ready to merge

#10539 chore(kit): refactor `min` / `max` logic for new `InputMonth`
  projects/demo/src/modules/components/input-month/examples/1/index.html
  projects/demo/src/modules/components/input-month/examples/5/index.html
  projects/demo/src/modules/components/input-month/examples/5/index.ts
  projects/demo/src/modules/components/input-month/examples/import/template.md
  projects/demo/src/modules/components/input-month/index.html
  projects/kit/components/input-month/input-month.directive.ts
  projects/kit/components/input-month/native-month-picker/native-month-picker.component.ts
  projects/kit/components/input-month/native-month-picker/native-month-picker.template.html
Labels: ready to merge

#10534 fix(core): focus option by mousemove only in dropdown manager
  projects/core/components/data-list/option.component.ts
  projects/demo/src/modules/components/tabs/examples/3/index.html
  projects/demo/src/modules/components/tabs/examples/3/index.ts
Labels: ready to merge

#10554 fix(kit): support customizing number of visible lines in `tui-push`
  projects/demo/src/modules/components/push/index.html
  projects/demo/src/modules/components/push/index.ts
  projects/kit/components/push/push.component.ts
  projects/kit/components/push/push.style.less
Labels: ready to merge

#10551 fix(core): `TuiDataList` attr(data-label) not correct working in Chrome
  projects/core/components/data-list/data-list.style.less
Labels: ready to merge

#10543 chore(demo): `Icon` add example inline svg
  projects/demo/src/modules/components/icon/examples/10/index.ts
  projects/demo/src/modules/components/icon/index.html
Labels: ready to merge

#10552 fix(core): `TuiDataList` attr(data-label) not correct working in Chrome
  projects/core/components/data-list/data-list.style.less
Labels: ready to merge, v3

#10538 fix(core): focus option by mousemove only in dropdown manager
  projects/core/components/data-list/option/option.component.ts
  projects/core/components/data-list/option/option.style.less
Labels: v3

#10558 ci: move commitlint to CI
  .github/workflows/lint.yml
Labels: ready to merge

#10557 fix(legacy): textarea flickering when type space
  projects/legacy/components/textarea/textarea.style.less
Labels: ready to merge

#10565 fix(kit): textarea flickering when type space
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge, v3

#10564 chore: ignore to check default branch
  .github/workflows/lint.yml
Labels: ready to merge

#10575 chore(demo): rename documentation page of legacy generation of `Select`
  projects/demo-playwright/tests/legacy/select/select.mobile.pw.spec.ts
  projects/demo-playwright/tests/legacy/select/select.pw.spec.ts
  projects/demo-playwright/utils/is-flaky-examples.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/select-legacy/examples/1/index.html
  projects/demo/src/modules/components/select-legacy/examples/1/index.ts
  projects/demo/src/modules/components/select-legacy/examples/10/index.html
  projects/demo/src/modules/components/select-legacy/examples/10/index.ts
  projects/demo/src/modules/components/select-legacy/examples/11/index.html
  projects/demo/src/modules/components/select-legacy/examples/11/index.ts
  projects/demo/src/modules/components/select-legacy/examples/2/index.html
  projects/demo/src/modules/components/select-legacy/examples/2/index.less
  projects/demo/src/modules/components/select-legacy/examples/2/index.ts
  projects/demo/src/modules/components/select-legacy/examples/3/index.html
  projects/demo/src/modules/components/select-legacy/examples/3/index.less
  projects/demo/src/modules/components/select-legacy/examples/3/index.ts
  projects/demo/src/modules/components/select-legacy/examples/4/index.html
  projects/demo/src/modules/components/select-legacy/examples/4/index.less
  projects/demo/src/modules/components/select-legacy/examples/4/index.ts
  projects/demo/src/modules/components/select-legacy/examples/5/index.html
  projects/demo/src/modules/components/select-legacy/examples/5/index.less
  projects/demo/src/modules/components/select-legacy/examples/5/index.ts
  projects/demo/src/modules/components/select-legacy/examples/6/index.html
  projects/demo/src/modules/components/select-legacy/examples/6/index.less
  projects/demo/src/modules/components/select-legacy/examples/6/index.ts
  projects/demo/src/modules/components/select-legacy/examples/7/index.html
  projects/demo/src/modules/components/select-legacy/examples/7/index.less
  projects/demo/src/modules/components/select-legacy/examples/7/index.ts
  projects/demo/src/modules/components/select-legacy/examples/8/index.html
  projects/demo/src/modules/components/select-legacy/examples/8/index.less
  projects/demo/src/modules/components/select-legacy/examples/8/index.ts
  projects/demo/src/modules/components/select-legacy/examples/9/account/index.html
  projects/demo/src/modules/components/select-legacy/examples/9/account/index.less
  projects/demo/src/modules/components/select-legacy/examples/9/account/index.ts
  projects/demo/src/modules/components/select-legacy/examples/9/index.html
  projects/demo/src/modules/components/select-legacy/examples/9/index.less
  projects/demo/src/modules/components/select-legacy/examples/9/index.ts
  projects/demo/src/modules/components/select-legacy/examples/import/import.md
  projects/demo/src/modules/components/select-legacy/examples/import/template.md
  projects/demo/src/modules/components/select-legacy/index.html
  projects/demo/src/modules/components/select-legacy/index.less
  projects/demo/src/modules/components/select-legacy/index.ts
Labels: ready to merge

#10556 fix(addon-table): improve `tuiSortChange` event
  projects/addon-table/components/table/directives/direction-order.directive.ts
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/table.options.ts
  projects/demo/src/modules/components/table/examples/4/index.html
  projects/demo/src/modules/components/table/examples/4/index.ts
Labels: community contribution

#10579 fix(layout): `BlockStatus` fix margin when description block is empty
  projects/addon-mobile/styles/common/block-status.less
  projects/demo/src/modules/components/block-status/examples/8/index.html
  projects/demo/src/modules/components/block-status/examples/8/index.less
  projects/demo/src/modules/components/block-status/examples/8/index.ts
  projects/demo/src/modules/components/block-status/index.ts
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge

#10578 ci(demo): fix prerender of `API` & `Setup` pages of legacy components
  scripts/generate-demo-routes-file.ts
Labels: ready to merge

#10581 fix(layout): `BlockStatus` fix margin when description block is empty
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge, v3

#10563 chore(demo): add wrapper component
  projects/demo/src/modules/pipes/field-error/examples/7/index.html
  projects/demo/src/modules/pipes/field-error/examples/7/index.ts
  projects/demo/src/modules/pipes/field-error/index.html
Labels: ready to merge

#10567 chore(demo): `Notification` add customization example
  projects/demo/src/modules/components/data-list/examples/6/index.html
  projects/demo/src/modules/components/data-list/examples/6/index.ts
  projects/demo/src/modules/components/notification/examples/4/index.html
  projects/demo/src/modules/components/notification/examples/4/index.less
  projects/demo/src/modules/components/notification/examples/4/index.ts
  projects/demo/src/modules/components/notification/index.ts
Labels: ready to merge

#10583 fix(kit): disabled checkbox must not be interactive
  projects/kit/styles/components/checkbox.less
Labels: ready to merge

#10585 chore(kit): refactor dropdown logic for non-editable `InputMonth` textfield
  projects/cdk/utils/dom/is-element-editable.ts
  projects/core/directives/dropdown/dropdown.bindings.ts
  projects/demo-playwright/tests/kit/input-month/input-month.pw.spec.ts
  projects/demo-playwright/utils/page-objects/calendar-month.po.ts
  projects/demo-playwright/utils/page-objects/index.ts
  projects/demo-playwright/utils/page-objects/input-month.po.ts
  projects/kit/components/input-month/input-month.directive.ts
Labels: ready to merge

#10566 fix(legacy): do not expand textarea horizontally for long word
  projects/legacy/components/textarea/textarea.style.less
Labels: ready to merge

#10610 chore: move axe config to env
  projects/demo-playwright/playwright.config.ts
  projects/demo-playwright/tests/demo/demo.pw.spec.ts
Labels: ready to merge

#10611 fix(kit): do not expand textarea horizontally for long word
  projects/kit/components/textarea/textarea.style.less
Labels: ready to merge, v3

#10613 fix(kit): scrollbar in multi-select with data-list-wrapper
  projects/kit/components/multi-select/multi-select.style.less
Labels: ready to merge, v3

#10637 feat(addon-doc): prettify object in popup notification
  projects/addon-doc/components/api/api-item.component.ts
Labels: ready to merge

#10592 fix(core): synchronize driver's state
  projects/core/directives/dropdown/dropdown.directive.ts
Labels: ready to merge

#10626 chore(demo): add example with `TuiValueTransformer` for `InputNumber` documentation page
  projects/demo/src/modules/components/input-number/examples/8/index.html
  projects/demo/src/modules/components/input-number/examples/8/index.ts
  projects/demo/src/modules/components/input-number/index.html
Labels: ready to merge

#10636 feat(addon-charts): add `tapColumn` output event in `tui-bar-chart`
  projects/addon-charts/components/bar-chart/bar-chart.component.ts
  projects/addon-charts/components/bar-chart/bar-chart.template.html
  projects/demo/src/modules/components/bar-chart/index.html
Labels: ready to merge

#10630 chore: make header examples semantic
  projects/core/styles/components/title.less
  projects/demo/src/modules/components/header/examples/1/index.html
  projects/demo/src/modules/components/header/examples/2/index.html
  projects/demo/src/modules/components/header/examples/3/index.html
  projects/demo/src/modules/components/header/examples/import/template.md
  projects/layout/components/header/header.styles.less
Labels: ready to merge

#10643 refactor: use `tuiAsDataListHost(x)` instead of `tuiProvide(TUI_DATA_LIST_HOST, x)`
  projects/kit/directives/button-select/button-select.directive.ts
  projects/layout/components/navigation/aside-group.component.ts
  projects/layout/components/navigation/aside-item.directive.ts
Labels: ready to merge

#10651 chore(demo): add button group example with elastic container
  projects/demo/src/modules/components/button-group/examples/4/index.html
  projects/demo/src/modules/components/button-group/examples/4/index.less
  projects/demo/src/modules/components/button-group/examples/4/index.ts
  projects/demo/src/modules/components/button-group/index.ts
  projects/demo/used-icons.ts
  projects/kit/directives/button-group/button-group.style.less
Labels: ready to merge

#10654 chore(schematics): add html comments for colored icons
  projects/cdk/schematics/ng-update/interfaces/html-comment.ts
  projects/cdk/schematics/ng-update/utils/templates/template-comments.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-svg.spec.ts
Labels: ready to merge

#10657 chore: actualize db
  projects/demo/src/modules/app/pages.ts
Labels: ready to merge

#10660 feat(core): new version of `TuiOption`
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.tokens.ts
  projects/core/components/data-list/data-list.ts
  projects/core/components/data-list/index.ts
  projects/core/components/data-list/option/option-content.ts
  projects/core/components/data-list/option/option-legacy.component.ts
  projects/core/components/data-list/option/option.directive.ts
  projects/demo/src/modules/components/button-close/examples/1/index.ts
  projects/demo/src/modules/components/button/examples/3/index.ts
  projects/demo/src/modules/components/tag/examples/3/index.ts
  projects/demo/src/modules/components/tag/examples/6/index.ts
  projects/demo/src/modules/customization/routable/eager/examples/1/index.ts
  projects/demo/src/modules/customization/routable/eager/examples/2/index.ts
  projects/demo/src/modules/customization/routable/lazy/examples/1/index.ts
  projects/demo/src/modules/directives/appearance/examples/1/index.ts
  projects/demo/src/modules/directives/appearance/examples/2/index.ts
  projects/demo/src/modules/directives/appearance/examples/4/index.ts
  projects/demo/src/modules/directives/appearance/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/5/index.ts
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.html
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.ts
  projects/demo/src/modules/directives/fade/examples/2/index.ts
  projects/demo/src/modules/directives/fluid-typography/examples/1/index.ts
  projects/demo/src/modules/directives/ripple/examples/2/index.ts
  projects/demo/src/modules/directives/sensitive/examples/2/index.ts
  projects/demo/src/modules/directives/skeleton/examples/1/index.ts
  projects/demo/src/modules/directives/theme/examples/2/index.ts
  projects/demo/src/modules/info/related/index.ts
  projects/demo/src/modules/info/testing/disable-animation/index.ts
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
  projects/experimental/components/input-phone-international/input-phone-international.template.html
Labels: ready to merge

#10659 feat(kit): add `shift` output event to `carousel` component
  projects/core/components/dialog/dialog.component.ts
  projects/demo/src/modules/components/button-group/examples/4/index.html
  projects/demo/src/modules/components/button-group/examples/4/index.ts
  projects/demo/src/modules/components/button-group/index.ts
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/directives/button-group/button-group.style.less
Labels: ready to merge

#10664 chore(core): refactor some logic inside new version of `TuiOption`
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.style.less
  projects/core/components/data-list/option/option.directive.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/5/index.html
  projects/demo/src/modules/directives/dropdown-hover/examples/5/index.ts
  projects/demo/src/modules/directives/dropdown-selection/examples/2/index.less
Labels: ready to merge

#10668 fix(core): `Dialog` content section inherit border-radius
  projects/core/components/dialog/dialog.style.less
Labels: ready to merge, v3

#10666 chore(demo): `SheetDialog` rename fullsize -> fullscreen
  projects/demo/src/modules/components/sheet-dialog/index.html
Labels: ready to merge

#10673 feat(addon-mobile): `SheetDialog` add `tuiResponsiveDialog` directive
  projects/addon-mobile/directives/index.ts
  projects/addon-mobile/directives/responsive-dialog/index.ts
  projects/addon-mobile/directives/responsive-dialog/ng-package.json
  projects/addon-mobile/directives/responsive-dialog/responsive-dialog.directive.ts
  projects/addon-mobile/directives/responsive-dialog/responsive-dialog.module.ts
  projects/addon-mobile/directives/responsive-dialog/responsive-dialog.service.ts
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.ts
  projects/demo/src/modules/components/sheet-dialog/sheet-dialog.component.ts
  projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts
  projects/demo/src/modules/components/sheet-dialog/sheet-dialog.template.html
Labels: ready to merge, v3

#10679 fix(legacy): late init control binding in `tuiMultiSelectGroup`
  projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
Labels: ready to merge

#10682 fix(cdk): `tuiCreateToken` with no arguments should not create token with default `undefined`-value
  projects/cdk/utils/miscellaneous/create-token.ts
Labels: ready to merge

#10325 feat: add `tui-pager`
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/pager/examples/1/index.html
  projects/demo/src/modules/components/pager/examples/1/index.ts
  projects/demo/src/modules/components/pager/examples/2/index.html
  projects/demo/src/modules/components/pager/examples/2/index.ts
  projects/demo/src/modules/components/pager/examples/3/index.html
  projects/demo/src/modules/components/pager/examples/3/index.less
  projects/demo/src/modules/components/pager/examples/3/index.ts
  projects/demo/src/modules/components/pager/examples/import/import.md
  projects/demo/src/modules/components/pager/examples/import/template.md
  projects/demo/src/modules/components/pager/index.html
  projects/demo/src/modules/components/pager/index.ts
  projects/demo/used-icons.ts
  projects/kit/components/index.ts
  projects/kit/components/pager/index.ts
  projects/kit/components/pager/ng-package.json
  projects/kit/components/pager/pager.component.html
  projects/kit/components/pager/pager.component.ts
  projects/kit/components/pager/pager.styles.less
  projects/kit/styles/components/progress-bar.less
Labels: ready to merge

#10641 feat(kit): `ItemsWithMore` add multiline mode
  projects/demo/src/modules/components/items-with-more/examples/4/index.html
  projects/demo/src/modules/components/items-with-more/examples/4/index.less
  projects/demo/src/modules/components/items-with-more/examples/4/index.ts
  projects/demo/src/modules/components/items-with-more/index.html
  projects/demo/src/modules/components/items-with-more/index.ts
  projects/kit/components/items-with-more/items-with-more.component.ts
  projects/kit/components/items-with-more/items-with-more.directive.ts
  projects/kit/components/items-with-more/items-with-more.service.ts
  projects/kit/components/items-with-more/items-with-more.style.less
  projects/kit/components/items-with-more/items-with-more.template.html
Labels: ready to merge

#10687 fix(core): add hint marker to custom components
  projects/demo-playwright/tests/kit/line-clamp/line-clamp.pw.spec.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
Labels: ready to merge

#10691 fix(addon-mobile): `Button` uppercase
  projects/addon-mobile/components/theme-android/theme-android.style.less
Labels: ready to merge, v3

#10692 feat(addon-mobile): `SheetDialog` add close directive to listen close events
  projects/addon-mobile/components/sheet-dialog/index.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog-close.directive.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.module.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
Labels: v3

#10686 chore: collision snapshot filename
  projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
Labels: ready to merge

#10693 feat(addon-doc): add `TuiDocAPINumberItem` for configure input api option
  projects/addon-doc/components/api/api-item-number.directive.ts
  projects/addon-doc/components/api/api-item.component.ts
  projects/addon-doc/components/api/api-item.template.html
  projects/addon-doc/components/index.ts
  projects/addon-doc/index.ts
  projects/demo/src/modules/components/pager/index.html
Labels: ready to merge

#10698 chore(e2e): add screenshot for `tuiSheetDialog`
  projects/demo-cypress/src/tests/sheet.cy.ts
Labels: ready to merge

#10700 fix(addon-mobile): use `display: block` on sheet host
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
Labels: ready to merge

#10696 refactor(core): add built-in `gap` for new `Option`
  projects/core/components/data-list/data-list.style.less
Labels: ready to merge

#10671 feat(layout): `ChipGroup` add new component
  projects/addon-mobile/styles/common/item-group.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/item-group/examples/1/index.html
  projects/demo/src/modules/components/item-group/examples/1/index.ts
  projects/demo/src/modules/components/item-group/examples/2/index.html
  projects/demo/src/modules/components/item-group/examples/2/index.less
  projects/demo/src/modules/components/item-group/examples/2/index.ts
  projects/demo/src/modules/components/item-group/examples/3/index.html
  projects/demo/src/modules/components/item-group/examples/3/index.less
  projects/demo/src/modules/components/item-group/examples/3/index.ts
  projects/demo/src/modules/components/item-group/examples/4/index.html
  projects/demo/src/modules/components/item-group/examples/4/index.less
  projects/demo/src/modules/components/item-group/examples/4/index.ts
  projects/demo/src/modules/components/item-group/examples/import/import.md
  projects/demo/src/modules/components/item-group/examples/import/template.md
  projects/demo/src/modules/components/item-group/index.html
  projects/demo/src/modules/components/item-group/index.ts
  projects/kit/components/items-with-more/items-with-more.style.less
  projects/layout/components/index.ts
  projects/layout/components/item-group/index.ts
  projects/layout/components/item-group/item-group.directive.ts
  projects/layout/components/item-group/item-group.styles.less
  projects/layout/components/item-group/ng-package.json
Labels: ready to merge

#10702 fix(experimental): valid references for compilation step
  projects/experimental/components/search-results/search-results.ts
Labels: ready to merge
