Repository taiga-family/taiga-ui, pull requests merged in 2025-02, with the labels that each got.

#10258 fix(kit): `InputDateTime` not reset initial value to min/max and show actual in calendar
  projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
  projects/demo/src/modules/components/input-date-time/examples/1/index.html
  projects/demo/src/modules/components/input-date-time/examples/1/index.ts
  projects/kit/components/input-date-time/input-date-time.component.ts
Labels: v3

#10251 chore(demo-playwright): `InputDateRange` add test not reset initial value to min/max and show actual in calendar
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
  projects/demo/src/modules/components/input-date-range/examples/1/index.ts
Labels: v4

#10293 fix(kit): `Carousel` fix autoscroll in ssr
  projects/demo/src/modules/components/carousel/examples/1/index.html
  projects/demo/src/modules/components/carousel/examples/1/index.ts
  projects/kit/components/carousel/carousel.directive.ts
Labels: ready to merge

#10292 fix(addon-doc): `DocAPIItem` throws error for signal-based output handlers
  projects/addon-doc/components/api/api-item.component.ts
Labels: ready to merge

#10295 chore: fix changelog
  CHANGELOG.md
  projects/kit/components/input-pin/input-pin.style.less
Labels: ready to merge

#10253 fix(addon-mobile): `ElasticSticky` recalculates offsetTop if host content was changed
  projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
  projects/demo/src/modules/directives/elastic-sticky/examples/1/index.less
  projects/demo/src/modules/directives/elastic-sticky/examples/2/index.html
  projects/demo/src/modules/directives/elastic-sticky/examples/2/index.ts
  projects/demo/src/modules/directives/elastic-sticky/index.html
Labels: ready to merge

#10269 feat(addon-mobile): `BottomSheet` add new component
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.component.ts
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.style.less
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.template.html
  projects/addon-mobile/components/bottom-sheet/index.ts
  projects/addon-mobile/components/bottom-sheet/ng-package.json
  projects/addon-mobile/components/index.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
  projects/addon-table/components/table/th/th.style.less
  projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts
  projects/core/components/scrollbar/scrollbar.style.less
  projects/core/styles/mixins/mixins.less
  projects/demo-playwright/tests/layout/input-search.pw.spec.ts
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/import/import.md
  projects/demo/src/modules/components/bottom-sheet/examples/import/template.md
  projects/demo/src/modules/components/bottom-sheet/index.html
  projects/demo/src/modules/components/bottom-sheet/index.less
  projects/demo/src/modules/components/bottom-sheet/index.ts
  projects/demo/src/modules/components/input-search/examples/1/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.html
  projects/demo/used-icons.ts
  projects/experimental/components/accordion/accordion.directive.ts
  projects/experimental/components/search-results/search-history.component.html
  projects/experimental/components/search-results/search-history.component.ts
  projects/layout/components/input-search/input-search.component.ts
Labels: ready to merge

#10298 chore: drop codefactor
  README.md
Labels: ready to merge

#10299 chore(demo): `InputDate` fix example with items
  projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts
  projects/demo/src/modules/components/input-date/examples/3/index.ts
  projects/demo/src/modules/components/input-date/index.ts
Labels: ready to merge

#10302 fix(core): regression of selecting day when used min length
  projects/core/components/calendar/calendar-sheet.component.ts
  projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
Labels: ready to merge

#10316 refactor: rename `silent` to `zoneless`
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
  projects/addon-commerce/components/input-card-group/input-card-group.template.html
  projects/addon-doc/components/demo/index.ts
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.component.ts
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
  projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/ripple/ripple.directive.ts
  projects/addon-table/components/reorder/reorder.component.ts
  projects/cdk/directives/active-zone/active-zone.directive.ts
  projects/cdk/directives/droppable/droppable.directive.ts
  projects/cdk/directives/focus-trap/focus-trap.directive.ts
  projects/cdk/directives/resizer/resizer.directive.ts
  projects/cdk/schematics/ng-update/v4/steps/templates/migrate-prevent-default.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-prevent-default.spec.ts
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/option.component.ts
  projects/core/components/dialog/dialog.template.html
  projects/core/components/dialog/dialogs.component.ts
  projects/core/components/root/root.component.ts
  projects/core/components/spin-button/spin-button.component.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/directives/dropdown/dropdown-context.directive.ts
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/core/directives/hint/hint-pointer.directive.ts
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.html
  projects/demo/src/modules/components/data-list/examples/5/index.html
  projects/demo/src/modules/components/dialog/examples/4/index.html
  projects/demo/src/modules/components/services/keyboard-service/examples/1/index.html
  projects/demo/src/modules/components/textfield/examples/5/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/4/index.html
  projects/kit/components/calendar-range/calendar-range.template.html
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/elastic-container/elastic-container.component.html
  projects/kit/components/files/file/file.template.html
  projects/kit/components/files/input-files/input-files.component.ts
  projects/kit/components/pagination/pagination.template.html
  projects/kit/components/tiles/tile-handle.directive.ts
  projects/kit/components/tiles/tiles.component.ts
  projects/legacy/components/input-date-multi/input-date-multi.template.html
  projects/legacy/components/input-date-time/input-date-time.template.html
  projects/legacy/components/input-date-time/native-date-time/native-date-time.directive.ts
  projects/legacy/components/input-date/input-date.template.html
  projects/legacy/components/input-date/native-date/native-date.component.ts
  projects/legacy/components/input-month-range/input-month-range.template.html
  projects/legacy/components/input-month/input-month.template.html
  projects/legacy/components/input-password/input-password.template.html
  projects/legacy/components/input-tag/input-tag.component.ts
  projects/legacy/components/input-tag/input-tag.template.html
  projects/legacy/components/input-time/native-time/native-time.component.ts
  projects/legacy/components/input-year/input-year.template.html
  projects/legacy/components/multi-select/multi-select.template.html
  projects/legacy/components/multi-select/native-multi-select/native-multi-select-group.component.ts
  projects/legacy/components/multi-select/native-multi-select/native-multi-select.component.ts
  projects/legacy/components/primitive-textfield/primitive-textfield.template.html
  projects/legacy/components/tag/tag.template.html
Labels: ready to merge

#10307 feat(layout): `Cell` add disabled state
  projects/demo/src/modules/components/cell/examples/9/index.html
  projects/demo/src/modules/components/cell/examples/9/index.less
  projects/demo/src/modules/components/cell/examples/9/index.ts
  projects/demo/src/modules/components/cell/index.ts
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge

#10320 feat(addon-mobile): `SheetDialog` content inherit border-radius
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
Labels: ready to merge

#10323 chore: flaky bottom-sheet e2e
  projects/demo-playwright/utils/is-flaky-examples.ts
Labels: ready to merge

#10318 fix(experimental): `SearchResults` fix focusing hidden tabs
  projects/experimental/components/search-results/search-results.component.ts
  projects/layout/components/navigation/subheader.component.ts
Labels: ready to merge

#10328 fix(kit): `Avatar` fix icon color for appearances
  projects/core/directives/icons/icons.directive.ts
  projects/demo/src/modules/components/avatar/examples/2/index.html
  projects/kit/components/avatar/avatar.component.ts
  projects/kit/components/avatar/avatar.style.less
  projects/kit/components/avatar/avatar.template.html
Labels: ready to merge

#10335 feat(testing): change `PLATFORM_ID` to server on jest environment
  projects/cdk/utils/browser/test/browsers.spec.ts
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#10322 fix(legacy): `InputDate` ignore null value if internal value is already null
  projects/legacy/components/input-date-range/input-date-range.component.ts
  projects/legacy/components/input-date-time/input-date-time.component.ts
  projects/legacy/components/input-date/input-date.component.ts
  projects/legacy/components/input-date/test/input-date.component.spec.ts
Labels: ready to merge

#10332 feat(addon-mobile): `@taiga-ui/layout` should be peer dependency
  package-lock.json
  projects/addon-mobile/package.json
Labels: ready to merge

#10334 chore: `actions/upload-artifact` update from 3.1.3 to 4.6.0
  .github/workflows/e2e.yml
  .github/workflows/test.yml
Labels: ready to merge, v3

#10333 fix(experimental): `Avatar` colored icon object-fit
  projects/experimental/components/avatar/avatar.component.ts
Labels: ready to merge, v3

#10326 chore(demo): add more information about `TuiDialogContext`
  projects/demo/src/modules/components/dialog/examples/import/lazy-dialog.md
  projects/demo/src/modules/components/dialog/index.html
  projects/demo/src/modules/components/dialog/index.ts
Labels: ready to merge

#10336 fix(kit): `Tabs` properly inherit font styles
  projects/core/styles/mixins/mixins.less
  projects/demo/src/modules/components/tabs/examples/7/index.html
  projects/demo/src/modules/components/tabs/examples/7/index.less
  projects/demo/src/modules/components/tabs/examples/7/index.ts
  projects/demo/src/modules/components/tabs/index.html
  projects/demo/src/modules/components/tabs/index.ts
  projects/kit/components/tabs/tabs-with-more.component.ts
  projects/kit/components/tabs/tabs-with-more.style.less
  projects/kit/components/tabs/tabs.style.less
Labels: ready to merge

#10329 feat(kit): `Connected` add support for `Accordion`
  projects/addon-charts/components/bar/bar.style.less
  projects/core/styles/mixins/date-picker.less
  projects/core/styles/mixins/picker.less
  projects/core/types/direction.ts
  projects/demo/src/modules/components/accordion/examples/2/index.html
  projects/demo/src/modules/components/accordion/examples/2/index.less
  projects/demo/src/modules/components/accordion/examples/2/index.ts
  projects/demo/src/modules/components/accordion/examples/6/index.html
  projects/demo/src/modules/components/accordion/examples/6/index.less
  projects/demo/src/modules/components/accordion/examples/6/index.ts
  projects/demo/src/modules/components/accordion/index.ts
  projects/demo/used-icons.ts
  projects/experimental/components/accordion/accordion.style.less
  projects/experimental/components/expand/expand.style.less
  projects/experimental/components/input-phone-international/input-phone-international.style.less
  projects/kit/components/drawer/drawer.component.ts
  projects/kit/components/drawer/drawer.style.less
  projects/kit/components/input-number/input-number.style.less
  projects/kit/components/preview/pagination/preview-pagination.style.less
  projects/kit/components/preview/zoom/preview-zoom.style.less
  projects/kit/components/slider/slider.style.less
  projects/kit/directives/connected/connected.style.less
  projects/layout/components/navigation/aside.style.less
  projects/legacy/components/input-number/input-number.style.less
  projects/legacy/components/input-slider/input-slider.style.less
  projects/styles/markup/tui-table.less
Labels: ready to merge

#10342 feat(addon-mobile): `BottomSheet` add new component
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.component.ts
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.module.ts
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.style.less
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.template.html
  projects/addon-mobile/components/bottom-sheet/index.ts
  projects/addon-mobile/components/bottom-sheet/ng-package.json
  projects/addon-mobile/components/index.ts
  projects/demo-playwright/tests/demo/is-flaky-examples.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/bottom-sheet/bottom-sheet.component.ts
  projects/demo/src/modules/components/bottom-sheet/bottom-sheet.module.ts
  projects/demo/src/modules/components/bottom-sheet/bottom-sheet.template.html
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/1/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/2/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.ts
  projects/demo/src/modules/components/bottom-sheet/examples/import/import-module.md
  projects/demo/src/modules/components/bottom-sheet/examples/import/insert-template.md
  projects/demo/used-icons.ts
Labels: ready to merge, v3

#10347 feat(kit): `Chip` add default rules for fade
  projects/demo/src/modules/components/chip/examples/6/index.html
  projects/demo/src/modules/components/chip/examples/6/index.less
  projects/demo/src/modules/components/chip/examples/6/index.ts
  projects/demo/src/modules/components/chip/index.html
  projects/demo/src/modules/components/chip/index.ts
  projects/demo/used-icons.ts
  projects/kit/styles/components/chip.less
Labels: ready to merge

#10268 feat(addon-table): add new output event with sort and direction changes
  projects/addon-table/components/table/directives/sort-by.directive.ts
  projects/addon-table/components/table/directives/sortable.directive.ts
  projects/addon-table/components/table/directives/table.directive.ts
  projects/addon-table/components/table/table.options.ts
  projects/demo/src/modules/components/table/examples/4/index.html
  projects/demo/src/modules/components/table/examples/4/index.ts
Labels: ready to merge

#10354 fix(experimental): `TUI_ICON_RESOLVER` fix default path to respect base href
  projects/experimental/tokens/icon-resolver.ts
Labels: v3

#10352 chore(demo-cypress): use experimental `TuiInputPhoneInternational` for CT
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
Labels: ready to merge

#10361 fix(testing): mock the platform before each test
  projects/addon-doc/components/code/tests/code.component.spec.ts
  projects/addon-doc/components/code/tests/highlight.spec.ts
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#10363 chore: fix
  projects/kit/components/tabs/test/tabs.component.spec.ts
Labels: ready to merge

#10358 fix(experimental): `InputPhoneInternational` detects `countryIsoCode` on control update with complete phone
  projects/demo-cypress/src/tests/input-phone-international.cy.ts
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
Labels: ready to merge

#10343 feat(core): add font scaling option
  projects/addon-table/components/table/th/th.style.less
  projects/cdk/directives/font-size/font-size.directive.ts
  projects/core/components/data-list/data-list.style.less
  projects/core/styles/components/appearance.less
  projects/core/styles/components/button.less
  projects/core/styles/components/textfield.less
  projects/core/styles/mixins/mixins.less
  projects/core/styles/theme/appearance/primary.less
  projects/core/styles/theme/variables.less
  projects/core/utils/miscellaneous/font-scaling.ts
  projects/core/utils/miscellaneous/index.ts
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/app/app.style.less
  projects/demo/src/modules/app/stackblitz/project-files/src/global_styles.less.md
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.ts
  projects/demo/src/modules/components/bottom-sheet/index.less
  projects/demo/src/modules/components/bottom-sheet/index.ts
  projects/demo/src/modules/components/input-search/examples/1/index.less
  projects/kit/styles/components/chip.less
  projects/layout/components/navigation/drawer.component.ts
  projects/layout/components/navigation/header.style.less
Labels: ready to merge

#10370 feat(testing): add resize observer polyfill
  package-lock.json
  projects/addon-doc/components/code/tests/code.component.spec.ts
  projects/addon-doc/components/code/tests/highlight.spec.ts
  projects/cdk/utils/browser/test/browsers.spec.ts
  projects/kit/components/tabs/test/tabs.component.spec.ts
  projects/testing/package.json
  projects/testing/setup-jest/index.ts
Labels: ready to merge

#10375 fix(core): enable pointer-events on disabled button
  projects/core/components/button/button.style.less
Labels: ready to merge, v3

#10374 fix(legacy): `InputDateMulti` include first/last date as valid
  projects/kit/components/input-date-multi/input-date-multi.component.ts
  projects/kit/components/input-date-multi/test/input-date-range.component.spec.ts
Labels: v3

#10377 feat(kit): `UnfinishedValidator` allow dynamic messages
  projects/kit/directives/unfinished-validator/unfinished-validator.directive.ts
  projects/legacy/directives/unfinished-validator/unfinished-validator.directive.ts
Labels: ready to merge

#10380 fix(kit): `Files` hide element when empty
  projects/kit/components/files/files/files.styles.less
Labels: ready to merge

#10382 chore: some codestyle cleanup
  projects/addon-table/components/reorder/reorder.component.ts
  projects/kit/components/tiles/index.ts
  projects/kit/components/tiles/test/reorder-functions.spec.ts
  projects/kit/components/tiles/tile-reorder.provider.ts
  projects/kit/components/tiles/tiles.component.ts
  projects/kit/components/tiles/tiles.tokens.ts
Labels: ready to merge

#10378 fix(core): enable pointer events on disabled button
  projects/core/styles/components/appearance.less
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/demo-playwright/tests/addon-commerce/input-card-group.pw.spec.ts
  projects/demo/src/modules/components/button/examples/2/index.html
Labels: ready to merge

#10379 fix(kit): `ActionBar` fix background color
  projects/kit/components/action-bar/action-bar.component.ts
  projects/kit/components/action-bar/action-bar.style.less
Labels: ready to merge

#10388 fix(layout): `Card` add default background color
  projects/layout/components/card/card.styles.less
Labels: ready to merge

#10390 fix(kit): `Checkbox`, `Radio`, `Switch` return the lost appearance mode
  projects/kit/components/checkbox/checkbox.component.ts
  projects/kit/components/radio/radio.component.ts
  projects/kit/components/switch/switch.component.ts
Labels: ready to merge

#10392 fix(kit): valid font size for stepper
  projects/kit/components/stepper/stepper.style.less
Labels: ready to merge

#10393 chore(demo): invalid css variable name
  projects/demo/src/modules/components/bar-chart/examples/2/index.less
Labels: ready to merge

#10397 chore(demo): add example
  projects/demo/src/modules/components/icon/examples/9/index.html
  projects/demo/src/modules/components/icon/examples/9/index.less
  projects/demo/src/modules/components/icon/examples/9/index.ts
  projects/demo/src/modules/components/icon/index.html
Labels: ready to merge

#10405 fix(kit): improve caret management for `InputNumber` on step action
  projects/cdk/utils/dom/value-binding.ts
  projects/demo-playwright/tests/kit/input-number/input-number.pw.spec.ts
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge

#10416 fix(demo): `TuiHeader` add `TuiTitle` to import example
  projects/demo/src/modules/components/header/examples/import/import.md
  projects/demo/src/modules/components/header/index.html
Labels: ready to merge

#10417 fix(demo): `TuiHeader` add `TuiTitle` to import example
  projects/demo/src/modules/experimental/header/examples/import/import-module.md
  projects/demo/src/modules/experimental/header/header.component.ts
Labels: ready to merge, v3

#10415 chore(demo): add design forbiddance to use `label[tuiLabel]` with `s`-size `Textfield`
  projects/demo/src/components/textfield/index.html
  projects/demo/src/modules/components/input-card/index.html
  projects/demo/src/modules/components/input-number/index.html
  projects/demo/src/modules/components/input-phone-international/index.html
  projects/demo/src/modules/components/textfield/index.html
Labels: ready to merge

#10412 feat(layout): `Form` simplify columns
  projects/demo/src/modules/components/form/examples/2/index.html
  projects/demo/src/modules/components/form/examples/2/index.less
  projects/layout/components/form/form.styles.less
Labels: ready to merge

#10418 feat(addon-mobile): `TuiSheetDialog` provide `TUI_SCROLL_REF`
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
Labels: ready to merge

#10411 feat(layout): `Navigation` update according to specs
  projects/demo/src/modules/components/navigation/examples/1/index.html
  projects/layout/components/navigation/header.style.less
Labels: ready to merge

#10408 fix(kit): add additional overload to `tuiFilterByInput` pipe
  projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
Labels: ready to merge

#10402 chore: fix appearance
  projects/core/styles/theme/appearance/action.less
Labels: ready to merge

#10420 refactor: use de morgan rule for conditions
  projects/cdk/schematics/ng-update/steps/replace-enums.ts
  projects/core/components/root/root.component.ts
  projects/legacy/components/input-range/input-range.component.ts
Labels: ready to merge

#10427 chore(demo): improve stability of anchor scrolling
  projects/addon-doc/components/example/example.style.less
  projects/addon-doc/components/navigation/navigation.component.ts
  projects/addon-doc/components/navigation/scroll-into-view.directive.ts
  projects/demo-playwright/utils/goto.ts
  projects/demo/src/modules/app/abstract.app.ts
  projects/demo/src/modules/app/app.config.ts
  projects/demo/src/modules/app/utils/viewport-scroller.service.ts
Labels: ready to merge

#10433 chore(kit): `InputNumber` is decomposed to directive + optional `TuiInputNumberStep` component
  projects/kit/components/input-number/index.ts
  projects/kit/components/input-number/input-number.directive.ts
  projects/kit/components/input-number/input-number.ts
  projects/kit/components/input-number/step/input-number-step.component.ts
  projects/kit/components/input-number/step/input-number-step.style.less
  projects/kit/components/input-number/step/input-number-step.template.html
Labels: ready to merge

#10455 fix(kit): `InputNumber` should support `[attr.maxLength]`
  projects/demo-cypress/src/tests/input-number/maxlength.cy.ts
  projects/kit/components/input-number/input-number.directive.ts
Labels: ready to merge

#10430 fix(core): fix dropdown when host is svg element
  projects/core/directives/dropdown/dropdown.component.ts
Labels: ready to merge

#10431 fix(core): `DataList` fix empty content
  projects/core/components/data-list/data-list.component.ts
  projects/layout/components/navigation/aside-item.directive.ts
Labels: ready to merge

#10453 chore: disable experimental mode
  projects/demo-cypress/cypress.config.ts
Labels: ready to merge

#10460 chore(demo): update `Slider` documentation example
  projects/demo/src/modules/components/slider/examples/6/index.html
  projects/demo/src/modules/components/slider/index.html
Labels: ready to merge

#10461 feat(addon-mobile): `Chip` add mobile styles
  projects/addon-mobile/styles/common/chip.less
  projects/addon-mobile/styles/taiga-ui-mobile.less
Labels: ready to merge

#10462 chore(demo): fix checkbox-labeled demo
  projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.component.ts
Labels: ready to merge, v3

#10466 chore: entry is duplicated in metadata array
  projects/demo/src/modules/components/bar-chart/examples/2/index.ts
  projects/legacy/components/multi-select/multi-select.module.ts
Labels: ready to merge

#10481 chore(demo-cypress): mock current date for `MobileCalendar` tests
  projects/demo-cypress/src/tests/mobile-calendar.cy.ts
Labels: ready to merge

#10480 fix(addon-commerce): `InputCardGroup` should remove browser autofill styles for Chrome on IOS
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/core/styles/theme/appearance/textfield.less
Labels: ready to merge

#10483 chore: ignore schematics pipeline on release branch
  .github/workflows/schematic.yml
Labels: ready to merge
