Repository taiga-family/taiga-ui, pull requests merged in 2025-04, with the labels that each got.

#10717 feat(core): add `<tui-popups />`
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.template.html
  projects/core/directives/popup/index.ts
  projects/core/directives/popup/popups.component.ts
  projects/demo/src/modules/customization/viewport/examples/3/index.ts
Labels: ready to merge

#10689 fix(kit): ignore transition directly on tile
  projects/demo/src/modules/components/tiles/examples/3/index.html
  projects/demo/src/modules/components/tiles/examples/3/index.less
  projects/demo/src/modules/components/tiles/examples/3/index.ts
  projects/demo/src/modules/components/tiles/index.html
  projects/kit/components/tiles/tile.component.ts
  projects/kit/components/tiles/tile.service.ts
  projects/kit/components/tiles/tiles.component.ts
  projects/kit/components/tiles/tiles.style.less
Labels: ready to merge

#10672 feat(cdk): add `tuiFullscreen`
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.style.less
  projects/addon-doc/components/example/example.template.html
  projects/cdk/constants/used-icons.ts
  projects/core/components/fullscreen/fullscreen.component.ts
  projects/core/components/fullscreen/index.ts
  projects/core/components/fullscreen/ng-package.json
  projects/core/components/index.ts
  projects/core/components/root/root.component.ts
  projects/core/components/root/root.template.html
  projects/demo-cypress/src/tests/nested-root.cy.ts
  projects/demo/src/assets/icons/stackblitz.svg
  projects/demo/src/modules/app/stackblitz/edit/index.less
  projects/demo/src/modules/app/stackblitz/edit/index.ts
Labels: ready to merge

#10725 chore(demo): documentation typo
  projects/demo/src/modules/customization/i18n/dynamic.md
Labels: ready to merge

#10733 feat(addon-mobile): `SheetDialog` pass appearance from context
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
Labels: ready to merge, v3

#10709 feat(core): `Dialog` add event handler to change close button theme
  projects/core/components/dialog/dialog.component.ts
  projects/core/components/dialog/dialog.template.html
Labels: ready to merge, v3

#10715 fix(core): do not use hardcoded `tui-hint` selector
  projects/core/directives/hint/hint.component.ts
  projects/experimental/components/hint/hint.component.ts
  projects/kit/components/line-clamp/line-clamp-box.component.ts
Labels: ready to merge

#10736 fix(addon-mobile): `SheetDialog` content inherit border-radius
  projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
Labels: ready to merge, v3

#10731 fix(legacy): do not match value until user is writing value in `InputTime`
  projects/demo-playwright/tests/legacy/input-time/input-time.pw.spec.ts
  projects/legacy/components/input-time/input-time.component.ts
Labels: ready to merge

#10748 fix(experimental): `Cell` increase `tuiCellActions` specificity
  projects/experimental/directives/cell/cell.styles.less
Labels: v3

#10744 fix(kit): do not match value until user is writing value in InputTime
  projects/kit/components/input-time/input-time.component.ts
Labels: v3

#10747 fix(layout): `Cell` increase `tuiCellActions` specificity
  projects/demo/src/modules/components/cell/examples/9/index.html
  projects/demo/src/modules/components/cell/examples/9/index.less
  projects/demo/src/modules/components/cell/examples/9/index.ts
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge

#10759 ci: add `@taiga-ui/eslint-plugin-experience-next` to `IGNORABLE_TAIGA_PACKAGES`
  scripts/shared/ignorable-packages.ts
Labels: ready to merge

#10760 fix(core): `InputMonth` should hide Android text select handle
  projects/core/components/textfield/select-like.directive.ts
Labels: ready to merge

#10761 fix(core): `Textfield` has invalid width for `[tuiChevron]`'s icon
  projects/kit/directives/chevron/chevron.style.less
Labels: ready to merge

#10754 fix(core): `Textfield` add vertical padding
  projects/addon-table/components/table/th/th.style.less
  projects/core/components/textfield/select-like.directive.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/styles/components/appearance.less
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/table.less
Labels: ready to merge

#10767 refactor(core): add `autocomplete: 'off'` for `TuiSelectLike`
  projects/core/components/textfield/select-like.directive.ts
Labels: ready to merge

#10774 fix(legacy): reuse `identityMatcher` inside `tuiMultiSelectGroup`
  projects/cdk/utils/miscellaneous/array-toggle.ts
  projects/demo-playwright/tests/legacy/multi-select/multi-select.pw.spec.ts
  projects/demo/src/modules/components/multi-select/examples/15/index.html
  projects/demo/src/modules/components/multi-select/examples/15/index.ts
  projects/demo/src/modules/components/multi-select/index.ts
  projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
Labels: ready to merge

#10775 fix(kit): add deeper import for `TuiChevron`
  projects/kit/components/tabs/tabs-with-more.component.ts
Labels: ready to merge

#10642 feat(kit): `Select` refactor to new `Textfield`
  .cspell.json
  projects/core/components/data-list/data-list.component.ts
  projects/core/components/data-list/data-list.tokens.ts
  projects/core/components/data-list/option/option-content.ts
  projects/core/components/textfield/index.ts
  projects/core/components/textfield/select.directive.ts
  projects/core/components/textfield/textfield-accessor.ts
  projects/core/components/textfield/textfield-auxiliary.ts
  projects/core/components/textfield/textfield.component.ts
  projects/core/components/textfield/textfield.directive.ts
  projects/core/components/textfield/textfield.template.html
  projects/core/directives/index.ts
  projects/core/directives/items-handlers/index.ts
  projects/core/directives/items-handlers/items-handlers.directive.ts
  projects/core/directives/items-handlers/items-handlers.tokens.ts
  projects/core/directives/items-handlers/ng-package.json
  projects/core/styles/components/textfield.less
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/select/examples/1/index.html
  projects/demo/src/modules/components/select/examples/1/index.ts
  projects/demo/src/modules/components/select/examples/2/index.html
  projects/demo/src/modules/components/select/examples/2/index.ts
  projects/demo/src/modules/components/select/examples/3/index.html
  projects/demo/src/modules/components/select/examples/3/index.less
  projects/demo/src/modules/components/select/examples/3/index.ts
  projects/demo/src/modules/components/select/examples/4/index.html
  projects/demo/src/modules/components/select/examples/4/index.ts
  projects/demo/src/modules/components/select/examples/5/index.html
  projects/demo/src/modules/components/select/examples/5/index.less
  projects/demo/src/modules/components/select/examples/5/index.ts
  projects/demo/src/modules/components/select/examples/6/index.html
  projects/demo/src/modules/components/select/examples/6/index.ts
  projects/demo/src/modules/components/select/examples/7/index.html
  projects/demo/src/modules/components/select/examples/7/index.ts
  projects/demo/src/modules/components/select/examples/8/index.html
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/components/select/examples/8/option.ts
  projects/demo/src/modules/components/select/examples/import/import.md
  projects/demo/src/modules/components/select/examples/import/template.md
  projects/demo/src/modules/components/select/index.html
  projects/demo/src/modules/components/select/index.ts
  projects/demo/src/utils/example.pipe.ts
  projects/demo/used-icons.ts
  projects/experimental/components/search-results/search-results.component.html
  projects/kit/components/data-list-wrapper/data-list-group-wrapper.template.html
  projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
  projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
  projects/kit/components/index.ts
  projects/kit/components/select/index.ts
  projects/kit/components/select/native-select/native-select.component.ts
  projects/kit/components/select/native-select/native-select.template.html
  projects/kit/components/select/ng-package.json
  projects/kit/components/select/select-option/select-option.component.ts
  projects/kit/components/select/select-option/select-option.style.less
  projects/kit/components/select/select.directive.ts
  projects/kit/components/select/select.ts
  projects/kit/tokens/items-handlers.ts
Labels: ready to merge

#10786 fix(cdk): `ng-add` fix wrapping with tui-root for `UTF-8 with BOM` templates
  projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
Labels: ready to merge

#10791 feat(addon-doc): customize fullscreen buttons
  projects/addon-doc/components/example/example.template.html
  projects/addon-doc/tokens/doc-icons.ts
  projects/cdk/constants/used-icons.ts
Labels: ready to merge

#10785 fix(layout): `Navigation` fix aside highlights
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/layout/components/navigation/aside.style.less
  projects/layout/components/navigation/drawer.component.ts
Labels: ready to merge

#10800 feat(addon-doc): hide fullscreen button when device doesn't support fullscreen API
  projects/addon-doc/components/example/example.component.ts
  projects/addon-doc/components/example/example.template.html
Labels: ready to merge

#10818 fix: add `ngSkipHydration` for `<input/>`-s with template inside (to prevent SSR hydration error)
  projects/addon-commerce/components/input-card/input-card.component.ts
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/input-month/native-month-picker/native-month-picker.component.ts
  projects/kit/components/input-number/step/input-number-step.component.ts
  projects/kit/components/input-password/input-password.component.ts
  projects/kit/components/input-pin/input-pin.component.ts
  projects/layout/components/input-search/input-search.component.ts
Labels: ready to merge

#10812 fix(core): `DropdownOpen` sync state when changed externally
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
  projects/demo/src/modules/directives/dropdown-open/index.html
Labels: ready to merge

#10811 chore(cdk): fix running font scale watcher multiple times
  projects/cdk/utils/miscellaneous/font-size-watcher.ts
Labels: ready to merge

#10777 fix(kit): navigate to active element after first render for `tuiStepper`
  projects/kit/components/stepper/stepper.component.ts
Labels: ready to merge

#10792 fix(kit): `InputDateRange` update input value after control value changed
  projects/demo/src/modules/components/input-date-range/examples/5/index.html
  projects/demo/src/modules/components/input-date-range/examples/5/index.ts
  projects/kit/components/input-date-range/input-date-range.component.ts
  projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
Labels: ready to merge, v3

#10778 feat(kit): `Textarea` add new component
  projects/core/styles/components/textfield.less
  projects/core/styles/theme/appearance/textfield.less
  projects/demo-playwright/tests/kit/textarea/textarea.pw.spec.ts
  projects/demo-playwright/tests/legacy/textarea/textarea.pw.spec.ts
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/textarea-legacy/examples/1/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/1/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/2/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/2/index.less
  projects/demo/src/modules/components/textarea-legacy/examples/2/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/3/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/3/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/4/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/4/index.less
  projects/demo/src/modules/components/textarea-legacy/examples/4/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/5/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/5/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/6/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/6/index.less
  projects/demo/src/modules/components/textarea-legacy/examples/6/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/7/index.html
  projects/demo/src/modules/components/textarea-legacy/examples/7/index.ts
  projects/demo/src/modules/components/textarea-legacy/examples/import/import.md
  projects/demo/src/modules/components/textarea-legacy/examples/import/template.md
  projects/demo/src/modules/components/textarea-legacy/index.html
  projects/demo/src/modules/components/textarea-legacy/index.ts
  projects/demo/src/modules/components/textarea/examples/1/index.html
  projects/demo/src/modules/components/textarea/examples/1/index.less
  projects/demo/src/modules/components/textarea/examples/1/index.ts
  projects/demo/src/modules/components/textarea/examples/2/index.html
  projects/demo/src/modules/components/textarea/examples/2/index.ts
  projects/demo/src/modules/components/textarea/examples/3/index.html
  projects/demo/src/modules/components/textarea/examples/3/index.less
  projects/demo/src/modules/components/textarea/examples/3/index.ts
  projects/demo/src/modules/components/textarea/examples/import/import.md
  projects/demo/src/modules/components/textarea/examples/import/template.md
  projects/demo/src/modules/components/textarea/index.html
  projects/demo/src/modules/components/textarea/index.ts
  projects/demo/src/modules/components/textfield/examples/3/index.html
  projects/demo/src/modules/components/textfield/examples/4/index.html
  projects/experimental/components/input-phone-international/input-phone-international.component.ts
  projects/kit/components/index.ts
  projects/kit/components/textarea/index.ts
  projects/kit/components/textarea/ng-package.json
  projects/kit/components/textarea/textarea.component.ts
  projects/kit/components/textarea/textarea.options.ts
  projects/kit/components/textarea/textarea.style.less
  projects/kit/components/textarea/textarea.template.html
  projects/kit/directives/index.ts
  projects/kit/directives/textarea-limit/index.ts
  projects/kit/directives/textarea-limit/ng-package.json
  projects/kit/directives/textarea-limit/textarea-limit.directive.ts
  projects/kit/directives/textarea-limit/textarea-limit.style.less
Labels: ready to merge

#10782 feat(addon-mobile): `DropdownMobile` supports new `Select`
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts
  projects/addon-mobile/directives/dropdown-mobile/index.ts
  projects/addon-mobile/directives/dropdown-mobile/option-mobile/option-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/option-mobile/option-mobile.style.less
  projects/addon-mobile/directives/dropdown-mobile/option-mobile/option-mobile.template.html
  projects/demo/src/modules/components/select/examples/2/index.ts
  projects/demo/src/modules/components/select/examples/6/index.html
  projects/demo/src/modules/components/select/examples/6/index.ts
  projects/demo/src/modules/components/select/examples/7/index.html
  projects/demo/src/modules/components/select/examples/7/index.ts
  projects/demo/src/modules/components/select/examples/8/index.html
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/components/select/examples/9/index.html
  projects/demo/src/modules/components/select/examples/9/index.ts
  projects/demo/src/modules/components/select/examples/9/option.ts
  projects/demo/src/modules/components/select/index.html
  projects/demo/src/modules/components/select/index.ts
Labels: ready to merge

#10846 chore(demo): broken initial state of API page for `Range`
  projects/demo/src/modules/components/range/index.html
  projects/demo/src/modules/components/range/index.ts
Labels: ready to merge

#10847 fix(core): use child combinator for all selectors inside non-encapsulated `Textfield` styles
  projects/core/styles/components/textfield.less
Labels: ready to merge

#10845 chore(core): `DropdownOpen` ignore key events when there's no dropdown content
  projects/core/directives/dropdown/dropdown-open.directive.ts
  projects/kit/components/input-number/step/input-number-step.component.ts
Labels: ready to merge

#10850 chore(demo): new example `Choose form control output` for `Select` documentation
  projects/demo/src/modules/components/select/examples/1/index.ts
  projects/demo/src/modules/components/select/examples/10/index.html
  projects/demo/src/modules/components/select/examples/10/index.ts
  projects/demo/src/modules/components/select/examples/10/option.ts
  projects/demo/src/modules/components/select/examples/5/index.html
  projects/demo/src/modules/components/select/examples/5/index.ts
  projects/demo/src/modules/components/select/examples/6/index.html
  projects/demo/src/modules/components/select/examples/6/index.less
  projects/demo/src/modules/components/select/examples/6/index.ts
  projects/demo/src/modules/components/select/examples/7/index.html
  projects/demo/src/modules/components/select/examples/7/index.ts
  projects/demo/src/modules/components/select/examples/8/index.html
  projects/demo/src/modules/components/select/examples/8/index.ts
  projects/demo/src/modules/components/select/examples/9/index.html
  projects/demo/src/modules/components/select/examples/9/index.ts
  projects/demo/src/modules/components/select/index.html
  projects/demo/src/modules/components/select/index.ts
Labels: ready to merge

#10855 refactor: replace deprecated params of `Number`-mask by new alternatives
  projects/demo/src/modules/components/textfield/examples/5/index.ts
  projects/kit/components/input-number/input-number.directive.ts
  projects/legacy/components/input-number/input-number.component.ts
Labels: ready to merge

#10825 feat(core): update `tuiLink` appearance by spec
  projects/core/components/link/link.directive.ts
  projects/core/components/link/link.options.ts
  projects/core/styles/components/link.less
  projects/demo/src/modules/components/link/examples/3/index.html
  projects/demo/src/modules/components/link/examples/3/index.less
  projects/demo/src/modules/components/link/examples/3/index.ts
  projects/demo/src/modules/components/link/index.ts
  projects/demo/used-icons.ts
Labels: ready to merge

#10857 refactor(kit): use pointer events for `Range` (+`setPointerCapture`)
  projects/kit/components/range/range-change.directive.ts
Labels: ready to merge

#10868 revert: `tuiLink` appearance
  projects/core/styles/components/link.less
Labels: ready to merge

#10872 feat(layout): `InputSearch` add manual open control
  projects/demo/src/modules/components/input-search/examples/1/index.html
  projects/demo/src/modules/components/input-search/examples/1/index.ts
  projects/layout/components/input-search/input-search.component.ts
Labels: ready to merge

#10866 chore: migration `NG_EVENT_PLUGINS` => `provideEventPlugins()`
  projects/addon-doc/components/navigation/navigation.style.less
  projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
  projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
  projects/cdk/schematics/ng-update/interfaces/replacement-identifier.ts
  projects/cdk/schematics/ng-update/steps/replace-identifier.ts
  projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
  projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts
  projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
  projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
  projects/demo/src/modules/app/app.const.ts
  projects/demo/src/modules/app/home/examples/main-standalone.md
  projects/demo/src/modules/app/home/home.template.html
Labels: ready to merge

#10869 fix(kit): `Textarea` fix change detection issues
  projects/cdk/directives/native-validator/native-validator.directive.ts
  projects/demo/src/modules/components/link/examples/3/index.html
  projects/kit/components/carousel/carousel.component.ts
  projects/kit/components/textarea/textarea.component.ts
  projects/kit/components/textarea/textarea.options.ts
  projects/kit/directives/textarea-limit/textarea-limit.directive.ts
Labels: ready to merge

#10859 fix(kit): `Range` has change detection problems with active state of thumb
  projects/demo-cypress/src/tests/slider/slider-with-ng-model.cy.ts
  projects/kit/components/slider/slider.component.ts
Labels: ready to merge

#10873 fix(core): `Link` fix `Chevron` not rotating
  projects/core/components/link/link.directive.ts
  projects/core/components/link/link.options.ts
  projects/core/styles/components/link.less
  projects/core/styles/mixins/mixins.less
  projects/demo/src/modules/components/link/examples/2/index.html
  projects/demo/src/modules/components/link/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/3/index.html
  projects/kit/components/breadcrumbs/breadcrumbs.style.less
Labels: ready to merge

#10876 fix(addon-mobile): support block status without image
  projects/demo/src/modules/components/block-status/examples/5/index.html
  projects/layout/components/block-status/block-status.style.less
Labels: ready to merge

#10541 feat(kit): `FloatingContainer` add new directive
  projects/core/animations/animations.ts
  projects/core/styles/mixins/mixins.less
  projects/core/styles/mixins/mixins.scss
  projects/demo/src/modules/app/app.routes.ts
  projects/demo/src/modules/app/demo-routes.ts
  projects/demo/src/modules/app/pages.ts
  projects/demo/src/modules/components/floating-container/examples/1/index.html
  projects/demo/src/modules/components/floating-container/examples/1/index.less
  projects/demo/src/modules/components/floating-container/examples/1/index.ts
  projects/demo/src/modules/components/floating-container/examples/2/index.html
  projects/demo/src/modules/components/floating-container/examples/2/index.less
  projects/demo/src/modules/components/floating-container/examples/2/index.ts
  projects/demo/src/modules/components/floating-container/examples/3/index.html
  projects/demo/src/modules/components/floating-container/examples/3/index.less
  projects/demo/src/modules/components/floating-container/examples/3/index.ts
  projects/demo/src/modules/components/floating-container/examples/4/index.html
  projects/demo/src/modules/components/floating-container/examples/4/index.less
  projects/demo/src/modules/components/floating-container/examples/4/index.ts
  projects/demo/src/modules/components/floating-container/examples/5/index.html
  projects/demo/src/modules/components/floating-container/examples/5/index.less
  projects/demo/src/modules/components/floating-container/examples/5/index.ts
  projects/demo/src/modules/components/floating-container/examples/6/index.html
  projects/demo/src/modules/components/floating-container/examples/6/index.less
  projects/demo/src/modules/components/floating-container/examples/6/index.ts
  projects/demo/src/modules/components/floating-container/examples/import/import.md
  projects/demo/src/modules/components/floating-container/examples/import/template.md
  projects/demo/src/modules/components/floating-container/index.html
  projects/demo/src/modules/components/floating-container/index.less
  projects/demo/src/modules/components/floating-container/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/1/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/1/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/2/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/2/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/2/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/3/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/6/index.ts
  projects/demo/src/modules/components/sheet-dialog/examples/7/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/7/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/7/index.ts
  projects/demo/src/modules/components/sheet-dialog/index.html
  projects/demo/src/modules/components/sheet-dialog/index.less
  projects/demo/src/modules/components/sheet-dialog/index.ts
  projects/kit/components/floating-container/floating-container.directive.ts
  projects/kit/components/floating-container/floating-container.less
  projects/kit/components/floating-container/index.ts
  projects/kit/components/floating-container/ng-package.json
  projects/kit/components/index.ts
Labels: ready to merge

#10883 chore(demo): `FloatingContainer` remove commented code
  projects/demo/src/modules/components/floating-container/examples/3/index.html
Labels: ready to merge

#10856 fix(addon-mobile): `DropdownMobile` fix when used in a dialog
  package-lock.json
  package.json
  projects/addon-commerce/components/input-card-group/input-card-group.style.less
  projects/addon-mobile/components/bottom-sheet/bottom-sheet.template.html
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
  projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
  projects/core/components/data-list/data-list.style.less
  projects/core/components/dialog/dialogs.style.less
  projects/core/components/textfield/textfield.template.html
  projects/core/styles/theme/appearance/textfield.less
  projects/demo-cypress/src/tests/dropdown-mobile.cy.ts
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.html
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.less
  projects/demo/src/modules/components/bottom-sheet/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown/examples/6/index.html
  projects/demo/src/modules/directives/dropdown/examples/6/index.ts
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge

#10892 fix(kit): `InputNumber` rejects decimal part (even if `precision > 0`) if affixes include decimal pseudo separator
  projects/kit/components/input-number/input-number.component.ts
Labels: ready to merge, v3

#10896 chore: add hyphens example
  projects/demo/src/modules/directives/fade/examples/4/index.html
  projects/demo/src/modules/directives/fade/examples/4/index.less
  projects/demo/src/modules/directives/fade/examples/4/index.ts
  projects/demo/src/modules/directives/fade/index.html
  projects/demo/src/modules/directives/fade/index.ts
Labels: ready to merge

#10891 fix(core): `Root` fix dropdowns when scrollable
  projects/core/components/root/root.style.less
  projects/core/directives/dropdown/dropdown.component.ts
  projects/core/directives/dropdown/dropdown.directive.ts
  projects/core/directives/dropdown/dropdowns.component.ts
  projects/core/tokens/viewport.ts
  projects/demo/src/modules/customization/viewport/examples/1/index.less
  projects/demo/src/modules/customization/viewport/examples/2/index.ts
Labels: ready to merge

#10901 chore(demo): remove usage of legacy `Select`
  projects/demo-playwright/tests/core/dialogs/dialogs.pw.spec.ts
  projects/demo/src/modules/components/accordion-/examples/2/index.html
  projects/demo/src/modules/components/accordion-/examples/2/index.ts
  projects/demo/src/modules/components/bar-chart/examples/2/index.html
  projects/demo/src/modules/components/bar-chart/examples/2/index.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
  projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.template.html
  projects/demo/src/modules/components/form/examples/2/index.html
  projects/demo/src/modules/components/form/examples/2/index.ts
  projects/demo/src/modules/components/utils/format/examples/2/index.html
  projects/demo/src/modules/components/utils/format/examples/2/index.ts
  projects/demo/src/modules/components/utils/miscellaneous/examples/3/index.html
  projects/demo/src/modules/components/utils/miscellaneous/examples/3/index.less
  projects/demo/src/modules/components/utils/miscellaneous/examples/3/index.ts
  projects/demo/src/modules/components/utils/miscellaneous/examples/4/index.html
  projects/demo/src/modules/components/utils/miscellaneous/examples/4/index.ts
  projects/demo/src/modules/directives/dropdown-hover/examples/3/index.html
  projects/demo/src/modules/directives/dropdown-hover/examples/3/index.ts
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.html
  projects/demo/src/modules/directives/dropdown-open/examples/2/index.ts
  projects/demo/src/modules/directives/hint/examples/5/index.html
  projects/demo/src/modules/directives/hint/examples/5/index.ts
  projects/demo/src/modules/directives/validator/examples/1/index.html
  projects/demo/src/modules/directives/validator/examples/1/index.ts
Labels: ready to merge

#10898 chore(layout): `Cell` inside `Select` has overflown last character
  projects/demo/src/modules/components/cell/examples/7/index.html
  projects/demo/src/modules/components/cell/examples/7/index.ts
  projects/layout/components/cell/cell.styles.less
Labels: ready to merge

#10888 fix(core): `SelectOption` has change detection problems with checked state
  projects/core/components/notification/notification.directive.ts
  projects/core/directives/icons/icons.directive.ts
  projects/demo-cypress/src/tests/select.cy.ts
  projects/layout/components/navigation/drawer.component.ts
Labels: ready to merge

#10887 chore(demo): `SheetDialog` remove unnecessary scroll behaviour
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.html
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
  projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
Labels: ready to merge

#10875 fix(kit): skeleton animation does not depend on animation speed
  projects/kit/directives/skeleton/skeleton.style.less
Labels: ready to merge

#10694 feat(addon-table): added expandable table behaviour
  .cspell.json
  projects/addon-commerce/components/input-card-group/input-card-group.component.ts
  projects/addon-table/components/table/index.ts
  projects/addon-table/components/table/table-expand/table-expand.component.ts
  projects/addon-table/components/table/table-expand/table-expand.style.less
  projects/addon-table/components/table/table-expand/table-expand.template.html
  projects/addon-table/components/table/table.ts
  projects/addon-table/components/table/tbody/tbody.component.ts
  projects/demo-playwright/playwright.config.ts
  projects/demo/src/modules/components/table/examples/9/index.html
  projects/demo/src/modules/components/table/examples/9/index.less
  projects/demo/src/modules/components/table/examples/9/index.ts
  projects/demo/src/modules/components/table/index.ts
Labels: ready to merge

#10907 fix(addon-charts): hint appearance not passed to bar-chart (#10899)
  projects/addon-charts/components/bar-chart/bar-chart.component.ts
  projects/addon-charts/components/bar-chart/bar-chart.template.html
Labels: ready to merge

#10911 fix(kit): `InputMonth` with enabled native picker should never show desktop dropdown
  projects/core/components/textfield/textfield.component.ts
  projects/demo-playwright/tests/kit/input-month/input-month.pw.spec.ts
  projects/demo-playwright/utils/page-objects/input-month.po.ts
  projects/kit/components/input-month/input-month.directive.ts
  projects/kit/components/input-month/native-month-picker/native-month-picker.style.less
Labels: ready to merge

#10909 chore(demo): `Dialog` add custom dialog with directive example
  projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.component.ts
  projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.directive.ts
  projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.service.ts
  projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.style.less
  projects/demo/src/modules/customization/dialogs/examples/2/index.html
  projects/demo/src/modules/customization/dialogs/examples/2/index.ts
  projects/demo/src/modules/customization/dialogs/index.html
  projects/demo/src/modules/customization/dialogs/index.ts
Labels: ready to merge

#10908 chore: increase timings
  projects/demo-playwright/tests/demo/demo.pw.spec.ts
  projects/demo-playwright/tests/kit/line-clamp/line-clamp.pw.spec.ts
Labels: ready to merge

#10915 fix(kit): get rid of dot before extension-less files
  projects/demo-playwright/stubs/no-extension-file
  projects/demo-playwright/tests/kit/input-files/input-files.pw.spec.ts
  projects/kit/components/files/file/file.component.ts
Labels: ready to merge

#10919 fix(core): fixed parent closing when nested hint is closed
  projects/core/directives/hint/hint-hover.directive.ts
  projects/core/directives/hint/hint.component.ts
Labels: ready to merge
